### ISSUE TITLE
About client.cfg

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1009]
"All configuration can be done by adding a configuration file named client.cfg to your current working directory or /etc/luigi (although this is further configurable)"

I got two problems:
(1) "your current working directory" is not clear enough, how can luigid find the client.cfg in "my current working directory"?
(2)"although this is further configurable",  how to configure the configure file path for luigid ?

Thanks everyone in advance.

**Comment by leafjungle** [comment]
The doc link:  http://luigi.readthedocs.org/en/stable/configuration.html

**Comment by Tarrasch** [comment]
Does it look better here @leafjungle? https://github.com/spotify/luigi/pull/1010,

As for luigid, it's quite unfortunate that it uses the same logic for configuration as the client (it couples them for no good reason).

**Comment by leafjungle** [comment]
@Tarrasch ，Thank you very much.

I set the config file path by environment variable.

But I still puzzled  by "the current work space directory", is it the same directory with my python program (such as OneTask.py) ?

**Comment by Tarrasch** [comment]
@leafjungle are you confused over "current working directory"? I mean, try running `man pwd` in a terminal.
