### ISSUE TITLE
Why is configuration file called 'client.cfg'

### ISSUE THREAD

**Issue by soxofaan** [spotify/luigi#1029]
Maybe a stupid question, but why is the configuration file called `client.cfg`, when it typically contains non-client (e.g. scheduler) stuff as well?

Wouldn't it be nicer to have at least some hint of "luigi" in the name, e.g. `luigi.cfg`?

Can be handy when you use the "use config from current working dir" from a directory with loads of other configs and files.

**Comment by Tarrasch** [comment]
I guess this is for historical reasons.

But, I think, in the long run, that it should only contain client-side related config. So I'm not sure we should rename it as we might change our minds again. No strong opinions though.

**Comment by Tarrasch** [comment]
As for a luigi hint in the name. It's by default stored in `/etc/luigi/client.cfg` no?

**Comment by soxofaan** [comment]
indeed, for the global config `/etc/luigi/client.cfg`, it is,
but like I noted, you can also use `./client.cfg` (from working dir).
It's not that unusual to have your project's root as working dir, which is typically littered with all sorts of config files. Having a non descriptive name like `client.cfg` is not really helpful for overview :)

**Comment by soxofaan** [comment]
Current version of pull request above (#1030) is the easy part: just adding support for `./luigi.cfg`

the harder part is deciding about:
- Also add support `/etc/luigi/luigi.cfg`?
- whether to choose one over the other and update documentation/code comments accordingly?
- also, about:

    > in the long run, that it should only contain client-side related config

   how to split client vs non-client, e.g. `luigi.cfg`, `luigid.cfg`? What with non-client stuff in `luigi.cfg` then?

**Comment by Tarrasch** [comment]
Good points all over and I really appreciate the PR you sent.

I like the `luigid.cfg` idea. :)

**Comment by soxofaan** [comment]
I went a step further and added a commit that updates to "luigi.cfg" in various parts of documentation. comments, ...

Feel free to comment

I was also considering to also add support for `/etc/luigi/luigi.cfg` to make the documentation less confusing. But I thought to first await some feedback from the maintainers about all this

**Comment by leafjungle** [comment]
I find that both the client ( interface.py, cmdline.py, etc) and server (scheduler.py) will read the client.cfg.  
scheduler.py read client.cfg for "resources".

So it is a bit confused. what will luigi do if the client and server are deployed in different machines?  we have to put client.cfg in both machines?

**Comment by Tarrasch** [comment]
Yea, I guess that's why they renamed it from `client.cfg`, as it's not only read by the client.

**Comment by Tarrasch** [comment]
Closing this issue. as it got properly renamed with backward compatibility (see the referenced commits in this issue).
