### ISSUE TITLE
d3 and mixed content

### ISSUE THREAD

**Issue by skazi0** [spotify/luigi#1052]
We're running luigi scheduler behind nginx proxy which serves everything over https. Current index.d3.html links to http://d3js.org/d3.v3.js which doesn't work well with browsers causing 'mixed content' errors. Unfortunately d3js.org doesn't have https version.
The easiest solution would be to bundle d3 with luigi and serve it from /static.

**Comment by Tarrasch** [comment]
I'm pretty sure they bundled it with luigi? There was at least some huge file that was committed. Find and ping the author in this ticket I would say. :)

**Comment by skazi0** [comment]
the only huge file I see in /static/visualizer/js is dagre-d3.js which doesn't seem to have d3 built in.
https://github.com/spotify/luigi/blob/master/luigi/static/visualiser/index.d3.html loads both d3.v3.js and dagre-d3.js.

**Comment by Tarrasch** [comment]
Ok, ping the approriate commiters then. :)

**Comment by gpoulin** [comment]
d3js is available over TLS un cloudflare
https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js . However,
bundling it might be a good idea.

2015-07-08 11:14 GMT-04:00 Arash Rouhani <notifications@github.com>:

**Comment by hadesbox** [comment]
Hi @skazi0 ! ... I that library its not available on https! 

Either try to change the url, or bundle it!

@Tarrasch, someone said in the past we should use a package manager to manage all the front dependencies... I'll investigate into it, I dont want to keep bundling JS files with some kLOCs.

The thing is, if we do go for the package manager, its likely to make the installation more complicated.

**Comment by skazi0** [comment]
Hi @hadesbox, currently I worked this around locally by downloading the library and serving it from my host. This is OK for me but I thought that you might want some more generic solution that would work out of the box for everyone.

**Comment by Tarrasch** [comment]
Given my zero knowledge of working with front end. I can't contribute with a technical solution. :)

**Comment by erikbern** [comment]
sounds like we can just serve it from cloudflare using `<script src="://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js">` – this will make sure to use whatever protocol is used

**Comment by mfcabrera** [comment]
Apparently @erikbern proposal is now an anti-pattern https://twitter.com/paul_irish/status/588502455530311680 - Should we close this @Tarrasch ? or can we explicitly use https for this?

**Comment by Tarrasch** [comment]
Interesting observation with the anti-pattern. I didn't know that. I haven't seen any contributions to d3 lately so this will probably never be picked up. Closing.
