### ISSUE TITLE
Task done twice

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1054]
| 986 |     229 | PENDING    | 2015-07-09 14:23:15 |
| 987 |     230 | PENDING    | 2015-07-09 14:23:15 |
| 988 |     230 | RUNNING    | 2015-07-09 14:23:15 |
| 989 |     230 | DONE       | 2015-07-09 14:25:03 |
| 990 |     229 | RUNNING    | 2015-07-09 14:25:03 |
| 991 |     229 | FAILED     | 2015-07-09 14:25:04 |
| 992 |     229 | PENDING    | 2015-07-09 14:25:06 |
| 993 |     230 | PENDING    | 2015-07-09 14:25:06 |
| 994 |     230 | RUNNING    | 2015-07-09 14:25:06 |
| 995 |     230 | DONE       | 2015-07-09 14:29:16 |
| 996 |     229 | RUNNING    | 2015-07-09 14:29:16 |
| 997 |     229 | FAILED     | 2015-07-09 14:29:17 |
+-----+---------+------------+---------------------+

In my case, Task 229 requires Task 230.
IN the above, it is the task_events table.
Task 230 is DONE in the record 989, And done again in 995, why?

**Comment by leafjungle** [comment]
And the task 229 is failed because: RuntimeError: Unfulfilled dependency at run time: (Task 230).

But Task 230 is already done, why Unfulfilled?

**Comment by Tarrasch** [comment]
Well. Nobody can debug this. But either:

 1. There's a luigi bug
 2. Your requires/complete/run methods aren't correctly setup. There's no way to statically check this. You have to think them through on your own. :)

**Comment by leafjungle** [comment]
@Tarrasch , My task do not have any necessary input or output, I just set a temp folder for them.

Is that the possible reason ? the complete() function?

By the way, what is the relationship between run()  and complete() function?

**Comment by Tarrasch** [comment]
Relationship is that after `run()` is run, `complete()` should always return True from that point and on. That should even be true if you run it from another machine (if you do that of course)

**Comment by leafjungle** [comment]
@Tarrasch , thank you for you kindly reply.  I have no way out the problem: 

And the task 229 is failed because: RuntimeError: Unfulfilled dependency at run time: (Task 230).

But Task 230 is already done, why Unfulfilled?

**Comment by Tarrasch** [comment]
Have you grepped for "Unfulfilled dependency at run time" in the code? It should give some understanding and context.

**Comment by leafjungle** [comment]
@Tarrasch , I add some debug log in worker.py, and the log contains:

TaskA:
2015-07-10 13:31:45,978 - luigi-interface - INFO - [pid 3736] Worker Worker(salt=136469116, workers=100, host=xxxxx, username=xxxxx, pid=3733) done      TaskA(cdate=20140313, slicer=00) - [worker.py:160]
if TaskA.complete() print:
2015-07-10 13:31:45,978 - luigi-interface - INFO - task done, task info: TaskA(cdate=20140313, slicer=00) - [worker.py:164]

TaskB requires TaskA, when TaskB check its dependicies:
if not TaskA.complete() print:
2015-07-10 13:31:45,997 - luigi-interface - INFO - not complete:TaskA(cdate=20140313, slicer=00)  - [worker.py:130]


=========================
so TaskA.complete() return different values above.

**Comment by leafjungle** [comment]
@Tarrasch , From my log, I see that TaskB fails because it find that TaskA is "not complete"(completed actually), and then Luigi runs TaskA again.
So in the mysql and the log, I see TaskA runs twice and TaskB is always failed.

**Comment by leafjungle** [comment]
I implement the complete() function myself in my task with my own logic.

The problem above solved.  

Thanks for @Tarrasch very much.

**Comment by RajveerParikh** [comment]
What is the difference between the complete method and the exists method? Why would we ever need both? 
And I am getting similar behavior but when I add a complete method, it executes before my run method and the task still executed 2 times.
