### ISSUE TITLE
How to tag the Task as failed in run() function?

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1055]
Hi, guys

In case of any exceptions, I want to tag the task as failed, what should I do?

return 1? 

Thanks for any help.

**Comment by Tarrasch** [comment]
Well, just let the exception get thrown. Luigi as a framework will take care of it and you'll visually see the failure in the scheduler. See http://tarrasch.github.io/luigid-basics-jun-2015/#/9

**Comment by leafjungle** [comment]
Thank you very much. solved.
