### ISSUE TITLE
Run daily task

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1057]
Hii, guys.

I want to run TaskA each day. And  today's work should not run if yesterday's work has not completed yet.

I set a date paramter for TaskA:   TaskA(curdate), and it requires TaskA(curdate -1 )

How can I start this work?  I have to run TaskA(long future), so it will recursively run each TaskA from now on.

Thus, I can see A LOT and A LOT pending task in the visualiser website.

Any other solutions?

**Comment by themalkolm** [comment]
Do you terminate the backward dependency or it goes infinite to the beginning of the world? It could explain A LOT of pending tasks.

You can simply run task in cron every day, right? So a new one will appear in the scheduler.

**Comment by erikbern** [comment]
Yeah you have to terminate it i.e. put a TaskA(2000-01-01) somewhere

**Comment by leafjungle** [comment]
@themalkolm ,  by crontab, TaskA(curdate) has to check the status of TaskA(curdate - 1) manually.

**Comment by leafjungle** [comment]
@erikbern , Even though, still a lot of pending tasks are displayed in the website.

In the end, I add a status-check of TaskA(curdate - 1) logic in my program.

While I do not think it is the best solution.

**Comment by erikbern** [comment]
I don't quite understand this problem. Please provide more explanation and I can re-open
