### ISSUE TITLE
Retry settings/logic at task level instead of at "global" scheduler level

### ISSUE THREAD

**Issue by soxofaan** [spotify/luigi#1073]
Hi,

At the moment we have several luigi runs, for which we'd like to have different retry behaviour (some tasks should be retried every hour, some every ten minutes, for some tasks it's fine to be disabled after first failure, etc)

As far as I understand with current luigi we would have to use different configs for each run. And even then it is not possible to have different retry settings within the same run.

Wouldn't it make more sense to be able do define retry settings (retry delay, disable-num-failures, window, ...) or even retry related logic (e.g. custom back-off delay function, send warning mail, switching to a fallback task implementation, ...) at the task level instead of having this as global/scheduler properties?

I don't have a concrete proposal at the moment, but I just wanted to check with the maintainers if there are already ideas around this

**Comment by Tarrasch** [comment]
I haven't had the intent to implement this. The reason is that we don't have one big execution of luigi that depends on all other tasks. We've broken it up into many smaller executions with `ExternalTask`s and whatnot. In that case we are fine with per-execution settings. :)

**Comment by soxofaan** [comment]
We also don't have the intent to have one big luigi execution to cover it all.
The issue is that splitting your execution run based on desired retry behaviour is a bit weird and cumbersome.

**Comment by mfcabrera** [comment]
Closing this as it was fixed by #1791
