### ISSUE TITLE
S3CopyToTable does not support AWS temporary security credentials

### ISSUE THREAD

**Issue by deuxpi** [spotify/luigi#1078]
We needed to use temporary (instance profile) credentials to delegate access to the S3 bucket, but the S3CopyToTable task does not support this style of credentials. The solution we currently use is to override the `copy(self, cursor, f)` method if an `aws_security_token` task parameter is defined. I would be willing to propose a PR that provides this functionality directly from S3CopyToTable and S3CopyJSONToTable if there is any interest.

Redshift documentation: http://docs.aws.amazon.com/redshift/latest/dg/copy-parameters-credentials.html#copy-credentials-temporary

**Comment by dlstadther** [comment]
@deuxpi If you need to make this change for your org, feel free to contribute back to Luigi via a PR. (That's what I do). There may be only a small group of people who may need this feature, but it's a group nonetheless.

**Comment by erikbern** [comment]
great if you want to put together a  PR!

**Comment by dlstadther** [comment]
Resolved by #1702
