### ISSUE TITLE
Clean-up hooks on worker shutdown

### ISSUE THREAD

**Issue by graingert** [spotify/luigi#1088]
I've got a py.test test case:

```python
from datascience.reports import do_report
from datascience.models import redshift as redshift_models
from datascience import db

def test_report_luigi_task(redshift_description):
    # do_report.Report extends luigi.contrib.sqla.CopyToTable
    class TestReport(do_report.Report):
        connection_string = redshift_description.db_connect_url
        connect_args = redshift_description.connect_args

    luigi.build(luigi.build([TestTask()], local_scheduler=True, workers=NUM_WORKERS)
    session = db.RedshiftSession(redshift_description.engine())
    assert session.query(redshift_models.LuigiMarker).count() == 1
    ....
```

where "redshift_description" is a pytest fixture for an automatically created redshift database. This database is then dropped at the end of the function. 

However when running this test, it is impossible to drop the newly created database because there are connections open to this database. I've found that because luigi.contrib.sqla.SQLAlchemyTarget maintains a dictionary of engine instances these engines are not `disposed()` when the test function finishes.

It would be nice if it were possible to register callbacks on worker shutdown, in particular to dispose of these engines in the thread they were created in, or other cleanup.

**Comment by Tarrasch** [comment]
sqlalchemy --> Ping @gouthambs :)

**Comment by gouthambs** [comment]
I dont know much about how the luigi shutdown happens. @Tarrasch If there is a way to trigger some calls at shutdown, we can implement the cleanup.

**Comment by Tarrasch** [comment]
@graingert, is this related to what you did in #1089?

**Comment by Tarrasch** [comment]
Luigi comes with some pretty crude events/hooks on task completion. But you want it on Worker shut down?

**Comment by ulzha** [comment]
^ A new issue where I believe we'd be addressing this in a generic fashion.
