### ISSUE TITLE
A __repr__ somewhere in the HdfsTarget chain conflicts with the Google Cloud Storage naming convention

### ISSUE THREAD

**Issue by geowurster** [spotify/luigi#1092]
I'm running Luigi on Google's Cloud Infrastructure and am encountering an issue with `HdfsTarget()`.  Judging by the traceback below it looks like Luigi is using the task's `__repr__()` to create a file name for a log.  The full traceback is provided below but the important line appears at the very bottom:

```python
mv: Google Cloud Storage path must not have consecutive '/' characters, got '/py-hadoop-output/type-hist.txt/_logs/history/job_201507202121_0001_1437757538771_kwurster_%22TypeHist(infiles=gs://a-directory/input/'
```

It looks like Luigi is creating a log (or giving hadoop a name to use for a log?) that is derived from a `__repr__()`, and since I'm using a Cloud Storage datasource as input, the repr contains `gs://`, which wouldn't normally be a problem for HDFS, except that Google's HDFS is actually transparently writing to a Cloud Storage bucket of your choosing instead of a more traditional HDFS location.

Can anyone provide some information about how that log path is being generated?  In the short term I would like to try altering the naming convention so I can continue with what I'm working on.

**Full Traceback**

```python
Runtime error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/luigi/worker.py", line 137, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python2.7/dist-packages/luigi/worker.py", line 88, in _run_get_new_deps
    task_gen = self.task.run()
  File "/usr/local/lib/python2.7/dist-packages/luigi/contrib/hadoop.py", line 666, in run
    self.job_runner().run_job(self)
  File "/usr/local/lib/python2.7/dist-packages/luigi/contrib/hadoop.py", line 520, in run_job
    luigi.contrib.hdfs.HdfsTarget(output_hadoop).move_dir(output_final)
  File "/usr/local/lib/python2.7/dist-packages/luigi/contrib/hdfs/target.py", line 156, in move_dir
    move_succeeded = self.fs.rename_dont_move(self.path, path)
  File "/usr/local/lib/python2.7/dist-packages/luigi/contrib/hdfs/abstract_client.py", line 60, in rename_dont_move
    self.rename(path, dest)
  File "/usr/local/lib/python2.7/dist-packages/luigi/contrib/hdfs/hadoopcli_clients.py", line 98, in rename
    self.call_check(load_hadoop_cmd() + ['fs', '-mv'] + path + [dest])
  File "/usr/local/lib/python2.7/dist-packages/luigi/contrib/hdfs/hadoopcli_clients.py", line 68, in call_check
    raise hdfs_error.HDFSCliError(command, p.returncode, stdout, stderr)
HDFSCliError: Command ['hadoop', 'fs', '-mv', 'py-hadoop-output/type-hist.txt-temp-2015-07-24T17-05-29.290633', 'py-hadoop-output/type-hist.txt'] failed [exit code 255]
---stdout---

---stderr---
15/07/24 17:08:11 INFO gcs.GoogleHadoopFileSystemBase: GHFS version: 1.4.1-hadoop1
mv: Google Cloud Storage path must not have consecutive '/' characters, got '/py-hadoop-output/type-hist.txt/_logs/history/job_201507202121_0001_1437757538771_kwurster_%22TypeHist(infiles=gs://a-directory/input/'
Usage: java FsShell [-mv <src> <dst>]
------------
```

**Comment by Tarrasch** [comment]
Have you tried running `['hadoop', 'fs', '-mv', 'py-hadoop-output/type-hist.txt-temp-2015-07-24T17-05-29.290633', 'py-hadoop-output/type-hist.txt']` for the `hadoop fs` cli? It really seems like a bug in the connector. There's not consecutive `/` characters in that input. No?

**Comment by geowurster** [comment]
@Tarrasch The problem is a logfile inside `py-hadoop-output/type-hist.txt-temp-2015-07-24T17-05-29.290633` and the only process that would be aware of `TypeHist(infiles=gs://gfw-hadoop-test-asia/input/` is something Luigi related, although I'm not quite sure how the file could be created without triggering the GCS error.  That command generates the same error.

I found [`luigi.contrib.hadoop.run_and_track_hadoop_job()`](https://github.com/spotify/luigi/blob/master/luigi/contrib/hadoop.py#L244-L334) and it looks like this might be writing offending file with `write_luigi_history()`.  I'm out of time today but will pick this up again on Monday.

Here's the output from the command you suggested running:

```console
$ hadoop fs -mv /py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113 py-hadoop-output/T.txt
15/07/24 20:45:40 INFO gcs.GoogleHadoopFileSystemBase: GHFS version: 1.4.1-hadoop1
mv: Google Cloud Storage path must not have consecutive '/' characters, got '/py-hadoop-output/T.txt/_logs/history/job_201507202121_0002_1437758970979_kwurster_%22TypeHist(infiles=gs://gfw-hadoop-test-asia/input/'
Usage: java FsShell [-mv <src> <dst>]
```

**Comment by Tarrasch** [comment]
@geowurster, can you describe how `/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113` is an offending file path? Yes, luigi typically appends a `temp-1234567890` part to files for atomic moves. But the path seems valid.

In particular, the gcs connector complains about `consecutive '/'` of which there are none. No?

**Comment by geowurster** [comment]
@Tarrasch Sure.  So this file path appears to be fine:

```console
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113
```

except that since its in HDFS its actually a directory containing smaller subsets of the data and some ancillary files:

```console
$ hadoop fs -ls /py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/_logs
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/_SUCCESS
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00000
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00001
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00002
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00003
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00004
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00005
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00006
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00007
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00008
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00009
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00010
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00011
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00012
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00013
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00014
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00015
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00016
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00017
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00018
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00019
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00020
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00021
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00022
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00023
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/part-00024
```

One of these ancillary files is a directory called `_logs` that contains a single subdirectory called `history` that contains two files:

```console
$ hadoop fs -ls /py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/_logs/history/job_201507202121_0002_conf.xml
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/_logs/history/job_201507202121_0002_1437758970979_kwurster_%22TypeHist%28infiles%3Dgs%3A%2F%2Fgfw-hadoop-test-asia%2Finput%2F
```

the last of which is the file that contains the `//`:

```console
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/_logs/history/job_201507202121_0002_1437758970979_kwurster_%22TypeHist%28infiles%3Dgs%3A%2F%2Fgfw-hadoop-test-asia%2Finput%2F
```

Here's what it looks like if you decode the URL:

```console
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113/_logs/history/job_201507202121_0002_1437758970979_kwurster_"TypeHist(infiles=gs://gfw-hadoop-test-asia/input/
```

So, when the GCS connector copies this file:

```console
/py-hadoop-output/type-hist.txt-temp-2015-07-24T17-29-21.470113
```

It's actually copying a directory containing a bunch of other files, one of which contains a `//`.

Running `hadoop fs -cat` on this file shows that it is the MapReduce log, so I believe Luigi is capturing hadoop's log stream and dumping it into this file, as evidenced by the `TypeHist(` prefix.

**Comment by geowurster** [comment]
@tarrasch I should mention that `TypeHist` is the task I am executing from the commandline.

**Comment by Tarrasch** [comment]
Ok. Thanks for clarifying. I understand the problem now. :)

But I won't be able to fix it for you unfortunately. Let us know if anything hindering you from sending a PR.

**Comment by geowurster** [comment]
@Tarrasch Ok, will do.

**Comment by geowurster** [comment]
For anybody following along, it looks like the problem really is in the hadoop -> GCS connector.  Explicitly moving only the problem file with `hadoop fs -mv` or `gsutil mv` succeeds, but attempting to move the entire directory with either fails.  Interestingly, `gsutil` throws this error when attempting to move:

```console
Skipping cloud sub-directory placeholder object (gs://base/py-hadoop-output/type-hist.txt-temp-2015-07-27T18-48-47.879095/) because such objects aren't needed in (and would interfere with) directories in the local file system
```

**Comment by geowurster** [comment]
We tracked this down and believe its an issue with Google's Hadoop CLI not properly decoding a URL.

**Comment by Tarrasch** [comment]
Did you create a ticket in Google's issue tracker? Can you link to it?
