### ISSUE TITLE
luigi hadoop streaming didn't get to run

### ISSUE THREAD

**Issue by endeavorchan** [spotify/luigi#1095]
hi,
I tried to run the example wordcount_hadoop.py 
the debug info is:

No handlers could be found for logger "luigi-interface"
DEBUG: Checking if WordCount(date_interval=2015-07-24) is complete
cmd /home/work/luigi/journeyman/hadoop-client/hadoop/bin/hadoop
DEBUG: Running file existence check: /home/work/luigi/journeyman/hadoop-client/hadoop/bin/hadoop fs -stat /app/ecom/aries/vs/vsmed/zhouyang/cc/text-count/2015-07-24
INFO: Scheduled WordCount(date_interval=2015-07-24) (DONE)
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
INFO: Done
INFO: There are no more tasks to run at this time
INFO: Worker Worker(salt=466880144, workers=1, host=sh01-vs-health-dp00.sh01.baidu.com, username=work, pid=18406) was stopped. Shutting down Keep-Alive thread

It seems that hadoop didn't get to run 
I don't know why?
Any one can help? thanks in advance.

**Comment by erikbern** [comment]
It seems like the output file already exists. Is that the case?

**Comment by endeavorchan** [comment]
No, it didn't generate any output. 
We used to run Hadoop streaming job one by one, and now we want to use luigi to run a pipline of streaming jobs.

basically we use 

hadoop streaming  -D mapred.job.name=vsmed_chenchen34_python_wenda_del_tag -D mapred.job.priority=NORMAL -D mapred.job.map.capacity=1000 -D mapred.job.reduce.capacity=200 -D mapred.reduce.tasks=500 -D stream.num.map.output.key.fields=1 -D num.key.fields.for.partition=1 -partitioner org.apache.hadoop.mapred.lib.KeyFieldBasedPartitioner   -input /app/ecom/aries/vs/vsmed/zhouyang/jiaohuwenda/output_data/filt_disease_list/ -output /app/ecom/aries/vs/vsmed/zhouyang/jiaohuwenda/output_data/del_tag_repeated_ans_test -cacheArchive /share/python2.7.tar.gz#python27  -file del_tag.py -file /home/users/chenchen34/netdisk/journeyman/hadoop_scripts/HadoopUtil.py -mapper "python27/bin/python2.7 del_tag.py -p map" -reducer "python27/bin/python2.7 del_tag.py -p reduce"


this command to run a single hadoop job, it seems the command never gets to run.

In addition, Hadoop was deployed on another cluster and I want to deploy luigi on my own server and run hadoop remotely. Maybe I lost some configuration?


Thanks.

**Comment by endeavorchan** [comment]
ah, yeah. My bad. You are right, erikbern. I already create the file. So it didn't get to run.  Thanks!

**Comment by Tarrasch** [comment]
Closing :)

Hopefully @nicolehedblom's patch in #1091 will make these bug reports a thing of the past.
