### ISSUE TITLE
Truthiness of luigi.Parameter is unexpected.

### ISSUE THREAD

**Issue by mrdrozdov** [spotify/luigi#1100]
I'd expect the following to make sense.

```python
class MyTask(luigi.Task):
  some_field = luigi.Parameter(default=None)
  def run(self):
    if self.some_field:
      doStuff()
    else:
      raise RuntimeError("The some_field is None")
```

Except we always enter the first block and `doStuff` even when some_field=None.

This could be fixed by overriding the bool functionality of the Parameter class. Something similar as what's seen in this SO post. http://stackoverflow.com/questions/2233786/overriding-bool-for-custom-class

**Comment by erikbern** [comment]
Can you send a full breaking example? I doubt there's actually an issue here – this is such a central component that we would have seen massive issues earlier

**Comment by mrdrozdov** [comment]
@erikbern You can try running this example off my branch. Exception should be thrown. 

https://github.com/mrdrozdov/luigi/tree/mrdrozdov/truthiness

```
python examples/bool.py
```

**Comment by mrdrozdov** [comment]
Double checking.

**Comment by mrdrozdov** [comment]
Looks like I might be wrong? I definitely saw this happen today, but can't repro. This could be a-okay.

PS. I posted an example but it was contradictory to my point so I deleted the comment.

**Comment by mrdrozdov** [comment]
I wonder if we're using a different version of Luigi.

**Comment by mrdrozdov** [comment]
Well... It looks like it's fine! Sheez. We have this code block.

```python
something = luigi.Parameter(default=None)

def run(self):
  if self.something:
    log("Something is [%s]" % self.something)
```

And in our logs, I can see:

```
Something is [None]
```

Maybe we're passing a None string? Which would be ridiculous. Anyway, I can't reproduce the problem, but I did learn a little bit about override python object truthiness today. Sorry for the false alarm @erikbern !

**Comment by mrdrozdov** [comment]
For posterity, this is the example I put together. It proves that the issue is actually a non-issue. https://github.com/mrdrozdov/luigi/blob/ad5d9e245e9ef583cf1f89b54124e531a4a40396/examples/bool.py

**Comment by erikbern** [comment]
and in your example it runs correctly?

**Comment by mrdrozdov** [comment]
Correct. If there was an issue, I'd expect the RuntimeError to be thrown, but the error is not thrown.
