### ISSUE TITLE
hadoop streaming stuck on 0%

### ISSUE THREAD

**Issue by endeavorchan** [spotify/luigi#1105]
Hi,
Recently, I post the same question.  (I use luigi to run mapreduce and the program gets sucked)

Now I find that the problem is in

luigi/mrrunner.py   in  CLASS Runner

class Runner(object):
    """ 
    Run the mapper or reducer on hadoop nodes.
    """
    def __init__(self, job=None):
        self.extract_packages_archive()
        self.job = job or pickle.load(open("job-instance.pickle", "rb"))
        self.job._setup_remote()
 ...

When I delete this  "self.job = job or pickle.load(open("job-instance.pickle", "rb")) " the programme gets to run. It seems luigi failed to load "job-instance.pickle"  in hadoop cluster.    

I noticed in the debug report:

INFO: /home/work/luigi/journeyman/hadoop-client/hadoop/bin/hadoop jar /home/work/luigi/journeyman/hadoop-client/hadoop/contrib/streaming/hadoop-2-streaming.jar -D mapred.job.name="WordCount(date_interval=2015-07-24)" -D mapred.reduce.tasks=25 -mapper python mrrunner.py map -reducer python mrrunner.py reduce -file /home/work/local/lib/python2.7/site-packages/luigi-1.2.2-py2.7.egg/luigi/mrrunner.py -file /tmp/tmp8reXTj/packages.tar -file /tmp/tmp8reXTj/job-instance.pickle -input /app/ecom/aries/vs/vsmed/zhouyang/cc/text-count/2015-07-24.txt -output /app/ecom/aries/vs/vsmed/zhouyang/cc/text/2015-07-24-temp-2015-07-31T13-56-37.397800

" -file /tmp/tmp8reXTj/packages.tar -file /tmp/tmp8reXTj/job-instance.pickle"

These two files were included. However, I can't find these two files in /tmp.  

Someone know what's going on. Hope my question is qualified this time.  Thanks in advance.

Chen

**Comment by Tarrasch** [comment]
I have no idea Chen. This functionality is working for others. Maybe try to make a small sample you can quickly iterate on (perhaps using minicluster) and then remove stuff from you example iteratively until you find the culprit.

Good luck!

**Comment by erikbern** [comment]
Do you have the output from Hadoop?

I remember vaguely seeing a bug where sometimes if you don't have permission to write to output, the mapreduce job gets stuck at 0%. Maybe check that you have permission to write to the output directory?

**Comment by endeavorchan** [comment]
Thanks.

I found that in this line of codes " pickle.load(open("job-instance.pickle", "rb"))"

open("job-instance.pickle", "rb") succeeds. The file job-instance.pickle do exists on the cluster. But when use pickle to deserialize the class, it failed and there is a IO exception according to the log in hadoop cluster.

I try to run pickle.load(open("job-instance.pickle", "rb")) locally. It seems that the first time I run, it output an warning message which is `No handlers could be found for logger "luigi-interface"`.   I'm just suspecting that this output may cause the exception.  (Maybe I'm wrong).  So is there a way to avoid this warning?

Thanks so much!

**Comment by erikbern** [comment]
Can you send the full output of the mapreduce job running on the hadoop cluster

**Comment by endeavorchan** [comment]
ok


INFO: /home/work/luigi/journeyman/hadoop-client/hadoop/bin/hadoop jar /home/work/luigi/journeyman/hadoop-client/hadoop/contrib/streaming/hadoop-2-streaming.jar -D mapred.job.name="WordCount(date_interval=2015-07-24)" -D mapred.reduce.tasks=25 -mapper python mrrunner.py map -reducer python mrrunner.py reduce -file /home/work/local/lib/python2.7/site-packages/luigi-1.2.2-py2.7.egg/luigi/mrrunner.py -file /tmp/tmpyTXCIT/packages.tar -file /tmp/tmpyTXCIT/job-instance.pickle -input /app/ecom/aries/vs/vsmed/zhouyang/cc/text-count/2015-07-24.txt -output /app/ecom/aries/vs/vsmed/zhouyang/cc/text/2015-07-24-temp-2015-08-04T11-33-40.973921
INFO: 15/08/04 11:33:45 INFO mapred.JobClient: class org.apache.hadoop.security.UnixUserGroupInformation
INFO: 15/08/04 11:33:45 INFO mapred.JobClient: class org.apache.hadoop.security.UnixUserGroupInformation
INFO: 15/08/04 11:33:46 INFO hdfs.FMSClient: Write 38562072659316765 in pipeline 10.73.66.32:7001, 10.73.71.20:7001, 10.73.172.41:7001, 10.73.39.54:7001, 10.73.86.50:7001, 10.73.86.39:7001, 10.73.19.57:7001, 10.73.78.58:7001, 10.73.47.40:7001, 10.75.28.57:7001
INFO: 15/08/04 11:33:49 INFO util.NativeCodeLoader: Loaded the native-hadoop library
INFO: 15/08/04 11:33:49 INFO compress.LzoCodec: Successfully loaded & initialized native-lzo library
INFO: 15/08/04 11:33:49 INFO compress.LzmaCodec: Successfully loaded & initialized native-lzma library
INFO: 15/08/04 11:33:49 INFO compress.QuickLzCodec: Successfully loaded & initialized native-quicklz library
INFO: 15/08/04 11:33:49 INFO mapred.FileInputFormat: getInputPaths: dirs: hdfs://nmg01-mulan-hdfs.dmop.baidu.com:54310/app/ecom/aries/vs/vsmed/zhouyang/cc/text-count/2015-07-24.txt
INFO: 15/08/04 11:33:49 INFO mapred.FileInputFormat: Total input paths to process : 1
INFO: 15/08/04 11:33:49 WARN mapred.FileInputFormat: Split size is optimized by default, you can set 'abaci.split.optimize.enable=false' to skip it
INFO: 15/08/04 11:33:49 INFO hdfs.FMSClient: Write 17451449740115761 in pipeline 10.73.47.47:7001, 10.75.20.26:7001, 10.75.56.48:7001
INFO: 15/08/04 11:33:50 INFO mapred.JobClient: splits size : 1
INFO: 15/08/04 11:33:51 INFO hdfs.FMSClient: Write 20829149460375497 in pipeline 10.73.87.25:7001, 10.73.165.14:7001, 10.73.84.49:7001
INFO: 15/08/04 11:33:51 INFO split.SplitUtils: create hdfs://nmg01-mulan-hdfs.dmop.baidu.com:54310/app/dc/deva/system/mapred/job_20150721201233_723113/split.done
INFO: 15/08/04 11:33:51 INFO hdfs.FMSClient: Write 17169974763405257 in pipeline 10.75.23.15:7001, 10.73.167.12:7001, 10.73.58.48:7001
INFO: 15/08/04 11:33:52 INFO mapred.JobClient: Running job: job_20150721201233_723113
INFO: 15/08/04 11:33:52 INFO mapred.JobClient: To kill this job, run:
INFO: 15/08/04 11:33:52 INFO mapred.JobClient: /home/work/luigi/journeyman/hadoop-client/hadoop/bin/../bin/hadoop job -Dmapred.job.tracker=nmg01-mulan-job.dmop.baidu.com:54311 -kill job_20150721201233_723113
INFO: 15/08/04 11:33:52 INFO mapred.JobClient: Tracking URL: http://nmg01-mulan-mapred11.nmg01.baidu.com:8030/jobproxy.jsp?jobid=job_20150721201233_723113
INFO: 15/08/04 11:34:10 INFO mapred.JobClient:  map 0% reduce 0%
INFO: 15/08/04 11:35:35 INFO mapred.JobClient: Updating completed job! Ignoring ...
INFO: 15/08/04 11:35:35 INFO mapred.JobClient: Updating completed job! Ignoring ...
INFO: 15/08/04 11:35:35 ERROR mapred.JobClient: Job not Successful!
INFO: Streaming Job Failed!
ERROR: [pid 2412] Worker Worker(salt=798270974, workers=1, host=sh01-vs-health-dp00.sh01.baidu.com, username=work, pid=2412) failed    WordCount(date_interval=2015-07-24)
Traceback (most recent call last):
  File "/home/work/local/lib/python2.7/site-packages/luigi-1.2.2-py2.7.egg/luigi/worker.py", line 137, in run
    new_deps = self._run_get_new_deps()
  File "/home/work/local/lib/python2.7/site-packages/luigi-1.2.2-py2.7.egg/luigi/worker.py", line 88, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/work/local/lib/python2.7/site-packages/luigi-1.2.2-py2.7.egg/luigi/contrib/hadoop.py", line 667, in run
    self.job_runner().run_job(self)
  File "/home/work/local/lib/python2.7/site-packages/luigi-1.2.2-py2.7.egg/luigi/contrib/hadoop.py", line 517, in run_job
    run_and_track_hadoop_job(arglist)
  File "/home/work/local/lib/python2.7/site-packages/luigi-1.2.2-py2.7.egg/luigi/contrib/hadoop.py", line 335, in run_and_track_hadoop_job
    return track_process(arglist, tracking_url_callback, env)
  File "/home/work/local/lib/python2.7/site-packages/luigi-1.2.2-py2.7.egg/luigi/contrib/hadoop.py", line 325, in track_process
    (tracking_url, e), out, err)
HadoopJobError: ('Streaming job failed with exit code 1. Additionally, an error occurred when fetching data from http://nmg01-mulan-mapred11.nmg01.baidu.com:8030/jobproxy.jsp?jobid=job_20150721201233_723113: No module named mechanize', 'packageJobJar: [/home/work/local/lib/python2.7/site-packages/luigi-1.2.2-py2.7.egg/luigi/mrrunner.py, /tmp/tmpyTXCIT/packages.tar, /tmp/tmpyTXCIT/job-instance.pickle, /home/work/hadoop-v2/hadoop-data/hadoop-unjar3402696732145068550/] [] /tmp/streamjob8791689882851898594.jar tmpDir=null\n', "15/08/04 11:33:45 INFO mapred.JobClient: class org.apache.hadoop.security.UnixUserGroupInformation\n15/08/04 11:33:45 INFO mapred.JobClient: class org.apache.hadoop.security.UnixUserGroupInformation\n15/08/04 11:33:46 INFO hdfs.FMSClient: Write 38562072659316765 in pipeline 10.73.66.32:7001, 10.73.71.20:7001, 10.73.172.41:7001, 10.73.39.54:7001, 10.73.86.50:7001, 10.73.86.39:7001, 10.73.19.57:7001, 10.73.78.58:7001, 10.73.47.40:7001, 10.75.28.57:7001\n15/08/04 11:33:49 INFO util.NativeCodeLoader: Loaded the native-hadoop library\n15/08/04 11:33:49 INFO compress.LzoCodec: Successfully loaded & initialized native-lzo library\n15/08/04 11:33:49 INFO compress.LzmaCodec: Successfully loaded & initialized native-lzma library\n15/08/04 11:33:49 INFO compress.QuickLzCodec: Successfully loaded & initialized native-quicklz library\n15/08/04 11:33:49 INFO mapred.FileInputFormat: getInputPaths: dirs: hdfs://nmg01-mulan-hdfs.dmop.baidu.com:54310/app/ecom/aries/vs/vsmed/zhouyang/cc/text-count/2015-07-24.txt\n15/08/04 11:33:49 INFO mapred.FileInputFormat: Total input paths to process : 1\n15/08/04 11:33:49 WARN mapred.FileInputFormat: Split size is optimized by default, you can set 'abaci.split.optimize.enable=false' to skip it\n15/08/04 11:33:49 INFO hdfs.FMSClient: Write 17451449740115761 in pipeline 10.73.47.47:7001, 10.75.20.26:7001, 10.75.56.48:7001\n15/08/04 11:33:50 INFO mapred.JobClient: splits size : 1\n15/08/04 11:33:51 INFO hdfs.FMSClient: Write 20829149460375497 in pipeline 10.73.87.25:7001, 10.73.165.14:7001, 10.73.84.49:7001\n15/08/04 11:33:51 INFO split.SplitUtils: create hdfs://nmg01-mulan-hdfs.dmop.baidu.com:54310/app/dc/deva/system/mapred/job_20150721201233_723113/split.done\n15/08/04 11:33:51 INFO hdfs.FMSClient: Write 17169974763405257 in pipeline 10.75.23.15:7001, 10.73.167.12:7001, 10.73.58.48:7001\n15/08/04 11:33:52 INFO mapred.JobClient: Running job: job_20150721201233_723113\n15/08/04 11:33:52 INFO mapred.JobClient: To kill this job, run:\n15/08/04 11:33:52 INFO mapred.JobClient: /home/work/luigi/journeyman/hadoop-client/hadoop/bin/../bin/hadoop job -Dmapred.job.tracker=nmg01-mulan-job.dmop.baidu.com:54311 -kill job_20150721201233_723113\n15/08/04 11:33:52 INFO mapred.JobClient: Tracking URL: http://nmg01-mulan-mapred11.nmg01.baidu.com:8030/jobproxy.jsp?jobid=job_20150721201233_723113\n15/08/04 11:34:10 INFO mapred.JobClient:  map 0% reduce 0%\n15/08/04 11:35:35 INFO mapred.JobClient: Updating completed job! Ignoring ...\n15/08/04 11:35:35 INFO mapred.JobClient: Updating completed job! Ignoring ...\n15/08/04 11:35:35 ERROR mapred.JobClient: Job not Successful!\nStreaming Job Failed!\n")
INFO: Skipping error email. Set `error-email` in the `core` section of the luigi config file to receive error emails.
DEBUG: Removing directory /tmp/tmpyTXCIT
DEBUG: 1 running tasks, waiting for next task to finish
DEBUG: Asking scheduler for work...
INFO: Done
INFO: There are no more tasks to run at this time
INFO: Worker Worker(salt=798270974, workers=1, host=sh01-vs-health-dp00.sh01.baidu.com, username=work, pid=2412) was stopped. Shutting down Keep-Alive thread

##The above is the whole output. I figured out to eliminate the warning output. But it still  stuck on 0%.
and below is the exception threw out.


java.io.IOException: hce child exception : subprocess exited with code 143
	at org.apache.hadoop.mapred.hce.Application.abort(Application.java:881)
	at org.apache.hadoop.mapred.hce.HceMapRunner.run(HceMapRunner.java:88)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:383)
	at org.apache.hadoop.mapred.Child.main(Child.java:226)
Caused by: java.lang.Throwable: TaskContext closeAll() failed!
	at org.apache.hadoop.mapred.hce.BinaryProtocol$UplinkReaderThread.run(BinaryProtocol.java:143)


-------
updated

**Comment by erikbern** [comment]
This seems like the output of the job locally. What about output from the tasktracker?

**Comment by endeavorchan** [comment]
You mean info from that tracking url?    I can't see any other output.

**Comment by endeavorchan** [comment]
thanks erikbern

this is the error message 

Traceback (most recent call last):
  File "mrrunner.py", line 102, in <module>
    main()
  File "mrrunner.py", line 95, in main
    Runner().run(kind, stdin=stdin, stdout=stdout)
  File "mrrunner.py", line 49, in __init__
    self.job = job or pickle.load(open("job-instance.pickle", "rb"))
  File "wordcount_hadoop.py", line 18, in <module>
    import luigi
  File "luigi/__init__.py", line 21, in <module>
    from luigi import task
  File "luigi/task.py", line 34, in <module>
    from luigi.task_register import Register, TaskClassException
  File "luigi/task_register.py", line 25, in <module>
    from ordereddict import OrderedDict
ImportError: No module named ordereddict
HCE_WARNING 08-04 14:08:04  [PipeStreaming.cc:11


seems I don't have this module

**Comment by endeavorchan** [comment]
hi erikbern,

With your suggestion, I finally get it to run. Thanks.

I am new to hadoop, so ashamed that I always debug locally and never try to see the log of the hadoop tracker.  

The problem is because the python run on the cluster is version 2.6.
And there is another problem  is  in contrib/hadoop.py

from cached_property import cached_property

there is no such module, so I put cached_property.py in the directory.

I highly suggested that you can include cached_property.py in the contrib directory. Because it's not a default python library.

Thanks again for your help.

Chen

**Comment by erikbern** [comment]
I think it's fine to require 2.7 installed on the task trackers, but I don't think we should require any particular packages to be installed. We shouldn't depend on `cached_property` in hadoop.py when running Hadoop job.

**Comment by Tarrasch** [comment]
Hmm, is this just a matter of doing `import attached_property; attach(cached_property)`? Though I imagined our minicluster tests should have caught this. Perhaps not :-/.

@endeavorchan, since you're deep into this problem and have good understanding by now. Do you mind sending a PR with the fix? :)

**Comment by endeavorchan** [comment]
No problem. I'll do that latter.

**Comment by erikbern** [comment]
yeah or just avoid importing `cached_property` if it's not part of the standard library
