### ISSUE TITLE
Luigi on top of AWS 

### ISSUE THREAD

**Issue by kwent** [spotify/luigi#1113]
Hi,

I would like to know how easy it would be to use Luigi on top of AWS.

Maybe i could launch a workflow where each task is executed over AWS Lambda.

Any thoughts and any good start to realize that with Luigi ?

Regards,

**Comment by Tarrasch** [comment]
Have you tried searching the history in the luigi-users google group? There are quite many companies using luigi with AWS.

**Comment by kwent** [comment]
Oh nice i will take a closer look to the google group. Closing for now.
