### ISSUE TITLE
How to cancel/stop a pending task?

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1116]
task A requires task B, when B is running, I want to stop taskB, and cancel taskA.

what can I do ?

**Comment by Tarrasch** [comment]
There's no way to do this from the central scheduler. The only way is to cancel the job manually.

**Comment by leafjungle** [comment]
@Tarrasch , I see.  But how can I cancel a task manually? It will always waiting for the complementation of required tasks.

**Comment by Tarrasch** [comment]
I meant something naive like "Ctrl+C". :)

**Comment by leafjungle** [comment]
the solution:
ps -ef |grep luigi |grep -v luigid |grep "xxxx" 
kill -9 yyyyy

Thanks @Tarrasch very much, and this question is closed.

**Comment by jumanSalameh** [comment]
I am having a problem with a zombie task. I have some tasks running in luigi centralized server but there's one specific task that's been running forever and I need to kill it. can anyone help with that please?

**Comment by elipapa** [comment]
is this still the case?

**Comment by dlstadther** [comment]
@elipapa As far as i'm aware, yes. If the session is active and in the foreground, `ctrl+c`; if it's in the background, `ps -ef .... kill <pid>`.

**Comment by aschmu** [comment]
I think this is weird that there's no abort button. Do people who use luigi in production have custom scripts to handle this case ?

**Comment by Tarrasch** [comment]
@aschmu, it was recently added in Luigi (not sure if it's released yet).

> Do people who use luigi in production have custom scripts to handle this case ?

I do think you still need to do some manual hacking and have some understanding on where stuff is running and how to cancel it to operate luigi.

**Comment by H4dr1en** [comment]
Still the case?

**Comment by joooeey** [comment]
It would be sweet to have this feature!

**Comment by morales0021** [comment]
I dont understand why they can just put a cancel button
