### ISSUE TITLE
Support unix sockets for faster internal connections

### ISSUE THREAD

**Issue by graingert** [spotify/luigi#1118]
We plan to have one machine with luigid running, with the web-gui protected by Nginx auth.

It would be great if we could use a unix socket for improved internal networking performance both for the nginx proxy and the luigi workers.

**Comment by erikbern** [comment]
Good idea – feel free to put together a pull request!

**Comment by gpoulin** [comment]
@graingert Did you have a benchmark that show that the tcp connection is a bottleneck in your case? I have the impression it won't make that much a difference. Maybe for the worker using a connection pool (are we doing it at the moment?), would be easier the implement and would have benefice for more use cases.

**Comment by graingert** [comment]
we also don't need to make a firewall rule

**Comment by tashrifbillah** [comment]
Hi @graingert , can you give an example about how to write a unix-socket for luigid?

**Comment by graingert** [comment]
@tashrifbillah sorry, I don't use this library anymore

**Comment by tashrifbillah** [comment]
For future Googlers, here is my show and tell on this topic:

https://groups.google.com/g/luigi-user/c/PTLkefG8oNI
