### ISSUE TITLE
Luigi Truck Factor

### ISSUE THREAD

**Issue by gavelino** [spotify/luigi#1120]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Luigi** and obtained a value of **6**.

The developers responsible for this TF are:

Erik Bernhardsson - author of 41% of the files
Elias Freider - author of 12% of the files
Joe Crobak - author of 6% of the files
Pedro Salgado (steenzout) - author of 6% of the files
Alexander Krasnukhin - author of 6% of the files
Joe Ennever - author of 6% of the files

To validate our results, we would like to ask **Luigi** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Luigi**?

(b) Do you agree that **Luigi** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Luigi** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by Tarrasch** [comment]
I'm not mentioned in the truck factor? I'm pretty sure me (and Erik) are the main truck factor people. :)

Sorry, but your algorithm is completely incorrect for this repository. I would suggest you look more at recent committers over original creators of files, which is completely misleading your algorithm in this case.
