### ISSUE TITLE
Long tuples in map reduce

### ISSUE THREAD

**Issue by stroykova** [spotify/luigi#1123]
Hello!

I have started to use luigi for hadoop streaming. Jobs with "key\tvalue" records work fine. But when I started to use "key\tvalue1\tvalue2..." tuples, reduce function receives value1 only. Reason is in ```hadoop.JobTask._reduce_input``` function:

```
def _reduce_input(self, inputs, reducer, final=NotImplemented):
        """
        Iterate over input, collect values with the same key, and call the reducer for each unique key.
        """
        for key, values in groupby(inputs, key=lambda x: self.internal_serialize(x[0])):
            for output in reducer(self.deserialize(key), (v[1] for v in values)):
                yield output
        if final != NotImplemented:
            for output in final():
                yield output
        self._flush_batch_incr_counter()
```

Should it be ```v[1:]``` instead of ```v[1]```?
Is it bug or feature?

I can always redefine this function in subclass, but it looks like a bug.

**Comment by stroykova** [comment]
Also, hadoop streaming has settings like this:

```
    # partition by [0]
    # sort by [0, 1, 2, 3]
    'mapred.text.key.partitioner.options': '-k1,1',
    'stream.num.map.output.key.fields': 4,
```

It means, that key possibly has different length. 
Class can has field ```key_length```, so this function will group by ```x[:key_length]``` and reduce values like```v[key_length:]```.

This feature can became a feature request, if it corresponds with luigi architecture. Or can be recommended as implementation for every ```hadoop.JobTask``` subclass.

**Comment by Tarrasch** [comment]
I think you do

    yield k, (v1, v2)

over

    yield k, v1, v2

**Comment by stroykova** [comment]
Thank you, that was the problem.

**Comment by Tarrasch** [comment]
Great, closing then :)

**Comment by erikbern** [comment]
we should probably raise an exception when you yield a non-tuple or a tuple with anything else than 2 arguments

**Comment by stroykova** [comment]
@erikbern sounds good. At least small example in documentation will help to understand this error.

**Comment by Tarrasch** [comment]
@stroykova, do you mind creating some docs or checks? :)
