### ISSUE TITLE
Issues Opening Local Target as Output

### ISSUE THREAD

**Issue by nickthorpe** [spotify/luigi#1144]
When attempting to open and write to output with the following syntax (paper_output = self.output().open('w')) no file is created following the run (on AWS EC2 instance... running Ubuntu). This was the syntax given in the documentation here: http://luigi.readthedocs.org/en/stable/tasks.html (see Task.run)

The same syntax works running on Windows 10. When the line was changed to the following syntax (        with self.output().open('w') as paper_output:) the output was successfully created (on both operating systems).

**Comment by erikbern** [comment]
Did you close the file? (just making sure)

**Comment by nickthorpe** [comment]
... I did not. tested it and worked. thank you for the quick response!

**Comment by erikbern** [comment]
no problem :)
