### ISSUE TITLE
Config: `error-email` is not recognized by luigid

### ISSUE THREAD

**Issue by Yoone** [spotify/luigi#1148]
I have a `client.cfg`, automatically loaded by luigid:

    2015-08-19 16:02:03,549 luigi-interface[8164] INFO: Loaded ['client.cfg']
    2015-08-19 16:02:03,551 luigi.server[8164] INFO: No prior state file exists at /var/lib/luigi-server/state.pickle. Starting with clean slate
    2015-08-19 16:02:03,554 luigi.server[8164] INFO: Scheduler starting up

Here are what the contents of the file look like:

    [core]
    error-email: ybentz@*******.com

But when I get an error from executing a script, it still outputs this:

    INFO: Skipping error email. Set `error-email` in the `core` section of the luigi config file to receive error emails.

**Comment by Tarrasch** [comment]
That's odd. Are you using HEAD? There recently was one or two PRs merged related to email sending. Hmm..

**Comment by Yoone** [comment]
I have luigi 1.3.0, but the code seems to be different from what I can see on the repo. Oh and I'm using Python 3.4, I don't know if that matters...

**Comment by Tarrasch** [comment]
You need to restart luigid before it honors your config change I think. But error-email is related to the clients, not luigid.

**Comment by Yoone** [comment]
I did restart luigid after every change, and changing the port for instance didn't work.

My bad about the clients, it did work once I put it in the right directory, thank you.

**Comment by Tarrasch** [comment]
Cool, closing then. Please feel free to add the any documentation so the next user will not be confused. :)
