### ISSUE TITLE
restart scheduler is required when index.html is edited?

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1151]
static/visualiser/index.html

When I edit this file, I have to restart the center scheduler to make the modification effective.

why? is there any solution to make the modification effective by refresh the browser?

**Comment by Tarrasch** [comment]
Hmm, it that perhaps a Browser or Tornado setting? I've never developed on the visualizer tbh. :)

**Comment by leafjungle** [comment]
I think tornado setting options could be found to enable the modification effective immediately, but I can not found it.

And another solution is that after modify index.html, just restart the center planner.  But after that, all the tasks are cleared from the visualizer.

**Comment by Tarrasch** [comment]
@leafjungle what? `luigid`, if properly configured, should save a state file on exit and read it. It was made for this purpose I think, so you can restart the server (on upgrades) without losing state.

**Comment by leafjungle** [comment]
@Tarrasch , 

(1)I see, I stop the luigid by kill -9 , which is not the correct way.

(2) I am wonderring a problem: when I am restarting the luigid, I run a new task, will this task be skipped?

(3) each time after editing index.html, I do not want to restart luigid. I find that tornado will not reload any modification if debug set to false.
so tornado setup option should add: debug=true .

**Comment by leafjungle** [comment]
@Tarrasch , But I am wondering how to add "debug=True" option to tornado ~

**Comment by leafjungle** [comment]
The problem is solved by editing server.py, add "debug": True to settings of tornado Application.

**Comment by Tarrasch** [comment]
@leafjungle, cna you show more in detial where you added `"debud": True`? For future reference I mean.

**Comment by leafjungle** [comment]
@Tarrasch 
server.py
settings = {"static_path": os.path.join(os.path.dirname(__file__), "static"), "unescape": tornado.escape.xhtml_unescape}
-->
settings = {"static_path": os.path.join(os.path.dirname(__file__), "static"), "unescape": tornado.escape.xhtml_unescape, "debug": True}
