### ISSUE TITLE
how to get task id of each Task?

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1152]
As I can see in the source: scheduler.py of "class Task"

self.id = task_id

https://github.com/spotify/luigi/blob/a4da86914d77284145f42b332d49383981b08d40/luigi/scheduler.py

so each task has a attribute "id"?

in my task, when I use "self.id", an error occured:

object has no attribute 'id'

And other question:  this id is the same as the "id" stored in mysql tasks table?

**Comment by erikbern** [comment]
There are two (at least) classes named `Task` somewhat confusingly. Look at task.py

**Comment by leafjungle** [comment]
@erikbern , 
And other question: this id is the same as the "id" stored in mysql tasks table?

It seems that I can not find  "insert into tasks" table  source code?

**Comment by erikbern** [comment]
i think it's the same thing yeah
