### ISSUE TITLE
Task history breaks if you specify an empty string as a parameter value

### ISSUE THREAD

**Issue by martinxsliu** [spotify/luigi#1171]
The task history interface currently uses the [id_to_name_and_params](https://github.com/spotify/luigi/blob/1596c06e75c65f09a0e824f03ccab36f8790525f/luigi/tools/parse_task.py) function to parse the task_id into a (task_family, {params}) tuple.

Unfortunately, the parsing patterns used is not robust to empty parameter values (e.g. task_id = 'Foo(bar=bar, baz=)' as the value token is omitted.

Does anyone have an easy fix for this, otherwise I'll try to submit a PR sometime soon?

**Comment by Tarrasch** [comment]
No, there's no easy fix. It's just broken. :(

We would very happy to review a PR removing the use of that function. :)

**Comment by erikbern** [comment]
ugh i've maintained for a long time that we need to kill the `id_to_name_and_params` function.

maybe i should just go ahead and do it. i hate it

**Comment by martinxsliu** [comment]
Fixed by https://github.com/spotify/luigi/pull/1309
