### ISSUE TITLE
puzzled with task.complete() function

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1183]
outputs = flatten(self.output())
return all(map(lambda output: output.exists(), outputs))

what does this mean? it means that once the output folder exists, this task is finished?

**Comment by Tarrasch** [comment]
Yes. But you are free to override the `complete()` definition.

**Comment by erikbern** [comment]
woudl be cleaner with `return all([output.exists() for output in flatten(self.output()])` imho

**Comment by leafjungle** [comment]
Yes. But you are free to override the complete() definition.

@Tarrasch , yeah, I override this function. I just do not understand the default implemtation.

**Comment by sisidra** [comment]
Default implementation returns true iff all possible outputs exists.
`def output(self):` can return multiple outputs, complex structure same as `def requires(self):`
For example:
```def output(self):
  return { "tsv": HdfsTarget("/path/to/tsv"), "csv": HdfsTarget("/path/to/csv") }
def run(self):
  self.output()["tsv"].open().write("asd\tasd").close()
  self.output()["csv"].open().write("asd,asd").close()```

**Comment by sisidra** [comment]
@erikbern more understandable usually is expanded version (for loop) not oneliners :P

**Comment by leafjungle** [comment]
@sisidra, But if the task file write several files, how does complete() function knows whether all the files are done?
( complete() function is not called by this task himself, but called by other tasks).

**Comment by Tarrasch** [comment]
@leafjungle it knows by using the default implementation of `complete()`.

**Comment by sisidra** [comment]
Yes, that's what default implementation does: checks if all of targets exists. If any does not, it returns false.
This is one of reasons why HdfsTarget and LocalTarget are atomic when you do `*Target().open() ...write() ...close()` with writing to temp file and moving to actual location on close.
