### ISSUE TITLE
Problem with running PySpark task

### ISSUE THREAD

**Issue by maver1ck** [spotify/luigi#1185]
Hi,
I have problem with running PySpark task.

	spark@spark-1:~$ cat MyTaskPySpark.py
	import sys
	import luigi
	from luigi.contrib.spark import PySparkTask

	print(sys.version)

	class MyTaskPySpark(PySparkTask):
			def main(self, sc):
					#sc.addPyFile(mojskrypt.py)
					sc.addPyFile("/mnt/spark/mytask.py")
					x = sc.parallelize(['a','b','c','a','b'])
					x = x.map(lambda s: (s, 1)).reduceByKey(lambda a, b: a + b)
					print x.collect()

	if __name__ == "__main__":
			luigi.run()

	spark@spark-1:~$ cat client.cfg
	[spark]
	spark-submit: /mnt/spark/spark/bin/spark-submit
	master: spark://spark-1:7077
	py-files: ["MyTaskPySpark.py"]

	spark@spark-1:~$ python MyTaskPySpark.py MyTaskPySpark --local-scheduler
	2.7.6 (default, Jun 22 2015, 17:58:13)
	[GCC 4.8.2]
	DEBUG: Checking if MyTaskPySpark() is complete
	/usr/local/lib/python2.7/dist-packages/luigi/worker.py:211: UserWarning: Task MyTaskPySpark() without outputs has no custom complete() method
	  is_complete = task.complete()
	INFO: Scheduled MyTaskPySpark() (PENDING)
	INFO: Done scheduling tasks
	INFO: Running Worker with 1 processes
	DEBUG: Asking scheduler for work...
	DEBUG: Pending tasks: 1
	INFO: [pid 23193] Worker Worker(salt=993230963, workers=1, host=spark-1, username=spark, pid=23193) running   MyTaskPySpark()
	INFO: Running: ['/mnt/spark/spark/bin/spark-submit', '--master', 'spark://spark-1:7077', '--deploy-mode', 'client', '--name', 'MyTaskPySpark', '--py-files', '["MyTaskPySpark.py"]', '/usr/local/lib/python2.7/dist-packages/luigi/contrib/pyspark_runner.py', '/tmp/MyTaskPySparkXfdkSG/MyTaskPySpark.pickle']
	INFO: Spark job stdout:
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/luigi/contrib/pyspark_runner.py", line 57, in <module>
		PySparkRunner(*sys.argv[1:]).run()
	  File "/usr/local/lib/python2.7/dist-packages/luigi/contrib/pyspark_runner.py", line 43, in __init__
		self.job = pickle.load(fd)
	ImportError: No module named MyTaskPySpark

	ERROR: [pid 23193] Worker Worker(salt=993230963, workers=1, host=spark-1, username=spark, pid=23193) failed    MyTaskPySpark()
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/luigi/worker.py", line 137, in run
		new_deps = self._run_get_new_deps()
	  File "/usr/local/lib/python2.7/dist-packages/luigi/worker.py", line 88, in _run_get_new_deps
		task_gen = self.task.run()
	  File "/usr/local/lib/python2.7/dist-packages/luigi/contrib/spark.py", line 335, in run
		super(PySparkTask, self).run()
	  File "/usr/local/lib/python2.7/dist-packages/luigi/contrib/spark.py", line 245, in run
		raise SparkJobError('Spark job failed {0}'.format(repr(args)), out=stdout, err=stderr)
	SparkJobError: Spark job failed ['/mnt/spark/spark/bin/spark-submit', '--master', 'spark://spark-1:7077', '--deploy-mode', 'client', '--name', 'MyTaskPySpark', '--py-files', '["MyTaskPySpark.py"]', '/usr/local/lib/python2.7/dist-packages/luigi/contrib/pyspark_runner.py', '/tmp/MyTaskPySparkXfdkSG/MyTaskPySpark.pickle']
	STDOUT: Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/luigi/contrib/pyspark_runner.py", line 57, in <module>
		PySparkRunner(*sys.argv[1:]).run()
	  File "/usr/local/lib/python2.7/dist-packages/luigi/contrib/pyspark_runner.py", line 43, in __init__
		self.job = pickle.load(fd)
	ImportError: No module named MyTaskPySpark

	INFO: Skipping error email. Set `error-email` in the `core` section of the luigi config file to receive error emails.
	DEBUG: 1 running tasks, waiting for next task to finish
	DEBUG: Asking scheduler for work...
	INFO: Done
	INFO: There are no more tasks to run at this time
	INFO: Worker Worker(salt=993230963, workers=1, host=spark-1, username=spark, pid=23193) was stopped. Shutting down Keep-Alive thread

Any ideas ?

**Comment by erikbern** [comment]
it seems like the array gets interpreted as a string on the command line (see --py-files) below

SparkJobError: Spark job failed ['/mnt/spark/spark/bin/spark-submit', '--master', 'spark://spark-1:7077', '--deploy-mode', 'client', '--name', 'MyTaskPySpark', '--py-files', '["MyTaskPySpark.py"]', '/usr/local/lib/python2.7/dist-packages/luigi/contrib/pyspark_runner.py', '/tmp/MyTaskPySparkXfdkSG/MyTaskPySpark.pickle']

**Comment by maver1ck** [comment]
I changed cfg file. Same problem.

{code}
SparkJobError: Spark job failed ['/mnt/spark/spark/bin/spark-submit', '--master', 'spark://spark-1:7077', '--deploy-mode', 'client', '--name', 'MyTaskPySpark', '--py-files', '/mnt/spark/MyTaskPySpark.py', '/usr/local/lib/python2.7/dist-packages/luigi/contrib/pyspark_runner.py', '/tmp/MyTaskPySparkylJSd0/MyTaskPySpark.pickle'
{code}

I think I shouldn't add current task Python file to py-files. Only libraries. 
Anybody can run PySparkTask with Spark 1.4.1 ?

**Comment by maver1ck** [comment]
Funny thing.
When I compress MyTaskPySpark.py to MyTaskPySpark.zip and change client.cfg to:
{code}
spark-submit: /mnt/spark/spark/bin/spark-submit
master: spark://spark-1:7077
py-files: /mnt/spark/c.zip
{code}
It works !!!
So there is a problem with plain .py files support.

**Comment by erikbern** [comment]
That's not good. Maybe we should zip by default?

**Comment by piskvorky** [comment]
@maver1ck I can run PySparkTask against both 1.4.1 and 1.5.0. I do not have to specify the "current task file" explicitly.

However, `py-packages` option doesn't work, so we still end up zipping dependencies manually (as another pipeline step, run just before the PySparkTask).

**Comment by maver1ck** [comment]
@piskvorky 
Could you tell me what's is your configuration and how you launch your task ?

**Comment by piskvorky** [comment]
Sure. Config (relevant part):

```
[spark]
py-files = /tmp/package1.zip,/tmp/package2.zip,/tmp/package3.zip
```

launched with:

```bash
$ time LUIGI_CONFIG_PATH=./luigi_local.cfg python ./luigi_pipeline.py
```

where `luigi_pipeline.py` just runs `luigi.run(main_task_cls=FinalizerTask)` in its `__main__`.

That's it. The `/tmp/X.zip` files are created in an explicit task inside the pipeline. Importantly, there is no extra `py-files` config for `luigi_pipeline.py` itself. The hardwired `py-files` paths could be made dynamic too, I suppose.

I would really look into imports from the pickled job -- there's some automagical path renaming shenanigans in there, plenty of room for error, which could result in the same type of failure you're seeing.

**Comment by maver1ck** [comment]
"where luigi_pipeline.py just runs luigi.run(main_task_cls=FinalizerTask) in its __main__."
I think that explains that it works.

**Comment by Tarrasch** [comment]
This is resolved, right? Closing...

**Comment by mfcabrera** [comment]
is there a nice alternative to what @piskvorky  did? like the attach method of hadoop?

**Comment by villanuevab** [comment]
I am getting the same error with `no module named ...`, the name of the python script with the task in it. Is the solution merely to zip and add to `client.cfg`? This seems inefficient.
