### ISSUE TITLE
launch task to center planner of different port

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1195]
I have two center planner server running in the same machine.(different port).

I want to send task A to planner_host of port 8082, and send task B to planner_host of port 8083.

What can I do?

**Comment by leafjungle** [comment]
task A  has nothing to do with task B. I do not want to put them in the same center planner, so I use two ports.

**Comment by Tarrasch** [comment]
There's something like `--scheduler-port 8083`, I think the docs should be up to date

**Comment by leafjungle** [comment]
@Tarrasch, it works, thanks very much.

**Comment by Tarrasch** [comment]
Great :)
