### ISSUE TITLE
Add an option to prevent Worker from catching exceptions from Task.run()

### ISSUE THREAD

**Issue by belevtsoff** [spotify/luigi#1201]
In our project this problem arises when unit testing tasks with dynamic dependencies (i.e. their `run()` method yields a generator). Because `luigi` has it's own mechanism of dealing with such cases, we use `worker.run()` to test a task. However, if one wants to test that a task raises under certain conditions, `worker.run()` catches that exception and logs, making it problematic to make sure a right kind of error was raised. It would be great to have smth like `Worker(..., raise_on_error=False)` kw argument of the `Worker`'s constructor.

If there are no objections, I can put together a PR

**Comment by Tarrasch** [comment]
We would happily accept such a PR. :)

I'm also interested to hear how you use dynamic dependencies.

**Comment by erikbern** [comment]
You mean the default would be to catch the exception and log it, but it's possible to override so that the Worker re-raises the exception? Yeah makes sense for unit tests

**Comment by erikbern** [comment]
it might be a bit messy get it working with the multiprocessing RPC but not too hard

**Comment by belevtsoff** [comment]
@Tarrasch cool. We have a kind of luigi pipeline generator that uses information from a kind of `nx.DiGraph` and then puts together a corresponding luigi pipeline. That's a static part. During the process of putting together luigi tasks, the generator might find that two nodes in the graph are pointing to the same target (a) -> (c) <- (b). In this case, the data from those deps has to be joined in a certain way, and that requires pulling additional data from a source:
(a) -> (c) <- (b)
(src)   _/
 Now, we don't want users to create the (src)->(c) link manually, but be do want the process of pulling the additional data to appear as a proper luigi.Task dependency on the final pipeline. That's where dynamic deps are used: when such situation arises, (c).run() pulls (src) dep dynamically

**Comment by belevtsoff** [comment]
@erikbern hm, I might have underestimated the amount of work required... But I guess someone will help me on the PR-review board

**Comment by erikbern** [comment]
Yeah the Worker code is pretty messy right now, for a reason – turns out there's a million ways things can go wrong (exceptions, signals, etc) and you need to deal with them in different ways. But I think you can essentially just pickle the exception and put it onto the queue back and then unpickle and raise.

**Comment by belevtsoff** [comment]
Closed by #1205

**Comment by daveFNbuck** [comment]
#1205 just got reverted. It turns out that custom exceptions often can't be unpickled due to a bug in python 2, so it was breaking my pipelines in a big way
