### ISSUE TITLE
Luigi Slackbot

### ISSUE THREAD

**Issue by jfeala** [spotify/luigi#1203]
um, @daveFNbuck [mentioned](https://github.com/spotify/luigi/pull/1086) a Luigi slack bot? 

Huge :+1: if you can share it!

**Comment by Tarrasch** [comment]
@jfeala he put it up here: https://github.com/houzz/hubot-luigi :)

**Comment by jfeala** [comment]
awesome, thanks!

On Thu, Sep 10, 2015 at 9:56 AM, Arash Rouhani <notifications@github.com>
wrote:

> @jfeala <https://github.com/jfeala> he put it up here:
> https://github.com/houzz/hubot-luigi :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/luigi/issues/1203#issuecomment-139241867>.
>



-- 
Jacob Feala, PhD
Scientific Investigator II, Bioinformatics
H3 Biomedicine
300 Technology Square
Cambridge, MA 02139
(mobile) 858-366-2951
Jacob_Feala@H3Biomedicine.com

-- 
[This e-mail message may contain privileged, confidential and/or 
proprietary information of H3 Biomedicine. If you believe that it has been 
sent to you in error, please contact the sender immediately and delete the 
message including any attachments, without copying, using, or distributing 
any of the information contained therein. This e-mail message should not be 
interpreted to include a digital or electronic signature that can be used 
to authenticate an agreement, contract or other legal document, nor to 
reflect an intention to be bound to any legally-binding agreement or 
contract.]

**Comment by daveFNbuck** [comment]
Is there a way to link the slack bot to this repo so it'll be easier for luigi users to find?

**Comment by Tarrasch** [comment]
@daveFNbuck You can just open a PR and point to it in the README somehow. :)
