### ISSUE TITLE
Many pending tasks, but no worker will process them.

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1215]
hii, guys.

I am sure that all the pending tasks are not "disabled" (retry times=100, and they are processed 0 or 1 times only).

what is the reason?

**Comment by Tarrasch** [comment]
> Many pending tasks, but no worker will process them.

Have you seen http://tarrasch.github.io/luigid-basics-jun-2015/#/? It might give more insights of how luigi works. Also check out the assistant feature.

**Comment by leafjungle** [comment]
@Tarrasch, I see that doc, is it means that I have to start task it again (by crontab?) to finish the pending tasks? 

Why does not the schduler automatically start a worker to check and do the pending task?

**Comment by leafjungle** [comment]
worker-keep-alive: True

I have config it in the client.cfg

**Comment by leafjungle** [comment]
In my design, each time I start a task A, a shell script will first check "ps -ef |grep A", if found a procedure, it will quit. otherwise start task A(N+1).

But I found that even task A is not finished, the procedure is gone.

**Comment by leafjungle** [comment]
I see in the log:

luigi.rpc.RPCError: Errors (1 attempts) when connecting to remote scheduler 'localhost'

**Comment by erikbern** [comment]
Closing this since not enough background
