### ISSUE TITLE
what's "assistant"?

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1217]
hii, guys.

is it has something to do with "worker"?

**Comment by erikbern** [comment]
it's an experimental feature to allow tasks to be run on a host separate from where it's scheduled. basically assistants pull all types of tasks and try to run them

**Comment by Sahilshetye** [comment]
Is assistant used while scheduling tasks from a different host in central scheduler configuration? or it has a different use case?

**Comment by ttpro1995** [comment]
hey guy, are we have documentation on "assistant" ?
