### ISSUE TITLE
Parameter containing unicode chars fail to serialize (MS Windows)

### ISSUE THREAD

**Issue by ThQ** [spotify/luigi#1223]
## Issue
A parameter set to contain unicode characters will make luigi fail with a UnicodeEncodeError on Windows 7.

## Root cause
Luigi serializes parameters by using the `str` function instead of `unicode`.

## Fix
In file `luigi/parameter.py`, class `Parameter`, function `serialize`, replace:

	> return str(x)
	
With:

	> return unicode(x)
	
## Steps to reproduce

Create a file named "test.py" filled with:

	> # -*- coding: iso-8859-1 -*-
	> 
	> import luigi
	> 
	> class UnicodeTask (luigi.WrapperTask):
	> 	unicode_param = luigi.Parameter(u"é")
	> 	
	> if __name__ == '__main__':
	>     luigi.run(main_task_cls=UnicodeTask)
	
Open the Windows command line (CMD.EXE) and run:

	> python test.py --local-scheduler
	
Luigi crashes with a UnicodeEncodeError:

	> Traceback (most recent call last):
	>   File "test.py", line 9, in <module>
	>     luigi.run(main_task_cls=UnicodeTask)
	>   File "C:\Users\_\Documents\TEST\luigi-bug\luigi\interface.py", line 421, in run
	>     tasks = interface.parse(cmdline_args, main_task_cls=main_task_cls)
	>   File "C:\Users\_\Documents\TEST\luigi-bug\luigi\interface.py", line 302, in parse
	>     return self.parse_task(cmdline_args, main_task_cls)
	>   File "C:\Users\_\Documents\TEST\luigi-bug\luigi\interface.py", line 299, in parse_task
	>     return [task_cls(**task_params)]
	>   File "C:\Users\_\Documents\TEST\luigi-bug\luigi\task_register.py", line 97, in __call__
	>     h[k] = instantiate()
	>   File "C:\Users\_\Documents\TEST\luigi-bug\luigi\task_register.py", line 78, in instantiate
	>     return super(Register, cls).__call__(*args, **kwargs)
	>   File "C:\Users\_\Documents\TEST\luigi-bug\luigi\task.py", line 265, in __init__
	>     task_id_parts.append('%s=%s' % (param_name, param_objs[param_name].serialize(param_value)))
	>   File "C:\Users\_\Documents\TEST\luigi-bug\luigi\parameter.py", line 276, in serialize
	>     return str(x)
	> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 0: ordinal not in range(128)

**Comment by erikbern** [comment]
Thanks – can you put together a pull request and submit?

**Comment by erikbern** [comment]
was this merged in a pull request?

**Comment by razovega** [comment]
was this merged in a pull request?

**Comment by ThQ** [comment]
Nope, bug is still here. Got bitten today again.
