### ISSUE TITLE
Runtime change in parameters is not fully respected by luigi

### ISSUE THREAD

**Issue by belevtsoff** [spotify/luigi#1226]
Changing luigi parameters after a Task was instantiated apply to some extent (i.e. the pipeline works with single worker and static deps), but is not respected when one has dynamic dependencies (i.e. only the values passed to the constructor get sent to the worker) and also the string representation of a task shows only default values (or those passed to the constructor). Here's an example:
```python
>>> class MyTask(Task):
...     p = Parameter(1)

>>> t = MyTask(p=3)
>>> repr(t)
"MyTask(p=3)"

>>> t.p = 7
>>> repr(t)
"MyTask(p=3)"
>>> t.p
7
```
I suspect that this is kind of a design decision, but it's not very clearly stated in the docs, so maybe it is not. Anyway, was this behaviour intended? Do you think trying to fix it is a bad idea?

**Comment by Tarrasch** [comment]
Yea it's by design. You are not allowed to change the parameter values when they're instantiated.

**Comment by belevtsoff** [comment]
Ok, I see. It would be cool to see that quote in the docs though.

**Comment by erikbern** [comment]
there might be some way to disallow overriding these values but not sure how. lmk if you know!

**Comment by belevtsoff** [comment]
@erikbern I've implemented something similar via descriptors, but not sure is that's the optimal way. The drawback is that to avoid redundancy in naming (i.e. `p = Parameter("p", default=5)`) one also needs a metaclass to tell the descriptors what they are called inside the class that uses them (i.e. `p = Parameter(default=5)` should be told that it's called `p`). On the bright side, one can easily forbid writing them directly by raising a meaningful exception inside the `__set__` method and also implement a more encapsulated complex reading behavior, if needed. If you're interested, I can cook up a more detailed recipe.

**Comment by erikbern** [comment]
yeah probably not highest priority at this point. adding a `__set__` method might also slow down things that people do on a task object in general so not sure if that's ideal
