### ISSUE TITLE
Workers dying on errors that can't be unpickled

### ISSUE THREAD

**Issue by daveFNbuck** [spotify/luigi#1227]
If I have a task that raises an error on run that can't be unpickled, it kills the whole worker immediately. Example code:

```
import luigi

class MyError(BaseException):
    def __init__(self, a, b):
        pass


class MyTask(luigi.Task):
    def run(self):
        raise MyError(1, 2)


if __name__ == '__main__':
    luigi.run()
```

If I run this with the latest master, the whole worker dies on the error with the following traceback:

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    luigi.run()
  File "/Users/buck/workspace/luigi/luigi/interface.py", line 331, in run
    return _schedule_and_run(tasks, worker_scheduler_factory)
  File "/Users/buck/workspace/luigi/luigi/interface.py", line 184, in _schedule_and_run
    success &= w.run()
  File "/Users/buck/workspace/luigi/luigi/worker.py", line 790, in run
    self._handle_next_task()
  File "/Users/buck/workspace/luigi/luigi/worker.py", line 690, in _handle_next_task
    timeout=self._config.wait_interval))
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 135, in get
    res = self._recv()
TypeError: ('__init__() takes exactly 3 arguments (1 given)', <class '__main__.MyError'>, ())
```

whereas if I run with older code, it recovers from the failure and carries on. The problem seems to be that the exception is now put into the result queue and cannot be successfully unpickled when it's retrieved from the queue in the parent process. This is the same error you get if you pickle and try to unpickle the error.

**Comment by erikbern** [comment]
Nice catch. This must have been introduced in #1205 

We should add a test for this and possibly revert right away.

It's weird that even that simple exception class can't be unpickled. Are we doing something wrong with how we pickle?

**Comment by erikbern** [comment]
What??? Pickle doesn't support exceptions?
```
>>> import pickle
>>> class MyException(BaseException):
...    def __init__(self, a): self.a = a
... 
>>> a = pickle.dumps(MyException(42))
>>> a
"c__main__\nMyException\np0\n(tRp1\n(dp2\nS'a'\np3\nI42\nsb."
>>> pickle.loads(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1133, in load_reduce
    value = func(*args)
TypeError: __init__() takes exactly 2 arguments (1 given)
```

**Comment by erikbern** [comment]
Seems like this is an old bug: http://bugs.python.org/issue1692335

Either way let's just revert #1205?

**Comment by daveFNbuck** [comment]
It was a fairly easy catch for me, as my workers don't last very long before something throws a custom exception. Reverting #1205 makes sense, as this is a pretty serious bug.

**Comment by belevtsoff** [comment]
That's weird. Both the presented pipeline and pickling exceptions work well on my setup (python 2.7.10). What python version does it affect?

**Comment by daveFNbuck** [comment]
I get the error in Python 2.7.10. I think it's fixed in 3.3.

```
$ python                                                                                                                                                                  [16:25:39]
Python 2.7.10 (default, Jun 10 2015, 19:42:47)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> class E(BaseException):
...   def __init__(self, a): pass
...
>>> from pickle import loads, dumps
>>> loads(dumps(E(1)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1133, in load_reduce
    value = func(*args)
TypeError: __init__() takes exactly 2 arguments (1 given)
```

vs

```
$ python3                                                                                                                                                                 [16:27:38]
Python 3.4.3 (default, Jun 10 2015, 19:56:14)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> class E(BaseException):
...   def __init__(self, a): pass
...
>>> from pickle import loads, dumps
>>> loads(dumps(E(1)))
E(1,)
```

I think it depends on whether the __init__ function of your class has the same number of arguments as its base class.

**Comment by belevtsoff** [comment]
Ok. Hmm, it's hard to think of a workaround other than allowing the functionality only for python 3.3+

**Comment by daveFNbuck** [comment]
If you just need this feature for testing, you could just check that the status is FAILED and the expl contains the expected error message. You could either pass a mock scheduler in to see what the run adds or throw a fixed error type with the error message on FAILED and catch it to check the message.

My approach would be to just call the task's run function in my unit tests. Then you can directly test that the right dependencies are generated and nothing will get in the way of capturing errors. This should also make your unit tests faster. This should be especially easy for the tests where you expect errors, as you're presumably not relying on the side-effects of processing the new dependencies anyway.

**Comment by belevtsoff** [comment]
@daveFNbuck I use the approach of calling `run` directly when it is applicable (most of the times). However, there are cases (e.g. some custom subclass adds another dependency to the requires method of its parent) where it is important that the right dep is added and that luigi does call its `run` method when the dependent task is added to the worker. This can still be done other way of course (e.g. by splitting into a couple of tests) at a cost of convenience.
