### ISSUE TITLE
About the connection error

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1230]
I encounted two cases:
(1)RPC Errors (1 attempts) when connecting to remote scheduler 'localhost'
(2)URLError: <urlopen error [Errno 111] Connection refused>

I am wondering that it has something to do with tornado's settings.
And I am wondering how to show all the connections of tornado, and is there any limit ?

**Comment by leafjungle** [comment]
This problem still remains, and it seems very hard to find any solution. @Tarrasch 

thiese cases appears accidentally.

**Comment by Tarrasch** [comment]
To be honest I'm not sure. If you study the code, maybe you can conclude that they can be merged into one?

**Comment by erikbern** [comment]
Closing this until you can provide some more information
