### ISSUE TITLE
workers limit?

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1236]
(1) When I start a luigi task, I can speicifiy the "workers" parameter, what will happen if that number is very large? is there any limits?

I am wondering this problem because I encounted a case: I start a job (workers = 100), and none of its tasks is executed, but actually the corresponding worker is found in the scheduler's worker list.

(2)There are some workers, with 0 pending tasks and 0 running tasks, but it will not quit. which is a bit strange.

**Comment by Tarrasch** [comment]
No there's no limit. Why would there be?

0 pending and 0 running just means that your workflow was complete when you invoked luigi.

**Comment by leafjungle** [comment]
@Tarrasch , thank you  very much for you nice reply.
I am debuging the python code.

in scheduler.py
def get_work(self, host=None, assistant=False, **kwargs):
     in_workers = (assistant and task.workers) or worker_id in task.workers

I do not understand the "in_workers".

In my viw, "get_work" will check all the tasks, and find the most suitable task. It has two factors:
(1)enough resources
(2)no undone dependent task

So what's "in_workers"?

**Comment by leafjungle** [comment]
And another problem: when I restart the central scheduler, all the client procedure will shut down because they can not connect to server. And when I restart the central scheduler, the clients are still shut down. Nobody would get_work from scheduler, How can luigi finish all the remaining tasks?

**Comment by leafjungle** [comment]
@Tarrasch , after debuging, I found all the tasks are pending because of "resouces not enough". But acutally no tasks is running currently.

And in scheduler.py: get_work function:
if not best_task and self._schedulable(task) and self._has_resources(task.resources, greedy_resources):
       if in_workers and self._has_resources(task.resources, used_resources):
             best_task = task  ##NOTICE##best task is the return task, if found, we should update greedy_resources here, instead of in the following "else" branch.
       else:
             workers = itertools.chain(task.workers, [worker_id]) if assistant else task.workers
             for task_worker in workers:
                  if greedy_workers.get(task_worker, 0) > 0:
                       # use up a worker
                       greedy_workers[task_worker] -= 1
                       # keep track of the resources used in greedy scheduling
                       for resource, amount in six.iteritems((task.resources or {})):
                           greedy_resources[resource] += amount            
                       break
   
I am puzzled about the ##NOTICE## above.

**Comment by leafjungle** [comment]
![image](https://cloud.githubusercontent.com/assets/6143261/9976166/bca5d18c-5f0d-11e5-9b93-0b60a32cd0fd.png)

if we found a best_task in scheduler.py, where is the code to update used_resources and available resources?

**Comment by leafjungle** [comment]
![2323](https://cloud.githubusercontent.com/assets/6143261/9976201/ea673326-5f0e-11e5-88c4-55f0d4226e50.png)

**Comment by Tarrasch** [comment]
I don't have the code in my head. But I recall we didn't keep track of used resources. We recalculate it  every time on `get_work`.

**Comment by Tarrasch** [comment]
> when I restart the central scheduler, all the client procedure will shut down because they can not connect to server

There's a reconnect and sleep interval. Have you tried to reconfigure down? Luigi clients can't handle a longer down-time of the server. But a server restart should only be a few seconds at most. No?

**Comment by leafjungle** [comment]
@Tarrasch 
There's a reconnect and sleep interval.    more detail? what is the configuration? I have read all the config in http://luigi.readthedocs.org/en/stable/configuration.html and can not find the right one.

Luigi clients can't handle a longer down-time of the server,   how long is the limit ?

--------------
"task with no stakeholders" means done tasks?

**Comment by Tarrasch** [comment]
You can just test this locally I think. It's `rpc-connect-timeout` you're looking for. Please feel free to contribute back by adding some more description to that parameters description.

**Comment by leafjungle** [comment]
@Tarrasch , well, rpc-connect-timeout is not the same as "reconnect and sleep interval".

I think we need "rpc-connect-retry-times" and "rpc-connect-retry-interval" options.

restart the central scheduler itself may takes a few seconds, but sometimes I stop scheduler, and add some debug python code( cost  half hour), and then restart the central scheduler.

**Comment by leafjungle** [comment]
Yeah, many concepts such as "worker" "assistant" "client-server mode" should be better documented.

I hope I can make luigi better.

**Comment by leafjungle** [comment]
"Luigi clients can't handle a longer down-time of the server, how long is the limit ?"

The clients may encount "rpc error: connection error/refused" even when the central scheduler is alive, accidentally.

so I want to make the retry unlimitly, and the connect-timeout set to a bit long (3 minutes).

**Comment by Tarrasch** [comment]
> I think we need "rpc-connect-retry-times" and "rpc-connect-retry-interval" options.

Sure makes sense. It's a bit intricate though, we probably don't want retries for `/api/ping` for example. Feel free to send a PR parametrising the retry-times (i think it's 3 by default). What is "rpc-connect-retry-interval" is it just a renaming of the currently existing `rpc-connect-timeout`?

> "Luigi clients can't handle a longer down-time of the server, how long is the limit ?" still this is a problem.
As I said, you can test this locally. Spawn a luigid and start sending tasks to it and then shut luigid down and see what happens on client side.

> The clients may encount "rpc error: connection error/refused" even when the central scheduler is alive, accidentally.

Really? Is your luigid massively overloaded or something?

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.

Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
