### ISSUE TITLE
for scheduler, what if task.workers are killed?

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1237]
Each task has attribute "workers", recording which client(host, pid, etc) are doing this task.

I am wondering what if the corresponding worker in the client is killed?
I know client have to ping scheduler frequently, and if a client has a long time not pinging the scheduler, what will the scheduler do?

-------------
I found some tasks have empty workers, is these tasks will always be pending?

**Comment by Tarrasch** [comment]
Luigid prunes orphaned tasks periodically.

Luigid is used in production at many relatively big enterprises. Naturally these simple things are covered.

**Comment by leafjungle** [comment]
I see in the "def prune" function, thank you very much.
