### ISSUE TITLE
Pending Tasks: 0  Unique Pending Tasks: 0  Running Tasks: 0

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1238]
Pending Tasks: 0  
Unique Pending Tasks: 0  
Running Tasks: 0

I encount a case: all the tasks are done, but the procedure is still exist for long time(three or four hours).
I am wondering how long will the procedure quit if all the tasks are done?

**Comment by leafjungle** [comment]
I see in worker.py: if assistant is used, the procedure will always keep alive even all the tasks are done.

**Comment by erikbern** [comment]
this wasn't an issue right?
