### ISSUE TITLE
Release early, release often

### ISSUE THREAD

**Issue by toidi** [spotify/luigi#1247]
I suggest to make luigi release and release luigi more often in future. For example 1 time per month.

**Comment by Tarrasch** [comment]
I think we need to merge #1182 first and iterate on the documentation once first. Also  I'm curious about #1243.

Can you review #1182 @toidi?

**Comment by toidi** [comment]
Ok. I will take a look this evening.

**Comment by Tarrasch** [comment]
Thanks @toidi !!
