### ISSUE TITLE
Composition of parameters

### ISSUE THREAD

**Issue by riga** [spotify/luigi#1253]
Consider this small example:

```python
class A(Task):
    log = Parameter(default="/var/log.txt")

class B(Task):
    logPath = Parameter(default="~/")

class C(A, B):
    logFile = Parameter(default="log.txt")
```

Now, I want to tell task ``C`` to overwrite its inherited ``log`` parameter, which should be ``os.path.join(logPath, logFile)``. To be consistent with the instance caching, I cannot use the
``__init__`` method. However, I could extend the default ``get_param_values`` method, but
that does not seem clean enough to me. In cases like this I would propose something like a
hook to ensure parameter flexibility when e.g. working in such inheritance scenarios. If ``A.log``
had not default (which might be the case if you want to define ``A`` as some kind of interface),
the extension of ``get_param_values`` wouldn't work anyway.

Edit: solved in PR #1254.

**Comment by Tarrasch** [comment]
Do you really need to inherit from `A`? I'm not that fond of parameters being dependent on each other within one Task. Can't you just override `log` with a property in `C`?

**Comment by riga** [comment]
I see your point w.r.t. that minimal example.

However, our setup is a way more complex (we use luigi to structure a physics analysis of data from the LHC at CERN), which makes it difficult and unmanageable for us to simply override parameters of super tasks.

E.g. one of our tasks (``CustomTask``) defines 9 parameters. Its super tasks (we have several inheritance layers and multiple inheritance at some points) contains a task (``BaseTask``) that defines only one parameter (``myParam``) that has no default value. For logical reasons, ``CustomTask`` uses 6 of its 9 parameters to compose the value of its (inherited) ``myParam`` parameter. Of course, there might be some redundance, but that's wanted. Other tasks inheriting from ``BaseTask`` define ``myParam`` in a different way or even leave it blank to require explicit definition.

**Comment by Tarrasch** [comment]
> However, our setup is a way more complex (we use luigi to structure a physics analysis of data from the LHC at CERN), which makes it difficult and unmanageable for us to simply override parameters of super tasks.

LHC?! That's cool! Didn't know it used luigi. :)

Have you thought of `CustomTask` not inheriting from `BaseTask`? Or maybe have a `BaseTaskWithMyParam` that inherits from `BaseTask`, so you could then have something like:

```
class BaseTask(luigi.Task):
    @abstractproperty
    def my_param(self):
         pass

    def calculate_energy(self):   # Or whatever physicist use luigi for ;)
         mass = self.my_param + 5
         return mass*speed_of_light^2;


class BaseTaskWithMyParam(BaseTask):
    my_param = luigi.Parameter()

class BaseTaskWithMyParam(BaseTask):
    a = luigi.Parameter()
    b = luigi.Parameter()
    c = luigi.Parameter()
    
    @property
    my_param(self):
        return a + b + c
```

**Comment by erikbern** [comment]
I'm not in love with #1254 – let's try to figure out a way to solve it before introducing more concepts to Luigi.

I would consider factoring out implementation from parameter classes and use mixins. What is the reason you need to use multiple inheritance? If it's in order to inherit implementation (the `run` method or similar) then I would factor out the implementation into a separate class inheritance structure. This is something that happened a lot at Spotify – i.e.. the `run` method is defined on base classes with parameters, and then concrete subclasses define parameters

**Comment by erikbern** [comment]
Separately I think it's actually fine to override `__init__` as long as you remember to call the super constructor. Does this not work?

**Comment by riga** [comment]
> @Tarrasch: Have you thought of ``CustomTask`` not inheriting from ``BaseTask``?

We also discussed that idea, but from a logical point-of-view and for our use-case it makes more sense to us to keep that inheritance.

> @erikbern: Separately I think it's actually fine to override __init__ as long as you remember to call the super constructor. Does this not work?

Actually no. When I use ``__init__``, the parameter will have the expected value, but this circumvents the instance cache since it defines the unique cache key [prior to invoking``__init__``](https://github.com/spotify/luigi/blob/48671f60ada2966d986eb7d9d6b36c2acd3ed32b/luigi/task_register.py#L93). And this is the actual reason for the complication in the first place.

**Comment by erikbern** [comment]
Ok – can you explain why your situation is special and why you can't do the inheritance refactoring? I'm pretty hesitant to add more core functionality to the `Task` class for something that's just a convenience

**Comment by riga** [comment]
Yeah. Although the PR is rather straightforward, I felt a little uncomfortable touching the core functionality ;)

This is a simplified excerpt of our task structure.

```python
class AnalysisTask(Task):

	localRoot = Parameter("/user/public")
	campaign  = Parameter(default="analysisFiles")
	setup     = Parameter(default="RunIIFall15")
	dataset   = Parameter(default="ttJets")
	lepton    = Parameter(default="mu")
	shift     = Parameter(default="nominal")
	postfix   = Parameter() # required
	
	@property
	def analysisId(self):
		return (self.campaign, self.setup, self.dataset,
		        self.lepton, self.shift, self.postfix)


class GridTask(Task):

	gridTaskName = Parameter() # required
	
	@property
	def gridWorkArea(self):
		return os.path.join(os.getcwd(), "grid_tasks")
	
	@property
	def gridTaskDir(self):
	    return os.path.join(self.gridWorkArea, self.gridTaskName)


class GridAnalysisTask(GridTask, AnalysisTask):

	# here I want to override gridTaskName to always be something
	# like "gridTaskName = '_'.join(self.analysisId)"
	gridTaskName = Parameter(default=None, description="ignored, set automatically")

	@property
	def gridWorkArea(self):
		return os.path.join(self.localRoot, "grid_tasks")


class GridSubmitTask(GridTask):
	...


class GridStatusTask(GridTask):
	...


class GridAnalysisSubmitTask(GridAnalysisTask, GridSubmitTask):
	...
```


The important part is where I want to override ``gridTaskName`` in the ``GridAnalysisTask`` class. With the hook method proposed in the PR I would simply do:

```python

class GridAnalysisTask(GridTask, AnalysisTask):

	gridTaskName = Parameter(default=None, description="ignored, set automatically")
	
	@classmethod
	def param_hook(cls, result, args, kwargs):
		keys = ("campaign", "setup", "dataset", "lepton", "shift", "postfix")
		result["gridTaskName"] = "_".join(result[key] for key in keys)
	
	...
```

I want to point out that most tasks, e.g. ``AnalysisTask`` or ``GridTask`` are inherited by other tasks as well, so I cannot merge them (as this example would suggest) and we benefit a lot from the inheritance structure.

**Comment by Tarrasch** [comment]
And without the current PR, you can do

```{python}
class GridAnalysisTask(GridTask, AnalysisTask):

    # Note, we're overriding the Parameter member with a non-Parameter member
    @property
    def gridTaskName(self):
        keys = ("campaign", "setup", "dataset", "lepton", "shift", "postfix")
        return "_".join(result[key] for key in keys

    ...
```

Not only is it shorter, but it might suit you even better, as 

 * then `GridAnalysisTask(gridTaskName='abc')` will raise an `UnknownParameterException`.
 * The meaningless `gridTaskName` non-parameter will not be shown in  the visualiser

Also. It should also be intuitive, as *gridTaskName is not a parameter anymore*.

**Comment by riga** [comment]
Thanks, that's actually a pretty clean approach.
I'll check if it's suitable for all of our cases.

**Comment by Tarrasch** [comment]
Thanks @riga. Please let us know how it works. I've not done this myself. But I think it should work. :)

**Comment by riga** [comment]
I just checked and it works fine for most of our cases.
However, at some points we need the parameter of interest to remain a parameter and not a prop
in order to rely on instance caching.

But I think for the vast majority of luigi users, your approach works fine, so I will just implement
that hook into our custom base task class to cover our special cases ;)

Thank you, @Tarrasch and @erikbern, for your replies.

**Comment by Tarrasch** [comment]
Shouldn't there only be "more caching" if you have fewer parameters?

**Comment by erikbern** [comment]
Makes sense. If `gridTaskName` is derived from the other parameters, it shouldn't be a parameter. Parameters are like arguments to a function so you want to minimize the number of parameters you send
