### ISSUE TITLE
execution summary output is very different depending on number of results

### ISSUE THREAD

**Issue by demoray** [spotify/luigi#1260]
The execution summary is very different based on how many times a task was executed.  Given TaskA running once, TaskB running twice, and TaskC running thrice, the output looks like this:

\- 1 TaskA(arg=1)
\- TaskB(arg1=1, arg2=1) and TaskB(arg1=1, arg2=2)
\- TaskC(arg=/long/arg/here) and 30 other TaskC

It would be nice if the output was visually similar regardless of the number of times it was executed, such as:
\- 1 TaskA(arg1)
\- 2 TaskB(arg1=1, arg2=1), TaskB(arg1=1, arg2=2)
\- 30 TaskC(arg=/log/arg/here) ...

**Comment by Tarrasch** [comment]
I agree on it should always be a leading count-number for consistency. Would you like to send a PR? :)

**Comment by demoray** [comment]
Happy to, just didn't want to spend the time if nobody agreed with me.  PR will be coming shortly.

**Comment by demoray** [comment]
See #1263 for PR.

**Comment by erikbern** [comment]
awesome

**Comment by demoray** [comment]
this was merged
