### ISSUE TITLE
execution summary limits are hard coded

### ISSUE THREAD

**Issue by demoray** [spotify/luigi#1261]
The number of lines that an execution summary will print is hard coded to 5, with a comment that specifies to alter the hard coded value to change the limits [0].

It would be useful if this limit was configurable.

0 - https://github.com/spotify/luigi/blame/master/luigi/execution_summary.py#L97

**Comment by Tarrasch** [comment]
Hmm, can you send a PR? What number have you found to be more suitable?

**Comment by demoray** [comment]
Happy to, just didn't want to spend the time if nobody agreed with me.

For my work, I'd rather not have it limited.  A configurable limit would solve that for me.

**Comment by Tarrasch** [comment]
@demoray I suppose that could be marked by just having a very high integer?

Looking forward to your patches @demoray :)

**Comment by demoray** [comment]
See #1263 for PR.

**Comment by demoray** [comment]
this was merged
