### ISSUE TITLE
Unable to use empty parameters

### ISSUE THREAD

**Issue by demoray** [spotify/luigi#1270]
class A(luigi.Task):
   b = luigi.Parameter()
A(b="")

This generates the following exception:
luigi.server[23966] WARNING: Error saving Task history
Traceback (most recent call last):
  File "/tmp/luigi/local/lib/python2.7/site-packages/luigi/scheduler.py", line 1007, in _update_task_history
    self._task_history.task_started(task_id, host)
  File "/tmp/luigi/local/lib/python2.7/site-packages/luigi/db_task_history.py", line 94, in task_started
    task = self._get_task(task_id, status=RUNNING, host=worker_host)
  File "/tmp/luigi/local/lib/python2.7/site-packages/luigi/db_task_history.py", line 104, in _get_task
    task = self.tasks[task_id] = task_history.Task(task_id, status, host)
  File "/tmp/luigi/local/lib/python2.7/site-packages/luigi/task_history.py", line 38, in __init__
    self.task_family, self.parameters = task.id_to_name_and_params(task_id)
  File "/tmp/luigi/local/lib/python2.7/site-packages/luigi/task.py", line 64, in id_to_name_and_params
    return luigi.tools.parse_task.id_to_name_and_params(task_id)
  File "/tmp/luigi/local/lib/python2.7/site-packages/luigi/tools/parse_task.py", line 59, in id_to_name_and_params
    parsed = parser.parseString(task_id).asDict()
  File "/tmp/luigi/local/lib/python2.7/site-packages/pyparsing.py", line 1125, in parseString
    raise exc
ParseException: Expected ")" (at char 242), (line:1, col:243)

**Comment by erikbern** [comment]
let's kill `id_to_name_and_params` I hate that function

**Comment by stephenpascoe** [comment]
@erikbern I'm interested in trying to to get this fixed.  Is there somewhere that summarises the issue?  Where would be best to discuss a solution?

**Comment by stephenpascoe** [comment]
Duplicate of #1171 and #1132.

**Comment by erikbern** [comment]
We should just remove the function `id_to_name_and_params` and store all the parameters in the database

**Comment by stephenpascoe** [comment]
So, are some parameters not stored in the database (task_history I assume)?

I also think there are other issues with task_id which makes using it anywhere as a key problematic.  Clearly it is not safe to parse if parameters contain characters like "," or "=".  You can't reconstruct the task_id from a dictionary of parameters because the serialisation order depends on the order parameters are defined in the class.

Therefore, I was thinking task_id needs a significant overhaul.  E.g. hashing a reliable serialisation.

**Comment by erikbern** [comment]
The task id was never meant to be a serialization mechanism. It shouldn't be, either. Task id should be a unique identifier of the task and ideally human readable. We should store parameters separately somewhere else so we don't have the awkward deserialization

**Comment by stephenpascoe** [comment]
Right, I completely agree.  I think it's not too difficult to fix task_history so that it doesn't need to deserialise task_id.  It requires some changes to the internal API.  I'll prepare a PR.

**Comment by erikbern** [comment]
That would be awesome!

**Comment by demoray** [comment]
This was fixed by merging #1309
