### ISSUE TITLE
debian/control should include python-setuptools in Build-Depends

### ISSUE THREAD

**Issue by demoray** [spotify/luigi#1278]
Unless python-setuptools is installed, then /usr/bin/luigi and /usr/bin/luigid do not get installed appropriately.

Given that setuptools is a build prerequisite rather than a runtime prerequisite, there is almost no impact to the end user systems.

**Comment by erikbern** [comment]
Great can you send a pull request?

**Comment by demoray** [comment]
sure.  Will do shortly.

**Comment by demoray** [comment]
the PR was merged
