### ISSUE TITLE
python-pip is an "install requirement"

### ISSUE THREAD

**Issue by demoray** [spotify/luigi#1280]
The debian package has python-pip as a install time requirement.  

Typically, any required python library should be a package prerequisite, and the package should not install/update any other libraries either during installation or runtime.

Is this an oversight?

**Comment by erikbern** [comment]
No strong feelings, sounds like you know more about Debian so you are probably right :)

**Comment by demoray** [comment]
the PR I submitted was merged

**Comment by Tarrasch** [comment]
Thanks for cleaning up the issues @demoray :)
