### ISSUE TITLE
makedirs uses LBYL rather than EAFP, which causes errors with multiple concurrent workers

### ISSUE THREAD

**Issue by demoray** [spotify/luigi#1284]
luigi.LocalTarget.makedirs uses this pattern:

    if parentfolder and not os.path.exists(parentfolder):
        os.makedirs(parentfolder)

If multiple concurrent workers happen to makedirs at the same time, this will generate an exception.  The same issue occurs in:
* contrib.ssh.RemoteFileSystem.get
* contrib.ftp.RemoteFileSystem.get
* contrib.hadoop.JobTask._setup_links

Note: contrib.ssh.RemoteFileSystem.put and contrib.ssh.RemoteFileSystem.mkdir do not, as these use "mkdir -p", which does not complain about trying to create the directory if it already exists.

These should use the following pattern:

    if parentfolder:
        try:
            os.makedirs(parentfolder)
        except OSError:
            pass

https://docs.python.org/2/glossary.html#term-lbyl 
https://docs.python.org/2/glossary.html#term-eafp

**Comment by demoray** [comment]
Note, this race condition is unpleasant to write a test to show empirically, but this error occurs roughly a dozen times a day in my workflow.

**Comment by erikbern** [comment]
This makes sense – would be happy to merge a PR

**Comment by Tarrasch** [comment]
Fixed in #1285
