### ISSUE TITLE
Proposal to change task_id serialisation

### ISSUE THREAD

**Issue by stephenpascoe** [spotify/luigi#1312]
## Problem summary

luigi.Task.task_id is currently used for 2 purposes within the codebase: a unique identifier for the task and a short summary of the task and its significant parameters.  IMO these two purposes are in conflict and we should separate them out.  The main problems I've encountered boil down to these points:

 - task_id cannot be reliably deserialised to get parameter values.  We know we shouldn't use it as such, but it is sometimes tempting.

 - task_id cannot be reliably serialised from a dictionary of parameters.  It depends on the order of parameter declarations in the task class.  Therefore we can't create it if we don't have the class (such as in the scheduler, javascript or external tools).  We always need to pass around both the task_id and the parameters.  This duplicates all parameter values.

 - DbTaskHistory does not store task_id at all.  It stores parameters in a table which looses ordering information.  We cannot reliably find a task in DbTaskHistory given a task_id.  Even if we know the parameters, we need a query with 1 join per parameter, which can be inefficient with many parameters with similar values.

## Proposal

 1. Change task_id to be based on the task_family and a hash of the parameter dictionary.  This would still give some human-readable information but would hide the parameter values.  E.g. "<family>#<hash>" where <hash> is the md5 digest of a sorted json serialisation of the parameter dictionary.

 2. Keep str(task) as a human readable summary of the task

 3. Review references to task_id in the worker, scheduler and visualiser code and use task_id when we want an identifier and str(task) when we want a summary.

 4. Add the new task_id as a column in the DbTaskHistory database

I expect this would be disruptive to people's downstream tools.  It would need evaluating and probably a major version change.  If I get the impression this change would be accepted, I am willing to do the implementation, test it and run it in production for a while before it is merged into master.

**Comment by ulzha** [comment]
Sounds good!

For correct hashing one might need canonicalization on codepoint escaping too in JSON strings, not only the sorting of JSON keys. (Googled http://wiki.laptop.org/go/Canonical_JSON as an example, but it seems to be outright specifying non-JSON, by allowing control characters...?!)

**Comment by ulzha** [comment]
I always wondered if it might even be preferable to deprecate the ambiguous summary format completely. Instead always have str(task) be of the form `<Python class name>(<significant parameters as canonicalized JSON>)`, with some conventions about DateParameter etc. string representations...

**Comment by erikbern** [comment]
Happy to split it up, but now that we're sending and storing all parameters to the central planner is it even necessary? We could just make the `task_id` a bit simpler and still make it somewhat human readable.

**Comment by stephenpascoe** [comment]
@erikbern I think that's what I'm suggesting.  E.g. 
    task_id = "MyTask#a4fe53b3"
    str(task) = "MyTask(foo=42, bar=12)"

However, I also like @ulzha's suggestion of str(task)="MyTask({"foo":42,"bar":12})".  That way we see what bytes are used in the hash.

**Comment by erikbern** [comment]
yeah i was thinking something like task_id = `MyTask_42_12_a4fe53b3` but I'm fine either way

**Comment by demoray** [comment]
I thought I commented, but don't see my thoughts listed here.  Rather than str() with some custom parsers, why not convert the serialization to repr?  

It would be nice to just use 'eval' rather than come up with a custom parser with custom syntax to reconstitute a task.

    repr(...)
        repr(object) -> string

        Return the canonical string representation of the object.
        For most object types, eval(repr(object)) == object.

At least some of the __str__ instances are repr safe already.

**Comment by erikbern** [comment]
i think anything that encourages using `eval` is bad

**Comment by Tarrasch** [comment]
Oh, I thought the parameters was sorted alphabetically. Yea this needs fixing then...

**Comment by stephenpascoe** [comment]
I've started work at https://github.com/stephenpascoe/luigi/tree/task_id_hashing

task_id becomes "<family>#<md5(params)>" where params is normalised JSON.  Many tests needed updating to look for the new task_ids.  I can get all tests to pass with one exception: `CentralPlannerScheduler._recursive_deps()` parses the task_id to find the parameters of a dependency if it is missing.

https://github.com/stephenpascoe/luigi/blob/task_id_hashing/luigi/scheduler.py#L882

This code already falls-back to returning {} as parameters if it can't parse the task_id so I am hoping this feature isn't too important.

I'm yet to try this beyond running the tests.

**Comment by erikbern** [comment]
This is great. We should fix `CentralPlannerScheduler._recursive_deps()`

Do you have any examples of how tasks id's are serialized?

I really appreciate you working hard on these core component of Luigi! Typically for an open source project all pull requests are small feature additions but every feature introduces some amount of cruft that accumulates to the point where someone has to make a bigger system wide change

**Comment by stephenpascoe** [comment]
Well, this one is an itch I need to scratch to get my system working.

Somehow my example got dropped from the previous commit.  The task_id is `<family>#<md5(params)>`.  E.g.

```
In [2]: class Task(luigi.Task):
   ...:     foo = luigi.Parameter()
   ...:     bar = luigi.Parameter()
   ...:     
In [3]: t = Task(foo='a', bar='b')
In [4]: t.task_id
Out[4]: 'Task#ae255306131d4be55d553d1bcf37d919'
In [5]: str(t)
Out[5]: 'Task(foo=a, bar=b)'
```

**Comment by erikbern** [comment]
Btw while we're at it – maybe # isn't the best special character to use since it doesn't work in URL's. maybe just use underscore?

**Comment by erikbern** [comment]
Did you consider including some of the params in human readable format?

**Comment by stephenpascoe** [comment]
My argument is that the id should be short and give some indication of what it is (i.e. in this case the task_family).  When you want to know the parameters they should be available by other means:
 - If you are a worker it is str(task) (via __str__() method)
 - If you are in the scheduler the params are passed around in a dictionary
 - If you are in an API client the params are generally returned as JSON.

I understand this might be too big a change for the community.  If necessary we can simply change to task_id being "<family><params-json>".  This would be very quick change now I've separated-out its use as identifier and summary.  However, IMO this has a couple of disadvantages:

 1. task_ids get long.  Params often contain paths and other repetitive information.
 2. The API duplicates these parameters in the task_id and params-json.

I'd like to experiment a bit to see if I can make the task-hash approach work first.

On the separator.  I'll test whether "#" clashes with Luigi's use of URLs.  I think it's important that it isn't a valid Python identifier character, otherwise we can introduce ambiguities.

**Comment by stephenpascoe** [comment]
So I have tested 2 solutions in my fork https://github.com/stephenpascoe/luigi/tree/task_id_hashing.

 1. task_id = <task_family>#<md5-params-json> e.g. MyTask#2f8acf3fe5e5c2839a04b7677d9399b8
 2. task_id = <task_family>#<params-json> e.g. MyTask#{"foo":"bar"}

E.g. 

In both cases the tests pass, including the visualser tests.  I am ready to try this out on real workflows in our staging environment.  Which one do you think we should go for?  I set out the advantages of no. 1 above but no. 2 is clearly less disruptive and easier to read.

**Comment by mmongeon-aa** [comment]
I would prefer to use option 2 simply because it would make custom event handlers much more useful out of the box. We have already been using this method(json dumps and sort) to serialize tasks for external monitoring. It would be very handy to have that string directly usable in the web ui.

 +1 for params-json and Stpehen

**Comment by erikbern** [comment]
idk i think with the json we would be back to the old situation where people think it's a deserializable representation of the task but it's not

I would prefer something like the first three arguments and then some md5 string, and no weird characters like #. So like MyTask_bar_5_test_b789bc78fe

**Comment by stephenpascoe** [comment]
When you say "first 3 arguments" do you mean the first 3 parameters according to the class definition, or the first 3 after sorting by parameter name?  What if one of these contains an underscore?  What if the class name contains an underscore?

**Comment by erikbern** [comment]
I don't see an issue with that... it's just an id, not mean to be parsed

**Comment by stephenpascoe** [comment]
OK, I see the point.

@mmongeon-aa note the API already returns task parameters as json so you can still get at the params.

**Comment by erikbern** [comment]
yeah in fact i would actually prefer task id's that are very hard to reverse... that way people understand it's not a serialization mechanism (which was a problem with the previous approach)

**Comment by stephenpascoe** [comment]
I have this working:

 task_id = "<family>_<param-var1>_<param-var2>_<param-var3>_<hash>"

where param-vars are truncated to 16 chars and hash is truncated to 10 chars.  The only problem is that `scheduler._recursive_deps()` can't deduce the family or parameters for any dependency which hasn't been added yet.  I'm setting the family to 'UNKNOWN' which I think will be OK.

**Comment by erikbern** [comment]
That's great!

I thought about the thing in the scheduler too, but I don't think there's much we can (or should) do.
