### ISSUE TITLE
Parameters named "task" no longer working on CLI

### ISSUE THREAD

**Issue by daveFNbuck** [spotify/luigi#1335]
Most of my Tasks have a parameter named task. This was fine until I recently grabbed the latest code and found that it's treating this flag as an override for the positional task argument. This will be very annoying for me to write out of my code. Is there a strong reason that it needs to be like this?

**Comment by daveFNbuck** [comment]
If this is necessary, there should at least be an error when I try to name a parameter "task", as I would have at least been able to detect this in my unit tests before deploying the new luigi.

**Comment by Tarrasch** [comment]
Thanks for reporting!!! I'll fix right away!

**Comment by daveFNbuck** [comment]
Thanks for the quick fix!
