### ISSUE TITLE
PR  #1137 yields SIGUSR1 AttributeError on Windows

### ISSUE THREAD

**Issue by danielsack** [spotify/luigi#1360]
PR #1137 put in place `signal.SIGUSR1` which breaks luigi on Windows machines. Replacing all instances of `SIGUSR1` with `SIGTERM` appears to fix the issue.

Specifically, the error generated:
```
(env) PS C:\Users\...> python .\hello_world.py
python : 'ps' is not recognized as an internal or external command,
At line:1 char:1
+ python .\hello_world.py
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ('ps' is not rec...ternal command,:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
operable program or batch file.
Traceback (most recent call last):
  File ".\hello_world.py", line 12, in <module>
    luigi.run(['examples.HelloWorldTask', '--workers', '1', '--local-scheduler'])
  File "C:\Users\...\env\lib\site-packages\luigi\interface.py", line 207, in run
    return _run(*args, **kwargs)['success']
  File "C:\Users\...\env\lib\site-packages\luigi\interface.py", line 235, in _run
    return _schedule_and_run([cp.get_task_obj()], worker_scheduler_factory)
  File "C:\Users\...\env\lib\site-packages\luigi\interface.py", line 185, in _schedule_and_run
    scheduler=sch, worker_processes=env_params.workers, assistant=env_params.assistant)
  File "C:\Users\...\env\lib\site-packages\luigi\interface.py", line 138, in create_worker
    scheduler=scheduler, worker_processes=worker_processes, assistant=assistant)
  File "C:\Users\...\env\lib\site-packages\luigi\worker.py", line 370, in __init__
    signal.signal(signal.SIGUSR1, self.handle_interrupt)
AttributeError: 'module' object has no attribute 'SIGUSR1'
```

**Comment by erikbern** [comment]
can you send a PR

**Comment by danimcgoo** [comment]
daniel do you want to do this? I'm happy to send a PR. Let me know.

**Comment by danielsack** [comment]
@erikbern @danimcgoo - happy to; will submit in a min or two

**Comment by erikbern** [comment]
@daveFNbuck you added the SIGUSR1 signal in 3800a986 – any issues changing it to SIGTERM?

**Comment by danielsack** [comment]
@erikbern forgive my lack of familiarity with this whole process, but do I not have permission to commit branches?

**Comment by danielsack** [comment]
@danimcgoo - might be more efficient if you submit this one while I work out my github auth issues

**Comment by danielsack** [comment]
Just submitted PR #1361

**Comment by daveFNbuck** [comment]
If you use SIGTERM, then a vanilla kill command won't kill a worker anymore. Maybe this should be configurable and have a different default on windows? We'd also need to make sure to store the replaced SIGTERM handler and call it at the end of the handler in the worker, as various mapreduce-related contrib libraries also handle SIGTERM.

**Comment by daveFNbuck** [comment]
A quicker solution might be to just catch the exception and do nothing when registering the signal handler fails. I can put out a quick PR for that, as I'm not sure how to make this feature work in an acceptable way on windows.

**Comment by erikbern** [comment]
yeah that sounds reasonable. or just throw SIGTERM on windows and SIGUSR1 on other platforms

**Comment by sma202** [comment]
Was this fixed?  Still getting the same error.
