### ISSUE TITLE
Dependency graph fails sometimes

### ISSUE THREAD

**Issue by Massou31** [spotify/luigi#1364]
hi,
With luigi 2.0.0, sometimes the task dependency graph fails to display with errors like:
```Couldn't find task DailyBiWorkflow(executor=all,%20date=2015-09-12,%20with_sftp_upload=False,%20with_reconciliation_analyse=False)```

There are no errors in luigi logs.
I think this may be caused by a failure in the urlencode but I have not investigated in it yet.

is there some parameters to luigi task that may cause this bug (to long strings, python objects, ...)?

**Comment by Massou31** [comment]
Hi,
the issue is solved.

**Comment by dlstadther** [comment]
If this has been resolved, could you close the issue? Thanks!
