### ISSUE TITLE
Hierarchical Wrapper Tasks Check All Child Dependencies Repetitively

### ISSUE THREAD

**Issue by rg-redbull** [spotify/luigi#1365]
Hello,
I am using a hierarchy of wrapper tasks to group related sets of jobs.

For example---

WrapWrapperTasks - requires all the below steps
WrapDownloadTasks - requires several DownloadTask
WrapExtractTasks - requires several ExtractTask, requires WrapDownloadTasks
WrapUploadTasks - requires several UploadTask. requires WrapExtractTasks.

I believe that every time I check WrapWrapperTasks for completion, it looks at the output of complete() for every single child task in the hierarchy, even if the same complete check had been run moments ago by one of the child tasks. This seems duplicative and adds up for bigger hierarchies.

One solution could be to override the complete method on these tasks to first look up any previous completion of the same task to avoid the extra checks. Is there a recommended way to do this? Any other suggestions for managing hierarchical dependencies like this? I ask because checking the targets can add up to lot of unnecessary API / DB calls.

**Comment by erikbern** [comment]
Easiest solution is probably just write to a dummy file from the wrapper tasks

**Comment by rg-redbull** [comment]
Thanks, I wound up doing something similar to that --- I added a callback to write all completed task Id's to a cache file. Then subclassed WrapperTask to check the file first before checking outputs for children.
