### ISSUE TITLE
FTP RemoteTarget tries to create local temp file in root

### ISSUE THREAD

**Issue by jeffcjohnson** [spotify/luigi#1368]
luigi.contrib.ftp.RemoteTarget open('r') tries to create a local temporary file based on the remote file path with a random suffix but using the entire path of the remote file.

In my case, the remote file is in the root folder of the FTP server so it tries to create the same file locally with '-luigi-tmp-%09d' as a suffix.  Because I don't have write permission to my root folder it fails.

**Comment by a86c6f7964** [comment]
+1
https://github.com/spotify/luigi/blob/7a63da8b7c6fc48fde6479ae969581c160d6516c/luigi/contrib/ftp.py#L261

I cannot think of any reason that this needs to be at self.path instead of something like '/tmp/' in unix.

**Comment by erikbern** [comment]
yeah that sounds messed up. would love it if you can send a PR
