### ISSUE TITLE
Make logging configurable

### ISSUE THREAD

**Issue by gf-atebbe** [spotify/luigi#137]
Currently the configuration of the logger is done by interface.setup_interface_logging using a hard-coded format.  It would be nice if an option was added so that luigi didn't configure the logger and left it up to the user to do, or accepted a configuration file instead of using a hard-coded format.  It seems like the easiest thing to do would be to add a flag that could be set before the workflow runs, but it would be more nicer if it all just came from a config file.

**Comment by themalkolm** [comment]
Shouldn't this issue be closed?
