### ISSUE TITLE
Add method to S3Target to get back path

### ISSUE THREAD

**Issue by matthewdu** [spotify/luigi#1371]
With an `S3Target(path)`, we can load data into S3 at the specified path. It would be useful if we could also get back the path at which the target is pointing to so it can be used in subsequent tasks.

Correct me if I'm wrong, but I couldn't find any way to do this. I can work on a PR if this sounds reasonable.

**Comment by erikbern** [comment]
Yes we should just set `self.path = path` in the constructor of `S3Target` :)
