### ISSUE TITLE
@luigi.Task.event_handler for a method

### ISSUE THREAD

**Issue by alexeygrigorev** [spotify/luigi#1373]
I want to do some cleaning if one specific task fails. For example if a Hadoop task fails, I would like to clean up a bit and remove created directories from HDFS. 

Here's how I do it now:

```
@luigi.Task.event_handler(Event.FAILURE)
def on_failure(task, exception):
    if isinstance(task, MyHadoopTast):
        print 'removing %s' % task.output()
        task.output().remove()
```

It would be very nice to have something like it, but as a method for one specific task, for example:

```
class MyHadoopTask(HadoopJarJobTask):

    # some stuff like output(), etc

    @luigi.Task.event_handler(Event.FAILURE)
    def on_failure(self, exception):
        self.output().remove()
```

Is it possible to do now? If not, it would be a good feature to have.

**Comment by erikbern** [comment]
yeah or we could just have a `on_failure` method on each task or something like that.

Is this Hadoop cleanup fairly generic? Consider just implementing it on the base hadoop class and make it configurable

**Comment by alexeygrigorev** [comment]
Yeah, just a method `on_failure` would be even better. And probably not very hard to implement - I may even try to see if I can do it myself, and open a PR in case I succeed. 

> Is this Hadoop cleanup fairly generic? Consider just implementing it on the base hadoop class and make it configurable

Not at the moment, but my pipeline is quite small now, so it may become quite generic in the future - so I'll probably do as you say. Still, having the method would be nice

**Comment by alexeygrigorev** [comment]
I see that you already have an `on_failure` method. Does it have the desired functionality?
