### ISSUE TITLE
Top Artists Example Refers to HDFSTarget in AggregateArtists

### ISSUE THREAD

**Issue by dhurlburtusa** [spotify/luigi#1374]
The `AggregateArtists` class of this example is returning a `luigi.LocalTarget` in the output method. However, the explanation below the snippet talks about HDFSTarget instead:

> `HdfsTarget` is a built in class that makes it easy to read/write from/to HDFS.
> It also makes all file operations atomic, which is nice in case your script crashes for any reason.

I believe it should be explaining `luigi.LocalTarget` instead. I looked up the API documentation for LocalTarget and it said nothing about making all file operations atomic. So I am not sure what the correct wording would be otherwise I would just make a PR.

The change needs to be made in luigi/doc/example_top_artists.rst. Line 66-68 needs to be changed from

> :class:`~luigi.contrib.hdfs.HdfsTarget` is a built in class that makes it
> easy to read/write from/to HDFS. It also makes all file operations
> atomic, which is nice in case your script crashes for any reason.

to something like

> :class:`~luigi.LocalTarget` is a built in class that makes it
> easy to read/write from/to the local filesystem. It also makes all file operations
> atomic, which is nice in case your script crashes for any reason.

**Comment by erikbern** [comment]
Just change the LocalTarget to HdfsTarget in the example

LocalTarget also supports atomic file operations

**Comment by dhurlburtusa** [comment]
Thanks. I will make a PR after I am done reading the documentation.
