### ISSUE TITLE
ReadTheDocs - Latest (Incorrect Page titles)

### ISSUE THREAD

**Issue by dlstadther** [spotify/luigi#1381]
For http://luigi.readthedocs.org/en/latest/*.html, the page titles are "____ -- Luigi 1.0 Documentation".

Since Luigi 2.0 is the Latest, these pages should be titled " _____ -- Luigi 2.0 Documentation".

I can make this change if someone can point me in the correct direction for Luigi ReadTheDoc code.

Thanks,

**Comment by dlstadther** [comment]
^ Same goes for http://luigi.readthedocs.org/en/stable

**Comment by dlstadther** [comment]
Is [luigi/doc/conf.py](https://github.com/spotify/luigi/blob/master/doc/conf.py#L115-L117) the correct code to make this change?

**Comment by erikbern** [comment]
great if you can make the change! not sure where it goes

**Comment by Tarrasch** [comment]
Ah, so that's why Google results always say "Luigi 1.0 Documentation" even though it's not.

Thanks for fixing @mvj3!
