### ISSUE TITLE
dynamic resources

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#1385]
Hi, I need to define dynamic resources, such as:

x = luigi.Parameter()

if x==1:
      resources = {"x1": 1}
elif x==2:
      resources = {"x2": 1}

what is the solution?
I have to change the __init__ function?

I think the way of resources definition should be the same as requires, in a function not in a member variable.

**Comment by mvj3** [comment]
The answer that @erikbern gave at https://github.com/spotify/luigi/issues/1362#issuecomment-152177510 maybe is the right choice. e.g.

```python
➜  python
Python 2.7.9 (default, Jul 27 2015, 11:02:06) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import luigi
>>> class FoobarTask(luigi.Task):
...   x = luigi.IntParameter()
...   @property
...   def resources(self):
...     return {"x{}".format(self.x): 1}
... 
>>> f1 = FoobarTask(x=2)
>>> f1.x
2
>>> f1.resources
{'x2': 1}
>>> 
```

**Comment by erikbern** [comment]
we could change the default interface so that it's a method, might make more sense

let me know if the property decorator works though

**Comment by leafjungle** [comment]
@mvj3 @erikbern , the property decorator works !

Thanks very much. This problem could be closed.
