### ISSUE TITLE
luigi.contrib.pig.PigJobTask pig_parameters not working

### ISSUE THREAD

**Issue by openmartin** [spotify/luigi#1398]
I add some pig_parameters to my task,  in the the command line, I see it use paramter_file，but it's not working, pig script cann't read the paramter.

I read the code, found the tempfile.NamedTemporaryFile()
after writelines, it need flush().

param_file.writelines(line(k, v) for (k, v) in items)
param_file.flush()

prop_file.writelines(line(k, v) for (k, v) in items)
prop_file.flush()

**Comment by openmartin** [comment]
I am on Mac OS X 10.10.5 , Python 2.7.10

**Comment by erikbern** [comment]
Can you put together a pull request? Would appreciate it!

**Comment by openmartin** [comment]
It has already been fixed in master branch, sorry about it. 
Because I install from pip, so I didn't see it.
see commit 82ef8fd9dfe5af3014660c253a653039fbde7905.

This issue can be closed.

**Comment by erikbern** [comment]
Thanks! I will try to push a new version to pip shortly
