### ISSUE TITLE
Luigi Executing MySql query twice

### ISSUE THREAD

**Issue by rohit135** [spotify/luigi#1415]

**Comment by erikbern** [comment]
that's weird – can you provide the full code?

**Comment by rohit135** [comment]
class DailyFacebookReport(ETLTask):
    yml_config_path = Parameter()
    start_date = Parameter(default=(datetime.datetime.now() - datetime.timedelta(days=4)).strftime('%Y-%m-%d'))
    end_date = Parameter(default=(datetime.datetime.now() - datetime.timedelta(days=1)).strftime('%Y-%m-%d'))

    @staticmethod
    def date_range(start_date, end_date):
        for n in range(int((end_date - start_date).days)):
            yield start_date + datetime.timedelta(n)

    def requires(self):
        tasks = []

        sd = self.start_date.split("-")
        ed = self.end_date.split("-")

        first_day = datetime.date(int(sd[0]), int(sd[1]), int(sd[2]))
        last_day = datetime.date(int(ed[0]), int(ed[1]), int(ed[2])) + datetime.timedelta(days=1)

        for single_date in self.date_range(first_day, last_day):
            tasks.append(
                DeleteFacebookReportOutputForDate(
                    self.yml_config_path,
                    self.end_date,
                    single_date.strftime("%Y-%m-%d")
                )
            )

            tasks.append(
                DeleteFacebookReportDataForDate(
                    self.yml_config_path,
                    self.start_date,
                    single_date.strftime("%Y-%m-%d")
                )
            )

        yield tasks

    def run(self):
        tasks = []

        sd = self.start_date.split("-")
        ed = self.end_date.split("-")

        first_day = datetime.date(int(sd[0]), int(sd[1]), int(sd[2]))
        last_day = datetime.date(int(ed[0]), int(ed[1]), int(ed[2])) + datetime.timedelta(days=1)

        for single_date in self.date_range(first_day, last_day):
            tasks.append(
                GetFacebookReports(
                    self.yml_config_path,
                    single_date.strftime("%Y-%m-%d")
                )
            )

        yield tasks

        try:
            connection_data = self.config.mysql['bi']
            connection_data['database'] = 'marketing'
            connection = general.mysql.connect(connection_data)
            cursor = connection.cursor()

            monitoring_query = """INSERT INTO production.table_monitoring_log (country,
                                  table_name,step,updated_at,key_date,
                                  total_rows,total_rows_check)
                                  SELECT "Regional","marketing.facebook_campaign","finish",
                                  NOW(), MAX(date), count(*), count(*)
                                  FROM marketing.facebook_campaign"""

            print "##################################"
            print monitoring_query
            print "##################################"

            cursor.execute(monitoring_query)
            connection.commit()
            with open(self.output().path, 'wb') as target:
                target.write('Done' + datetime.datetime.now().strftime('%Y%m%d%H%M%S'))
        except Exception as e:
            print e

    def output(self):
        return LocalTarget('output/facebook/daily-facebook-%s-%s.log' % (self.start_date, self.end_date))


This is all i can provide to you. This is the class I mentioned above.
Thanks
