### ISSUE TITLE
Issues with command line parameters in luigi 2.0.0 and base classes

### ISSUE THREAD

**Issue by sadovsky** [spotify/luigi#1416]
We have traditionally kicked off our jobs using the following:

```
pythonLuigiController.py LuigiEnsembleScore --workers 5 --BaseLuigi-model-id 166 --LuigiEnsembleScore-id-value 0
```

This used to work fine, but with the new way parameters are parsed, we're unable to set parameters for other classes (besides the Task we're running) at the command line.

Essentially, we have a BaseLuigi class that is inherited by all our tasks:

```
class BaseLuigi(luigi.Task):
    model_id = luigi.IntParameter()

    def __init__(self, s3_path="s3://somepath/", *args, **kwargs):
        luigi.Task.__init__(self, *args, **kwargs)

etc...

```

Then our classes utilize it as so:

```
class LuigiSomeOtherClass(BaseLuigi):

    def __init__(self, *args, **kwargs):
        BaseLuigi.__init__(self, *args, **kwargs)

etc...

```

Make sense?  We're trying to avoid yielding the variable throughout all our classes.  We attempted using globals to fix it, but have some issues around that as well.  Any ideas?  Any way for us to still pass parameters to the base class with the new command line setup?

**Comment by mfcabrera** [comment]
I am closing this. @sadovsky   you may want to take a look at http://luigi.readthedocs.io/en/stable/api/luigi.util.html
