### ISSUE TITLE
Confusing positional parameter advice

### ISSUE THREAD

**Issue by mausch** [spotify/luigi#1424]
http://luigi.readthedocs.org/en/stable/_modules/luigi/parameter.html#Parameter shows that the default value for `positional` is `True`, but a few lines below that in the docstring it recommends `positional=False`, which leads to confusion.

The purpose of the flag is not very clear either.

**Comment by erikbern** [comment]
I think the recommendation `positional=False` applies to the case when you have parameter in an abstract base class. We should qualify that docstring a bit

**Comment by Tarrasch** [comment]
I myself would like to think of the reason for the default to be only historical. :)

Closing, @mausch, please let us know if you still find the new wording to be unclear.

**Comment by mausch** [comment]
Thanks! This is a very nice improvement.
It would be great to have examples of when one would use true or false in this flag.

**Comment by Tarrasch** [comment]
Well. Maybe not the nicest, but you can always `git grep positional=` or [search online on github](https://github.com/spotify/luigi/search?utf8=%E2%9C%93&q=positional%3DFalse)

**Comment by mausch** [comment]
Cheers
