### ISSUE TITLE
Scheduler only hosts on unix socket when run in the background

### ISSUE THREAD

**Issue by jasonnance** [spotify/luigi#1437]
Support for hosting the central scheduler on a unix socket was added, which is nice, but the scheduler ignores the `--unix-socket` argument from the command line when `--background` is not also supplied.  

This will work properly, and the scheduler will listen on the provided unix socket:
```
luigid --unix-socket /path/to/socket --background
```

With this command, the scheduler will still listen on the default port (8082):
```
luigid --unix-socket /path/to/socket
```

Fixing this would be a simple matter of passing the `unix_socket` argument onto the call to `server.run` in the case where the server is not daemonized, but was there a reason this functionality was left out in the first place?  If so, it probably ought to be in the documentation; as is, reading it gives me the impression that I should be able to tell the scheduler to listen on a unix socket regardless of whether it's running in the background.

**Comment by Tarrasch** [comment]
@graingert maybe knows?

**Comment by graingert** [comment]
I've only ever run this in the background so never noticed

**Comment by Tarrasch** [comment]
Oh ok. @jasonnance, would you like to send a PR with a fix? :)
