### ISSUE TITLE
Managing result targets from within luigi

### ISSUE THREAD

**Issue by kevhill** [spotify/luigi#1450]
Hey, I've been using luigi to run some ETL pipelines, and have run into some minor issues with managing deployments. I was wondering how others would handle the situation.

Ok, so the issue is that during development, sometimes the underlying code for each etl step might change. For example, we might add a new column to an intermediate table, or change the data source for an existing column. 

Locally, during development, this is pretty trivial to solve as I can just go and delete the offending task results, those jobs will be rerun, and they handle the updates to the rows themselves.

On production however, this becomes a bit tricker. We are using Docker with a EBS backing for persistent task logs, and have a security-first minded policy that no one should ever need to ssh into a running container or have free access to `docker exec` on the container. So, I'm trying to figure out how to manage the deletion/invalidation of those task logs from within luigi itself. Ideally i would be able to tell a central scheduler running on the container 'hey forget about these particular jobs', but given the separation of execution, my local workers won't be able to see the relevant log files to delete/archive. 

Has anyone run into a similar issue? How did you solve it?

**Comment by Tarrasch** [comment]
When you say "task logs" and "task results". Do you mean "task `ouput()`s"?

Do you mean you are not allowed to delete files on Amazon EBS?

**Comment by kevhill** [comment]
yes, i do mean the `output()`s. Sorry for any confusion.

EBS is not intended to be mounted in multiple places simultaneously, so without ssh'ing into the container, or having some secondary system to manage the mount switching for a production level system, accessing it directly is impossible. What I'm trying to do is avoid having to build and manage a second system.

**Comment by erikbern** [comment]
And you mean some way to delete downstream results given some task?

Yeah that sounds pretty useful. Not sure how to build it but definitely would be cool

**Comment by kevhill** [comment]
Yeah, exactly. Something where I could communicate to the central scheduler 'hey, delete or archive that job output'.

The issues I've come up with when thinking about how to get this done are:

1) how to have a remove worker have access to the job files
2) authorization. Right now there's no form of auth in luigi, and that's probably fine as there is not much havok a person could cause. If you can start to delete job outputs however, this could become a real concern.

**Comment by erikbern** [comment]
this could work with the "assistant" feature somehow (which has been an experimental feature for a long long time now)

**Comment by erikbern** [comment]
basically the scheduler would tell the assistant to delete the output of some task

this also requires extending the target class with a "delete" method, but should be doable

**Comment by kevhill** [comment]
oh. I hadn't the the assistant feature before!

I'm assuming you are referring to this: http://luigi.readthedocs.org/en/latest/api/luigi.interface.html?highlight=assistant#luigi.interface.core.assistant

does that mean you can have the task executed on the scheduler rather than on a separate worker?

**Comment by erikbern** [comment]
kind of... assistants do not schedule any tasks and they can execute any task. so the schedule doesn't execute anything. it's a step towards an architecture where scheudling and execution is separated, and the scheduler can "farm out" work

**Comment by kevhill** [comment]
ah, so i guess not the same process as the scheduler, but executed on the same box?

I'll play around with it and see what I can come up with.

**Comment by erikbern** [comment]
it can be executed on any box

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [x] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
