### ISSUE TITLE
init_mapper/init_reducer will be called twice for LocalJobRunner

### ISSUE THREAD

**Issue by allenlz** [spotify/luigi#1474]
As for init_mapper,

First: https://github.com/spotify/luigi/blob/2959b83f8485d9550a0b5842446e58a434473158/luigi/contrib/hadoop.py#L599

Second: 
https://github.com/spotify/luigi/blob/2959b83f8485d9550a0b5842446e58a434473158/luigi/contrib/hadoop.py#L958

Anyone know how it comes? Maybe a bug?
Thanks.

**Comment by Tarrasch** [comment]
Most probably a bug. Pull requests are welcome :)

**Comment by Tarrasch** [comment]
Great job @allenlz. Very efficient :)
