### ISSUE TITLE
"missing boto" warning for hadoop import

### ISSUE THREAD

**Issue by davemt** [spotify/luigi#1485]
Currently when the `luigi.contrib.hadoop` module is imported we get a WARNING about s3 being imported without boto module available  (also manifests as "No handler for logger" errors if hadoop imported outside the task-running interface context).

I assume plenty of folks are using hadoop without s3, so we should get rid of the warning somehow.

**Comment by erikbern** [comment]
great if you can send a PR resolving this issue :)
