### ISSUE TITLE
Task dependancies running slowly

### ISSUE THREAD

**Issue by a-campbell** [spotify/luigi#1492]
I am running a task with >100000 dependency tasks (each of which has one dependency). It appears that when the scheduler is informed about all these dependencies in the `requires` method, the dependencies are generated very slowly. The log line `DEBUG: Asking scheduler for work` sits there for ~2 minutes before a worker starts running the next dependency. However, when dependencies are dynamically called for in the `run` method, the script moves much faster. Any idea what might be causing this slowdown?

This runs fast:
```
class MyTask(luigi.Task):
    def requires(self):
        self.tasks = list_of_100000_OtherTasks
        return 
    def run(self):
         yield self.tasks.pop()
```

This runs slow:
```
class MyTask(luigi.Task):
    def requires(self):
        return list_of_100000_OtherTasks
    def run(self);
        pass
```

**Comment by erikbern** [comment]
Luigi gets pretty slow with lots of tasks, that's a known issue. Would love it if you can debug a bit and figure out what part of the code is slow and why dynamic requirements are much faster!

**Comment by a-campbell** [comment]
Thanks! I'll take a look.

**Comment by Tarrasch** [comment]
I can partially explain this. The time complexity for `get_work` is O(#pendingtasks). It you use dynamic requirements there will only be at most 1 pending task at any moment.

**Comment by twiecki** [comment]
@Tarrasch That makes sense. Any way to improve the scheduler's scaling?

**Comment by Tarrasch** [comment]
The easiest way is probably to just limit the number of tasks that you require. Maybe you can limit 1'000 tasks at a time and have the program conned to run every minute (it will not run simultaneously thanks to client-side lock). The luigi.tools.range kind of does something like this already. You have a task-limit and it can do the complete checks quite efficiently by using globs or a user-provided bulk complete method.

**Comment by twiecki** [comment]
The number of tasks is provided by the data (each item in the data is processed as a task). Are you suggesting to block the tasks somehow?
But it seems like you're also saying that we won't get parallelization in which case we can stick to the yield method.

**Comment by Tarrasch** [comment]
I'm suggesting something like:

```
def requires(self):
    yield take_first(100, [dependency for dependencies if not dependency.complete()])
```

And in many realistic cases you can use the existing Range module. This parallelizes very good actually. If you have 10 luigi-client machines with 15  `--workers` each, you'll get 150 simultaneously running tasks. Spotify used this strategy for backfilling data.

> But it seems like you're also saying that we won't get parallelization in which case we can stick to the yield method.

Actually it's the other way around.  Yielding 1 task at a time will. You can yield 100 tasks at a time though.

**Comment by twiecki** [comment]
That's very helpful, thanks!

**Comment by Tarrasch** [comment]
I'm closing this. Many viable workarounds are presented so. Please let us know how it worked out for you @twiecki @a-campbell

**Comment by twiecki** [comment]
Confirmed form @a-campbell that it's working well. Thanks again.
