### ISSUE TITLE
test_external_task_retries in worker_test fails since #1449

### ISSUE THREAD

**Issue by ehdr** [spotify/luigi#1521]
Or in other words, an error email is sent when `ExternalTask`s fail, even though no email should be sent(?).

`git bisect` says that f24579704e048b25e47d393af9ebadf843f88ddc is the first bad commit, which is #1449. I think the reason is that f24579704e048b25e47d393af9ebadf843f88ddc [adds an `expl`][1] when failing, but [worker.py still assumes that 'If no `expl`, it is because of a retry-external-task failure'][2], and uses that to check when error emails should be skipped. So since `expl` is no longer `None` there, and email will be sent, even for `ExternalTask`s.

Not entirely sure what the right solution is, but I guess some more robust way of detecting if it is an `ExternalTask` that failed? Would checking `not isinstance(task, ExternalTask)` work, or are there cases where `ExternalTask`s fail for other reasons, and then the error email _should_ be sent?

[1]: https://github.com/spotify/luigi/pull/1449/files#diff-b438c8dc80f50172445c72006dc7c8f7R168
[2]: https://github.com/spotify/luigi/blob/master/luigi/worker.py#L769

**Comment by erikbern** [comment]
sorry i'm confused – the build is currently passing on travis – are you saying that the unit tests incorrectly passes where it should fail?

**Comment by ehdr** [comment]
Hmm... maybe I'm confused as well? ;) Most of the PR's (including my #1520) are failing, see e.g.: https://travis-ci.org/spotify/luigi/jobs/103927232

Also, `tox -e py34-nonhdfs test/worker_test.py` fails for me locally on master?

**Comment by erikbern** [comment]
yeah it fails locally. let me see if we can fix

**Comment by erikbern** [comment]
And btw I'm pretty tired of all this special case handling around ExternalTask. Too much logic relying on various artifacts.

**Comment by ehdr** [comment]
Yeah... Do we even need to set an `expl` at [worker.py:168][1]? You'd still get the message at [worker.py:591][2], right?

A more generic solution might be something like adding a per-task `max_tries` parameter to `luigi.Task`, which could be set to `1` in `ExternalTask` (unless `retry-external-tasks` is `True`)?

[1]: https://github.com/spotify/luigi/blob/f245797/luigi/worker.py#L168
[2]: https://github.com/spotify/luigi/blob/f245797/luigi/worker.py#L591

**Comment by Tarrasch** [comment]
Fixed in #1522 thanks to @casey-green.

**Comment by ehdr** [comment]
:+1:

**Comment by davemt** [comment]
We do want expl, because that gets propagated to the UI. Without this there is no explanation at all in interface when a task is retrying because external input is missing.

**Comment by davemt** [comment]
Would be even better if there was a separate state for external-missing as mentioned in #1522 discussion.

**Comment by erikbern** [comment]
ok i forgot to follow up on it but might take another look at it
