### ISSUE TITLE
Docs are wrong, Python is Strongly typed...

### ISSUE THREAD

**Issue by jeremyjjbrown** [spotify/luigi#1535]
"Python is not a strongly typed language and you don’t have to specify the types of any of your parameters. You can simply use the base class Parameter if you don’t care."

Python is 100% Strongly typed.

https://wiki.python.org/moin/Why%20is%20Python%20a%20dynamic%20language%20and%20also%20a%20strongly%20typed%20language

**Comment by erikbern** [comment]
yes correct. it should say that python is not a *statically* typed language.

can you send a pull request and fix this?

**Comment by Tarrasch** [comment]
This is fixed in PR already
