### ISSUE TITLE
Global luigi params passed through command line

### ISSUE THREAD

**Issue by jumanSalameh** [spotify/luigi#1551]
I have an id that i need to use for all tasks in my workflow, but I do not want to specify a luigi param in each task, since the value is gonna be the same. and I need something cleaner than passing parameters across tasks which is what I'm currently doing. 
The problem about this approach is that the param will be significant only for the task I specify it in and i need it to be significant for all tasks and passed through the command line.
what im doing now is sth like: 

`class A(luigi.Task):`
    `id=luigi.IntParameter()`

`class B(luigi.Task):`
    `def run(self):`
          `runid_param = Parameter()`
           `runid=runid_param.task_value('A','id')`
           `#use id for sth`

**Comment by erikbern** [comment]
You can set the value of a parameter for all task by specifying `--A-id 42` – this should do the trick.

**Comment by jumanSalameh** [comment]
I do that @erikbern but I wanted the param to be significant for all tasks not just A and still be able to use it once in the command.
but thanks a lot. I found a workaround to make the param significant for all tasks instead of global. I needed to pass the param I wanted to use as global backwards to all other tasks starting from the last one which is the one that luigi starts with, but I didnt find a way to use global params instead of passing them through tasks like this:

class B(luigi.Task):
id=luigi.IntParameter()
def requires(self):
return {'my_id':A(self.id)

class A(luigi.Task):
id=luigi.IntParameter()

**Comment by erikbern** [comment]
Yeah I think that's a good solution. It's a bit more verbose but I think it's good to make things explicit :)

**Comment by H4dr1en** [comment]
Well, I have dozens of tasks with 5 global variables that I want to share between all the tasks and passing them from the last task to the first task is definitely too verbose. No possibility to configure this from the luigi.cfg file?

**Comment by H4dr1en** [comment]
So, taken from this [SO answer](https://stackoverflow.com/questions/48509083/how-to-make-a-parameter-available-to-all-luigi-tasks), the proper way to do it is to define a global config class inheriting from `luigi.config`:

```
class globalConfig(luigi.Config):
    shared_param1 = luigi.Parameter()
    shared_param2 = luigi.Parameter()
   ...
```

And now the trick is to use the luigi.cfg file to easily set the value of these parameters:

```
[globalConfig]
shared_param1: global_value_1
shared_param2: global_value_2
...
```

You can then access these global parameters in any step using the following:

```
class myTask(luigi.Task):
    ...
    print(globalConfig().shared_param1)
    ...
```
