### ISSUE TITLE
send_email doesn't trim recipient's email address

### ISSUE THREAD

**Issue by qiao-meng-zefr** [spotify/luigi#1559]
The send_email function simply split email address list by comma, and this leads to email address like " john.doe@example.com" (a space before the address).

The problem line is [here](https://github.com/spotify/luigi/blob/master/luigi/notifications.py#L260)

Suggest fix is:
```python
for r in recipients:
    recipients_tmp.extend(r.split(',').strip())
```

**Comment by erikbern** [comment]
Can you send a pull request? Thanks

**Comment by qiao-meng-zefr** [comment]
Sure

**Comment by erikbern** [comment]
great :)

**Comment by qiao-meng-zefr** [comment]
@erikbern Ready for review.
