### ISSUE TITLE
Salesforce - Handling large datasets

### ISSUE THREAD

**Issue by dlstadther** [spotify/luigi#1575]
Within the salesforce module i wrote, a segmentation fault will occur when querying for very large datasets.

When querying all, a [single list is maintained and extended](https://github.com/spotify/luigi/blob/master/luigi/contrib/salesforce.py#L314). For small(er) datasets this isn't problematic, but large sets cause a segmentation fault due to lack of memory. Based on what I gathered from [someone's SO](http://stackoverflow.com/questions/19127777/a-python-segmentation-fault), this memory issue was not caught because it occurred within a recursive function.

**What I'm seeking is best practice in Python (or in general) to handle the maintenance of large datasets.** Is it best to sacrifice speed, bite the bullet and deal with tons of I/O operations by appending to a local tmp file? Or is there something better? I know that pandas dataframes exists, but I'm not sure if that's the best option due to some of the [known Pandas Caveats](http://pandas.pydata.org/pandas-docs/stable/gotchas.html#nan-integer-na-values-and-na-type-promotions).

(For reference, the Salesforce download was successful for 360,000 records, but failed at 540,000 (and counting).)

**Comment by garynackenson** [comment]
The memory issue in the SO was due to having a recursive function with an
unbounded limit. :)
