### ISSUE TITLE
S3 multipart directory copy not working

### ISSUE THREAD

**Issue by jpiper** [spotify/luigi#1582]
The method call [here](https://github.com/spotify/luigi/blame/master/luigi/s3.py#L361) is using an incorrect method signature which means when trying to copy a folder of files with files larger than 64mb, the copy will fail. Unfortunately because of the `moto` bug that prevents the s3 multipart_copy test from working, this isn't covered in the test suite.

Also, we have two sets of threading methodologies here, where the `multipart_copy` doesn't use the same thread pool as the the copy method.

I'll try and consolidate both of these methods into one `copy` method that share a common thread pool.

**Comment by erikbern** [comment]
great!
