### ISSUE TITLE
Help, Could I build and run async tasks with pure python?

### ISSUE THREAD

**Issue by fy0** [spotify/luigi#1590]
Example:
Here's a server, the task sender.
Users request for task, then server ask for luigid to start task, and keep task id because users may be want to know status of tasks.
Could luigi do this? 

class Task1 ...

class Task2 ...

t1 = Task1()
t1.async_run()

Or maybe I'm wrong because luigi just care workflow, I must be use something like celery to run tasks?
But celery have it's own task list, should I setting many many workers to keep task priority works?
I'm puzzled ..

**Comment by Tarrasch** [comment]
Try reading this page first: http://luigi.readthedocs.org/en/latest/execution_model.html

It explains a bit and shows you the luigi-jargon so you can pose an easier-to-understand question :)

**Comment by fy0** [comment]
No executor, no asynchronous, right?
