### ISSUE TITLE
Dependency graph visualization does not display arrows in chrome.

### ISSUE THREAD

**Issue by ziky90** [spotify/luigi#1604]
I am using the last released version of luigi 2.0.1 and I have find out that chrome does not display arrows in the D3 visualization.

My version of chrome is: 48.0.2564.116 (64-bit)

When I go to the Javascript console, I am getting the following error:
![image](https://cloud.githubusercontent.com/assets/1810839/13949428/4a461044-f025-11e5-84b1-d3cece764113.png)

**Comment by thomasgilgenast** [comment]
I'm seeing the same error on Chrome Version 49.0.2623.112 m (32-bit) with luigi==2.1.1

**Comment by dlstadther** [comment]
I'm just kinda guessing here, but D3 is mentioned within [visualiserApp.js](https://github.com/spotify/luigi/blob/master/luigi/static/visualiser/js/visualiserApp.js) which was commited by @stephenpascoe as PR #1086 . Maybe he'd know what might be causing this.

**Comment by stephenpascoe** [comment]
I'm seeing the same now in Version 49.0.2623.87 (64-bit).  The upstream project has a ticket for it (https://github.com/cpettitt/dagre-d3/issues/202).  I think it only needs an upgrade to dagre-d3.
