### ISSUE TITLE
Parallel scheduling can't handle externalized dependencies

### ISSUE THREAD

**Issue by daveFNbuck** [spotify/luigi#1608]
If you do something like
```
def requires(self):
    return luigi.task.externalize(SomeTask())
```
in a Task and then schedule it with the `--parallel-scheduling`, the scheduling will hang forever. The cause is that externalize sets `task.run = NotImplemented` and `NotImplemented` is not serializable so it can't be put in the multiprocessing queue.

My instinct is to fix this by just setting `task.run = None` or some other picklable value and treating that like NotImplemented in worker, but I'm afraid this will have weird side effects and leave the bug open for people implementing their own externalize functionality. Any other ideas?

Also, there's no indication that anything bad happened when this bug is triggered. We should find a way to catch this type of error and kill scheduling when it happens.

**Comment by erikbern** [comment]
sgtm – we could just change `NotImplemented` to `None`

**Comment by daveFNbuck** [comment]
If we just change NotImplemented to None, won't that potentially break user code?

**Comment by erikbern** [comment]
I think it's fine. We should probably check both cases in worker.py just in case someone has old code. But off the top of my head I don't see why it would break any code

**Comment by metra** [comment]
Would it be possible to log any pickling exceptions to make it obvious that there was an error queuing up the task?
