### ISSUE TITLE
Do not show non-significant parameters in history

### ISSUE THREAD

**Issue by fjavieralba** [spotify/luigi#1615]
I've configured luigi to store history in a SQLite.

When I access my task history at `luigi-scheduler:8082/history`, the interface is showing non-significant parameters such as passwords etc.

It would be great to not store that info in the DB, or at least avoid showing them in the GUI.

I'm using the latest stable release (Version 2.0.1)

**Comment by erikbern** [comment]
sounds like a good idea – can you send a pull request? thanks!

**Comment by fjavieralba** [comment]
Sure, will look into it :)

**Comment by mfcabrera** [comment]
Closing this as there is already many PRs dealing with this and there is a decision to be made regarding how to handle this properly. See https://github.com/spotify/luigi/pull/1892/files#diff-f5f076fb9da1107cb1221ae176bbc955R91
