### ISSUE TITLE
[Feature request/discussion] Spark context worker

### ISSUE THREAD

**Issue by eadgbear** [spotify/luigi#1617]
I have already implemented this in [my own branch](https://github.com/slyons/luigi/tree/spark-context-worker) but I really would like some feedback before I put together a pull request. 

We have a need to execute a series of tasks all within the same Spark context. I achieved this by starting a luigi worker from within a running Spark context. The worker runs forever and runs whatever PySpark tasks are handed to it. It all feels like a bit of a hack, currently.

Does anyone have any ideas about how this could be done better?

**Comment by mfcabrera** [comment]
Hi @slyons could you create a PR for review? What would be a use case for this?. I think this would good for a "contrib" or a external repository outside of Luigi  as right now I can't understand think of a use case myself.

**Comment by Benyuel** [comment]
I've created/use something with a very similar purpose as slyons implementation.  An example is if I want to run a pipeline that has 3 tasks: Task 1 reads data, Task 2 processes it using a ML algorithm developed within spark, Task 3 writes/handles the output, Task 4 runs arbitary sparkSQL(file on HDFS) on the output.  If I want to run all of this using luigi within one pyspark context, I don't think this is doable as luigi currently stands (You'd have to submit 4 independent spark apps).  

The alternate implementation I use is [here](https://github.com/Benyuel/luigi-spark) for reference.  It has other modified features, so it's not solely for this purpose above.   This implementation handles submitting spark jobs programmatically via luigi and those spark jobs can be luigi tasks as well.  Once you submit a luigi task within a pyspark context, the modification in that repo allows arbitrary workers (cluster nodes running the spark job on a yarn cluster) to connect to my central scheduler and handle dependencies, resources, etc,. as a 'normal' luigi task would do outside of spark.  It's a little convoluted, but hopefully that makes sense.
