### ISSUE TITLE
Add B

### ISSUE THREAD

**Issue by jpotts18** [spotify/luigi#1618]
Bigquery allows for different field delimiters such as the pipe character "|" but this library does not support it

It would need to be added to the `configuration.load.fieldDelimiter` section of the job

https://github.com/spotify/luigi/blob/master/luigi/contrib/bigquery.py#L445

**Comment by Tarrasch** [comment]
Can you edit issue title to something more descriptive please?

**Comment by jpotts18** [comment]
I already have a PR for this #1619. I'll just close this.
