### ISSUE TITLE
Visualizer fails with similar range targets.

### ISSUE THREAD

**Issue by nugend** [spotify/luigi#1627]
I'm using Range Targets to guide the loading of some information that appears on a daily basis that we want to load ASAP. (We have the configuration set to retry on external task failures and to keep the workers alive)

When you run two Range Targets with the same parameters at the same time, but the target task has different parameters, the visualizer will only display one of the range targets in any given screen. The sub-tasks are of course still present and Luigi doesn't appear to have any issue with the Range targets being identical, so I am presuming this is an okay way to use Range. I don't know enough about JS to dig in and figure out what's going wrong, but I imagine it has something to do with the task parameters being identical.

My command lines look something like this:

```
# Note that I use 2016.04.01 to mean, start loading today's data. This is set in our cron job to change to whatever the current date is whenever it re-executes (which would be as soon as the job exits)
# 2 Days forward takes care of any issues with the international date line
luigi --module mymodule RangeDaily --start 2016.04.01 --days-forward 2 --of MyTask --MyTask-myparam 1
luigi --module mymodule RangeDaily --start 2016.04.01 --days-forward 2 --of MyTask --MyTask-myparam 2
```

Am I just going about this backassward? I feel like this would be an issue if you had to run a range on a parameterized task for any reason. Just to reiterate, there's *no* problem with the jobs running or anything, this only shows up as an issue in the visualizer.

**Comment by Tarrasch** [comment]
I wish this day would never come ... I was aware of this design issue when redesigning the parameter system. Though I opted for it to make the common case easy.

Yea the problem is indeed that the parameter set to the RangeDaily tasks is identical. If you can't live with it, just hack around and set different `--start` parameters. If you can't live with that bad hack, we should think about a proper solution ...

**Comment by nugend** [comment]
For me, it's a bit of an issue since I actually wrote a subclass of RangeDaily to let me *just* specify `--days-forward` and `--days-back` (so I could have jobs that are always looking forward and filling in anything missing from the past few days).

I mean, it's not a high priority for me since everything seems to work and the Scheduler doesn't really seem to have any problem with it, and we're not heavily relying on the visualizer, but it'd be *nice* if it worked right.

**Comment by nugend** [comment]
Now that each job is in part associated with a hash identifier, maybe that could be used to differentiate between instances in the visualizer?

**Comment by Tarrasch** [comment]
Actually. I totally forgot about this simple solution:

----

Use a new `DictParameter` called "pass-along" or something. This line:

    luigi --module mymodule RangeDaily --start 2016.04.01 --days-forward 2 --of MyTask --MyTask-myparam 1

becomes

    luigi --module mymodule RangeDaily --start 2016.04.01 --days-forward 2 --of MyTask --pass-along {myparam:1}

----

It doesn't solve the global problem, sure. But this common use case is solved.

**Comment by nugend** [comment]
Just to make sure I am correctly understanding the work around: I would modify RangeBase (or a sublcass, presumably) to have the pass-along parameter, then actually instantiate the of-class instance by using that dictionary as it's keyword arguments?

**Comment by Tarrasch** [comment]
Yes, pretty much. You have to change RangeBase itself. You would need to send a PR to this repository.

In particular this code needs to be changed to use the new parameter.: https://github.com/spotify/luigi/blob/8d39715092a67de0537e7c173babe6b8279d74ef/luigi/tools/range.py#L176-L181

Would you be interested to send a PR? :)

**Comment by nugend** [comment]
Not really. That sounds like a pretty screwy hack, especially if it *has* to be on the RangeBase class.

If I knew JS at all, I'd offer to try and figure out how to fix the visualizer.

**Comment by Tarrasch** [comment]
Disagree. I think it resolves the problem by removing a hack. The current hack is that in different execution environments (different global parameters), the one and same instantiated task (some RangeBase-child) requires *different* tasks for the same set of parameters it is input with. It's like using global variables. If we explicitly thread along all parameters from RangeBase, it becomes more like a pure and global-state-independent task.

What makes you think the problem is in the visualiser? There's no way the scheduler (which only acts on taskids) can resolve this.

**Comment by nugend** [comment]
Hmm, guess I'm a little confused on how the scheduler is identifying the different instances of the Range tasks.

I'll look at the scheduler code more in depth so I can understand it better.

**Comment by nugend** [comment]
Hey, sorry. I've been a little busy. Do you know if this would also affect the worker count_uniques option?

**Comment by Tarrasch** [comment]
Yes I think it will affect count_unqiues. Because the metatask (RangeBlah) is going to be assigned different ids when it's passing along different parameters to the child tasks.

**Comment by nugend** [comment]
Heh. Turns out it is causing an operational issues for me. Because I've got keep alive set to wait on some external tasks, some of the jobs aren't terminating so they can be rescheduled appropriately. I'll try and implement your suggested solution. After thinking about it more, I think you're right that it's the right way of taking care of it.

Also, I was also thinking about whether or not TaskParameters should *always* be accompanied by a pass-through or not. I couldn't come up with a great example that wouldn't be taken care of by a subclass of Range though. Any thoughts on whether pass-through is a general concept or not? I'll just work on the Range version, but I wonder if this'll come up again.

**Comment by Tarrasch** [comment]
Lol, are you suggesting to introduce `ParametersParameter`? ^^

I see your point. Let's start with not generalizing as you did in your PR. :)

**Comment by nugend** [comment]
No, no DictParameter is perfectly fine for passing along parameters (I think?). Sorry, I just meant it seemed like if you were taking a TaskParameter, you'd probably need to be able to pass parameters to it in a lot of cases.

The more I thought about it though, I believe that is really only the case when a TaskParameter is present in a subclass of WrapperTask (as is the case for Range)
