### ISSUE TITLE
Multiple Luigi.cfg Issues

### ISSUE THREAD

**Issue by dlstadther** [spotify/luigi#1629]
I have two separate packages of files (different ETL jobs) which both utilize the luigi framework. Thus, each have their own luigi.cfg with different contents. _No luigi_config_path has been set within environmental variables._

For the sake of simplicity, my directory structure looks approximately like the following:

```
/
-home
--ubuntu
---venv-etl-1
----scripts
-----execute.py
-----luigi.cfg
-----logging.conf
----...
---venv-etl-2
----scripts
-----execute.py
-----luigi.cfg
-----logging.conf
----...
```

`/home/ubuntu/venv-etl-1/scripts/luigi.cfg` has max reschedules set to `1`, while `/home/ubuntu/venv-etl-2/scripts/luigi.cfg` has it set to `3`.

However, both `venv-etl-x` jobs are rescheduled up to 3 times if there is a failure.

Both etl jobs run within virtualenvs and at separate (non overlapping) times.

**Comment by Tarrasch** [comment]
I have no idea what "max-reschdules" does. The docs (and code) seems to suggest it's worker-side thing. I don't get it. We have a scheduler so that worker shouldn't do re-schedules. Only the scheduler knows the "life story" of each Task no?

**Comment by dlstadther** [comment]
I found the issue over the weekend, but didn't look in the code yet to see what caused it. I'll try to investigate some more.

**Comment by dlstadther** [comment]
@Tarrasch , I can't speak to the internals of worker vs scheduler, but the docs and code do suggest that reschedules are handled by the worker.

So I still don't fully know what causes this, but I did find that the [docs](http://luigi.readthedocs.org/en/latest/configuration.html) note that the `[core]` option is called `max_reschedules`, but it looks in the configuration file for `worker-max-reschedules`. Since making this change in my luigi.cfg files, I haven't noticed the incorrect number of reschedules (but considering it's rare that jobs need to be rescheduled - it isn't a big deal for my daily executions).

A small change that I can make if necessary is update the [doc](https://github.com/spotify/luigi/blob/master/doc/configuration.rst#core) (from `max-reschedules` to `worker-max-reschedules`. If you're ok with this, i'll submit a quick PR.

**Comment by Tarrasch** [comment]
Actually what's wrong in the docs (and have been so for ages!) is that many things from `[core]` should be moved into `[worker]`. It's already done in the code and deprecation warnings are thrown, but the docs aren't updated :-/.

**Comment by dlstadther** [comment]
Oh wow, after closer look, there are a lot of issues with the docs for configuration variables.

* Doc's names match variable names more often than the config_path name which will be searched for.
* `wait-jitter` and `no-install-shutdown-handler` are the only worker config variables which don't default to `[core]`.

I'm also now confused as to why some configuration classes even specify `config_path`. Sometimes they do so to look in other sections (which is semi understandable in cases to be deprecated), but other times config_path is used to explicitly look within their own section (see [scheduler](https://github.com/spotify/luigi/blob/master/luigi/scheduler.py#L81-L104)).

I don't see these deprecated warnings you mention.

I'll put on my radar to update configuration docs for various sections based on what these sections have specified in their config classes.

**Comment by Tarrasch** [comment]
Yea, exactly, it's a mess. :-/

If the actual path is `[worker] timeout:`, but people use `[core] worker-timeout:`, they'll get a warning thrown by luigi during runtime. That's good, but it's bad that that happens when you follow the instructions in the docs.

**Comment by mfcabrera** [comment]
ping @Tarrasch  @dlstadther should we keep this open?

**Comment by Tarrasch** [comment]
Unfortunately we didn't keep to topic in our discussion. So we might as well create a new ticket whenever the issue araises.

In the meantime, did you find any interesting workaround @dlstadther ?

**Comment by dlstadther** [comment]
This was a long time ago (or at least what feels like a long time). My environment is very different than it used to be so I haven't re-experienced this issue.

Documentation around configuration names and sections definitely need to be fixed, but that's tangental to this issue and should be its own.
