### ISSUE TITLE
Cannot write to a binary file (LocalStorage)

### ISSUE THREAD

**Issue by wires** [spotify/luigi#1647]
Trying to implement a `msgpack` target (maybe not right approach...)

``` py
class MessagepackTarget(luigi.file.LocalTarget):
    def __init__(self, filename):
        super(MessagepackTarget, self).__init__(path=filename)

    def dump(self, d):
        with self.open('wb') as f:
            msgpack.pack(d, f)
```

This fails wether using mode `w` or `wb`:

```
  File "... python3.5/site-packages/msgpack/__init__.py", line 38, in pack
    stream.write(packer.pack(o))
TypeError: write() argument must be str, not bytes
```

I also tried with different format `super(MessagepackTarget, self).__init__(path=filename, format=GzipFormat)` but that fails as well:

```
  File "... python3.5/site-packages/luigi/file.py", line 126, in open:
    return self.format.pipe_writer(atomic_file(self.path))
TypeError: pipe_writer() missing 1 required positional argument: 'output_pipe'
```

What am I doing wrong?

**Comment by erikbern** [comment]
sounds like a python 3 thing.

can you figure out what's the underlying issue and send a pull request? much appreciated

**Comment by wires** [comment]
I tried, including various work arounds, but I couldn't get it to work... I think maybe it's due to somehow opening the file in 'w' mode, here https://github.com/spotify/luigi/blob/master/luigi/target.py#L266

I will isolate an example demonstrating the issue!

**Comment by erikbern** [comment]
I think Python 3 has both TextIO and BytesIO. We should probably pick one of them based on whether "b" is in the mode. Not sure

**Comment by wires** [comment]
O_O ... I am not sure either, other than that I'm not enjoying this Python 3 transition ⛅

https://docs.python.org/3/library/io.html#binary-i-o <= on first sight it looks like you are right, picking `BytesIO` on `b` might do the trick.

**Comment by wires** [comment]
OTOH, `FileIO` should be able to `write(bytes)` as well... (as it implements `RawIOBase`) 😕 https://docs.python.org/3/library/io.html#io.RawIOBase.write

**Comment by wires** [comment]
```py
# test.py
import luigi

class Test(luigi.Task):
    def run(self):
        self.output().open('wb').write(b'1234')

    def output(self):
        return luigi.file.LocalTarget(path='/tmp/zzzz')

# python -m luigi --local-scheduler --module test Test
# => TypeError: write() argument must be str, not bytes
```

^ minimal example demonstrating the problem

```py
import io
# fails
#br = io.BufferedWriter(io.FileIO('/tmp/xzz', 'w'))
#br.write(b'134')

# works
br = io.BufferedWriter(io.FileIO('/tmp/also_works', 'wb'))
br.write(b'134')
```

**Comment by wires** [comment]
Hmm,

seems the problem is indeed in format, passing `NopFormat` works...

```py
import luigi
from luigi.format import NopFormat

class Bullshit(luigi.Task):
    def run(self):
        self.output().open('wb').write(b'1234')

    def output(self):
        return luigi.file.LocalTarget(path='/tmp/zzzz', format=NopFormat)

if luigi.build([Bullshit()], workers=1, local_scheduler=True):
    print("success")
```

**Comment by erikbern** [comment]
so let's just fix it so that we pass the flags to io.FileIO.

can you give it a shot and send a pull request? thanks!

**Comment by wires** [comment]
Yeah, I fixed it here locally finally. I'll give PR a try, we can discuss the implementation details further there

**Comment by wires** [comment]
Hi, sorry, got interrupted; WIP branch is here https://github.com/wires/luigi/tree/issue-1647 will PR when done (test, etc).

I'm wondering about this strange thing, the following code doesn't work:

```py
return self.format.pipe_writer(atomic_file(self.path))
```
```
  File ".../python3.5/site-packages/luigi/file.py", line 126, in open
    return self.format.pipe_writer(atomic_file(self.path))
TypeError: pipe_writer() missing 1 required positional argument: 'output_pipe'
```

But this code does:

```py
af = atomic_file(self.path)
return self.format.pipe_writer(self.format, output_pipe=af)
```

Any thoughts?

**Comment by dlstadther** [comment]
The line you note as not working is what currently exists in Luigi and has tests which `open('w')` (thus executing that line of code).

Where is the location of this `self.format.pipe_writer(...)`?

**Comment by wires** [comment]
Ah, it's `luigi/file.py:126`, sorry I meant no longer working after patching it https://github.com/wires/luigi/commit/280c5e0446090f36f90db376b6628e673c4fa863

**Comment by wires** [comment]
I made a PR https://github.com/spotify/luigi/pull/1648 please don't merge yet ; this should make it easier to discuss it.

**Comment by timiyay** [comment]
Just started experimenting with `luigi`, trying to use it in a workflow that downloads a binary `.zip` file and writes it do disk.

I hit this issue immediately on Python 3.

FWIW, my expectation was that `self.output().open('wb')` would behave as expected. I would support an implementation that makes this happen.

**Comment by dewet22** [comment]
I hit the same issue trying to save task state using `pickle` objects. My current workaround is to use 
```with open(self.output().path, 'wb') as out_file:```
instead of
```with self.output().open('wb') as out_file:```

**Comment by wires** [comment]
It turns out that setting `format=luigi.format.Nop` on the target also does the trick. 

```python
def target(self):
    return LocalTarget(..., format=luigi.format.Nop)
```

**Comment by cmmp** [comment]
Is there any update to this?

It's February 2017. I just tried out Luigi and my first task hit this bug because of pickled files.

**Comment by dlstadther** [comment]
@cmmp does the comment above your not work for you? (setting `format=luigi.format.Nop`)

**Comment by cmmp** [comment]
@dlstadther it does work, but it's sad to write code using workarounds :(

I was really excited to use Luigi (coming from a Gearman background), but this made me a little sad. I mean, I get this is open source, but this bug is from April last year and there is a potential workaround from the same time https://github.com/spotify/luigi/pull/1648 that seems abandoned. I'm using Python 3 for everything. I'm now worried to start using it if support is not good atm.

**Comment by wires** [comment]
@cmmp I wanted to change this PR to become a documentation update which
explains that `format` option is needed for binary files, but didn't free
time yet. It was more confusion on how Luigi works than a "real bug".

And FWIW, we are still using Luigi, where most data is stored using
`msgpack` (as pickle doesn't perform except for the smallest datafiles).
Our processing code derives from a base class that (amongst others) sets up
`msgpack` writing. This has been running in production without too many
issues.

But (and I hope I don't offend anyone), I must say Luigi is somewhat
incidentally complex and brittle and in retrospect maybe not the best fit
for our use-case. Still, with some effort Luigi gets the job done and
otherwise stays out of your way.

There are good alternatives though, for instance, if you use pandas, you
might like [dask](https://dask.readthedocs.io/en/latest/) which is a part
of [the blaze ecosystem](http://blaze.pydata.org/).

HTH

**Comment by cmmp** [comment]
@wires That is an incredibly helpful answer. Thank you very much. I will look into dask and blaze.

**Comment by rhunwicks** [comment]
> My current workaround is to use `with open(self.output().path, 'wb') as out_file:` instead of `with self.output().open('wb') as out_file:`

@dewet22 with this approach I think you are bypassing the atomic file functionality of `LocalTarget` and writing directly to the final file. I.e. in a parallel execution environment a second worker might think the Task is complete before it really is.

**Comment by honnibal** [comment]
So the source of that open method is:

```python

    def open(self, mode='r'):
        rwmode = mode.replace('b', '').replace('t', '')
        if rwmode == 'w':
            self.makedirs()
            return self.format.pipe_writer(atomic_file(self.path))

        elif rwmode == 'r':
            fileobj = FileWrapper(io.BufferedReader(io.FileIO(self.path, mode)))
            return self.format.pipe_reader(fileobj)

        else:
            raise Exception("mode must be 'r' or 'w' (got: %s)" % mode)
```

It intentionally clobbers the 'b' from the format string. But why is that necessary?

**Comment by phowson** [comment]
@honnibal I agree. If someone is putting "b" in the string, it implies they don't understand luigi and don't know about the format constructor argument for LocalFile. I propose that the presence of a 'b' should throw an appropriate exception with the text "Use format=.....", rather than swallowing the "b"

**Comment by dcheck** [comment]
I've used luigi for several years, and just ran into this while upgrading to Python 3.

As a user, it's very confusing to find that I can't write a binary target file by opening it with a 'wb' mode.  Even if `format.Nop` were documented, it would be confusing for luigi target file semantics to be almost-identical to the python standard.  Standard fs usage is to pass the binary flag to `mode`, not to set a separate `format` kwarg.

Is there support from the code owners for an implementation that supports `mode=wb` for Targets?  I think several people in this thread would be happy to offer code, but need some direction on acceptable solutions first.

**Comment by dlstadther** [comment]
@dcheck I'm not intimately familiar with the implementation of Targets and why they were written the way they were. But that said, I'm open to improving them for binary writes.

Feel free to submit a PR, easing this behavior! Thanks!
