### ISSUE TITLE
SGEJobTask can fail on NFS due to use of shutil.rmtree

### ISSUE THREAD

**Issue by brcopeland** [spotify/luigi#1665]
First off, thank you @jfeala for the sge module.  I'm using luigi.contrib.sge.SGEJobTask to run jobs on my cluster and my temporary drive is on an NFS.  Not uncommonly, I get a traceback of the sort:

Traceback (most recent call last):
  File "/nfs/goldstein/software/python2.7.7/lib/python2.7/site-packages/luigi/worker.py", line 175, in run
    new_deps = self._run_get_new_deps()
  File "/nfs/goldstein/software/python2.7.7/lib/python2.7/site-packages/luigi/worker.py", line 117, in _run_get_new_deps
    task_gen = self.task.run()
  File "/nfs/goldstein/software/python2.7.7/lib/python2.7/site-packages/luigi/contrib/sge.py", line 215, in run
    self._run_job()
  File "/nfs/goldstein/software/python2.7.7/lib/python2.7/site-packages/luigi/contrib/sge.py", line 265, in _run_job
    shutil.rmtree(self.tmp_dir)
  File "/nfs/goldstein/software/python2.7.7/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/nfs/goldstein/software/python2.7.7/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/nfs/goldstein/software/python2.7.7/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/nfs/seqscratch09/bc2675/luigi_test/SimulateGeneBatchData__nfs_central_hom_63__nfs_central_hom_0feed55ade-8fa44d4fc0b45350/luigi'

I've read that shutil.rmtree can fail on an NFS due to too slow of a response.  I believe that changing line 265, `shutil.rmtree(self.tmp_dir)` to `subprocess.call(["rm", "-rf", self.tmp_dir])` should yield the same results while alleviating this problem.  This solution is obviously not portable to Windows, so this could be used if an OSError is thrown as a backup.

**Comment by jfeala** [comment]
Hi @brcopeland, thanks for using the SGE module!

It might be a hack, but does it help if you pause for a second (`time.sleep(1)`)  before deleting the tmp_dir? I wouldn't want to break Windows compatibility.

**Comment by jfeala** [comment]
on second thought, since this always has to run on SGE master node, it should never need windows compatibility. Does your proposed fix work? If so, please submit a PR because I've heard of similar issues with NFS race conditions.

**Comment by brcopeland** [comment]
Hi Jake, I made this change on my copy of luigi when I made this post and I have not encountered any problems since.  I'll submit the request.  Two other notes/modifications I've made to my local copy:
1. I parameterized the poll time for qstat, as personally I'm executing long running jobs and there may be several hundred at a time, thus taking up a lot of CPU cycles - any reason you chose to hardcode this?
2. I added a parameter to SGEJobTask (--run-locally) to have a job run locally instead.  I find this helpful in order to test these tasks without having to change the code at all.

Would you be interested in pull requests for either?

**Comment by mfcabrera** [comment]
Closing because it is apparently fixed by #1794
