### ISSUE TITLE
Dynamically change number of workers once a workflow has been launched

### ISSUE THREAD

**Issue by levipierce** [spotify/luigi#1678]
It would be incredibly useful to dynamically change the number of luigi workers once a workflow has been launched.  In this case I can scale up the number of spot requests in our kubernetes cluster to say 50 but I launched my luigi workflow with workers=25.  Maybe this exists?  I was thinking the control loop could read some environment variable and dynamically change the number of workers?  We do this with the autoscaler we built storing this number in etcd.  You can just curl and update the value of the key and the autoscaler will continue to make new spot requests.  Happy to implement this if you guys think this is doable...

Cheers,
~LP

**Comment by Tarrasch** [comment]
I've not seen this use case yet to be honest. I can give you some guidance if you want to implement this. But before doing that, please remember these workarounds that might be enough:

 * You can launch the luigi workers programatically. See `luigi.interface` module. Though it doesn't help you alter the number of workers once the workflow has commenced.
 * Even if you specify --workers 10000. Luigi will only create processes lazily. That is, if you have no more than 100 tasks only 100 processes will be created. Perhaps, one might want to experiment batching once workflow by using `--workers X --worker-task-limit Y`

**Comment by steveb-cirina** [comment]
+1 from me

I think this would be a useful feature as I sometimes have to throttle back a workflow that takes days so others may do compute intensive but shorter running tasks.  I also run into the situation where I realize after the fact that I could have launched more workers.

Thanks,
Steve

P.S. Luigi has been a great tool !  Thanks for supporting it.

**Comment by Tarrasch** [comment]
This is implemented in Luigi now (https://github.com/spotify/luigi/pull/1993), closing.
