### ISSUE TITLE
[WIP] Salesforce does not download all results for large result set

### ISSUE THREAD

**Issue by dacort** [spotify/luigi#1685]
For particularly large result sets, Salesforce will return multiple result IDs for a single batch. 

However, in [`get_batch_results`](https://github.com/spotify/luigi/blob/master/luigi/contrib/salesforce.py#L489), only the first result ID is being returned. The code should utilize `ET.findall` to return a list of result IDs and download each of those to append to the output file.

I'm planning on submitting a PR for this in the next couple of days.

**Comment by dlstadther** [comment]
@dacort Sorry about this. I wrote the bulk of Salesforce.py. Most of my salesforce queries involve the salesforce version of joins and so I was never able to use/test batch results well.

Thanks for your desire to improve this module!

**Comment by dacort** [comment]
No problem @dlstadther! Happy to be able to contribute. :)

**Comment by dacort** [comment]
Just realized this creates a CSV file with multiple headers. This shouldn't be merged in yet.

**Comment by dlstadther** [comment]
Once things are fixed, i'll review once more
