### ISSUE TITLE
TravisCI cdh builds are failing

### ISSUE THREAD

**Issue by dlstadther** [spotify/luigi#1687]
Something is going on with TravisCI when reading requirements for hdfs version number. For some reason, it's trying to parse part of the in-line comment and then failing.

I'm not aware of why this is happening just now and not always.

**Comment by Tarrasch** [comment]
It's because of tox 2.3.0 now existing on da internetz. http://tox.readthedocs.io/en/latest/changelog.html#id3

I'll submit a fix right now.

**Comment by Tarrasch** [comment]
Oh, I forgot to say. Thanks for reporting this @dlstadther :)
