### ISSUE TITLE
Failed job doesn't give non-zero exit code

### ISSUE THREAD

**Issue by arnov** [spotify/luigi#1721]
A failing job doesn't quit with a non-zero exit code

```
This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====


real    0m35.030s
user    0m46.968s
sys     0m2.036s
((conda)) [hadoop@ip-123-45-67-890 current]$ echo $?
0
```

**Comment by dlstadther** [comment]
Could you provide more detail on this job failure? What module are you using, does it happen all the time, etc.

**Comment by Tarrasch** [comment]
This is intended behaviour. See http://luigi.readthedocs.io/en/stable/configuration.html#retcode

**Comment by arnov** [comment]
Ah thanks, I must have missed that part of the docs :)
