### ISSUE TITLE
Enable overriding of retry_delay when running stuff manually

### ISSUE THREAD

**Issue by freider** [spotify/luigi#173]
Currently if a task fails you need to wait 15 min (the default retry_delay) before the the central scheduler will let the same or another worker run the task. This is to prevent triggering too many tasks that are failing anyways. However, when runnings things manually this can be quite annoying and you can't always run with --local-scheduler (if you for example have multiple overlapping pipelines). 

I suggest adding a --force-retry flag or similar that allows you to override the retry_delay from the client side (but it should only override failed retry, not run the task if some other worker is currently running it, which is already possible through --central-scheduler).

Additionally, I suggest that tasks that are killed by user interrupts (KeyboardInterrupt) should send some kind of message to the scheduler when shutting down, notifying it to not set a retry_delay, since it's probably undesirable to have aborted manual runs prevent scheduled ones.

**Comment by Tarrasch** [comment]
This is fixed 4 years later by @FxIII in #2091! Wohoo! (by fixed I mean reasonable work-around)

**Comment by FxIII** [comment]
@FxIII gains the ***necromancer*** badge
