### ISSUE TITLE
HdfsTarget commands fail when many targets are instantiated

### ISSUE THREAD

**Issue by daveFNbuck** [spotify/luigi#1740]
I've recently added an existence check to a large mapreduce task for which some input files may be missing. With a large enough set of inputs, it will fail every time. I've simplified it to the following code:

```python
from luigi.contrib.hdfs import HdfsTarget

many_targets = [HdfsTarget('/') for _ in range(2000)]
all(target.exists() for target in many_targets)
```

This will break if I use any past 1000 or so. Here the client uses snakebite. For a more direct triggering, we can also do

```python
from snakebite.client import AutoConfigClient

clients = [AutoConfigClient() for _ in range(10000)]
all(client.test('/', exists=True) for client in clients)
```

In either case, the bug goes away if I use a generator expression rather than a list comprehension. The problem is that when I'm dealing with objects coming out of luigi calls like input_hadoop, it's too late for me to decide between lists and iterators. I can code around this by instantiating all of my HdfsTargets with the same client, but I'm not sure this is safe. It could also be fixed in luigi if we had get_autoconfig_client return the same object each time. Is there any reason this wouldn't work?

**Comment by Tarrasch** [comment]
Thanks for the report. @daveFNbuck, do you understand what causes this? I don't understand how you got to the conclusion that making `get_autoconfig_client` returning the same objects resolves the issue.

Anyhow I'm pretty sure `get_autoconfig_client` returns different objects each time out of pure convenience of the implementers and that the object is so cheap and there's no need to cache it. Just keep thread/process-safety in mind when refactoring. :)

**Comment by daveFNbuck** [comment]
The bug comes from a system limit of how many file streams can be opened. I tried to dig into the snakebite code to figure out exactly where it happens. I think it's in the thrift communication. The problem is that each client opens a new communication pipe, so having too many open at once hits the limit. If every HdfsTarget has the same client, they don't open multiple pipes. The following code does not trigger the bug:
```
from luigi.contrib.hdfs import HdfsTarget, get_autoconfig_client

fs = get_autoconfig_client()
many_targets = [HdfsTarget('/', fs=fs) for _ in range(2000)]
all(target.exists() for target in many_targets)
```
The bug also does not get triggered if there's a chance to garbage collect between exist calls, which usually happens during normal luigi operation. It's only when you hold more HdfsTargets than your system limit on open files in memory at the same time and operate on them all that there's a problem.

**Comment by Tarrasch** [comment]
I see clearly now. Thanks for investigating this. Naturally, I would happily review and accept a PR fixing this :)

**Comment by daveFNbuck** [comment]
Just wanted to check if there was a good reason not to cache the autoconfig client, maybe threading/multiprocessing issues?

**Comment by Tarrasch** [comment]
I see, I unfortunately don't know.

**Comment by daveFNbuck** [comment]
I just ran some tests. It seems to be ok to persist the same client object across processes but not threads. Maybe we can make it safe by checking against threading.current_thread() to make sure we create a new one for each thread?

**Comment by Tarrasch** [comment]
I suppose the reason it works across processes is because you don't share the variables or anything like that in Python, hence it actually creates multiple objects. I might be wrong though. ^^

Yea I think your solution sounds sane.
