### ISSUE TITLE
S3 Feature Addition - will break current usage of list and listdir

### ISSUE THREAD

**Issue by dlstadther** [spotify/luigi#1741]
### This feature addition will break current use of `S3Client.list()` and `S3Client.listdir()`.

My question is... **_Since this is a niche-case feature that will break people's existing code who use one of these functions, would it still be valuable to submit a PR for this feature addition?_**

Due to a specific use-case where I need to know the total number and size of files copied between s3 buckets, I have modified `S3Client.listdir()` and `S3Client.list()` such that they return a generator consisting of `(path/fn, s3_item)`. The inclusion of this modification allows one to get [metadata about each file](http://boto.cloudhackers.com/en/latest/ref/s3.html#module-boto.s3.key) listed.

Current use of `list` or `listdir` looks like the following:

```python
from luigi import s3
s3_client = s3.S3Client()
for item in s3_client.list('s3://path/to/dir'):
    print(item)  #prints filename
for item in s3_client.listdir('s3://path/to/dir'):
    print(item)  #prints filename with path
```

If a PR for this feature is submitted and approved, usage would be the following:

```python
from luigi import s3
s3_client = s3.S3Client()
for path, item in s3_client.list('s3://path/to/dir'):
    print(path)  #prints filename
    print(item.last_modified)
    print(item.size)
for path, item in s3_client.listdir('s3://path/to/dir'):
    print(path)  #prints filename with path
    print(item.last_modified)
    print(item.size)
```

**Comment by dlstadther** [comment]
Code can be found [here](https://github.com/dlstadther/luigi/tree/s3_copy_size).

Changed files:  
* luigi/s3.py
* test/s3_test.py

**Comment by Tarrasch** [comment]
Why not extend the function (like pass a kwarg saying you also want `item) or create a new function?

**Comment by dlstadther** [comment]
Good idea. Thanks @Tarrasch
