### ISSUE TITLE
Add mention of conda-forge build to readme

### ISSUE THREAD

**Issue by pmlandwehr** [spotify/luigi#1746]
The `conda` scientific python distribution is currently pretty big in the research community. While the version of luigi packaged in the [official distribution](https://anaconda.org/anaconda/luigi) is quite out of date, the community-supported build on the [conda-forge channel](https://anaconda.org/conda-forge/luigi) is both current and actively maintained. As such, would y'all consider adding a mention to the README that, if folks are using `conda`, they can also install with `conda install -c conda-forge luigi`?

**Comment by sbourke** [comment]
Did minor PR - https://github.com/spotify/luigi/pull/1747 . thoughts ?

**Comment by pmlandwehr** [comment]
Looks pretty good; I'd mention that they are installing it from the [conda-forge](https://conda-forge.github.io/) channel, since it isn't a default. (Though blessed by Continuum as a positive thing, it would still be good to avoid that confusion.

**Comment by dlstadther** [comment]
@pmlandwehr Anyone can submit a PR 😃 Feel free to update the docs accordingly yourself

**Comment by erikbern** [comment]
maybe put it in the docs instead of readme – should keep readme concise

**Comment by veyu** [comment]
@erikbern Do you still want this in docs? Maybe moving "Getting Started" to side menu as new category (moving into new file)?
I could start paying back to community with solving this dreadful issue after 2 years :)
