### ISSUE TITLE
How to programmatically restart a specific task after failure?

### ISSUE THREAD

**Issue by saillsha** [spotify/luigi#1748]
I have a callback that listens for a failure event on a specific task. It attempts to fix the problem, but I cannot figure out how to automatically restart the failed task from the callback. Is there a way to do this?

**Comment by Tarrasch** [comment]
In luigi land, only workers ask for work. Typically, you have workers being launched at least hourly and then everything not finished will be run and that satisfies most business requirements. Furthermore there might already be workers that have registered that task and they will run the tasker even sooner if the central scheduler permits (check the configuration section for retrying). Having some delay is in general a good practice as theirs not point in constantly restart something that fails and waste resources (remember, luigi was originally made for Big Data).

If you for whatever reason really want to restart the task immediately, configure your scheduler appropriately and make your callback start a new worker (either grammatically with `interface.py` or start a new `luigi` cli process).

**Comment by saillsha** [comment]
Thanks for the details response @Tarrasch. I understand the best practice is to rerun the pipeline periodically, but given the constrains of the environment, we can only run once daily. I tried using `Interface.run([task])` to restart the failed task, but I get an error saying `Pid(s) 21389 already running`. It seems what I need to do is add the failed task back to the queue of pending tasks. Is there a way to accomplish this?

**Comment by Tarrasch** [comment]
`Interface.build()` bypasses the lockfile-check, but it's still not what you want.

Actually you don't need to put the failed task back in a queue. The task is already registered with the worker. You should just play around with configuration for `--worker-keep-alive` the schedulers options regarding delays for rerunning of failed tasks.

**Comment by peder** [comment]
I understand that, philosophically, Luigi is designed for idempotent jobs, thus there wasn't much effort given to restarting specific tasks. In nightly ETL environment, jobs might be long-running, and the entire ETL proces can take hours to execute. What if a task in the middle of the batch fails? Is there some backdoor method to "Restart At Step [n]"?

> In luigi land, only workers ask for work. Typically, you have workers being launched at least hourly and then everything not finished will be run. That solution satisfies most business requirements. Furthermore there might already be workers that have registered that task and they will run the tasker even sooner if the central scheduler permits

I'm not sure I follow... given a complex batch process with many dependencies, how would you recommend building an hourly schedule?

**Comment by Tarrasch** [comment]
Typically your dependency graph has many roots (typically `CreateFinalFileForReporting(date=xxx)`, `UploadUsersToDb(date=xxx)`). I recommend having something like.

```
13 * * * * luigi --module my_reporting_module CreateFinalFileForReporting
44 * * * * luigi --module my_db_ingestion_module UploadUsersToDb
```

Where 13 and 44 are "random" minutes for load balancing. Please play around with luigi a bit more to strengthen your understanding. :)

**Comment by mfcabrera** [comment]
closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [x] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [x] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
