### ISSUE TITLE
TypeError: can't pickle function objects with v2.2.0 PySparkTask

### ISSUE THREAD

**Issue by alextmeyer** [spotify/luigi#1765]
EDIT: (Similar issue to: https://github.com/spotify/luigi/issues/1714 but simplified and directly related to PySparkTask on 2.2.0)

Running simple module as a test (after running into this issue with a separate PySparkTask on a recently spun up EMR cluster with the newest version of Luigi installed - 2.2.0). Only running into this issue on Luigi==2.2.0, tested and works fine every version up until 2.2.0: 

Simple module:
```
import luigi
from luigi.contrib.spark import PySparkTask

class MyTask(PySparkTask):
    x = luigi.IntParameter()
    y = luigi.IntParameter(default=45)

    def main(self, sc, *args):
        sc.parallelize([self.x, self.y])
```

Continually running into the following error and the task fails out: 
```
ERROR: [pid 25382] Worker Worker(salt=572741934, workers=1, host=ip-<<>>, username=hadoop, pid=25382) failed    MyTask(x=123, y=456)
Traceback (most recent call last):
  File "/home/hadoop/venv/local/lib/python2.7/site-packages/luigi/worker.py", line 177, in run
    new_deps = self._run_get_new_deps()
  File "/home/hadoop/venv/local/lib/python2.7/site-packages/luigi/worker.py", line 115, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/hadoop/venv/local/lib/python2.7/site-packages/luigi/contrib/spark.py", line 281, in run
    self._dump(fd)
  File "/home/hadoop/venv/local/lib/python2.7/site-packages/luigi/contrib/spark.py", line 294, in _dump
    pickle.dump(self, fd)
  File "/home/hadoop/venv/lib64/python2.7/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
TypeError: can't pickle function objects
```

(Not sure if there were any significant changes in PysparkTask or potentially change in pickle version being used under the hood)

**Steps to reproduce (on EMR cluster):**
```
virtualenv -p /usr/bin/python2.7 venv
source venv/bin/activate
pip install --upgrade pip
pip install luigi # (this works when specify any version 2.0.1 to 2.1.0)
# TO FIX: pip install --upgrade 'luigi==2.1.1'
luigi --module my_module MyTask --x 123 --y 456 --local-scheduler
```

**Comment by Tarrasch** [comment]
Thanks for reporting this. I won't be able to look into this, but I guess the keyword to debug this is `can't pickle function objects`, somehow a function object became a member of the PySparkTask.

**Comment by davidljung** [comment]
SparkSubmitTask was recently rebased to inherit from ExternalProgramTask instead of luigi.Task - possibly related. https://github.com/spotify/luigi/commit/a0417c64fd5da4faa3ad6c2eb7cada47a6711acd

**Comment by bruteforcex** [comment]
Has there been any update on this?   We are experiencing the exact issue reported above (using version 2.3.0).  We have recently forced our environments to use an older luigi version (2.1.1) to work around this problem.  Or, is there a different/preferred workaround we can use for the time being?

FWIW, here's our traceback:

```Traceback (most recent call last):
  File "/home/data-processing-24edc0272/venv-samba_data_processing/local/lib/python2.7/site-packages/luigi/worker.py", line 181, in run
    new_deps = self._run_get_new_deps()
  File "/home/data-processing-24edc0272/venv-samba_data_processing/local/lib/python2.7/site-packages/luigi/worker.py", line 119, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/data-processing-24edc0272/venv-samba_data_processing/local/lib/python2.7/site-packages/luigi/contrib/spark.py", line 281, in run
    self._dump(fd)
  File "/home/data-processing-24edc0272/venv-samba_data_processing/local/lib/python2.7/site-packages/luigi/contrib/spark.py", line 294, in _dump
    pickle.dump(self, fd)
  File "/home/data-processing-24edc0272/venv-samba_data_processing/lib64/python2.7/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
TypeError: can't pickle function objects```

**Comment by peterg-eb** [comment]
Since the inability to pickle function objects is a well-known limitation of `pickle`/`cPickle`, how would the community feel about just requiring the [`dill` module ](https://pypi.python.org/pypi/dill) as a dependency of `PySparkTask`? A simple `import dill as pickle` in both `pyspark_runner.py` and `spark.py` would very likely resolve this issue.

**Comment by ivannotes** [comment]
I have encountered the same issue with luigi 2.3.0 too. I did some investigation, it seems `set_status_message` in task can not be pickled, It's might be because of code [here](https://github.com/spotify/luigi/blob/master/luigi/worker.py) and [here](https://github.com/spotify/luigi/blob/master/luigi/worker.py#L800). I will see if I can come up with a PR to resolve it.

**Comment by Tarrasch** [comment]
@peterg-eb, I would not like to introduce that module. Can you guys try to find a way to undo whatever changes that introduced this issue?

**Comment by peterg-eb** [comment]
I believe https://github.com/spotify/luigi/pull/1819 closes this issue, and the tests written by @ivannotes seem to bear that out.

**Comment by Tarrasch** [comment]
Thanks for the reminder @peterg-eb. I'm closing this now. :)

Conclusion is to upgrade to 2.3.1 if you experience this issue.
