### ISSUE TITLE
unhashable type dict

### ISSUE THREAD

**Issue by hevy-CC4477** [spotify/luigi#1780]
Hi,

I get this message: Not all parameter values are hashable so instance isn't coming from the cache coming from here: 
https://github.com/spotify/luigi/blob/master/luigi/task_register.py#L98.
Taking a look I found this error message: "unhashable type dict".

Why the type dict is unhashable ? and How can we fix that ?

Thanks,

**Comment by Tarrasch** [comment]
Should be fixed in the few latest version of luigi, given that you use the `DictParameter` that will freeze whatever dictionary-input it's given.

**Comment by nugend** [comment]
If you're not on the very latest version, you could see an issue with this when passing DictParameters on the command line.

**Comment by adghazali** [comment]
@Tarrasch  the reason for this is that dictionary can contain mutable data structures, correct? So DictParameter now will take the object-value rather than the object-reference? Just curious

**Comment by Tarrasch** [comment]
@adghazali, actually it's the dictionary itself that previously was mutable `dict()`. We now always convert it to some fort of a frozen dict. Your theory was very sound though, however luigi's DictParameter is in fact only a String--->String container. The strings themselves are already immutable.

**Comment by hevy-CC4477** [comment]
Thanks for the answer. Does the luigi behavior change with this version ? I got an error `TypeError: 'NoneType' object is not iterable`.

**Comment by adghazali** [comment]
Er that is because you are trying to pass a None value instead of a string for the DictParameter. I don't know your use case but you should have a default value (e.g '') so that you aren't passing NoneType objects.

**Comment by hevy-CC4477** [comment]
Thanks. I am trying to unfroze my dict, because I use boto3 and I need a dict not a Frozendict. I tried `dict(self.command.get_wrapped())` but I just get a part of the dict.

**Comment by Tarrasch** [comment]
@hevy-CC4477, you can use whatever you want, but for the *parameters* they have to be immutable data structures. Furthermore one shouldn't change the variables of parameters either, although luigi doesn't enforce this.

This is no longer about the original issue, so I'm closing it.
