### ISSUE TITLE
Add dry run flag

### ISSUE THREAD

**Issue by lebolo** [spotify/luigi#1806]
Is there a way to run luigi in "dry run" mode - to find out what tasks would get run but not actually run them? I found [this post](https://groups.google.com/d/msg/luigi-user/lAH_htE_3CU/Bb4vKuK-BwAJ) that suggests using `--workers 0` but that schedules the jobs before quitting. Ideally, it would be nice not to actually touch anything for information purposes (`luigi-deps` does a good job of listing dependencies but not what the task status would be).

**Comment by Tarrasch** [comment]
@lebolo, perhaps `--workers 0 --local-scheduler`? Unlike `--workers 0` solution it'll not touch your central scheduler and unlike `luigi-deps` it will actually carry out the necessary side effects to see what things are done yet and not.

**Comment by lebolo** [comment]
Yeah that's perfect! Would it be useful to add a `--dryrun` flag that wraps around this for others?

**Comment by Tarrasch** [comment]
That's a sensible idea. But it's hard to justify which behaviour is a dry run. In particular the  `--dryrun` you just suggested would still run the side-effects of the `complete()` methods.

I would prefer if we could have some documentation covering this. @lebolo, would you mind writing a short summary of the pros and cons of different "dryrun" methods? `luigi-deps`, `luigi-deps-tree` and `--workers 0 --local-scheduler`. Perhaps the chapter could be called something like "Various methods of dry running your pipeline".
