### ISSUE TITLE
Terminal Width affects Lock identification under Centos 6.5

### ISSUE THREAD

**Issue by nugend** [spotify/luigi#1808]
The luigi.lock.getpcmd function will return a shorter command line if the terminal is smaller in width. This can result in locks being misidentified as identical and can be a significant problem if your binary/scripts are located in deep paths.

Presumably there is some option that can be passed to ps to resolve this.

edit: It looks like if the ps command is changed to `ps x -wwo pid,args` that should take care of it.

**Comment by Tarrasch** [comment]
What is the "width" of a terminal? Are talking about the gui window in a users desktop environment???

**Comment by Tarrasch** [comment]
Ah, `ps` command tries to print human-readable output, so it's behaving differently based window size. Hence so does luigi. :)

**Comment by erikbern** [comment]
can you fix?

**Comment by nugend** [comment]
@erikbern This should probably be reopened since @keitap highlighted some issues with Busybox and my proposed fix.

If there's consensus on the right solution, I can implement and make a pull request.

Also, is there a right way to test cross platform compatibility of this? Maybe something that can be configured through Travis?
