### ISSUE TITLE
Checking downstream "dependencies".

### ISSUE THREAD

**Issue by johnclinaa** [spotify/luigi#183]
I have played around with the Luigi framework and see that it is great at checking "upstream" dependencies:  If I run job A, Luigi will check to make sure all other jobs that *A depends on* is current.  The visualization tool also display this dependency graph.

Is there a method or visualization command where I can check for downstream dependencies?  That is, for task A, what are the other tasks downstream that *depends on task A*.  This is useful in determing the effect and impact of a task on other tasks.

**Comment by Tarrasch** [comment]
Same as #286 (also closed)
