### ISSUE TITLE
Dataproc image-version param not supported

### ISSUE THREAD

**Issue by piotrpolatowski** [spotify/luigi#1831]
25 of August google upgraded default version of dataproc image to 1.1
https://cloud.google.com/dataproc/docs/concepts/dataproc-versions

The image is based on Spark 2.0. It would be great to have a choice of image version to support "legacy" Spark code.

Why it is not supported?

**Comment by erikbern** [comment]
> Why it is not supported?

because no one implemented it

**Comment by erikbern** [comment]
please send a pull request if you want support for it
