### ISSUE TITLE
Add a chat on Gitter icon?

### ISSUE THREAD

**Issue by impguard** [spotify/luigi#1875]
Hey, created a Gitter room for Luigi. Would it be feasible to toss a "Chat on Gitter" badge on the README? 

Something like this?

[![Chat on Gitter](https://img.shields.io/gitter/room/nwjs/nw.js.svg?maxAge=2592000)](https://gitter.im/spotify-luigi/Lobby)

**Comment by dlstadther** [comment]
It appears that the existing slack room is winning in popularity (https://groups.google.com/forum/#!topic/luigi-user/AfGtUS-WE8E). But if you'd like to push for the addition of Gitter as well, and wish for this to be added to the README.md, submit a PR for it and see what @Tarrasch says.

**Comment by Tarrasch** [comment]
Thanks for the summary @dlstadther. My two cents: think we shouldn't add this. If anything it should be a link to the [existing slack room](https://spotify-foss.slack.com/messages/luigi/). I personally don't use any of them though.

**Comment by impguard** [comment]
The issue with the slack room, however, is that it requires permission to access. In contrast, you simply need a github account to jump into the Gitter.

That burden is a huge inertia force for getting people to jump in and ask a question, not only in terms of figuring out where to ask to get that permission and also waiting on someone to give you permission.

We can add a link to the existing slack room. What is the process by which someone gets access to enter it, though?

**Comment by Tarrasch** [comment]
I like gitter over slack as well for exactly those reasons. However given that nobody is actively developing on luigi these days I think it's best to just have no channel.

btw., have you thought about starting with StackOverflow?

**Comment by mfcabrera** [comment]
@Tarrasch I think the fact that there's not active development on Luigi right now makes it a good idea to have channel? I mean maybe that way we can jumpstart a community with people that have system running on Luigi. Just my two cents.

**Comment by impguard** [comment]
I agree with Mfcabrera.

@Tarrasch That's a good point. I haven't thought about StackOverflow. I've found, though, as chatting tools becoming more prominent that they seem more useful due to the asynchronous yet synchronous nature (asynchronous until a conversation starts, then synchronous until its resolved). Though I do see your point.

**Comment by dlstadther** [comment]
Closing as the answer seems to be `meh`. Please reopen as becomes more active (a luigi chatroom, that is)

**Comment by dlstadther** [comment]
@bdrodes There is both a slack channel and a gitter room. Neither are active - maybe a couple posts/questions per year. The [google group](https://groups.google.com/forum/#!forum/luigi-user) or Github Issues are currently the best avenues.
