### ISSUE TITLE
Failed connecting to remote scheduler

### ISSUE THREAD

**Issue by jonathanng** [spotify/luigi#1894]
I have a setup with hundreds of workers. Sometimes up to 500 workers.

Often when the # of workers gets large, the scheduler becomes unresponsive. Visiting the scheduler UI results in a timeout. Workers fail to ping the scheduler.

I'm not exactly sure what the bottleneck is and how to improve performance? Is it a db bottleneck? Network bottleneck?

I've tried setting:
- ping_interval=60
- parallel_scheduling=True

If anyone has any ideas on how to fix or analyze the problem, please let me know. Thanks!

**Comment by jonathanng** [comment]
Looks like turning off record_task_history did the trick!

**Comment by ulzha** [comment]
We're seeing a similar problem and we're not using record_task_history; this issue might get some updates as we're looking into it.

**Comment by ulzha** [comment]
Well ours is slightly different. The scheduler is responsive anyway we look at it, UI works and CPU usage is only 15%, yet workers fail to connect to the scheduler somewhat often... Closing this and maybe opening a separate issue.
