### ISSUE TITLE
Workflow for asynchronous work, use ExternalTasks or other?

### ISSUE THREAD

**Issue by sklarsa** [spotify/luigi#1899]
I'm writing a workflow that involves using luigi to schedule asynchronous tasks.  I have one task (TaskA) that executes an async command, writes to output, and exits.  A second task (TaskB) depends on the output of TaskA, but must begin once the async command that was launched in TaskA has completed.  To resolve this, I created a third CheckerTask that checks if the asynchronous work is complete.  Since the CheckerTask doesn't run anything and only evaluates if a completion condition is met, I made it an ExternalTask.  Unfortunately, if I run `luigi TaskB` on the command line, the worker does not navigate further upstream than the CheckerTask and I get an execution summary similar to this:

```
Scheduled 2 tasks of which:
* 1 failed:
    - 1 CheckerTask(date=2016-10-25, task=TaskA)
* 1 were left pending, among these:
    * 1 had failed dependencies:
        - 1 TaskB(date=2016-10-25)
```

Based on what I see in #1449 and in `worker_external_task_test.py`, this looks like the expected behavior for external tasks that depend on other external tasks.  But is there a consensus on what to do with workflows such as the one I described above where luigi is used to orchestrate the async work?

The other option I was using was to check that the async work is complete in the body of `CheckerTask.run()` and throwing an error if the work is not completed.  While this does run as expected, it seems a little clunky, and I'm wondering if there's something in the framework that I'm missing to help implement this workflow.

Sample code:

```
class BaseTask(luigi.Task):
    date = luigi.DateParameter(default=datetime.date.today())

    def output(self):
        return luigi.LocalTarget("/tmp/luigitest/output/%s" % type(self).__name__)


class CheckerTask(BaseTask):
    task = luigi.TaskParameter()

    run = None

    def requires(self):
        return self.task(date=self.date)

    def complete(self):
        if not self.input().exists:
            return False

        if not os.path.exists(ASYNC_WORK_DONE_FLAG):
            return False

        return True


class TaskA(BaseTask):
    def run(self):
        # Kick off async work here

        with self.output().open('w') as outfile:
            outfile.write('done')


class TaskB(BaseTask):

    def run(self):
        "Running TaskB..."

        with self.output().open('w') as outfile:
            outfile.write('done')

    def requires(self):
        yield CheckerTask(task=TaskA, date=self.date)
```

**Comment by Tarrasch** [comment]
@sklarsa, please consider adding a comment why you're closing this. So others can solve the issue if they have the same issue.

**Comment by sklarsa** [comment]
Sure.  Firstly github issues may be the wrong forum for this, since it is a fairly open-ended question.  In the end, I just kept my solution of throwing errors in the `CheckerTask`s to stop the chain of execution until the downstream task was completed.
