### ISSUE TITLE
Luigi doesn't output FAILURE processing time, end time and start time

### ISSUE THREAD

**Issue by shaynewang** [spotify/luigi#1924]
When a task is failed the processing time is not recorded. As a result, the processing_time of a process left as initialized value.
```
{'job_id':'1479211214', 'datetime':'2016-11-15 04:12:44', 'task_id':'AdobeLoad_2016_11_14_page_summary_5281aeca7d', 'task_name':'AdobeLoad', 'task_date':'2016-11-14','task_report_name':'page_summary', 'start_time':'1479211963.7', 'end_time':'1479211964.12', 'process_time':'None', 'status':'FAILURE'}
{'job_id':'1479229552', 'datetime':'2016-11-15 09:07:09', 'task_id':'AdobeLoad_2016_11_14_page_summary_5281aeca7d', 'task_name':'AdobeLoad', 'task_date':'2016-11-14','task_report_name':'page_summary', 'start_time':'1479229554.92', 'end_time':'1479229629.66', 'process_time':'74.7349998951', 'status':'SUCCESS'}
```
Processing time for Failure events shouldn't be None or 0, therefore processing_time for FAILURE event should be calculated before exits.

Luigi let failed tasks have no processing time information. As a result, it could be hard to track failures. I think time information should be added to failed tasks.

**Comment by Tarrasch** [comment]
What are does dicts? Did you create them yourself or is it a luigi future?

**Comment by shaynewang** [comment]
@Tarrasch is just an output not by luigi
