### ISSUE TITLE
The retcode configuration does not consider task retry

### ISSUE THREAD

**Issue by bwtakacy** [spotify/luigi#1932]
Hi.

 I use the retcode configurations as below in luigi.cfg,
```
[retcode]
already_running=10
missing_data=20
not_run=25
task_failed=30
scheduling_error=35
unhandled_exception=40
```

When an one task was once failed and then succeeded in next retry in scheduling during a whole tasks execution, I expected the return code to be zero but actually was non zero.

For example,  running `examples/foo.py`  with some code change that `Bar(num=7)`  fails at the first time run but succeeds in the second time run,  all the tasks succeeded in the end but the return code is non zero.

```
===== Luigi Execution Summary =====

Scheduled 12 tasks of which:
* 11 ran successfully:
    - 10 examples.Bar(num=0...9)
    - 1 examples.Foo()
* 1 failed:
    - 1 examples.Bar(num=7)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

The program exited via sys.exit(). Exit status: 30
```

It seems that the result of `Bar(num=7)` was doubly counted both in success group and failed group.

**Comment by Tarrasch** [comment]
Definitely a bug I would say. Failures are normal and if we even know it got resolved we should not alarm anyone. Do you want to take a stab fixing this? :)

**Comment by bwtakacy** [comment]
Thanks for your comments!
I will try to create PR.
