### ISSUE TITLE
Checking if task is complete takes a very long time

### ISSUE THREAD

**Issue by chisaipete** [spotify/luigi#1958]
I'm sure it has something to do with my usage, but dependency checking while kicking off my luigi job is taking forever (minutes, up to an hour even!).

Basic task dependency tree looks like this:

    [ Wrapper Task ]
    |
    `--[ Task A ] (can have multiple instances of this)
        |
        `--[ Task 1 ]
            |
            `--[ Task i ]
                |
                `--[ Task a ] (this "spawns" a bunch of tasks [read: 10000], looks like a massive scatter)
                    |
                    |--[ Task a1.0 ] (there are tons of these, which have a sibling)
                    `--[ Task a1.1 ] (this is the sibling, both of these sibling tasks are dependent on the same sub-task:)
                        |
                        `--[Task a1 child]
                            |
                            `--[ Task ! ] (Every single task spawned by Task a is dependent on this task, looks like a massive gather in a graph)
                                |
                                `-- [ Task 0 ] (this is the very first task which should do real work, basically creating the area to gather data to)

Is this so slow because it's checking the dependencies down through the entire chain at each level of tasks?  Is there a way to short-circuit dependency checking or is there a better method to organizing these tasks that I'm not seeing?

**Comment by erikbern** [comment]
If you use dynamic dependencies then it could be pretty slow because it will re-run the task many times. Is that the case?

**Comment by chisaipete** [comment]
What do you mean by dynamic dependencies?  The number of tasks created by "Task a" is a known size, but it will always be very large and that list may change from run to run.

**Comment by chisaipete** [comment]
@erikbern it's not re-running a task multiple times that I can see, at least in the visualizer the count comes out to what I would expect.

**Comment by chisaipete** [comment]
I just realized support topics are really supposed to be posted in the Google Group.  I can close this if it's not appropriate here.  xposted to google group.

**Comment by Tarrasch** [comment]
I close here, lets continue in google groups. :)
