### ISSUE TITLE
Allow schema to be specified for target table in sqla.CopyToTable

### ISSUE THREAD

**Issue by sd2k** [spotify/luigi#1984]
This could be supported by passing overriding the `schema` attribute of the task, and passing this to the `sqlalchemy.MetaData` constructor in `sqla.CopyToTable.create_table`.

A consideration: should we also allow a schema to be specified for the marker table? My current use case requires them to be different.

If this sounds OK I'll write it up later and create a PR for review.

**Comment by dlstadther** [comment]
@sd2k Any update here?

**Comment by sd2k** [comment]
@dlstadther I've been using a subclass of `CopyToTable` which overrides `create_table`. I'll send a PR.
