### ISSUE TITLE
DictParameter cannot be loaded from a configfile

### ISSUE THREAD

**Issue by hnykda** [spotify/luigi#1989]
Since configparser doesn't support having dictionary as a parameter, a [DictParameter](http://luigi.readthedocs.io/en/stable/api/luigi.parameter.html#luigi.parameter.DictParameter) cannot be set in a file like e.g. something like this:
```
mydictparam = {'a':3, 'b':2, 'c':1, ...}
```

is there some workaround?

**Comment by Tarrasch** [comment]
It works in the same way all other parameters I think (it uses the `parse()` method). Have you looked if there's any test cases similar to this?

**Comment by hnykda** [comment]
I am sorry, my bad - I must *not* to be multiline.
