### ISSUE TITLE
Structuring the project - problem with changing PYTHONPATH to find tasks

### ISSUE THREAD

**Issue by hnykda** [spotify/luigi#1996]
Hi,

I would like to use `luigi` for my project, but I can't manage to structure in a different way then having all tasks and other libraries I want to import in them in a root directory.

What I would ideally have is something like:
```
__init__.py
tasks  # my tasks, quite a lot of them, and there is even baseTask.py I would like to subclass in each class, so would like to do `from tasks.baseTask import baseTask` in each of my tasks
lib  # code which is shared by various tasks from tasks, so e.g. in task/taskA.py there would be something like "from lib import utils"
luigi.cfg
project_configs  # configs with different parameters for different projects I wanna process through pipeline
```

but with this layout, there seems not to be a way how to run it. 

This will fail when trying to import something from `lib` inside a task or even importing `baseTask` (and I cannot perform relative import).
```
LUIGI_CONFIG_PATH=projectA.cfg PYTHONPATH='tasks/' luigi --module taskA someTask  --local-scheduler
```

This doesn't find task at all of course.
```
LUIGI_CONFIG_PATH=projectA.cfg luigi --module taskA someTask  --local-scheduler
```

The only workaround is to add `import sys; sys.path.append('.')` to each task, which is really ugly! The other solution is to have one giant folder with all tasks and place lib inside it, which is again an unclean design.

**Comment by Tarrasch** [comment]
I really would like to have a convention. Perhaps exactly the one you suggest! However, right now there's no recommended best practice for your luigi code that I know of.

----

By the way, did you consider running something like:

    LUIGI_CONFIG_PATH=projectA.cfg PYTHONPATH='.' luigi --module tasks.taskA someTask  --local-scheduler

It could get you closer to something that works with at least a little bit ugliness.

**Comment by hnykda** [comment]
Oh my god! That is exactly I needed. Why this hadn't occurred me before... Thanks a lot, I think this is sufficient solution. 

And personally, I wouldn't be against having a new (optional) env variable such as `LUIGI_TASKS_DIR` or something like that which would be automatically appended to `sys.path` when luigi starts. Having an option to specify this in `luigi.cfg` would be nice as well.

**Comment by Tarrasch** [comment]
I have a different and more bold vision, basically I want to make:

    PYTHONPATH='.' luigi --module tasks.taskA someTask  --local-scheduler

into

    PYTHONPATH='.' luigi tasks.taskA.someTask  --local-scheduler

In other words, I want to implement so that luigi autoloads that task by first trying to import the `tasks.taskA` module, and by convention luigi users will have the same "task namespace" as python module name. Feel free to give feedback on this idea.
