### ISSUE TITLE
luigi.s3.S3Client.listdir docstring talks of copying

### ISSUE THREAD

**Issue by sanxiyn** [spotify/luigi#2001]
listdir doesn't copy files, so docstring is wrong.

```
:param start_time: Optional argument to copy files with modified dates after start_time
:param end_time: Optional argument to copy files with modified dates before end_time
```

**Comment by dlstadther** [comment]
I believe that is my fault. I added that functionality to s3copy and must have forgotten to update the docstrings after copy/pasting them.

I'll take a pass through s3 docstrings and update them either today or tomorrow. Thanks

**Comment by Tarrasch** [comment]
Closing this as #2003 fixed this.
