### ISSUE TITLE
Python 2.6 compatibility

### ISSUE THREAD

**Issue by sbliven** [spotify/luigi#2010]
I'm forced to use python 2.6 on one of our servers. With some minor syntax adjustments I've been running luigi 2.5.0 without problems on this server. I have a python26 branch on my fork: https://github.com/sbliven/luigi/tree/python26

Would there be any interest in broadening backwards luigi compatibility to these older systems?

**Comment by erikbern** [comment]
luigi doesn't support python 2.6 any more unfortunately

**Comment by Tarrasch** [comment]
Yea, support was actually actively removed at some point in time (over a year ago I think). I'm closing this, but this issue will still show up in search results for people looking for it.

**Comment by sbliven** [comment]
That's what I thought. I mostly just wanted to document that I'm working on support for those who absolutely need it.
