### ISSUE TITLE
run method is start over again.

### ISSUE THREAD

**Issue by mtoriumi** [spotify/luigi#2014]
python:3.6
luigi:2.5.0

run method is start over from the beginning when returning a generator object.
because Losing the generator object of the first task.

Is this the intended behavior?

**Comment by erikbern** [comment]
if you use dynamic requirements, yes

**Comment by mtoriumi** [comment]
Thank you for your reply.

**Comment by erikbern** [comment]
we should probably make this a bit more clear in the documentation.

there's also some possible heuristic optimizations we could make to "resume" the run method and avoid this in most cases
