### ISSUE TITLE
Visualizer Task History Web Page Clipped on Left for Info

### ISSUE THREAD

**Issue by steveb-cirina** [spotify/luigi#2019]
Hi

I am having an issue with the `/history` part of the Luigi Visualizer GUI; more specifically, when viewing the task id.  The **Info** part is clipped on the left as in the picture below when going to the following local URL:

`hxxp://localhost:8082/history/by_id/1`  (here just for illustration of relative path)

You can see that the **Info** part is clipped and the rest just has little or no margin.

![screen shot 2017-02-08 at 4 29 02 pm](https://cloud.githubusercontent.com/assets/22382505/22764017/e2f6450c-ee1c-11e6-87b3-523e9aa7ca86.png)

When I change `<div class="row">`, by removing the class, then the clipping goes away.

I am using python 2.7 and luigi 2.3.  This has the same issue on Chrome and Safari on Mac OS X (El Cap).

Thanks.
-Steve

**Comment by amarco90** [comment]
[This PR](https://github.com/spotify/luigi/pull/2061) should fix the issue.

**Comment by steveb-cirina** [comment]
Thanks.
