### ISSUE TITLE
Luigi Visulizer Pruning : Turning off

### ISSUE THREAD

**Issue by steveb-cirina** [spotify/luigi#2022]
Hi

I am interested in being able to turn off pruning or change the timing to be settable in the config file.  I noticed the following code in `server.py`

    ...
    # prune work DAG every 60 seconds
    pruner = tornado.ioloop.PeriodicCallback(scheduler.prune, 60000)
    pruner.start()
    ....

I think this is where this is getting set and I am looking to see if this is the only place.

I would be happy to work on making this a configurable option but it would be good to get some guidance as I haven't looked at this code much and have not yet done a PR from GitHub.

Thanks.

**Comment by steveb-cirina** [comment]
I also see the `scheduler.py` does some pruning.

**Comment by Tarrasch** [comment]
Why do you want to do this? Luigi prunes the graph on every page load even if I'm not mistaken even.

-----

If you want to make tasks live longer, then that is already configurable. :)

**Comment by steveb-cirina** [comment]
I would like to have the dependency graph around longer.  How do I do this ?  Is this what you are referring to being configurable ?

**Comment by chrispalmer** [comment]
@steveb-cirina See `remove-delay` in the scheduler configuration section - https://luigi.readthedocs.io/en/stable/configuration.html#scheduler-config

The `prune` method gets called on a regular basis but it only removes tasks if they haven't had any stakeholders for `remove-delay` seconds.

**Comment by steveb-cirina** [comment]
@chrispalmer Thanks, I will check that out.

**Comment by Tarrasch** [comment]
Closing this. I don't think there's any follow-up on this at the moment.
