### ISSUE TITLE
Failed to build luigi

### ISSUE THREAD

**Issue by tresellefreshers2016** [spotify/luigi#2027]
I am  getting the same error while pip install luigi
Can you please help me?   
 

----------
 copying luigi\static\visualiser\js\tipsy.js -> build\lib\luigi\static\visualiser\js
 copying luigi\static\visualiser\js\visualiserApp.js -> build\lib\luigi\static\visualiser\js
 creating build\lib\luigi\static\visualiser\js\test
 copying luigi\static\visualiser\js\test\graph_test.js -> build\lib\luigi\static\visualiser\js\test
 creating build\lib\luigi\static\visualiser\lib
 copying luigi\static\visualiser\lib\jquery-1.10.0.min.js -> build\lib\luigi\static\visualiser\lib
 copying luigi\static\visualiser\lib\jquery.slimscroll.min.js -> build\lib\luigi\static\visualiser\lib
 copying luigi\static\visualiser\lib\mustache.js -> build\lib\luigi\static\visualiser\lib
 error: can't copy 'luigi\static\visualiser\lib\URI.js': doesn't exist or not a regular file

  ----------------------------------------
  Failed building wheel for luigi
  Running setup.py clean for luigi
Failed to build luigi
Installing collected packages: luigi
  Running setup.py install for luigi ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\treselle\\appdata\\local\\temp\\pip-build-ql05v6\\luigi\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'e
xec'))" install --record c:\users\treselle\appdata\local\temp\pip-ad2et1-record\install-record.txt --single-version-externally-managed --compile:

**Comment by Tarrasch** [comment]
Please fix formatting of this issue, and then feel free to reopen it.
