### ISSUE TITLE
Failed building wheel for luigi

### ISSUE THREAD

**Issue by GunasekaranR** [spotify/luigi#2028]
Running setup.py bdist_wheel for luigi ... error
  Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\treselle\\appdata\\local\\temp\\pip-buil
d-ql05v6\\luigi\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exe
c'))" bdist_wheel -d c:\users\treselle\appdata\local\temp\tmpa7equkpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\luigi
  copying luigi\batch_notifier.py -> build\lib\luigi
  copying luigi\cmdline.py -> build\lib\luigi
  copying luigi\cmdline_parser.py -> build\lib\luigi
  copying luigi\configuration.py -> build\lib\luigi
  copying luigi\date_interval.py -> build\lib\luigi
  copying luigi\db_task_history.py -> build\lib\luigi
  copying luigi\event.py -> build\lib\luigi
  copying luigi\execution_summary.py -> build\lib\luigi
  copying luigi\file.py -> build\lib\luigi
  copying luigi\format.py -> build\lib\luigi
  copying luigi\interface.py -> build\lib\luigi
  copying luigi\local_target.py -> build\lib\luigi
  copying luigi\lock.py -> build\lib\luigi
  copying luigi\mock.py -> build\lib\luigi
  copying luigi\notifications.py -> build\lib\luigi
  copying luigi\parameter.py -> build\lib\luigi
  copying luigi\postgres.py -> build\lib\luigi
  copying luigi\process.py -> build\lib\luigi
  copying luigi\retcodes.py -> build\lib\luigi
  copying luigi\rpc.py -> build\lib\luigi
  copying luigi\s3.py -> build\lib\luigi
  copying luigi\scheduler.py -> build\lib\luigi
  copying luigi\server.py -> build\lib\luigi
  copying luigi\six.py -> build\lib\luigi
  copying luigi\target.py -> build\lib\luigi
  copying luigi\task.py -> build\lib\luigi
  copying luigi\task_history.py -> build\lib\luigi
  copying luigi\task_register.py -> build\lib\luigi
  copying luigi\task_status.py -> build\lib\luigi
  copying luigi\util.py -> build\lib\luigi
  copying luigi\worker.py -> build\lib\luigi
  copying luigi\__init__.py -> build\lib\luigi
  copying luigi\__main__.py -> build\lib\luigi
  creating build\lib\luigi\contrib
  copying luigi\contrib\bigquery.py -> build\lib\luigi\contrib
  copying luigi\contrib\bigquery_avro.py -> build\lib\luigi\contrib
  copying luigi\contrib\dataproc.py -> build\lib\luigi\contrib
  copying luigi\contrib\ecs.py -> build\lib\luigi\contrib
  copying luigi\contrib\esindex.py -> build\lib\luigi\contrib
  copying luigi\contrib\external_program.py -> build\lib\luigi\contrib
  copying luigi\contrib\ftp.py -> build\lib\luigi\contrib
  copying luigi\contrib\gcs.py -> build\lib\luigi\contrib
  copying luigi\contrib\hadoop.py -> build\lib\luigi\contrib
  copying luigi\contrib\hadoop_jar.py -> build\lib\luigi\contrib
  copying luigi\contrib\hive.py -> build\lib\luigi\contrib
  copying luigi\contrib\mrrunner.py -> build\lib\luigi\contrib
  copying luigi\contrib\mssqldb.py -> build\lib\luigi\contrib
  copying luigi\contrib\mysqldb.py -> build\lib\luigi\contrib
  copying luigi\contrib\opener.py -> build\lib\luigi\contrib
  copying luigi\contrib\pig.py -> build\lib\luigi\contrib
  copying luigi\contrib\postgres.py -> build\lib\luigi\contrib
  copying luigi\contrib\pyspark_runner.py -> build\lib\luigi\contrib
  copying luigi\contrib\rdbms.py -> build\lib\luigi\contrib
  copying luigi\contrib\redis_store.py -> build\lib\luigi\contrib
  copying luigi\contrib\redshift.py -> build\lib\luigi\contrib
  copying luigi\contrib\s3.py -> build\lib\luigi\contrib
  copying luigi\contrib\salesforce.py -> build\lib\luigi\contrib
  copying luigi\contrib\scalding.py -> build\lib\luigi\contrib
  copying luigi\contrib\sge.py -> build\lib\luigi\contrib
  copying luigi\contrib\sge_runner.py -> build\lib\luigi\contrib
  copying luigi\contrib\simulate.py -> build\lib\luigi\contrib
  copying luigi\contrib\spark.py -> build\lib\luigi\contrib
  copying luigi\contrib\sparkey.py -> build\lib\luigi\contrib
  copying luigi\contrib\sqla.py -> build\lib\luigi\contrib
  copying luigi\contrib\ssh.py -> build\lib\luigi\contrib
  copying luigi\contrib\target.py -> build\lib\luigi\contrib
  copying luigi\contrib\webhdfs.py -> build\lib\luigi\contrib
  copying luigi\contrib\__init__.py -> build\lib\luigi\contrib
  creating build\lib\luigi\contrib\hdfs
  copying luigi\contrib\hdfs\abstract_client.py -> build\lib\luigi\contrib\hdfs
  copying luigi\contrib\hdfs\clients.py -> build\lib\luigi\contrib\hdfs
  copying luigi\contrib\hdfs\config.py -> build\lib\luigi\contrib\hdfs
  copying luigi\contrib\hdfs\error.py -> build\lib\luigi\contrib\hdfs
  copying luigi\contrib\hdfs\format.py -> build\lib\luigi\contrib\hdfs
  copying luigi\contrib\hdfs\hadoopcli_clients.py -> build\lib\luigi\contrib\hdfs
  copying luigi\contrib\hdfs\snakebite_client.py -> build\lib\luigi\contrib\hdfs
  copying luigi\contrib\hdfs\target.py -> build\lib\luigi\contrib\hdfs
  copying luigi\contrib\hdfs\webhdfs_client.py -> build\lib\luigi\contrib\hdfs
  copying luigi\contrib\hdfs\__init__.py -> build\lib\luigi\contrib\hdfs
  creating build\lib\luigi\tools
  copying luigi\tools\deps.py -> build\lib\luigi\tools
  copying luigi\tools\deps_tree.py -> build\lib\luigi\tools
  copying luigi\tools\luigi_grep.py -> build\lib\luigi\tools
  copying luigi\tools\range.py -> build\lib\luigi\tools
  copying luigi\tools\__init__.py -> build\lib\luigi\tools
  creating build\lib\luigi\static
  creating build\lib\luigi\static\visualiser
  copying luigi\static\visualiser\index.html -> build\lib\luigi\static\visualiser
  copying luigi\static\visualiser\test.html -> build\lib\luigi\static\visualiser
  creating build\lib\luigi\static\visualiser\css
  copying luigi\static\visualiser\css\font-awesome.min.css -> build\lib\luigi\static\visualiser\css
  copying luigi\static\visualiser\css\tipsy.css -> build\lib\luigi\static\visualiser\css
  creating build\lib\luigi\static\visualiser\fonts
  copying luigi\static\visualiser\fonts\fontawesome-webfont.eot -> build\lib\luigi\static\visualiser\fonts
  copying luigi\static\visualiser\fonts\glyphicons-halflings-regular.eot -> build\lib\luigi\static\visualiser\fonts
  copying luigi\static\visualiser\fonts\fontawesome-webfont.svg -> build\lib\luigi\static\visualiser\fonts
  copying luigi\static\visualiser\fonts\glyphicons-halflings-regular.svg -> build\lib\luigi\static\visualiser\fonts
  copying luigi\static\visualiser\fonts\fontawesome-webfont.ttf -> build\lib\luigi\static\visualiser\fonts
  copying luigi\static\visualiser\fonts\glyphicons-halflings-regular.ttf -> build\lib\luigi\static\visualiser\fonts
  copying luigi\static\visualiser\fonts\fontawesome-webfont.woff -> build\lib\luigi\static\visualiser\fonts
  copying luigi\static\visualiser\fonts\glyphicons-halflings-regular.woff -> build\lib\luigi\static\visualiser\fonts
  copying luigi\static\visualiser\fonts\fontawesome-webfont.woff2 -> build\lib\luigi\static\visualiser\fonts
  creating build\lib\luigi\static\visualiser\js
  copying luigi\static\visualiser\js\graph.js -> build\lib\luigi\static\visualiser\js
  copying luigi\static\visualiser\js\luigi.js -> build\lib\luigi\static\visualiser\js
  copying luigi\static\visualiser\js\tipsy.js -> build\lib\luigi\static\visualiser\js
  copying luigi\static\visualiser\js\visualiserApp.js -> build\lib\luigi\static\visualiser\js
  creating build\lib\luigi\static\visualiser\js\test
  copying luigi\static\visualiser\js\test\graph_test.js -> build\lib\luigi\static\visualiser\js\test
  creating build\lib\luigi\static\visualiser\lib
  copying luigi\static\visualiser\lib\jquery-1.10.0.min.js -> build\lib\luigi\static\visualiser\lib
  copying luigi\static\visualiser\lib\jquery.slimscroll.min.js -> build\lib\luigi\static\visualiser\lib
  copying luigi\static\visualiser\lib\mustache.js -> build\lib\luigi\static\visualiser\lib
  error: can't copy 'luigi\static\visualiser\lib\URI.js': doesn't exist or not a regular file

  ----------------------------------------
  Failed building wheel for luigi
  Running setup.py clean for luigi
Failed to build luigi
Installing collected packages: luigi
  Running setup.py install for luigi ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\treselle\\appdata\\local\\temp\\pip-bu
ild-ql05v6\\luigi\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'e
xec'))" install --record c:\users\treselle\appdata\local\temp\pip-ad2et1-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\luigi
    copying luigi\batch_notifier.py -> build\lib\luigi
    copying luigi\cmdline.py -> build\lib\luigi
    copying luigi\cmdline_parser.py -> build\lib\luigi
    copying luigi\configuration.py -> build\lib\luigi
    copying luigi\date_interval.py -> build\lib\luigi
    copying luigi\db_task_history.py -> build\lib\luigi
    copying luigi\event.py -> build\lib\luigi
    copying luigi\execution_summary.py -> build\lib\luigi
    copying luigi\file.py -> build\lib\luigi
    copying luigi\format.py -> build\lib\luigi
    copying luigi\interface.py -> build\lib\luigi
    copying luigi\local_target.py -> build\lib\luigi
    copying luigi\lock.py -> build\lib\luigi
    copying luigi\mock.py -> build\lib\luigi
    copying luigi\notifications.py -> build\lib\luigi
    copying luigi\parameter.py -> build\lib\luigi
    copying luigi\postgres.py -> build\lib\luigi
    copying luigi\process.py -> build\lib\luigi
    copying luigi\retcodes.py -> build\lib\luigi
    copying luigi\rpc.py -> build\lib\luigi
    copying luigi\s3.py -> build\lib\luigi
    copying luigi\scheduler.py -> build\lib\luigi
    copying luigi\server.py -> build\lib\luigi
    copying luigi\six.py -> build\lib\luigi
    copying luigi\target.py -> build\lib\luigi
    copying luigi\task.py -> build\lib\luigi
    copying luigi\task_history.py -> build\lib\luigi
    copying luigi\task_register.py -> build\lib\luigi
    copying luigi\task_status.py -> build\lib\luigi
    copying luigi\util.py -> build\lib\luigi
    copying luigi\worker.py -> build\lib\luigi
    copying luigi\__init__.py -> build\lib\luigi
    copying luigi\__main__.py -> build\lib\luigi
    creating build\lib\luigi\contrib
    copying luigi\contrib\bigquery.py -> build\lib\luigi\contrib
    copying luigi\contrib\bigquery_avro.py -> build\lib\luigi\contrib
    copying luigi\contrib\dataproc.py -> build\lib\luigi\contrib
    copying luigi\contrib\ecs.py -> build\lib\luigi\contrib
    copying luigi\contrib\esindex.py -> build\lib\luigi\contrib
    copying luigi\contrib\external_program.py -> build\lib\luigi\contrib
    copying luigi\contrib\ftp.py -> build\lib\luigi\contrib
    copying luigi\contrib\gcs.py -> build\lib\luigi\contrib
    copying luigi\contrib\hadoop.py -> build\lib\luigi\contrib
    copying luigi\contrib\hadoop_jar.py -> build\lib\luigi\contrib
    copying luigi\contrib\hive.py -> build\lib\luigi\contrib
    copying luigi\contrib\mrrunner.py -> build\lib\luigi\contrib
    copying luigi\contrib\mssqldb.py -> build\lib\luigi\contrib
    copying luigi\contrib\mysqldb.py -> build\lib\luigi\contrib
    copying luigi\contrib\opener.py -> build\lib\luigi\contrib
    copying luigi\contrib\pig.py -> build\lib\luigi\contrib
    copying luigi\contrib\postgres.py -> build\lib\luigi\contrib
    copying luigi\contrib\pyspark_runner.py -> build\lib\luigi\contrib
    copying luigi\contrib\rdbms.py -> build\lib\luigi\contrib
    copying luigi\contrib\redis_store.py -> build\lib\luigi\contrib
    copying luigi\contrib\redshift.py -> build\lib\luigi\contrib
    copying luigi\contrib\s3.py -> build\lib\luigi\contrib
    copying luigi\contrib\salesforce.py -> build\lib\luigi\contrib
    copying luigi\contrib\scalding.py -> build\lib\luigi\contrib
    copying luigi\contrib\sge.py -> build\lib\luigi\contrib
    copying luigi\contrib\sge_runner.py -> build\lib\luigi\contrib
    copying luigi\contrib\simulate.py -> build\lib\luigi\contrib
    copying luigi\contrib\spark.py -> build\lib\luigi\contrib
    copying luigi\contrib\sparkey.py -> build\lib\luigi\contrib
    copying luigi\contrib\sqla.py -> build\lib\luigi\contrib
    copying luigi\contrib\ssh.py -> build\lib\luigi\contrib
    copying luigi\contrib\target.py -> build\lib\luigi\contrib
    copying luigi\contrib\webhdfs.py -> build\lib\luigi\contrib
    copying luigi\contrib\__init__.py -> build\lib\luigi\contrib
    creating build\lib\luigi\contrib\hdfs
    copying luigi\contrib\hdfs\abstract_client.py -> build\lib\luigi\contrib\hdfs
    copying luigi\contrib\hdfs\clients.py -> build\lib\luigi\contrib\hdfs
    copying luigi\contrib\hdfs\config.py -> build\lib\luigi\contrib\hdfs
    copying luigi\contrib\hdfs\error.py -> build\lib\luigi\contrib\hdfs
    copying luigi\contrib\hdfs\format.py -> build\lib\luigi\contrib\hdfs
    copying luigi\contrib\hdfs\hadoopcli_clients.py -> build\lib\luigi\contrib\hdfs
    copying luigi\contrib\hdfs\snakebite_client.py -> build\lib\luigi\contrib\hdfs
    copying luigi\contrib\hdfs\target.py -> build\lib\luigi\contrib\hdfs
    copying luigi\contrib\hdfs\webhdfs_client.py -> build\lib\luigi\contrib\hdfs
    copying luigi\contrib\hdfs\__init__.py -> build\lib\luigi\contrib\hdfs
    creating build\lib\luigi\tools
    copying luigi\tools\deps.py -> build\lib\luigi\tools
    copying luigi\tools\deps_tree.py -> build\lib\luigi\tools
    copying luigi\tools\luigi_grep.py -> build\lib\luigi\tools
    copying luigi\tools\range.py -> build\lib\luigi\tools
    copying luigi\tools\__init__.py -> build\lib\luigi\tools
    creating build\lib\luigi\static
    creating build\lib\luigi\static\visualiser
    copying luigi\static\visualiser\index.html -> build\lib\luigi\static\visualiser
    copying luigi\static\visualiser\test.html -> build\lib\luigi\static\visualiser
    creating build\lib\luigi\static\visualiser\css
    copying luigi\static\visualiser\css\font-awesome.min.css -> build\lib\luigi\static\visualiser\css
    copying luigi\static\visualiser\css\tipsy.css -> build\lib\luigi\static\visualiser\css
    creating build\lib\luigi\static\visualiser\fonts
    copying luigi\static\visualiser\fonts\fontawesome-webfont.eot -> build\lib\luigi\static\visualiser\fonts
    copying luigi\static\visualiser\fonts\glyphicons-halflings-regular.eot -> build\lib\luigi\static\visualiser\fonts
    copying luigi\static\visualiser\fonts\fontawesome-webfont.svg -> build\lib\luigi\static\visualiser\fonts
    copying luigi\static\visualiser\fonts\glyphicons-halflings-regular.svg -> build\lib\luigi\static\visualiser\fonts
    copying luigi\static\visualiser\fonts\fontawesome-webfont.ttf -> build\lib\luigi\static\visualiser\fonts
    copying luigi\static\visualiser\fonts\glyphicons-halflings-regular.ttf -> build\lib\luigi\static\visualiser\fonts
    copying luigi\static\visualiser\fonts\fontawesome-webfont.woff -> build\lib\luigi\static\visualiser\fonts
    copying luigi\static\visualiser\fonts\glyphicons-halflings-regular.woff -> build\lib\luigi\static\visualiser\fonts
    copying luigi\static\visualiser\fonts\fontawesome-webfont.woff2 -> build\lib\luigi\static\visualiser\fonts
    creating build\lib\luigi\static\visualiser\js
    copying luigi\static\visualiser\js\graph.js -> build\lib\luigi\static\visualiser\js
    copying luigi\static\visualiser\js\luigi.js -> build\lib\luigi\static\visualiser\js
    copying luigi\static\visualiser\js\tipsy.js -> build\lib\luigi\static\visualiser\js
    copying luigi\static\visualiser\js\visualiserApp.js -> build\lib\luigi\static\visualiser\js
    creating build\lib\luigi\static\visualiser\js\test
    copying luigi\static\visualiser\js\test\graph_test.js -> build\lib\luigi\static\visualiser\js\test
    creating build\lib\luigi\static\visualiser\lib
    copying luigi\static\visualiser\lib\jquery-1.10.0.min.js -> build\lib\luigi\static\visualiser\lib
    copying luigi\static\visualiser\lib\jquery.slimscroll.min.js -> build\lib\luigi\static\visualiser\lib
    copying luigi\static\visualiser\lib\mustache.js -> build\lib\luigi\static\visualiser\lib
    error: can't copy 'luigi\static\visualiser\lib\URI.js': doesn't exist or not a regular file

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\treselle\\appdata\\local\\temp\\pip-build-ql05v6\\luigi\\setup
.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record
 c:\users\treselle\appdata\local\temp\pip-ad2et1-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in
c:\users\treselle\appdata\local\temp\pip-build-ql05v6\luigi\

**Comment by Tarrasch** [comment]
Please fix formatting of this issue, and then feel free to reopen it.

**Comment by shahabedinh** [comment]
I had the same issue 

/opt/cloudera/parcels/Anaconda-4.0.0/bin/pip install luigi

....
reating build/lib/luigi/static/visualiser/lib
    copying luigi/static/visualiser/lib/mustache.js -> build/lib/luigi/static/visualiser/lib
    copying luigi/static/visualiser/lib/jquery-1.10.0.min.js -> build/lib/luigi/static/visualiser/lib
    error: can't copy 'luigi/static/visualiser/lib/URI.js': doesn't exist or not a regular file


then I download and then pip it.  

wget https://github.com/spotify/luigi/archive/master.zip
unzip master.zip
cd luigi-master/
sudo /opt/cloudera/parcels/Anaconda/bin/pip install .

and it works for me
