### ISSUE TITLE
pip install lugi does not install it properly

### ISSUE THREAD

**Issue by GunasekaranR** [spotify/luigi#2029]
error: can't copy 'luigi\static\visualiser\lib\URI.js': doesn't exist or not a regular file

----------------------------------------
Failed building wheel for luigi
Running setup.py clean for luigi
Failed to build luigi
Installing collected packages: luigi
Running setup.py install for luigi ... error

**Comment by Tarrasch** [comment]
Closing. Copy of #2028 probably.
