### ISSUE TITLE
Delay instantiating S3Client when generating S3Targets

### ISSUE THREAD

**Issue by jtratner** [spotify/luigi#2048]
I was profiling luigi code that had recursive dependencies (i.e., Task A grabs outputs from Task B which grabs outputs from Task C, etc) I noticed that there was a big performance hit when generating too many S3Targets (because boto has to hit the filesystem to check all config files and then a connection object [I believe] is generated to AWS).  This also means that you open a ton of file descriptors (so you can hit a ulimit if you fork too many times ).

I am happy to put up a PR implementing this change, but wanted to see if anybody had feedback on this before putting up a PR.

Rather than instantiating `S3Client` in the `__init__` method, I'd like to suggest changing `self.client` to a cached property that only instantiates the client at the moment we need it.

Pros:

- outputs() method is faster
- prereq for using a connection pool for communicating with S3
- caching S3Targets doesn't surprisingly leak file descriptors

Cons:

- validation errors on client kwargs only come out once you start trying to access targets, (currently you see it as soon as S3Target is instantiated)

**Comment by lsglick** [comment]
We also ran into issues on EC2 where calls to the metadata service weren't returning data, presumably because we were exceeding a reasonable rate of credential requests.
