### ISSUE TITLE
LocalTarget and temporary_path

### ISSUE THREAD

**Issue by adaitche** [spotify/luigi#2050]
FileSystemTarget has the method `temporary_path`, which returns a context manager. On exit the context manager renames the temporary path to the final path by means of the method `rename_dont_move` of the attribute fs (of type FileSystem).

When `temporary_path` is used on LocalTarget, on exit from the context manager the following warning is printed

```
lib/python3.5/site-packages/luigi/target.py:171: UserWarning: File system LocalFileSystem client doesn't support atomic mv.
  warnings.warn("File system {} client doesn't support atomic mv.".format(self.__class__.__name__))
```

This is because LocalFileSystem does not implement the `rename_dont_move` method and the default implementation is used. However LocalFileSystem has essentially implemented this functionality in the `move` method, but unfortunately it is not used by temporary_path.

Is there a particular reason for not implementing `rename_dont_move` on LocalFileSystem? If no, one could make `rename_dont_move` just a reference to the `move` method of LocalFileSystem, which already implements the desired functionality.

I am happy to submit a pull request, if the above suggestion makes sense.

**Comment by rbdixon** [comment]
If you put this pull request in I'll test it... I just hit the same issue.

**Comment by Tarrasch** [comment]
Ah, yes. The `temporary_path` path feature is new and this is a rough edge I didn't notice.  Please send a PR. :)
