### ISSUE TITLE
Advise of readme or notifications.py

### ISSUE THREAD

**Issue by 444thLiao** [spotify/luigi#2051]
Sorry for bothering you.

But there are plenty of differences between notifications.py and Readme, at [http://luigi.readthedocs.io/en/stable/configuration.html#core](url)

Especially at send email place, please formatted these two places at one standard. 
e.g when you teach us to write 'host' at [smtp] section , but your code get this info from [core] section with 'smtp_host'. So I think that is so unfriendly to users who use your module or tools.

That is my advise.

Here is your code at notifications.py
[https://github.com/spotify/luigi/blob/97232cb3094c41806e3f090afe352fd7cc5af076/luigi/notifications.py](url)

Here is your ReadMe or configuration.rst

> [smtp]

These parameters control the smtp server setup.

host
Hostname for sending mail throug smtp. Defaults to localhost.
local_hostname
If specified, overrides the FQDN of localhost in the HELO/EHLO command.
no_tls
If true, connects to smtp without TLS. Defaults to false.
password
Password to log in to your smtp server. Must be specified for username to have an effect.
port
Port number for smtp on smtp_host. Defaults to 0.
ssl
If true, connects to smtp through SSL. Defaults to false.
timeout
Sets the number of seconds after which smtp attempts should time out. Defaults to 10.
username
Username to log in to your smtp server, if necessary.

**Comment by Tarrasch** [comment]
Please send in your change suggestions as a PR. It's easier to discuss concrete details in that format. :)
