### ISSUE TITLE
can't install luigi

### ISSUE THREAD

**Issue by n3xus** [spotify/luigi#2055]
[ec2-user@ip-xx-xx-xx-xx luigi-2.6.0]$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to luigi.egg-info/requires.txt
writing luigi.egg-info/PKG-INFO
writing top-level names to luigi.egg-info/top_level.txt
writing dependency_links to luigi.egg-info/dependency_links.txt
writing entry points to luigi.egg-info/entry_points.txt
reading manifest file 'luigi.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'luigi.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
**error: can't copy 'luigi/static/visualiser/lib/URI.js': doesn't exist or not a regular file**

Our server is not connected to internet thus we are unable to pip install. So I've downloaded tar.gz file from pypi and tried to run setup.py. But got above error.

**Comment by kwilcox** [comment]
This has already been covered in #2017 #2027 #2028 #2029 and #2041. Resolved in #2033.
