### ISSUE TITLE
Executing 2 pipeline jobs, (Must be in SYNC, not paralelly)

### ISSUE THREAD

**Issue by stalat** [spotify/luigi#2084]
Hello there,

I am into Luigi framework development and I want to execute 2 jobs(Both are pipeline-jobs) in a single class, But in a way that Job2 must only run, when Job1 is executed completely.

```
class ExecuteTwoJobs(luigi.Task):
    def requires(self):
        reqs = []
        reqs.append(Job1(*args, **kwargs))
        reqs.append(Job2(*args, **kwargs))
        return reqs

    def output(self):
        //statements

    def run(self):
        //statements
```

Is there any way I can execute job1 and once it's completed, then go for execution of Job2. 

Any help is much appreciated

**Comment by Tarrasch** [comment]
Yes, just make Job2 require Job1. Optimistically closing. :)
