### ISSUE TITLE
Document prune_on_get_work (maybe add config for server's prune period?)

### ISSUE THREAD

**Issue by nugend** [spotify/luigi#2110]
I have a task that needs to retry its ExternalTasks very frequently (we have worker keep alive on as well as retry external tasks). I spent the day digging through the code trying to figure out why the worker wasn't actually retrying the External Tasks every few seconds as per the wait interval and retry delay settings.

Turns out it's because the scheduler was hardcoded to prune tasks once every 60 seconds and the worker couldn't get new work because the tasks weren't pruned. Turned on prune_on_get_work and everything worked fine. On the other hand... this should really be something you set on the *worker* and not on the scheduler daemon (that is, the workers should know when they need to prune before getting work so as to reduce the number of prunings needed).

Also, is there a good reason why the prune period shouldn't be dropped to less than 60 seconds? If not, it should probably be configurable.

**Comment by dlstadther** [comment]
Thanks for raising @nugend 

The worker/scheduler interaction is not my expertise. But am i correct that this is the code you're experiencing issues with?

https://github.com/spotify/luigi/blob/1d5a05e9ebcf09ac410b985bfd3c07a3df5d5f19/luigi/scheduler.py#L376-L379

If so, couldn't you just update the value of [`worker_disconnect_delay`](https://github.com/spotify/luigi/blob/1d5a05e9ebcf09ac410b985bfd3c07a3df5d5f19/luigi/scheduler.py#L129) in configuration?

**Comment by nugend** [comment]
Nope. This section:

https://github.com/spotify/luigi/blob/1d5a05e9ebcf09ac410b985bfd3c07a3df5d5f19/luigi/scheduler.py#L1090-L1106

The problem is that I've got some workers that are much more aggressive in trying to ingest data and most of the rest are far less aggressive. On these aggressive workers (which represent a much smaller percent of all my workers), I want to run the prune every time.

But the thing is that the config is set on the *scheduler*. So if I set it, it means *all* my workers force the prune to happen, which causes performance issues. If it were a per-worker setting, it would be much better for my purposes.

**Comment by dlstadther** [comment]
Per-worker configuration sounds like a much larger request which I'm not confident with direction. @Tarrasch do you have any insight here?

**Comment by nugend** [comment]
I admit ignorance to the quantity of work involved. I was hoping it wasn't huge since the prune call is right there at the top of the function and is already being controlled by a conditional.

**Comment by Tarrasch** [comment]
I feeling I am slowly forgetting the gritty details of how the worker-scheduler interaction works. But hopefully I can say something useful anyway. :)

> I spent the day digging through the code trying to figure out why the worker wasn't actually retrying the External Tasks every few seconds as per the wait interval and retry delay settings.

Doesn't this simply suggest something is wrong with the worker? Shouldn't it just recheck `complete()` for the external tasks and re-report it to the scheduler? How come anything server side (like pruning) comes to play here?

I recall we only created `prune_on_get_work` to make some test cases work without faking the 60 second delay (hence more deterministic). Perhaps the test cases are testing something similar to your case?

**Comment by nugend** [comment]
Because the scheduler won't reschedule an ExternalTask until it's been pruned (well, that was what we came to determine at any rate).

**Comment by Tarrasch** [comment]
Ah I see, the pruning step sets tasks to be runnable after being FAILED for too long. I'm not sure what the best solution is here. What do you propose?

**Comment by nugend** [comment]
Well, one or two things seem easy and reasonable to me: Configurable global prune frequency or letting the workers pass a "prune" option on the get_work call.

**Comment by nugend** [comment]
Go away stale bot!
