### ISSUE TITLE
RemoteFileSystem of luigi.contrib.ftp does not implement the listdir method.

### ISSUE THREAD

**Issue by dmohns** [spotify/luigi#2111]
Pretty much as the title states: Currently RemoteFileSystem of `luigi.contrib.ftp` does not implement the `listdir` method. 
As FTP basically provides access to an ordinary filesystem this should be perfectly do-able and would very helpful in certain situations.

**Comment by dlstadther** [comment]
@dmohns Please feel free to submit a PR!

**Comment by OstrichProjects** [comment]
@dmohns @dlstadther This feature request can be marked as resolved.
