### ISSUE TITLE
Success on missing output

### ISSUE THREAD

**Issue by byklo** [spotify/luigi#2112]
1. Download the tutorial script (https://github.com/spotify/luigi/blob/master/examples/top_artists.py)
2. Change Streams.run() to simple do a print (removing the 'with' block that writes to target)
3. `luigi --module top_artists Streams --date 2017-04-04`
4. Execution summary claims Streams ran successfully even though output was not created

Is this expected behaviour? If it is, can someone explain why - I may have the wrong mental model for this tool.

**Comment by Tarrasch** [comment]
Luigi doesn't check that it actually is `complete()` after a Task has run. :)

**Comment by erikbern** [comment]
right – if you run it multiple times then each time it will try to re-run the task because it notices that it doesn't exist

also – if you have another task that depends on Streams then it would throw an error once it detects that Streams ran but didn't produce output

**Comment by byklo** [comment]
Thank you!

**Comment by colmex** [comment]
Not to open up a closed issue but I found this from google so it's probably best to have the conversation here.

Why doesn't it check that it is actually `complete()` after the Task is run? This feels like it would make sense for it to check it's target after the `run`

CC: @Tarrasch @erikbern

**Comment by Tarrasch** [comment]
Both ways make sense. We went for the less work and "we trust you know your stuff" implementation. If your task is well-behaved it should always be `complete()` after `run()` successfully exits.
