### ISSUE TITLE
S3 target: resources = {'overwrite_resource': 1} does not work

### ISSUE THREAD

**Issue by Casyfill** [spotify/luigi#2122]
S3 target: resources = {'overwrite_resource': 1} does not work

I want to constantly overwrite the existing dump file on S3 (and make it public - also a functionality not supported?). Unfortunately, while `overwrite_resource:1` works for the local target, it does not so for S3.

**Comment by dlstadther** [comment]
@Casyfill Feel free to open a PR for each of these desired featured requests!

**Comment by Casyfill** [comment]
figured out how to overwrite stuff on s3, sorry for taking your time
