### ISSUE TITLE
Wrong configuration documentation

### ISSUE THREAD

**Issue by soq** [spotify/luigi#2133]
Hello.
In https://github.com/spotify/luigi/blob/master/doc/configuration.rst there are parameters with dash in name, but in code they are used with underline symbol. Here they are (written as in doc):
max-reschedules, max-shown-tasks, max-graph-nodes, parallel-scheduling, send-failure-email, email-interval, batch-mode, error-lines, error-messages, group-by-error-messages, batch-emails, remove-delay, retry-delay, state-path. 

Options spark-jar and spark-class (or spark_jar and spark_class) haven't used in code at all.

Please, fix or documenation, or code.

Thank you!

**Comment by Tarrasch** [comment]
Sorry about this. The code is correct and documentation is wrong. Do you mind stepping up and fixing the docs?

I wanted to spend some hackday creating a automatic cross-checking of this information, but never got around to do it.

**Comment by soq** [comment]
> Do you mind stepping up and fixing the docs?
Yes, I can try to fix it in a few days.
