### ISSUE TITLE
always use subprocess for worker timeout

### ISSUE THREAD

**Issue by a86c6f7964** [spotify/luigi#2155]
Creating a ticket for discussion in https://groups.google.com/forum/#!topic/luigi-user/YH6pxBngKDw

A worker can timeout talking to the luigi scheduler if `workers` is set to 1 and the task is a long running task. If you set the param to at least 2 then it will use a subprocess to ping the scheduler and keep the worker from timing out

**Comment by Tarrasch** [comment]
Thanks for opening this issue, but I close this in favor of an existing issue: https://github.com/spotify/luigi/issues/1822
