### ISSUE TITLE
scheduling large amounts of files

### ISSUE THREAD

**Issue by wkerzendorf** [spotify/luigi#2179]
I've written a Luigi pipeline to extract 1.2 mio files and then do some sed work on them - see 

```python
import luigi
from glob import glob
import os
raw_zips = '/1002/*.gz'


class ExtractGZ(luigi.Task):
    document_id = luigi.Parameter()

    def output(self):
        return luigi.LocalTarget(self.document_id + '.txt')

    def run(self):
        print os.path.dirname(self.document_id)


class TestTask(luigi.WrapperTask):
    def requires(self):
        for fname in glob(raw_zips):
            #print fname
            yield ExtractGZ(fname)
```

If I run this through Luigi on a few thousand files it schedules fine. But running this on the whole dataset it complains with `Failed connecting to remote scheduler`. I was told on SO that luigi can't handle this - but for my use case it would make perfect sense - if Luigi would do it this way (schedule the files separately - and specifically tell me if things fail).

**Comment by dlstadther** [comment]
@wkerzendorf Could you provide more of a stack trace? I've received that error message before, but it's been awhile that I can't recall the situation surrounding it.

**Comment by wkerzendorf** [comment]
@dlstadther just running the 1.2 mio files and then I can tell you. I'm running it against the scheduler and at some stage it trys to connect to the scheduler and the scheduler doesn't respond.

**Comment by wkerzendorf** [comment]
@dlstadther here we go
```
  File "/home/wkerzend/miniconda2/envs/deepthought/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/wkerzend/miniconda2/envs/deepthought/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='localhost', port=8082): Read timed out. (read timeout=10.0)
ERROR: Luigi unexpected framework error while scheduling TestTask()
Traceback (most recent call last):
  File "/home/wkerzend/miniconda2/envs/deepthought/lib/python2.7/site-packages/luigi/worker.py", line 656, in add
    for next in self._add(item, is_complete):
  File "/home/wkerzend/miniconda2/envs/deepthought/lib/python2.7/site-packages/luigi/worker.py", line 773, in _add
    retry_policy_dict=_get_retry_policy_dict(task),
  File "/home/wkerzend/miniconda2/envs/deepthought/lib/python2.7/site-packages/luigi/worker.py", line 490, in _add_task
    self._scheduler.add_task(*args, **kwargs)
  File "/home/wkerzend/miniconda2/envs/deepthought/lib/python2.7/site-packages/luigi/scheduler.py", line 115, in rpc_func
    return self._request('/api/{}'.format(fn_name), actual_args, **request_args)
  File "/home/wkerzend/miniconda2/envs/deepthought/lib/python2.7/site-packages/luigi/rpc.py", line 148, in _request
    page = self._fetch(url, body, log_exceptions)
  File "/home/wkerzend/miniconda2/envs/deepthought/lib/python2.7/site-packages/luigi/rpc.py", line 140, in _fetch
    last_exception
RPCError: Errors (3 attempts) when connecting to remote scheduler 'http://localhost:8082'

```

**Comment by wkerzendorf** [comment]
the scheduler
```2017-07-11 20:22:40,990 luigi.scheduler[82605] INFO: Starting pruning of task graph
2017-07-11 20:22:44,888 luigi.scheduler[82605] INFO: Done pruning task graph
2017-07-11 20:23:00,986 tornado.access[82605] INFO: 200 GET /api/ping (127.0.0.1) 0.80ms
2017-07-11 20:23:25,182 luigi.scheduler[82605] INFO: Starting pruning of task graph
2017-07-11 20:23:29,079 luigi.scheduler[82605] INFO: Done pruning task graph

```

**Comment by erikbern** [comment]
luigi won't do very well with this – especially since the `yield` construct will re-start the generator from scratch, leading to a O(n^2) with n = 1.2M

we should fix the quadratic complexity at some point, but also Luigi wasn't really built to handle millions of files.

I would try to batch them up in some way – maybe the files have some kind of timestamp or something so that you can batch them by small time intervals? Or batch them by the first few character(s) of the filename or something

**Comment by wkerzendorf** [comment]
@erikbern yes they are batchable - but I don't really want to. The nice thing would be that it tells me which ones fail and which ones don't. Actually is there a way to just batch things up and run them sequentially?

**Comment by wkerzendorf** [comment]
@erikbern these are independent files and the only thing I want is to move them through a pipeline one-by-one. How do I do this?

**Comment by wkerzendorf** [comment]
@erikbern So I'm working on making luigi run iteratively on batches using successive calls of `luigi.run` with small batches. Is that a sensible approach?

**Comment by wkerzendorf** [comment]
@dlstadther @erikbern okay that seems to work I can just call `luigi.run` over and over again from the script. Thanks

**Comment by wkerzendorf** [comment]
happy to close this.

**Comment by wkerzendorf** [comment]
actually - it doesn't like this `Pid(s) set([115103]) already running`

**Comment by Tarrasch** [comment]
> happy to close this.

This is too much of a one-person conversation. I'm closing this for now. Feel free to open other issues if you have something more concrete to ask. Luigi doesn't handle millions of simultaneous Tasks like that.

**Comment by wkerzendorf** [comment]
Just to complete the journey - it seems that recalling run and disabling the lock makes this work with many files. Maybe this proves useful for someone else:

```python
if __name__ == '__main__':
    for raw_dir in glob(raw_dirs):
        #TestTask.raw_dir=os.path.split(raw_dir)[-1]
        luigi.run(main_task_cls=TestTask, cmdline_args=['--rawdir={0}'.format(os.path.split(raw_dir)[-1]), '--workers=20', '--no-lock'])
```
