### ISSUE TITLE
Move HDFS file to encrypted zone failed.

### ISSUE THREAD

**Issue by zenghz** [spotify/luigi#2183]
Get error message when using `HdfsTarget` as output because `/tmp` is under unencryption zone and the destintation is under encryption zone.
---stderr---
mv: /tmp/data-matrix-luigitemp-720632922 can't be moved into an encryption zone.

Fixed by changing the `abstract_client.py` line 42, in `rename` from 
    ```return self.move(path, dest)```
to 
``` 
self.copy(path, dest)

self.remove(path)

return```

**Comment by Tarrasch** [comment]
I close this as this is just some work-around information, perhaps handy for someone with a similar. I close this as I see no action to be done here.
