### ISSUE TITLE
`output()` executes before `requires()`

### ISSUE THREAD

**Issue by citynorman** [spotify/luigi#2204]
I'm getting an error running the below where `output()` executes before `requires()` causing an error because the file doesn't exist. I'm confused why does `requires()` run before `output()` and is there a way to deal with the situation?

`    
 
    class BTask(luigi.Task):

        def output(self):
            #==> this executes before requires() with an error
            df_in = pd.read_pickle(self.input()['df_in'].path)
            return [luigi.LocalTarget('file%s.csv'%str(iDate) for iDate in df_in['date'].unique()]

        def requires(self):
            return {'df_in':ATask()}

`

I've searched the docs Execution Model and Design as well as github but haven't found a similar issue.

Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
luigi==2.6.2

**Comment by erikbern** [comment]
output should run before `requires()`. it runs to check whether the task is already completed

**Comment by erikbern** [comment]
in your example above, you should probably make the `df_in` a parameter or alternatively use dynamic dependencies on another task where `df_in` is a parameter

**Comment by citynorman** [comment]
Thanks @erikbern ! I actually call `output()` in `complete()` if I take those lines in `complete()` out it doesn't call `output()` before `require()`
`
class BTask(luigi.Task):

    def output(self):
        #==> this executes before requires() with an error
        df_in = pd.read_pickle(self.input()['df_in'].path)
        return [luigi.LocalTarget('file%s.csv'%str(iDate) for iDate in df_in['date'].unique()]

    def requires(self):
        return {'df_in':ATask()}

    def complete(self):
        for iFile in self.output():
            if not os.path.exists(iFile.path):
                return False
        return True


`

**Comment by erikbern** [comment]
i think this seems a bit un-idiomatic. off the top of my head what I would do is something like

* let `BTask() depend on ATask()`
* inside `BTask.run`, read the `df_in` of `ATask()`, and require a number of third task `CTask(iDate)`
* do all the processing inside the `CTask`

**Comment by tfiers** [comment]
To check for this, you can use this class with a custom `complete()` method instead of `luigi.Task`:

```py
from luigi import Task, Target
from luigi.task import flatten

class SafeTask(Task):
    @property
    def _dependencies(self) -> List[Task]:
        return flatten(self.requires())

    @property
    def _outputs(self) -> List[Target]:
        return flatten(self.output())

    @property
    def _all_dependencies_complete(self) -> bool:
        return all([dependency.complete() for dependency in self._dependencies])

    @property
    def _all_outputs_exist(self) -> bool:
        return all([output.exists() for output in self._outputs])

    def complete(self) -> bool:
        return self._all_dependencies_complete and self._all_outputs_exist
```

**Comment by konstantinmiller** [comment]
Is it the only use of `output()` to be called from `complete()` to check if the task is completed?
