### ISSUE TITLE
Create and share parameter inside Task class 

### ISSUE THREAD

**Issue by imalkov82** [spotify/luigi#2220]
I wish to create common class inside the my Task class and use it across all functions.
I fail to do it because (1) I can't create the parameter as luigi parameter in class constructor  and (2) if I create the parameter inside function and assign it to **_self_**, the parameter not visible to other class functions.  
Can you assist me how its done?

Use case example:

```
import MyContext

class MyTask(luigi.Task):

    conf_file = luigi.Parameter()

    def requires(self):
		# creating context conf_file param
        context = MyContext(self.conf_file)
		# use the context for the firts time
        return {item: MySubTask(item, context)
                for item in context.items}

    def output(self):
		# here I want to use the context again
        return luigi.LocalTarget(os.path.join(context.output_path))

    def run(self):
        with self.output().open('w') as f:
            for table, result in self.input().iteritems():
                # do something
```

Thanks

**Comment by Gr1f0n6x** [comment]
You can change the Task class definition and add inside it your own property like this:

```
    @property
    def context(self):
        return None
```

And in your task you can do now:
```
class MyTask(luigi.Task):
    ....
    @property
    def context(self):
        return MyContext(self.conf_file)
```

Maybe, it is not the best approach, but it should work
