### ISSUE TITLE
HdfsTarget is not workging in luigi > 2.6.1

### ISSUE THREAD

**Issue by zwotzie** [spotify/luigi#2223]
This code runs correct under luigi <= 2.6.1:

```python
from luigi.contrib import hdfs
import luigi.format

# just to be sure that realy the right version is used...
import pkg_resources
print "luigi ==", pkg_resources.get_distribution("luigi").version
print "snakebite ==", pkg_resources.get_distribution("snakebite").version

destination_file = '/tmp/test/file.gz'

target = hdfs.HdfsTarget(path=destination_file, format=luigi.format.Gzip)

if target.exists():
    target.remove(skip_trash=False)

fsobj = target.open('w')
fsobj.write('lol3\n')
fsobj.close()
```

with luigi 2.6.2 or 2.7.0 it breaks:
```python
luigi == 2.7.0
snakebite == 2.11.0
Traceback (most recent call last):
  File "/opt/tests/hdfs_target.py", line 18, in <module>
    fsobj.close()
  File "/opt/python-2.7.10/lib/python2.7/site-packages/luigi/format.py", line 224, in close
    self._output_pipe.close()
  File "/opt/python-2.7.10/lib/python2.7/site-packages/luigi/contrib/hdfs/format.py", line 51, in close
    remove(self.path)
  File "/opt/python-2.7.10/lib/python2.7/site-packages/luigi/contrib/hdfs/clients.py", line 62, in result
    return getattr(get_autoconfig_client(), method_name)(*args, **kwargs)
  File "/opt/python-2.7.10/lib/python2.7/site-packages/luigi/contrib/hdfs/snakebite_client.py", line 140, in remove
    return list(self.get_bite().delete(self.list_path(path), recurse=recursive))
  File "/opt/python-2.7.10/lib/python2.7/site-packages/snakebite/client.py", line 1540, in wrapped
    yield results.next()
  File "/opt/python-2.7.10/lib/python2.7/site-packages/snakebite/client.py", line 508, in delete
    for item in self._find_items(paths, processor, include_toplevel=True):
  File "/opt/python-2.7.10/lib/python2.7/site-packages/snakebite/client.py", line 1216, in _find_items
    raise FileNotFoundException("`%s': No such file or directory" % path)
snakebite.errors.FileNotFoundException: `/tmp/test/file.gz': No such file or directory
```

client.cfg:
```
[hdfs]
client = snakebite
snakebite_autoconfig = True
tmp_dir: /x/tmp
```

The file is correct in form and content written in "tmp_dir" (/x/tmp/username/test/file.gz-luigitemp-951771388).

**Comment by zwotzie** [comment]
my best guess is that this is the change which breaks it:

https://github.com/spotify/luigi/commit/a2f63c6b5968e09d0762c1edf27b90ca45cbae35

**Comment by andyherdfd** [comment]
Has anyone taken a look at this since it was posted? I've just encountered this same issue with `HdfsTarget` using snakebite client when attempting to upgrade from an older version of Luigi. I can confirm that it doesn't work in v2.7.5, and that it does work in v2.6.1. I haven't tried the versions in the middle to determine whether @zwotzie's guess at the commit which caused the issue is the culprit.

**Comment by dlstadther** [comment]
@thunderock , you were the last to contribute to luigi/contrib/hdfs. Could you take a look here? Candidly, I don't use this functionality of luigi - so i'm not likely much help here.

**Comment by dlstadther** [comment]
[here](https://github.com/spotify/luigi/compare/2.6.1...2.6.2) are the commits which were added for 2.6.2

**Comment by dlstadther** [comment]
[This commit](https://github.com/spotify/luigi/commit/a2f63c6b5968e09d0762c1edf27b90ca45cbae35) was included in the 2.6.2 release and changes a non-trivial amount of hdfs/format.py. Could you take a look to see if your issue propagates to these code changes, @andyherdfd / @zwotzie ?

**Comment by zwotzie** [comment]
I'd bet my house on it. We decided to leave Luigi in the long run for a real workflow solution (Camunda BPMN) and the import of files via Spark. 

But as they say: the dead live longer... maybe I'll check the code again for a bugfix.

**Comment by zwotzie** [comment]
As i suspected:

If I reverse the changes in luigi.contrib.hdfs.format.py the close method of HdfsAtomicWritePipe to:
```
    def close(self):
        super(HdfsAtomicWritePipe, self).close()
        rename(self.tmppath, self.path)
        # try:
        #     remove(self.path)
        # except HDFSCliError:
        #     pass
        # if not all(result['result'] for result in rename(self.tmppath, self.path) or []):
        #     raise HdfsAtomicWriteError('Atomic write to {} failed'.format(self.path))
```
it works like charme...

**Comment by zwotzie** [comment]
Ok here we go with the Problem catching the Exception. 

If using snakebite the exception when "automatic removing" the target comes from snakebite not from hdfs.errors.

And whether I really want the automatic deletion of the destination, I find questionable.

**Comment by zwotzie** [comment]
I found the answer in just one class behind (HdfsAtomicWriteDirPipe), There the exception handling is correct :+1: 

please correct this in the code.
