### ISSUE TITLE
Error in examples/top_artists.py

### ISSUE THREAD

**Issue by rantav** [spotify/luigi#226]
Hi, making my first steps with luigi here and I think there's a small problem in one of the examples (at least I see this prob).
The `top_artists.py` example has a task `Top10Artists` which is supposed to print its output to a tsv file. But it prints lines separated by spaces instead of tabs. I don't know, it looks kind of silly, but that's what I see as a result of [line 92](https://github.com/spotify/luigi/blob/master/examples/top_artists.py#L92)

As a result of this, inserting the data to postgres fails since [its default separator is \t](https://github.com/spotify/luigi/blob/master/luigi/postgres.py#L225)

I'd suggest a pull request if it wasn't my first 5 min with luigi and I would know what the heck I'm doing... :wink:

**Comment by Tarrasch** [comment]
Closing because this is outdated (surely).
