### ISSUE TITLE
Problems with dynamic_requirements.py example

### ISSUE THREAD

**Issue by lizmeister321** [spotify/luigi#2297]
As written, the dynamic_requirements.py example throws a TaskClassAmbiguousException for the "Config" task (caused by the "config" variable also appearing in ln 81). Easy fix -- got it to run by renaming the task to "ConfigA" -- but frustrating to those of us newer to luigi.

**Comment by erikbern** [comment]
do you mind creating a pull request and renaming it to maybe `Configuration` or something?

**Comment by dlstadther** [comment]
Resolved
