### ISSUE TITLE
Redshift COPY fails in luigi 2.7.1 when columns are not provided

### ISSUE THREAD

**Issue by dmohns** [spotify/luigi#2298]
Running Redshift COPY jobs with `columns = None` to prohibit table creation fails in luigi 2.7.1 with 
```
TypeError: object of type 'NoneType' has no len()
```

The root cause seems to be https://github.com/spotify/luigi/pull/2245/files#diff-778ea3db4cccaf4de6564889c5eb670fR338

A possible solution would be to change the line to
```python
if self.columns and len(self.columns) > 0:
```
unless I am missing some reason to explicitly ask only for `len(self.columns)`.

**Comment by dlstadther** [comment]
This seems like a reasonable solution. The motivation here was to handle the [default `column`](https://github.com/spotify/luigi/blob/master/luigi/contrib/rdbms.py#L71) definition or some structure with length > 0. Really, we should ensure that it is not `None` and an iterable with length greater than zero.

Feel free to PR!
