### ISSUE TITLE
Range tasks use None with DateParameter, which breaks using them as dynamic deps

### ISSUE THREAD

**Issue by himikof** [spotify/luigi#2305]
It seems that it has been decided (#1591, #1216) that using `Parameter(default=None)` should not be allowed and can fail. But range tasks in `luigi.tools.range` use them a lot (for example, `start` and `stop`).

This leads to the following task breaking (with dynamic deps -> task serialization is used):
```python
class Example(luigi.Task):
    start = luigi.DateParameter()

    def run(self):
        yield luigi.tools.range.RangeDaily(start=start, of=DoSomeWork)
```

I actually have one such case where I need to determine the date range to use after running another task. Is there another, proper way of achieving this?

Seems like optional `Parameters` should be directly supported somehow, including `to_str_params`/`from_str_params`.

**Comment by himikof** [comment]
This issue seems to be still relevant and unfixed. Since then the #2295 has added a `OptionalParameter` class with the required behavior, but it is still not used in `luigi.tools.range` and cannot be simply combined with typed parameters (e.g. `DateParameter`).

**Comment by dlstadther** [comment]
Thanks for re-raising @himikof !

Is this something you'd be comfortable contributing to resolve? I'd be happy to review!

Thanks!
