### ISSUE TITLE
Error While Submitting Spark Job.

### ISSUE THREAD

**Issue by Nikhillosalka** [spotify/luigi#2315]
**This is the code that I am running.**

import random

import luigi
import luigi.format
import luigi.contrib.hdfs
from luigi.contrib.spark import SparkSubmitTask
import subprocess
import os

class UserItemMatrix(luigi.Task):

    data_size = 1
    pathHdfs="hdfs://localhost:9000/injest/data/logs/parquet/2017-09-26/13/checkForInput.sh"

    def requires(self):
        print("Inside SparkALS requires")
        return []

    def run(self):
        '''
        Will Fetch the path from Some where. Currently Doing Nothing here.
        '''
        print("Inside UserItemMatrix Run")

    def output(self):
        self.pathHdfs

class SparkALS(SparkSubmitTask):
    data_size = luigi.IntParameter(default=1000)
    driver_memory = '2g'
    executor_memory = '3g'
    num_executors = luigi.IntParameter(default=100)
    app = '/Users/Nikhil/Projects/scala-maven-example-master/target/scala-maven-example-1.0.0-SNAPSHOT.jar'
    entry_class = 'com.jesperdj.example.hello.HelloScala'

    def requires(self):
        return UserItemMatrix()

    def app_options(self):
        print("Inside SparkALS app_options")
        return [self.input().path, self.output().path]

    def output(self):
        print("Inside SparkALS output")
        return luigi.contrib.hdfs.HdfsTarget('/als-output', format=luigi.format.Gzip)
if __name__ == "__main__":
    luigi.run()

**Expectation** : It should create a file at my local HDFS System. One Confusion. I am not specifying any HFDS Path so what is the default and in case if i want to access a remote HDFS how to do that?

**Error:**
DEBUG: Checking if SparkALS(data_size=1000, num_executors=100) is complete
Inside SparkALS output
/Library/Python/2.7/site-packages/luigi/parameter.py:261: UserWarning: Parameter "tmp_dir" with value "None" is not of type string.
  warnings.warn('Parameter "{}" with value "{}" is not of type string.'.format(param_name, param_value))
/Library/Python/2.7/site-packages/luigi/parameter.py:261: UserWarning: Parameter "effective_user" with value "None" is not of type string.
  warnings.warn('Parameter "{}" with value "{}" is not of type string.'.format(param_name, param_value))
/Library/Python/2.7/site-packages/luigi/parameter.py:261: UserWarning: Parameter "namenode_host" with value "None" is not of type string.
  warnings.warn('Parameter "{}" with value "{}" is not of type string.'.format(param_name, param_value))
DEBUG: Running file existence check: hadoop fs -stat /als-output
DEBUG: Checking if UserItemMatrix() is complete
/Library/Python/2.7/site-packages/luigi/worker.py:334: UserWarning: Task UserItemMatrix() without outputs has no custom complete() method
  is_complete = task.complete()
INFO: Informed scheduler that task   SparkALS_1000_100_dedafcea6b   has status   PENDING
Inside SparkALS requires
INFO: Informed scheduler that task   UserItemMatrix__99914b932b   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 2
INFO: [pid 4830] Worker Worker(salt=113263333, workers=1, host=dhcp-10-176-99-172.idc.oracle.com, username=Nikhil, pid=4830) running   UserItemMatrix()
Inside SparkALS requires
Inside UserItemMatrix Run
INFO: [pid 4830] Worker Worker(salt=113263333, workers=1, host=dhcp-10-176-99-172.idc.oracle.com, username=Nikhil, pid=4830) done      UserItemMatrix()
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   UserItemMatrix__99914b932b   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 4830] Worker Worker(salt=113263333, workers=1, host=dhcp-10-176-99-172.idc.oracle.com, username=Nikhil, pid=4830) running   SparkALS(data_size=1000, num_executors=100)
/Library/Python/2.7/site-packages/luigi/worker.py:175: UserWarning: Task UserItemMatrix() without outputs has no custom complete() method
  missing = [dep.task_id for dep in self.task.deps() if not dep.complete()]
ERROR: [pid 4830] Worker Worker(salt=113263333, workers=1, host=dhcp-10-176-99-172.idc.oracle.com, username=Nikhil, pid=4830) failed    SparkALS(data_size=1000, num_executors=100)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/luigi/worker.py", line 178, in run
    raise RuntimeError('Unfulfilled %s at run time: %s' % (deps, ', '.join(missing)))
RuntimeError: Unfulfilled dependency at run time: UserItemMatrix__99914b932b
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   SparkALS_1000_100_dedafcea6b   has status   FAILED
DEBUG: Checking if SparkALS(data_size=1000, num_executors=100) is complete
Inside SparkALS output
DEBUG: Running file existence check: hadoop fs -stat /als-output
DEBUG: Checking if UserItemMatrix() is complete
INFO: Informed scheduler that task   SparkALS_1000_100_dedafcea6b   has status   PENDING
Inside SparkALS requires
INFO: Informed scheduler that task   UserItemMatrix__99914b932b   has status   PENDING
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 2
INFO: [pid 4830] Worker Worker(salt=113263333, workers=1, host=dhcp-10-176-99-172.idc.oracle.com, username=Nikhil, pid=4830) running   UserItemMatrix()
Inside SparkALS requires
Inside UserItemMatrix Run
INFO: [pid 4830] Worker Worker(salt=113263333, workers=1, host=dhcp-10-176-99-172.idc.oracle.com, username=Nikhil, pid=4830) done      UserItemMatrix()
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   UserItemMatrix__99914b932b   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 4830] Worker Worker(salt=113263333, workers=1, host=dhcp-10-176-99-172.idc.oracle.com, username=Nikhil, pid=4830) running   SparkALS(data_size=1000, num_executors=100)
ERROR: [pid 4830] Worker Worker(salt=113263333, workers=1, host=dhcp-10-176-99-172.idc.oracle.com, username=Nikhil, pid=4830) failed    SparkALS(data_size=1000, num_executors=100)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/luigi/worker.py", line 178, in run
    raise RuntimeError('Unfulfilled %s at run time: %s' % (deps, ', '.join(missing)))
RuntimeError: Unfulfilled dependency at run time: UserItemMatrix__99914b932b
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   SparkALS_1000_100_dedafcea6b   has status   FAILED
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: There are 1 pending tasks possibly being run by other workers
DEBUG: There are 1 pending tasks unique to this worker
DEBUG: There are 1 pending tasks last scheduled by this worker
INFO: Worker Worker(salt=113263333, workers=1, host=dhcp-10-176-99-172.idc.oracle.com, username=Nikhil, pid=4830) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 ran successfully:
    - 1 UserItemMatrix()
* 1 failed:
    - 1 SparkALS(data_size=1000, num_executors=100)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

**Comment by dlstadther** [comment]
Firstly, this type of question is more appropriate for the mailing list and not Github Issues

Secondly, your error is an Unfulfilled Dependency error. Basically, your `SparkALS` class is expecting an `HdfsTarget`, but the run method of `SparkSubmitTask` (inherited from `ExternalProgram`) does not explicitly output to a non-tmp file. So it appears that your expected output differs from your desired.

Caveat: I have never used the Spark contrib module of Luigi.


Closing as this type of help question doesn't belong in GH issues
