### ISSUE TITLE
Connection overflow in central scheduler history

### ISSUE THREAD

**Issue by ron212** [spotify/luigi#2319]
Hi,
We use luigi central scheduler with history on PostgreSQL.
When we running task after a few minutes the  central scheduler fall because connection overflow. 

`sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection time out. timeout 30`

We are using luigi 2.7.1

Do you have any suggestion how to overcome those problems ?

Thanks,
Ron.

**Comment by kwilcox** [comment]
See http://docs.sqlalchemy.org/en/latest/errors.html#error-3o7r. There would need to be a way to specify additional parameters into the `create_engine` call at https://github.com/spotify/luigi/blob/1b2f0fd800b3b02a230d3613273f796fbc469c11/luigi/db_task_history.py#L82.
