### ISSUE TITLE
no documentation of python-daemon requirement for --background

### ISSUE THREAD

**Issue by baconz** [spotify/luigi#232]
I noticed that there is not much documentation around the `--background` option to luigid. Specifically, the python-daemon requirement is not documented anywhere except for the call-out in the debian control file. Is this because it is not meant for wide consumption, or just because nobody's gotten around to adding documentation for it? If it is the latter, I'm happy to add some quick docs.

**Comment by Tarrasch** [comment]
Seems fixed
