### ISSUE TITLE
Efficiently backfilling RedshiftQuery-based Tasks

### ISSUE THREAD

**Issue by samschlegel** [spotify/luigi#2329]
We are currently exploring porting a fairly complex hourly Airflow DAG over to Luigi. The DAG consists of about 25 SubDAGs, which each contain 3 tasks that run SQL queries on Redshift. As part of moving, we want to backfill that task over the past 2 years. Doing this naively by having tasks depend on their previous hour obviously wouldn't work, as that would be ~1.3 MM tasks trying to be scheduled at once, so the plan is to do it in chunks, probably a week at a time. I've written the tasks so that their `DateHourParameter` has a `batch_method` of `list`, and they combine into a single query for each of the 3 subtasks. 

This all works fine, if I stub out the completeness checks. The issue lies in that using Redshift as the backing store for the marker_table is prohibitively slow. `luigi-deps-tree` using RedshiftQuery takes 20 seconds for 1 hour, where with PostgresQuery it takes 300ms.

One solution is to use `luigi.tools.RangeHourly`, but the issue is this only works with the first task, not for all of it's dependencies. Is the proper direction here to extend `RangeHourlyBase` in all of the tasks and pass along the `RangeHourlyBase` parameters using `of_params`?

Another solution would be to use something else as the backing store for `RedshiftQuery` completeness checks, but it doesn't feel right to have `RedshiftTarget.exists()` check something besides Redshift, and we'd lose the benefit of updates to the table running in the same transaction as the query itself. All those aside, this seems like one of the easier solutions.

The only other solution I can think of, is to move `Task.bulk_complete` into luigi core, with a default impl that naively checks each `Task(...).complete()` individually, and use that everywhere possible in the worker. This is definitely the most involved solution, but I imagine that there are a lot of situations where this would lead to faster scheduling, and it would probably be the most beneficial to the ecosystem as a whole. However, as we aren't totally invested in Luigi yet, it's also the hardest sell.

Before I started down any of those three roads I was hoping I could get some feedback on the proposed solutions.

**Comment by danimcgoo** [comment]
Hi Sam, I don't have much to add, have you considered using S3 as a way to mark completion of the task? You could additionally write to Redshift so you have an easily queryable source, but have the framework check S3 instead. We also use Redshift as our marker table and have found it gets slow over time, so partitioning / archiving might assist.

I'm very curious as to why you're migration from Airflow to Luigi? Given Airflow seems like the hot tech at the moment in this space.
