### ISSUE TITLE
TypeError: Can't instantiate abstract class MongoTarget with abstract methods exists

### ISSUE THREAD

**Issue by samshipengs** [spotify/luigi#2331]
I just started learning to use Luigi. I was trying to implement the require and output function with a mongodb. Here is my sample code:

```from luigi.contrib.mongodb import MongoTarget
from pymongo import MongoClient

def output(self):
    # connect to db
    db_client= MongoClient(self.host, self.port)
    collection_name = 'myCollection'

    return MongoTarget(db_client, '_id', collection_name)
```

This returns a TypeError:
`TypeError: Can't instantiate abstract class MongoTarget with abstract methods exists`

I tried setting `db_client.__isabstractmethod__ = False` but the error stays.Has anyone experienced this error?

I'm using py3.6.1(Anaconda) on windows.

**Comment by Gr1f0n6x** [comment]
@samshipengs probably, you should explicitly implement method `exists()` of MongoDbTarget, because this class doesn't provide default implementation of it:
```
class MongoTarget(Target):

    """ Target for a resource in MongoDB """

    def __init__(self, mongo_client, index, collection):
        """
        :param mongo_client: MongoClient instance
        :type mongo_client: MongoClient
        :param index: database index
        :type index: str
        :param collection: index collection
        :type collection: str
        """
        self._mongo_client = mongo_client
        self._index = index
        self._collection = collection

    def get_collection(self):
        """
        Return targeted mongo collection to query on
        """
        db_mongo = self._mongo_client[self._index]
        return db_mongo[self._collection]

    def get_index(self):
        """
        Return targeted mongo index to query on
        """
        return self._mongo_client[self._index]
```

```
@six.add_metaclass(abc.ABCMeta)
class Target(object):
    """
    A Target is a resource generated by a :py:class:`~luigi.task.Task`.

    For example, a Target might correspond to a file in HDFS or data in a database. The Target
    interface defines one method that must be overridden: :py:meth:`exists`, which signifies if the
    Target has been created or not.

    Typically, a :py:class:`~luigi.task.Task` will define one or more Targets as output, and the Task
    is considered complete if and only if each of its output Targets exist.
    """

    @abc.abstractmethod
    def exists(self):
        """
        Returns ``True`` if the :py:class:`Target` exists and ``False`` otherwise.
        """
        pass
```

So, you have to extend MongoDBTarget and implement exists method in your class.
Hopefully, it can help

**Comment by samshipengs** [comment]
@Gr1f0n6x I see, thanks for pointing it out. So what I'm trying to do is pulling data from an API and put it into a mongodb with luigi. It seems like `MongoRangeTarget` might be something fits, and after looking at its code, I assume `index` should be the name of the db, 'collection' is the name of the collection and `document_ids` is the list of ids of records(documents) , and I need to have a column to check the uniqueness of the document as I don't want duplicates to get inserted into db, `field` looks like the name of this column. Please correct me if it's not at all what I just said.

My question is then, I don't want to just check if a record(document) or a list of records (with document_ids) already exists but checking all records sitting in the db, is there a way to do that or I should try to implement my own function?

**Comment by Gr1f0n6x** [comment]
@samshipengs , 

> It seems like MongoRangeTarget might be something fits

> but checking all records sitting in the db

If MongoRangeTarget fits to you, then you can just implement exists method for this target.
In general, i would recommend you to choose the most fitting class and customize it as you want

>  I need to have a column to check the uniqueness of the document as I don't want duplicates to get inserted into db, field looks like the name of this column

Unfortunately, i'm not familiar with MongoDB, so, i don't know the purpose of these parameters =)
