### ISSUE TITLE
Is it possible to use environment variables in luigi config?

### ISSUE THREAD

**Issue by stolpovsky** [spotify/luigi#2354]
I would like to reference an environment variable in client.cfg, something like this:

```
[DEFAULT]
output_dir = $(PROJECT_HOME)/output
```

where $(PROJECT_HOME) would be replaced with the value of environment variable.

**Comment by Tarrasch** [comment]
Luigi uses the built in logging framework for python, which I believe supports something like this, please check the docs over there.

**Comment by Tarrasch** [comment]
Sorry, I meant the [ConfigParser](https://docs.python.org/3/library/configparser.html#interpolation-of-values), got the words mixed up. :)

**Comment by stolpovsky** [comment]
It does not look like ConfigParser can handle environment variables. I was hoping to avoid having multiple config files that only differ by one value. Thanks for your answers.

**Comment by stolpovsky** [comment]
@snenkov: In your second example (assuming you are on Windows) replace [constants] with [DEFAULT].

**Comment by snenkov** [comment]
@stolpovsky Indeed this worked. Thanks!

**Comment by stolpovsky** [comment]
@snenkov: No problem. If you figure out how to reference env vars, please let me know.
