### ISSUE TITLE
Master build broken

### ISSUE THREAD

**Issue by yonromai** [spotify/luigi#2355]
Hey, the master build has been broken for ~2 weeks. Looks like a docker issue:
`ContainerError: Command 'test -d  /tmp/luigi-test' in image 'busybox:latest' returned non-zero exit status` 
from: https://travis-ci.org/spotify/luigi/jobs/336516969
@ulzha wanna take a look? If you don't have time, no big deal - I can take a look at it sometimes next week.

**Comment by Tarrasch** [comment]
Easiest is to just disable it (send a PR) similar to how many other tests are disabled.. Sorry for the inconvenience!

**Comment by yonromai** [comment]
fixed by: https://github.com/spotify/luigi/pull/2356

**Comment by Tarrasch** [comment]
Thank you!
