### ISSUE TITLE
race condition on lock :(

### ISSUE THREAD

**Issue by FxIII** [spotify/luigi#2357]
I think there is a race condition on 
**luigi/lock.py", line 93, in acquire_for**

```python
# Check if there is a pid file corresponding to this name
if not os.path.exists(pid_dir):
  os.mkdir(pid_dir)
```
between `if not [...]` and `mkdir` another process could have created the pid_dir resulting  in an unhandled OSError exception.

I think that ignore the exception if the folder exists will be enough, or perhaps just create the folder and say sorry if it was just there...

**Comment by dlstadther** [comment]
Feel free to submit a Pull Request if you believe `os.mkdir` should be surrounded in `try/except` (or whatever solution you believe to be best)!

Thanks
