### ISSUE TITLE
Consider using Github's CODEOWNERS

### ISSUE THREAD

**Issue by jamesmcm** [spotify/luigi#2360]
See: https://github.com/blog/2392-introducing-code-owners
and 
https://help.github.com/articles/about-codeowners/

This could be useful for making pull requests to know who should review which parts of the code (especially contrib modules).

It might also make it easier for newcomers to contact developers regarding their own patches, etc.

**Comment by dlstadther** [comment]
I briefly thought about this when GH published that blog post. I want to say it's a good idea to implement in hopes that auto assigning reviewers will aid in quicker PR reviews and merges - thus sparking luigi dev again; however, there exists some overhead in denoting/assigning these code owners - particularly for files with many contributors (i.e. 41 individuals have contributed to `parameter.py`).

All this said, I think it's worth trying - perhaps start with repo owners and contrib dir.

Thanks for starting this discussion!

**Comment by dlstadther** [comment]
Resolved by #2465 

The initial take was only at global owners and my redshift ownership. Contributions welcome :)
