### ISSUE TITLE
Luigi Error NGS pipeline ?

### ISSUE THREAD

**Issue by pinninti19** [spotify/luigi#2362]
Hi, can anyone help me , why it is showing error ?

**CMD**
python Luigipipeline.py --local-scheduler Custom_Genome_Pipeline

====== Running BWA ======
INFO: [pid 18146] Worker Worker(salt=235547989, workers=1, host=Curium, username=likith_reddy, pid=18146) done      Bwa_Mem(sample=SRR098401testsickle_1.fastq)
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   Bwa_Mem_SRR098401testsic_c845cfe3a6   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 11
INFO: [pid 18146] Worker Worker(salt=235547989, workers=1, host=Curium, username=likith_reddy, pid=18146) running   Convert_Sam_Bam(sample=SRR098401testsickle_1.fastq)
ERROR: [pid 18146] Worker Worker(salt=235547989, workers=1, host=Curium, username=likith_reddy, pid=18146) failed    Convert_Sam_Bam(sample=SRR098401testsickle_1.fastq)
Traceback (most recent call last):
  File "/home/likith_reddy/.local/lib/python2.7/site-packages/luigi/worker.py", line 194, in run
    new_deps = self._run_get_new_deps()
  File "/home/likith_reddy/.local/lib/python2.7/site-packages/luigi/worker.py", line 131, in _run_get_new_deps
    task_gen = self.task.run()
  File "Luigipipeline.py", line 60, in run
    "sam/"+self.sample+".sam"])
  File "Luigipipeline.py", line 15, in run_cmd
    p = subprocess.Popen(cmd, shell=False, universal_newlines=True, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   Convert_Sam_Bam_SRR098401testsic_c845cfe3a6   has status   FAILED
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: There are 11 pending tasks possibly being run by other workers
DEBUG: There are 11 pending tasks unique to this worker
DEBUG: There are 11 pending tasks last scheduled by this worker
INFO: Worker Worker(salt=235547989, workers=1, host=Curium, username=likith_reddy, pid=18146) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 13 tasks of which:
* 2 ran successfully:
    - 2 Bwa_Mem(sample=SRR098401testsickle_1.fastq,SRR098401testsickle_2.fastq)
* 2 failed:
    - 2 Convert_Sam_Bam(sample=SRR098401testsickle_1.fastq,SRR098401testsickle_2.fastq)
* 9 were left pending, among these:
    * 9 had failed dependencies:
        - 2 Call_Variant(sample=SRR098401testsickle_1.fastq,SRR098401testsickle_2.fastq)
        - 2 Convert_Bcf_Vcf(sample=SRR098401testsickle_1.fastq,SRR098401testsickle_2.fastq)
        - 1 Custom_Genome_Pipeline()
        - 2 Index_Bam(sample=SRR098401testsickle_1.fastq,SRR098401testsickle_2.fastq)
        - 2 Sort_Bam(sample=SRR098401testsickle_1.fastq,SRR098401testsickle_2.fastq)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

**Comment by jhrf** [comment]
See the line here in your output:

> OSError: [Errno 2] No such file or directory

The file you are supplying to your subprocess cannot be found. This is not a Luigi error.

**Comment by pinninti19** [comment]
hi, why I'm getting this error, I'm not able to figure out the error.
I installed sam, bam. bcf and bwa tools in my pc and provided local variables. 
Along with that I provided the R1 and R2 reads and ref.fa

**Comment by dlstadther** [comment]
> File "Luigipipeline.py", line 60, in run
> "sam/"+self.sample+".sam"])
> ....
> OSError: [Errno 2] No such file or directory

Your issue is on line 60 (or rather whatever the multi-line statement is that ends on line 60 of `Luigipipeline.py`.

As @jhrf mentioned, your issue the is lack of file existence. 

Regardless, please move this to the mailing group. Github Issues are not the place for diagnosing non-luigi issues. Regardless, thanks for reaching out to the community - see you in the mailing group!
