### ISSUE TITLE
Missing parameters for BigQueryLoadTask

### ISSUE THREAD

**Issue by justjoheinz** [spotify/luigi#2363]
It seems that `bq load` now requires the parameter `autodetect` if one want to autodetect the schema from import csv or json files. Just ommitting the schema is not sufficient anymore.

It also provides a paramter for null values.

I created some kind of mixin which takes care of this in my local codebase:

```
        if self.null_marker:
            job['configuration']['load']['null_marker'] = self.null_marker

        if self.schema:
            job['configuration']['load']['schema'] = {'fields': self.schema}
        else:
            job['configuration']['load']['autodetect'] = True
```

but I am not a python wizard, so I do not want to create a PR. This changes work for me though and it would be nice to have them in the proper `BigQueryLoadTask`.

**Comment by justjoheinz** [comment]
It would be nice if someone could look into this. I am not proficient enough in python to provide a PR. The issue is real however. the bigquery api has changed in regard to specifying that schemas should be autodetected.

**Comment by dlstadther** [comment]
@drj42 Looks like you were the most recent BigQuery contributor. Is this something you've happened to already written for yourself? Or perhaps something you'd like to take a stab at?

If not, maybe @dmohns or @ulzha ?

**Comment by justjoheinz** [comment]
Would be a pity to close this, if there is even a PR addressing the issue.

**Comment by dlstadther** [comment]
Sorry @justjoheinz - that PR slipped through my notifications. Just reviewed it to get motion on this issue.
