### ISSUE TITLE
Luigi pipeline 

### ISSUE THREAD

**Issue by pinninti19** [spotify/luigi#2371]
Hi,
I'm trying for the human exome dataset, it was exactly 29 hrs still it running. can you check this ....

**CMD**
**Luigi** python -m luigi --module Luigipipeline Custom_Genome_Pipeline --local-scheduler
DEBUG: Checking if Custom_Genome_Pipeline() is complete
DEBUG: Checking if Convert_Bcf_Vcf(sample=SRR098401_1) is complete
DEBUG: Checking if Convert_Bcf_Vcf(sample=SRR098401_2) is complete
INFO: Informed scheduler that task   Custom_Genome_Pipeline__99914b932b   has status   PENDING
DEBUG: Checking if Call_Variant(sample=SRR098401_2) is complete
INFO: Informed scheduler that task   Convert_Bcf_Vcf_SRR098401_2_1153ce33d1   has status   PENDING
DEBUG: Checking if Index_Bam(sample=SRR098401_2) is complete
Indexing ... Done
/home/likithreddy/miniconda3/lib/python3.6/site-packages/luigi/worker.py:334: UserWarning: Task Index_Bam(sample=SRR098401_2) without outputs has no custom complete() method
  is_complete = task.complete()
INFO: Informed scheduler that task   Call_Variant_SRR098401_2_1153ce33d1   has status   PENDING
DEBUG: Checking if Sort_Bam(sample=SRR098401_2) is complete
/home/likithreddy/miniconda3/lib/python3.6/site-packages/luigi/worker.py:334: UserWarning: Task Sort_Bam(sample=SRR098401_2) without outputs has no custom complete() method
  is_complete = task.complete()
INFO: Informed scheduler that task   Index_Bam_SRR098401_2_1153ce33d1   has status   PENDING
DEBUG: Checking if Convert_Sam_Bam(sample=SRR098401_2) is complete
INFO: Informed scheduler that task   Sort_Bam_SRR098401_2_1153ce33d1   has status   PENDING
DEBUG: Checking if Bwa_Mem(sample=SRR098401_2) is complete
INFO: Informed scheduler that task   Convert_Sam_Bam_SRR098401_2_1153ce33d1   has status   PENDING
INFO: Informed scheduler that task   Bwa_Mem_SRR098401_2_1153ce33d1   has status   PENDING
DEBUG: Checking if Call_Variant(sample=SRR098401_1) is complete
INFO: Informed scheduler that task   Convert_Bcf_Vcf_SRR098401_1_7300c92048   has status   PENDING
DEBUG: Checking if Index_Bam(sample=SRR098401_1) is complete
Indexing ... Done
/home/likithreddy/miniconda3/lib/python3.6/site-packages/luigi/worker.py:334: UserWarning: Task Index_Bam(sample=SRR098401_1) without outputs has no custom complete() method
  is_complete = task.complete()
INFO: Informed scheduler that task   Call_Variant_SRR098401_1_7300c92048   has status   PENDING
DEBUG: Checking if Sort_Bam(sample=SRR098401_1) is complete
/home/likithreddy/miniconda3/lib/python3.6/site-packages/luigi/worker.py:334: UserWarning: Task Sort_Bam(sample=SRR098401_1) without outputs has no custom complete() method
  is_complete = task.complete()
INFO: Informed scheduler that task   Index_Bam_SRR098401_1_7300c92048   has status   PENDING
DEBUG: Checking if Convert_Sam_Bam(sample=SRR098401_1) is complete
INFO: Informed scheduler that task   Sort_Bam_SRR098401_1_7300c92048   has status   PENDING
DEBUG: Checking if Bwa_Mem(sample=SRR098401_1) is complete
INFO: Informed scheduler that task   Convert_Sam_Bam_SRR098401_1_7300c92048   has status   PENDING
INFO: Informed scheduler that task   Bwa_Mem_SRR098401_1_7300c92048   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 13
INFO: [pid 3826] Worker Worker(salt=905540885, workers=1, host=CURIUM, username=likithreddy, pid=3826) running   Bwa_Mem(sample=SRR098401_2)
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 131580 sequences (10000080 bp)...
[M::process] read 131580 sequences (10000080 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 0, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 131580 reads in 11.895 CPU sec, 11.829 real sec
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 0, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 131580 reads in 13.610 CPU sec, 13.611 real sec

**Since yesterday, its showing the same prompt..**

**Here is Luigi.py script**.

from subprocess import check_output
import subprocess
import luigi
import os
import random

#faking the pipline for now

sample_list = ["SRR098401_1","SRR098401_2"]              

genome = "reference/hg38.fa"

def run_cmd(cmd):
    p = subprocess.Popen(cmd, shell=False, universal_newlines=True, stdout=subprocess.PIPE)
    p.wait()
    output = p.communicate()[0]
    return output

class Bwa_Mem(luigi.Task):

    # Ideally we have to show this but for now I am gonna fake it by creating a list of sample IDs
    # fastq_path = luigi.Parameter()

    sample = luigi.Parameter()
    #genome = luigi.Parameter()

    #def requires(self):
    #    return [LoadFastq(sample) for sample in sample_list]

    def output(self):
        return luigi.LocalTarget("sam/%s.sam" % self.sample)

    def run(self):
        tmp = run_cmd(["bwa",
                     "mem",
                     genome,
                     "fastq/"+self.sample+".fastq",
                     "fastq/"+self.sample+".fastq"])
        with self.output().open('w') as sam_out:
            sam_out.write(tmp)
        print ("====== Running BWA ======")

class Convert_Sam_Bam(luigi.Task):

    sample = luigi.Parameter()
    #genome = luigi.Parameter()

    def requires(self):
        return Bwa_Mem(self.sample)
    def output(self):
        return luigi.LocalTarget("bam/%s.bam" % self.sample)
    def run(self):
        tmp = run_cmd(["samtools",
                       "view",
                       "-bS",
                       "sam/"+self.sample+".sam"])
        with self.output().open('w') as bam_out:
            bam_out.write(tmp)
        print ("===== Converting Sam file to Bam file ======")

class Sort_Bam(luigi.Task):

    sample = luigi.Parameter()

    def requires(self):
        return Convert_Sam_Bam(self.sample)
    def run(self):
        tmp = run_cmd(["samtools",
                       "sort",
                       "bam/"+self.sample+".bam",
                       "bam/"+self.sample+".sorted"])
        print ("===== Sorting Bam =======")

class Index_Bam(luigi.Task):

    sample = luigi.Parameter()

    def output(self):
        print ("Indexing ... Done")
    def requires(self):
        return Sort_Bam(self.sample)
    def run(self):
        tmp = run_cmd(["samtools",
                       "index",
                       "bam/"+self.sample+".sorted.bam"])
        print ("==== Indexing Bam ====")

class Call_Variant(luigi.Task):

    sample = luigi.Parameter()
    def requires(self):
        return Index_Bam(self.sample)
    def output(self):
        return luigi.LocalTarget("bcf/%s.bcf" % self.sample)
    def run(self):
        tmp = run_cmd(["samtools",
                       "mpileup",
                       "-u",
                       "-f",
                       genome,
                       "bam/"+self.sample+".sorted.bam"])
        with self.output().open("w") as bcf_file:
            bcf_file.write(tmp)
        print ("=====  Calling Variants =======")

class Convert_Bcf_Vcf(luigi.Task):

    sample = luigi.Parameter()

    def requires(self):
        return Call_Variant(self.sample)
    def output(self):
        return luigi.LocalTarget("vcf/%s.vcf" % self.sample)
    def run(self):
        tmp = run_cmd(["bcftools",
                       "view",
                       "-v",
                       "-c",
                       "-g",
                       "bcf/"+self.sample+".bcf"])
        with self.output().open("w") as vcf_file:
            vcf_file.write(tmp)

        print ("===== Creating VCF =======")

class Custom_Genome_Pipeline(luigi.Task):

    def requires(self):
        return [Convert_Bcf_Vcf(sample) for sample in sample_list]

    def output(self):
        return luigi.LocalTarget("log.txt")

    def run(self):
        print ("running...")
#        for sample in sample_list:
#            print(sample + "\n")
#            return Convert_Bcf_Vcf(sample)
 

if __name__=='__main__':
    luigi.run()

**Comment by dlstadther** [comment]
closing this issue. 

- [ ] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.
- [x] This is a question not an issue. Use SO or the mailing list.

Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
