### ISSUE TITLE
SQLAlchemy reflection error when defining a schema

### ISSUE THREAD

**Issue by robin-weiss-sm** [spotify/luigi#2386]
Hey there!
I have been using the SQLAlchemy contrib module for some time and I have recently run into a problem with it. If I define a schema to be used for the target table, everything works fine when I run it for the first time. The task detects that the required table does not yet exist and creates it for me. 

However, when I run the task for the second time, I get a reflection error from SQLAlchemy 

`
sqlalchemy.exc.InvalidRequestError: Could not reflect: requested table(s) not available in Engine(<connection_string>) schema '<schema>': (<schema>.<table>)
`

I have isolated a section of code in the CopyToTable class that I think is at fault (it's in the table creation part that is called within run() ):
https://github.com/spotify/luigi/blob/0d87424e9224b71b3b1c5bf4967891f260039867/luigi/contrib/sqla.py#L342-L355

Here, the metadata is build with specifying the schema
https://github.com/spotify/luigi/blob/0d87424e9224b71b3b1c5bf4967891f260039867/luigi/contrib/sqla.py#L343
and here
https://github.com/spotify/luigi/blob/0d87424e9224b71b3b1c5bf4967891f260039867/luigi/contrib/sqla.py#L353-L354
the full table name, *including the schema* is used. Looking at the error it seems like its kind-of using the schema twice. Any thoughts? 

Thanks :)

**Comment by alexramos1** [comment]
using a mixed-case table name on Windnows causes this problem.
