### ISSUE TITLE
Luigi resources problem

### ISSUE THREAD

**Issue by giancarlosouza** [spotify/luigi#2389]
I am trying to limit the number of tasks that run in parallel with luigi, for example, I need that only 4 tasks that uses cassandra are allowed to run at the same time, but the other tasks that don't use it could run without any problems. I am having problems to make the resources on luigi work, maybe I am doing something wrong. I am using luigi version 2.5.0.
Here's how I am declaring the resources on my tasks:

> resources = {'cassandra': 2}

And on the luigi.cfg:

> [resources]
> cassandra: 8

With only that, it isn't working, but I think it should according to the documentation, or maybe I am missing something. Here's the message I receive:

> This progress looks :| because there were tasks that were not granted run permission by the scheduler

I got it working by adding this line on the luigi's worker source code, in the _add_task body:

> self._scheduler.update_resources(cassandra=8)

Any help would be appreciated.

**Comment by stolpovsky** [comment]
What's the deal with the colon in your luigi.cfg? Use "=", like so:

```
[resources]
cassandra = 8

```

**Comment by dlstadther** [comment]
@stolpovsky both `:` and `=` are valid for Python's ConfigParser

**Comment by giancarlosouza** [comment]
@stolpovsky Every example about luigi resources that I found was using the colon, but I also tried with the "=", and it didn't work as well.

**Comment by stolpovsky** [comment]
@giancarlosouza I was wrong about the colon, sorry for that.

**Comment by giancarlosouza** [comment]
@stolpovsky No problem, I tried your suggestion again just to be sure. If anyone could show me some simple example about resources that was actually tested it, with more than one resource for a task, I think it would be a lot of help.

**Comment by stolpovsky** [comment]
I set up a simple test, it works as expected. Can you try?

Create test_resources.py with the following contents, create dir structure like this:

- ~/luigi_workflows/
    - test_resources.py
    - test_output/ (empty dir)

```
import os
import time

import luigi

# To run:
# pythonpath=.. luigi --module=luigi_workflows.test_resources ManyMany --workers=100

class Sleep(luigi.Task):
    resources = {'foo': 10}

    fname = luigi.Parameter()

    def requires(self):
        []

    def full_path(self):
        return os.path.join(os.path.dirname(os.path.realpath(__file__)), 'test_output', self.fname)

    def run(self):
        time.sleep(1)
        with open(self.full_path(), 'w') as f:
            print('', file=f)

    def output(self):
        return luigi.LocalTarget(self.full_path())


class Many(luigi.WrapperTask):
    prefix = luigi.Parameter()
    n = luigi.IntParameter()

    def requires(self):
        for i in range(self.n):
            yield Sleep(fname='marker_{}_{}'.format(self.prefix, i))


class ManyMany(luigi.WrapperTask):
    n = luigi.IntParameter(default=20)

    def requires(self):
        for prefix in ['a', 'b', 'c']:
            for i in range(self.n):
                yield Many(prefix=prefix, n=self.n)

```

My config file's resources section looks like this:

```
[resources]
foo = 100

```

When I run, I can observe in LuigiTaskStatus graph that there are no more than 10 `Sleep` tasks running concurrently.

**Comment by stolpovsky** [comment]
Another thought: are you certain your client.cfg actually gets picked up? If it does not, then your `cassandra` resource has a value of 1 by default. Check that $LUIGI_CONFIG_PATH points to your client.cfg. To be sure, introduce an error into your client.cfg, bounce luigid and watch it fail. This will do it:

```
[DEFAULTS]
blah = 'blah'
```

Does it fail to start when you add this section to your config?

**Comment by giancarlosouza** [comment]
@stolpovsky So, I am testing your example, I made it work, but for that I had to export the LUIGI_CONFIG_PATH as you said, maybe that's the issue with my code, because I don't have anything in that LUIGI_CONFIG_PATH. 
When I run my luigi jobs, I modify the config on the code, like this:

```
config = luigi.configuration.LuigiConfigParser.instance()
config.add_config_path('~/luigi_workflows/conf/luigi.cfg')
```

I do that because there are many jobs with different configurations, so when the code of a specific job runs, it gets the respective configuration, and every configuration on it works, except the resources, maybe it just works when you have the LUIGI_CONFIG_PATH before executing the code?

**Comment by stolpovsky** [comment]
Note that both the scheduler `luigid` and workers `luigi` use the same config. If you specify it in your code, am I correct in assuming you only do it in the module you pass to `luigi`? The scheduler `luigid` needs to read the same config, so you would need to build your own `luigid` executable, or wrap it in a script where you export LUIGI_CONFIG_PATH. Unless you're doing this, your `luigid` runs with no config file, and your `cassandra` resource var defaults to 1.

**Comment by giancarlosouza** [comment]
@stolpovsky I get it now, testing my jobs with the LUIGI_CONFIG_PATH set, they worked as expected. I thought that only modifying the config on the require of the jobs was enough, but I understand now that the scheduler need the config for the resources beforehand. I was having soo many troubles because of those resources, thanks a lot!
