### ISSUE TITLE
contrib.kubernetes: Incompatibility with cluster auto-scaling and race conditions

### ISSUE THREAD

**Issue by himikof** [spotify/luigi#2407]
Issue #2334 introduced a use case where running a Job on a cluster with limited resources leads to "stuck" tasks, waiting for the needed cluster resources to appear. The PR #2335 then changed the behavior to fail immediately when containers are not all in ContainerCreating/Running state after creating the job.

This approach has the following problems:
- It is fundamentally incompatible with auto-scaling clusters. In such clusters, Unschedulable pods are normal - they are a signal to the cluster to spin up a few more VMs, which will handle the increased load (after they spend some time booting, of course).
- Many events in Kubernetes happen in an async way. For example, there is no guarantees that the job pods are already created after the job itself is finished creating, so expecting the pods to exist can fail due to a race condition.

I propose that due to async nature of Kubernetes the fast-failing should be an exception, not the norm. For example, #2334 could be solved in this way: if the user-specified setting says that the cluster is not auto-scaling AND there are any pods with condition["PodScheduled"].reason == "Unschedulable", fail fast.
And in other cases the luigi task should just patiently wait until the objects reach the desired state.

(There is a proposed progressDeadlineSeconds extension for jobs that can accurately detect jobs stuck in initialization, unfortunately, it is not yet implemented - kubernetes/kubernetes#58384)

@yonromai, what do you think?

**Comment by yonromai** [comment]
@himikof Thanks for raising this issue. Sounds good to me, feel free to PR
