### ISSUE TITLE
Redshit copytable never completed

### ISSUE THREAD

**Issue by AndresUrregoAngel** [spotify/luigi#2408]
I have done a very basic implementation to copy form an S3 location to redshift.

```python
import luigi
from luigi.contrib import redshift
class RedshiftCopy(redshift.S3CopyToTable):
    host = 'info'
    database = 'info'
    user = 'info'
    password = 'info'
    aws_access_key_id = 'info'
    aws_secret_access_key = 'info'
    table = 'info'
    copy_options = " info"
    s3_load_path ="info"

if __name__ == '__main__':
    luigi.run(['RedshiftCopy'])
```

At the end I get a message :  `Pid(s) {7762} already running` but in redshift never nothing happens

**Comment by dlstadther** [comment]
Verify a few things:
1) do you have a stalled query from a previous luigi process?
    * `select pid, trim(user_name), starttime, query from stv_recents where status='Running';`
2) do you have another instance of this luigi tasks running?
    * `ps -ef | grep 'python\|luigi'`

**Comment by rayrrr** [comment]
`luigi.build` might work better than `luigi.run` on the last line.
```
if __name__ == '__main__':
    luigi.build(['RedshiftCopy'])
```

**Comment by erikbern** [comment]
nice PR title 💩
