### ISSUE TITLE
MissingParameterException even though LUIGI_CONFIG_PATH is set?

### ISSUE THREAD

**Issue by silentsnooc** [spotify/luigi#2414]
I am having this `MainTask` which require `TransformToParquet`:
```python
class MainTask(luigi.Task):

    def requires(self):
        return TransformToParquet()

    def run(self):
        logging.info('All tasks done.')
        return

    def output(self):
        return self.requires().output()


if __name__ == '__main__':
    luigi.run()
    print('All done.')
```
This has two input paramters `input_file` and `output_hdfs_file`:

```python
class TransformToParquet(PySparkTask):

    input_file = luigi.Parameter()
    output_hdfs_file = luigi.Parameter()

    def requires(self):
        return []

    def output(self):
        return luigi.LocalTarget(self.output_hdfs_file)

    def run(self):
        sc = SparkContext(master=self.master, appName=TransformToParquet.__class__.__name__)
        convert_to_parquet(sc, self.input_file, self.output_hdfs_file)
```

I have a config file:

    [TransformToParquet]
    input_file=/media/data/subset_concatenated.txt
    output_hdfs_file=/media/data/transformed.parquet

which I am referring to via environment variable `LUIGI_CONFIG_PATH`.

However, I am getting

        raise parameter.MissingParameterException("%s: requires the '%s' parameter to be set" % (exc_desc, param_name))
    luigi.parameter.MissingParameterException: TransformToParquet[args=(), kwargs={}]: requires the 'input_file' parameter to be set

and I just can't see the problem especially since this used to work previously.

**Comment by Tarrasch** [comment]
Can you set it with command line or default path for the config-file? Perhaps you use luigi namespaces now?

**Comment by silentsnooc** [comment]
@Tarrasch My apologies - I found the problem ..

I had the following in my pom.xml


```xml
    <properties>
        <spring.boot.version>2.0.0.RELEASE</spring.boot.version>
    </properties>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.1.RELEASE</version>
    </parent>
```

I changed the version for the parent at some point but didn't change `spring.boot.version` accordingly. Setting both to the same version resolved the issue. 

I just wonder why things didn't get "worse" than FlywayDB just not running the SQL scripts but anyway. Setting both versions to 2.0.1.RELEASE solved the problem.

**Comment by silentsnooc** [comment]
@Tarrasch I will have to take a look at that tomorrow. I've tried to set it via command line but that didn't change anything. I'm not aware about namespaces - I don't think I'm using that.

**Comment by silentsnooc** [comment]
Okay, I was able to make this work. I'm not sure what the problem was but it's working again.
