### ISSUE TITLE
PostgresQuery does not honour `port`

### ISSUE THREAD

**Issue by maxalbert** [spotify/luigi#2416]
`PostgresQuery` fails when running a query against a PostgreSQL database on a non-standard port (other than 5432).

This is because the `PostgresTarget` which is the output of this task (and through which the DB connection is [established](https://github.com/spotify/luigi/blob/master/luigi/contrib/postgres.py#L362)) does not pass on the `port` argument (see [here](https://github.com/spotify/luigi/blob/master/luigi/contrib/postgres.py#L383)).

**Comment by dlstadther** [comment]
@maxalbert Feel free to submit a PR to enable support of passing non-standard ports for PostgresTarget/Query! Thanks

**Comment by maxalbert** [comment]
@dlstadther Thanks for the quick reply! The PR is #2417
