### ISSUE TITLE
Boto3 put_multipart AttributeError

### ISSUE THREAD

**Issue by dlstadther** [spotify/luigi#2421]
Found a bug here which wasn't caught before the merge of #2149:

```shell
Traceback (most recent call last):
  File "/home/user/venv/local/lib/python2.7/dist-packages/luigi/worker.py", line 203, in run
    new_deps = self._run_get_new_deps()
  File "/home/user/venv/local/lib/python2.7/dist-packages/luigi/worker.py", line 140, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/user/project/etl/base_task.py", line 192, in run
    self.client.put(self.src_fn, self.dst_fn)
  File "/home/user/venv/local/lib/python2.7/dist-packages/luigi/contrib/s3.py", line 252, in put
    self.put_multipart(local_path, destination_s3_path, **kwargs)
  File "/home/user/venv/local/lib/python2.7/dist-packages/luigi/contrib/s3.py", line 287, in put_multipart
    transfer_config = boto3.s3.transfer.TransferConfig(
AttributeError: 'module' object has no attribute 's3'
```

@ouanixi , do you have insight into what should be? (i haven't looked into it deeply, yet)

I'm using `boto3==1.7.4`

**Comment by ouanixi** [comment]
@dlstadther does `copy()` work for you ? That failing line of code is present in both `put_multipart` and `copy`

**Comment by ouanixi** [comment]
@dlstadther I cannot reproduce the error sorry !! Here's what I tried:
1- run the nonhdfs2.7 tests by making sure `boto3` is pinned to `1.7.4` in tox file and things passed fine.
2- setup a quick project by pip installing luigi from the repo (to make sure I'm using what's on master) and ran a quick task that was using S3Client's `put_multipart()` and again things worked just fine!!! Python version used is `3.6.4` with `boto3===1.7.4`
!!!!!!

**Comment by dlstadther** [comment]
Things learned:
1) don't submit a bug report at the end of the work-day (you won't be thinking clearly)
2) don't get carried away with copy/paste

The issue was 100% my fault. Output was a LocalTarget instead of a S3Target.

Sorry for the fire drill!

**Comment by ouanixi** [comment]
@dlstadther haha I've done a lot worse :)
