### ISSUE TITLE
DRMAA support

### ISSUE THREAD

**Issue by lucventurini** [spotify/luigi#2425]
Good afternoon,
                           I was wondering whether there are plans to integrate DRMAA into luigi, for seamless integration into various cluster environment.

Kind regards

**Comment by Tarrasch** [comment]
I've never heard of it. I imagine this is something organizations develop on their own and then open source after a year or so. Perhaps you'll have more luck asking in the mailing list?

**Comment by lucventurini** [comment]
This is the project: https://github.com/pygridtools/drmaa-python

In practice, it provides a cluster submission-agnostic way of coding. E.g. Snakemake uses it for job submission, making that workflow manager more flexible than Luigi for HPCs.
