### ISSUE TITLE
LocalFileSystem doesn't work with local URLs

### ISSUE THREAD

**Issue by jytug** [spotify/luigi#2429]
It would be useful to have `LocalFileSystem` work with local URLs, such as `file:///some/path`, not just with local paths.

**Comment by dlstadther** [comment]
Not sure of your use case, but if believed to be a valid and useful addition to Luigi __feel free to submit a PR__! All are welcome!

**Comment by jytug** [comment]
I mean a very simple modification to the class. It is frequent, when working with pyspark, to deal with local file URLs, such as the one I showed in the head post, especially within unit test suites, so it would be convenient to have methods such as `LocalFileSystem.listdir` yield results for urls as well, for instance:

```
>>> fs = luigi.LocalFileSystem()
>>> list(fs.listdir('file:///home/jytug/some_directory'))
['file:///home/jytug/some_directory/some_file.txt', ...]
```

I will open a PR, so that anyone with write permissions can decide if it's useful and should be included
