### ISSUE TITLE
Demos in docs are still using print XXX, how about using print(XXX) for better python3 support?

### ISSUE THREAD

**Issue by licuiwei** [spotify/luigi#2431]
I saw that Luigi says to be supporting both python2 and python3, but in the documents of [Running from the Command Line](https://luigi.readthedocs.io/en/latest/running_luigi.html), the demos are still using print in a way like "print self.x + self.y", which python3 doesn't support.
I'm using python3 and when I tried the demos, it gave me errors like this:
```
File "C:\python\my_module.py", line 9
print self.x + self.y
^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.x + self.y)?
```
So I think using "print(self.x+self.y)" instead may be better, because print() function is supported by both python2 and python3.
By fixing this, the docs and demos could be more friendly to beginners :).
PS. This "print" may also exist in other documents, I think these should all be fixed.

**Comment by dlstadther** [comment]
Feel free to submit a PR to update Demos for Python3 support
