### ISSUE TITLE
RangeWeekly and RangeMonthly

### ISSUE THREAD

**Issue by Casyfill** [spotify/luigi#2437]
In my case I have weekly and Monthly reports; 

I really like the way `luigi` uses:
`luigi --module all_reports RangeDaily --of AllReports --start 2015-01-01`,

but how can I use the same pattern for tasks with larger frequencies? 
I probably can create a custom class based on RangeDaily and just change timedelta(days=i) with timedelta(days=31), but then I won't be able to use luigi cli interface, right? shall I pr those two classes?

Another corresponding question - how can I marry those with `luigi.date_interval.Month` parameter classes? or shall I in this case generate them from date parameter within the task?

**Comment by robin-weiss-sm** [comment]
Hey there, 
I had the same problem and I just build my own classes and placed them in a utility module. You really only have to override the _finite_datetimes_ method when inheriting from RangeDaily.

I used Pandas date_range method and designed the Range classes to NOT include any incomplete week or month if the stop date is not end of week or month.

`
from luigi.tools.range import RangeDailyBase
import pandas as pd

class RangeWeekly(RangeDailyBase):
    """
    Run tasks for all weeks that are contained in the date range.
    Always take the last day (Sunday) and will leave out incomplete weeks.
    """

    def finite_datetimes(self, finite_start, finite_stop):
        """
        Simply returns the points in time that correspond to turn of week.
        """
        rng_idx = pd.date_range(finite_start, finite_stop, freq="W")
        rng = [x.to_pydatetime() for x in rng_idx.tolist()]
        return rng


class RangeMonthly(RangeDailyBase):
    """
    Run tasks for all months that are contained in the date range.
    Always take the last day of the month and leave out incomplete months.
    """

    def finite_datetimes(self, finite_start, finite_stop):
        """
        Simply returns the points in time that correspond to turn of month.
        """
        rng_idx = pd.date_range(finite_start, finite_stop, freq="M")
        rng = [x.to_pydatetime() for x in rng_idx.tolist()]
        return rng
`

Hope this helps :)

**Comment by Marabou** [comment]
Hello @robin-weiss-sm 

Could you show how you run tasks with RangeWeekly in the cli?

**Comment by Casyfill** [comment]
@robin-weiss-sm thanks, 
actually I have the same question as @Marabou

**Comment by robin-weiss-sm** [comment]
To be honest I don't ever run these range tasks from the CLI. It might be a problem because you can only specify one "--module" path if your tasks are split up into subfolders (as is my case).

What I end up doing is writing runner classes that run all my weekly aggregations. You could also just wrap your single use case in them I suppose.

```python
import datetime
import luigi
from luigi import date_interval

from tasks.utils import RangeWeekly
from tasks.visits.unique_visitors import UniqueVisitors


class RunWeeklyVisitsTasks(luigi.WrapperTask):
    # Default start date if not defined
    start_date = datetime.date(2017, 1, 1)
    # Range does not include last date, so range ends with but includes yesterday
    end_date = datetime.date.today()
    date_range = luigi.DateIntervalParameter(default=date_interval.Custom(start_date, end_date))

    def requires(self):
        range_params = {
            'param_name': 'date',
            'start': self.date_range.date_a,
            'stop': self.date_range.date_b,
            'days_back': 365,
            'task_limit': 365
        }

        yield RangeWeekly(of=UniqueVisitors, of_params={"taskParamA": "A", "taskParamB": "B"}, **range_params)
        # ... put any other weekly aggregations here
```

With "of_params" you can pass any params through to your actual tasks.

If you HAVE to use the CLI, I guess you could put the RangeWeekly task definition in the same python module as your 'runnee' task. If you name that file "tasks.py" , then it would end up something like

```bash
python -m luigi --module tasks RangeWeekly --start '2018-01-01' --stop '2018-11-12' --of MyTask  --param-name 'date' --task-limit 100 --days-back 100 --local-scheduler
```

Remember that if your "date" input parameter is named 'date' you'll have to change the "param-name" value in the CLI call.

Hope that helps.
