### ISSUE TITLE
Writing to S3 using S3Target and luigi.format.Gzip

### ISSUE THREAD

**Issue by jdcohen220** [spotify/luigi#2442]
I am wondering if someone has a working example of how to use the luigi.format.Gzip format on an S3Target. I have searched Google for hours with no luck. 

I have tried to write a simple task pipeline to do so which works correctly with UTF8 format, but when I pass the Gzip argument to the target constructor, I keep getting the following error:

> Exception ignored in: <bound method InputPipeProcessWrapper.__del__ of <luigi.format.InputPipeProcessWrapper object at 0x10cdca6a0>>
> Traceback (most recent call last):
>   File "/Users/jcohen/anaconda3/envs/rhpy35/lib/python3.5/site-packages/luigi/format.py", line 128, in __del__
>     self._finish()
>   File "/Users/jcohen/anaconda3/envs/rhpy35/lib/python3.5/site-packages/luigi/format.py", line 122, in _finish
>     raise RuntimeError('Error reading from pipe. Subcommand exited with non-zero exit status %s.' % self._process.returncode)
> RuntimeError: Error reading from pipe. Subcommand exited with non-zero exit status 1.

Below is the function I use to set up the target:

```
def s3_target(bucket, key, secret, base_dir, filename):
    """ Default S3 Client """
    s3client = S3Client(aws_access_key_id=key,
                        aws_secret_access_key=secret)
    return S3Target('%s%s%s' % (bucket, base_dir, filename),
                    format=luigi.format.Gzip,
                    client=s3client,
                    encrypt_key=True)
```

Example task pipeline:

```
BUCKET, KEY, SECRET = marketing_ops_bucket() #read in credentials from env vars


class InputFile(luigi.ExternalTask):
    """External task to read input file"""

    def output(self):
        filename = 'input.csv'

        return s3_target(BUCKET, KEY, SECRET, BASE_DIR, filename) #base dir is just the prefix we use for the bucket


class GetFile(luigi.Task):


    def requires(self):
        return InputFile()

    def run(self):

        with self.input().open('r') as input_file:
            names = next(csv.reader(input_file))
            fieldnames = [name.replace(' ', '_') for name in names]
            data = [row for row in csv.DictReader(input_file,
                                                  fieldnames=fieldnames)]

        with self.output().open('w') as f_open:
            dump(data, f_open)

    def output(self):

        job_name = 'test_write_gzip.json.gz'

        return s3_target(BUCKET, KEY, SECRET, BASE_DIR, job_name)
```

**Comment by ionwyn** [comment]
I believe the syntax is:

`luigi.s3.S3Target(S3_PATH, format=luigi.format.Gzip)`
