### ISSUE TITLE
Moving a LocalTarget does not change its attribute path

### ISSUE THREAD

**Issue by grauscher** [spotify/luigi#2447]
I have noticed that using `LocalTarget`'s `move` method, effectively changes its location on the local fs.
However, the `path` attribute of the `LocalTarget` object remains unchanged, thus, trying to remove it afterwards, by calling the `remove` method, does not work.

An example:
```python
# Instantiating an object
target = luigi.LocalTarget('/tmp/test.csv')
# Writing something to the file
with target.open('w') as fout:
    fout.write('asd')
# Renaming the file on the local fs
target.move('/tmp/test_2.csv')
# Raising an error, because the original file does not exist anymore:
target.remove()
```

The question is: Should the `path` of the object be updated after a `move` operation, thus "tracking" the object through the local fs?
If so, I'll be glad to submit a PR to solve this issue!

**Comment by Tarrasch** [comment]
Well, we're not going to change the behavior now as it would break so many instances.
