### ISSUE TITLE
Memory Error (Runtime Error)

### ISSUE THREAD

**Issue by 01123899** [spotify/luigi#2453]
Runtime error:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/luigi/worker.py", line 203, in run
    new_deps = self._run_get_new_deps()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/luigi/worker.py", line 140, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/luigi/contrib/external_program.py", line 107, in run
    stderr = self._clean_output_file(tmp_stderr)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/luigi/contrib/external_program.py", line 86, in _clean_output_file
    return ''.join(map(lambda s: s.decode('utf-8'), file_object.readlines()))
MemoryError

**Comment by veyu** [comment]
I would say this is issue with program which you are executing through `ExternalProgramTask`.
Line which results in `MemoryError` takes all program output from `stdout` or `stderr` and creates one big string from it. If you print a lot of data in `stdout` or have a lot of error messages in `stderr` it could be bigger then available memory.

**Comment by 01123899** [comment]
I found out that  this is not the real problem, I am gonna open other issue, thanks @veyu

**Comment by 01123899** [comment]
thank @veyu So do you think that it is not possible with luigi? or Can I change that configuration? Or maybe a bigger server?

**Comment by kwilcox** [comment]
It's is difficult to answer your questions without a better understanding of the problem. 

1. You need to run an external program
2. Said program generates lots of stdout and/or stderr

Do you require the stdout or stderr of the program? If not, try calling it directly through python's subprocess module. You could write the exit code to a file and check that in a custom `complete` method.
