### ISSUE TITLE
request version of luigi.interface.run() with return codes

### ISSUE THREAD

**Issue by arc12** [spotify/luigi#2456]
As I understand the current state of affairs, a CLI invokation will give return codes according to the [retcode] setting in luigi.cfg BUT if we use luigi.run() from Python then we get a true/false return for "success"

It would be helpful (and consistent) to have access to return codes when using luigi.run(), or a similar entry point.

**Comment by Tarrasch** [comment]
Can you use the [retcodes](https://github.com/spotify/luigi/blob/5f156492e4c873000aeeb0b8a7d77062efd73de6/luigi/retcodes.py) module directly? Feel free to send a PR with docs or improvments to the retcode api.
