### ISSUE TITLE
Segmentation Fault problems on OS X

### ISSUE THREAD

**Issue by jamesmcm** [spotify/luigi#2460]
Hi,

I am having issues with Segmentation Faults when running on OS X, it's the same issue as mentioned here: https://stackoverflow.com/questions/32978429/python-luigi-died-unexpectedly-with-exit-code-11

I run the task simply, with no additional workers, etc.:

```
PYTHONPATH="." luigi --module tasks TaskName --date 2018-07-13 --local-scheduler
```

But then fails:

```
2018-07-13 19:25:02 - Task SubTask_2018_07_13_23988_12796bfc6b died unexpectedly with exit code -11
INFO: Task SubTask_2018_07_13_23988_12796bfc6b died unexpectedly with exit code -11
```
By adding some debug lines, it seems the issue is making a POST request with the requests module:

```
req = requests.post(... )
```

Strangely it works fine on our Ubuntu server - exactly the same task files and dependencies.

This is driving me crazy, so it'd be great if anyone has any ideas of how to better debug it. ipdb doesn't work, as it seems it must be running in a subprocess or something.

The only thing unusual is the warning at the start of running the task, which only appears on OS X:

```
/Users/jamesmcm/anaconda3/lib/python3.6/site-packages/luigi/parameter.py:261: UserWarning: Parameter "task_process_context" with value "None" is not of type string.
  warnings.warn('Parameter "{}" with value "{}" is not of type string.'.format(param_name, param_value))
```

**Comment by repejota** [comment]
I see the same but as ERROR log:

```
ERROR:root:/usr/lib/python3.6/site-packages/luigi/parameter.py:261: UserWarning: Parameter "task_process_context" with value "None" is not of type string.
```

Your commit @HennyH fixes the problem. Could you consider to create a PR on this repo?

**Comment by jamesmcm** [comment]
Nice, but I doubt that's the issue causing the segfaults. Nevertheless, I'll try with that patch next week.

**Comment by HennyH** [comment]
@jamesmcm You're right my commit was unrelated to the segmentation faults but I came across this issue because I was receiving the same warning. (Didn't know referencing the issue number in my repository would include me in this comment! Was surprised haha). To me allowing the default value seems sensible (though perhaps the constructor of the Parameter should ensure that the default is `parse(serialize(_default)) == _default` or otherwise the user could have accidently provided an incompatible default...)

**Comment by Esfahan** [comment]
I see the same as UserWarning on CentOS 7.3 and Python 2.7.5.

```
/usr/lib/python2.7/site-packages/luigi/parameter.py:261: UserWarning: Parameter "task_process_context" with value "None" is not of type string.
  warnings.warn('Parameter "{}" with value "{}" is not of type string.'.format(param_name, param_value))
```

**Comment by ktran9891** [comment]
I am seeing the same thing. I'm using a Ubuntu 18.04 docker container.
```
/miniconda3/lib/python3.6/site-packages/luigi/parameter.py:284: UserWarning: Parameter "task_process_context" with value "None" is not of type string.
  warnings.warn('Parameter "{}" with value "{}" is not of type string.'.format(param_name, param_value))
```

**Comment by bryanpjohnson** [comment]
Regarding the segmentation faults, I think this happens on Mac OSX when forked threads call _scproxy.so, triggering dispatchlib, which is not fork safe.

A possible workaround is calling Luigi using an environment with no_proxy set to '*'.
