### ISSUE TITLE
luigi.Task.on_failure and luigi.Task.on_success vs. luigi.Event.FAILURE and luigi.Event.SUCCESS

### ISSUE THREAD

**Issue by DrPyser** [spotify/luigi#2470]
@freider 
@erikbern
 
Hi.

To react to the success or failure(raised exception) of a task, there seems to be two ways:
* `on_failure` and `on_success` methods of `luigi.Task`
* event handlers for `luigi.Event.FAILURE` and `luigi.Event.SUCCESS` events

Is one of those preferable, and will one eventually be deprecated?

Also, it would be great to have a bit more documentation on the event system(e.g. what information is passed for each event, and the signature of the event handlers).

Thank you all for the great work!

**Comment by dlstadther** [comment]
Hi @DrPyser . Thanks for bringing your concern! I'm not immediately sure of the answer to your questions. But a good start may be to view the git blame for those sections of code and mention those Github users here.

Regarding the minimal documentation on the event system, feel free to contribute back with any information you believe to be helpful for varying levels of Luigi users/developers!

**Comment by DrPyser** [comment]
Cool, added the mentions.

**Comment by dlstadther** [comment]
Ah, didn't realize these were OG-author contributions. @erikbern and @freider are both very busy and not likely to respond [quickly].

I'll see what time i can spare this week to attempt to provide an answer.

Any chance you know, @Tarrasch ?

**Comment by Tarrasch** [comment]
I haven't used it either, but an event system surely makes sense. @DrPyser, I would do this:

 * Check the mailing list for other users, maybe contact them. Alternatively just mail and ask for existing users and their experience.
 * Look at the blame's to see which one was addest the latest.
 * My intuition however is that `luigi.Event.FAILURE` is the more modern way.

Sorry that I can't be of more help!
