### ISSUE TITLE
RedshiftQuery doesn't set port 

### ISSUE THREAD

**Issue by gregroberts** [spotify/luigi#2473]
by default, when tasks from luigi.contrib.redshift have `RedshiftTarget` as an output, they do not set the port. e.g. in RedshiftQuery:

`    

    def output(self):
        """
        Returns a RedshiftTarget representing the executed query.
        Normally you don't override this.
        """
        return RedshiftTarget(
            host=self.host,
            database=self.database,
            user=self.user,
            password=self.password,
            table=self.table,
            update_id=self.update_id
        )
`

RedshiftTarget is based on PostgresTarget.
So if your redshift host doesn't include the port, these Tasks will fail, because they will default back to 5432. 
so if your Redshift instance is running on the default port, your tasks will fail until you explicitly override the output method, passing the port to the RedshiftTarget constructor.

Not a massive issue, for sure, but for consistencies sake, this ought to be changed.

**Comment by dlstadther** [comment]
Can you not just specific the port with `<host>:<port>` and it be extracted within [PostgresTarget's __init__()](https://github.com/spotify/luigi/blob/master/luigi/contrib/postgres.py#L125-L129)?

**Comment by gregroberts** [comment]
Thats true. I guess I'm just being pedantic because it means you have to
format the arguments differently for different databases.

**Comment by gregroberts** [comment]
By default surely the preferable behaviour is for the task to behave
equivalent to PostgresQuery, and just using the default Redshift port?

**Comment by dlstadther** [comment]
If you have a non-breaking code recommendation to enable the optional ability to provide explicit port, i'll review!

**Comment by gregroberts** [comment]
Will get on that tomorrow :)
