### ISSUE TITLE
botocore is a hidden dependency when using luigi.contrib.sge

### ISSUE THREAD

**Issue by mivade** [spotify/luigi#2479]
I am not using `luigi.contrib.s3` but nevertheless it tries to get imported:

```pytb
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    from luigi.contrib.sge import SGEJobTask
  File "/home1/depalati/src/luigi/luigi/contrib/sge.py", line 104, in <module>
    from luigi.contrib.hadoop import create_packages_archive
  File "/home1/depalati/src/luigi/luigi/contrib/hadoop.py", line 54, in <module>
    import luigi.contrib.s3
  File "/home1/depalati/src/luigi/luigi/contrib/s3.py", line 35, in <module>
    import botocore
ModuleNotFoundError: No module named 'botocore'
```

`create_packages_archive` looks useful and generic enough that it should live somewhere other than `luigi.contrib.hadoop`.

**Comment by mivade** [comment]
One common pattern is to have some top-level `utils` module that collects things like `create_package_archive` that don't necessarily fit anywhere else. The danger with this approach is that this can make `utils` a catchall for just about anything.

**Comment by dlstadther** [comment]
There is currently a `luigi/util.py` so it seems reasonable to have a `luigi/contrib/util.py` that we carefully allow code into.
