### ISSUE TITLE
Use of KerberosClient with webhdfs

### ISSUE THREAD

**Issue by pietermarsman** [spotify/luigi#2481]
Currently webhdfs uses InsecureClient by default. However, the hdfs package also has an KerberosClient which can be used to do authenticated requests. 

Our hdfs system uses Kerberos and I would like it if KerberosClient is added as an option. 

The KerberosClient does not need any additional settings (as far as I can test). And thus only an additional parameter is needed: `use_kerberos_client`. 

Are you willing to accept a pull request for this?

**Comment by dlstadther** [comment]
I, personally, do not use the HDFS/Hadoop side of Luigi. But so long as your suggested PR doesn't change the default behavior, please feel free to submit for review!

**Comment by Tarrasch** [comment]
> Are you willing to accept a pull request for this?

Yep, for sure.

**Comment by pietermarsman** [comment]
I've added some documentation and tested it on a cluster with kerberos authentication: it works!
