### ISSUE TITLE
TimeParameter class

### ISSUE THREAD

**Issue by grisaitis** [spotify/luigi#2485]
I have a use case where I want to parameterize a task by clock time. I don't see any Parameter classes using `datetime.time` as a value -- just `datetime.date` and `datetime.datetime` values. 

Has this been considered before? 

To clarify, The datetime parameters like `DateHourParameter` are overkill for me because I don't need the date portion, just the time.

**Comment by dlstadther** [comment]
I'm not sure I'm following the need here. Could you provide an example for where you'd need `datetime.time` and not `datetime.datetime`?

**Comment by grisaitis** [comment]
Borrowing from the `AggregateArtists ` example in the docs, let's say I want to know who the top artist is at 8am... not on a certain day, but aggregated by month, for example.

**Comment by Tarrasch** [comment]
Do you really care to do "logic" on this "8am" value? If not I think it makes more sense to give it a name such as "morning".

**Comment by miku** [comment]
@grisaitis, it would probably be not too complicated to create a custom parameter type in your application yourself (and override [parse](https://github.com/spotify/luigi/blob/a87266d78fd97fde69d1b86c0af390391f2ce307/luigi/parameter.py#L241-L251)). Here is an [example gist](https://gist.github.com/miku/3cea1abed8e392ed7b97630d28873298). You could use [dateutil](https://dateutil.readthedocs.io/en/stable/) to outsource time parsing and only consider, e.g. the hour as important:

```python
from luigi.parameter import Parameter
from dateutil.parser import parse

class TimeParameter(Parameter):
    """
    Consider only time of day.
    """

    def parse(self, value):
        """
        Parse various time formats into a time value, e.g. 8AM or 08:00
        """
        return parse(value).hour
```

That said, I would vote to close this issue, as it seems to be easily implemented outside luigi - as far as I understand it.
