### ISSUE TITLE
Install issues caused by `python-daemon`

### ISSUE THREAD

**Issue by EdMan1022** [spotify/luigi#2494]
Just a heads up, the `python-daemon` package was updated from 2.1.2 to 2.2.0, and for some reason, in some instances, `setuptools` doesn't properly handle a `docutils` requirement. Since the python-daemon requirement for luigi is only `python-daemon<3.0`, I'm having builds that previously passed fail. If anyone else has this issue, you can easily fix it by either manually specifying docutils in the requirements, or by explicitly setting `python-daemon==2.1.2`

[python-daemon repository](https://pagure.io/python-daemon)
[Issue for problem on python-daemon repo](https://pagure.io/python-daemon/issue/18)

**Comment by swardlincoln** [comment]
Having the same issue. Thanks for the work around.

**Comment by dlstadther** [comment]
Thanks for raising @EdMan1022 !

Feel free to submit a PR to resolve this - either link a specific 2.1.2 version or add docutils. I'll leave the details of the solution up to the submitter :)

**Comment by EdMan1022** [comment]
I'm not sure if there should be a change to the luigi requirements for this. I couldn't replicate the issue in my local environment, although admittedly I didn't try too hard to do so. So it's either some strange OS specific thing causing it, or it could have something to do with the version of `setuptools` or `pip` being used. Either way, I'd be worried about locking the package to a minor version, since that makes the install process less flexible, and there might be useful changes introduced later in the `python-daemon` package. I'd also hesitate to add `docutils` to the requirements, since it's really only needed during the install process for `python-daemon` and could bloat production images. If a lot of other users seem to hit this issue, and the person responsible for `python-daemon` doesn't figure out some sort of hotfix on their side, then I'd open a PR.

**Comment by chaspy** [comment]
I have the same issue. thanks.

**Comment by dlstadther** [comment]
@EdMan1022 Since you believe this might be some other cause, could you denote your OS/setuptools/pip versions where having issues?

**Comment by pybokeh** [comment]
I hope with Luigi's dependence on python-daemon, that doesn't mean Luigi may no longer work on Windows.  Please keep Luigi cross platform!  I have been using Luigi because Apache Airflow does not work on Windows.

**Comment by swardlincoln** [comment]
Is there any update on this issue? I'm still running into this problem and using the specific python-daemon lib (2.1.2) in my requirements.txt to get around the problem.

**Comment by honnix** [comment]
Will do a release very soon to push out #2536. If possible please help verify and close the issue. Thanks! @EdMan1022

**Comment by honnix** [comment]
Released 2.7.9.
