### ISSUE TITLE
contrib.ecs with launchType and networkConfiguration parameters

### ISSUE THREAD

**Issue by akddv** [spotify/luigi#2497]
I am a user of contrib.ecs but I find that I cannot launch my tasks without defining the two following parameters:

```
launchType='EC2'|'FARGATE',
networkConfiguration={
'awsvpcConfiguration': {
    'subnets': [
        'string',
    ],
    'securityGroups': [
        'string',
    ],
    'assignPublicIp': 'ENABLED'|'DISABLED'
}
}
```
(the above is taken from boto3 ECS.Client.run_task [documentation](https://boto3.readthedocs.io/en/latest/reference/services/ecs.html#ECS.Client.run_task))

Would it be possible to expose those from the contrib.ecs interface? Or did I miss something?

**Comment by dlstadther** [comment]
Hey @akddv ! Thanks for being a luigi user and coming here for clarity!

I'm not an ECS user myself, but after a quick look at `luigi/contrib/ecs.py` it looks like you'll need to contribute the ability to tack on additional ECS client attributes.

Feel free to open that PR and I'm happy to review!

**Comment by akddv** [comment]
Cool, I have just put in a PR.
It is my first time writing Python or using Github, I hope I am not breaking anything... Let me know.

**Comment by akddv** [comment]
Closing, no longer needed, as I moved to contrib.kubernetes.

**Comment by walkingpendulum** [comment]
Hi guys! I've just run into same issue and have no an option for moving to contrib.kubernetes. As I can see PR already made and approved except there is no test for proving functionality actually works because -- correct me if I wrong -- there isn't such mock functionality support in test framework.

I don't know how to push this issue further to the happy end but some good will from @dlstadther will be appreciated :)

**Comment by walkingpendulum** [comment]
Actually I would prefer to make new luigi.Parameter `run_task_kwargs` and unpack its content to boto3.client::ecs::run_task method.

Should I remake PR or should I make new one?

**Comment by dlstadther** [comment]
@walkingpendulum Feel free to copy the PR and open your own with your desired modifications and tests :)
