### ISSUE TITLE
contrib.ecs does not check container exit code

### ISSUE THREAD

**Issue by akddv** [spotify/luigi#2500]
I would like to add opt-in support for checking exit code of containers launched with the class ECSTask. The idea would be to do something similar to the class ExternalProgramTask which raises a RuntimeError exception if the task return code is non zero. Is raising such exception the right thing to do in case of failure?

**Comment by dlstadther** [comment]
Makes sense to me. Feel free to submit a PR!

**Comment by akddv** [comment]
Closing, no longer needed, as I moved to contrib.kubernetes.
