### ISSUE TITLE
Inserting JSON data into postgres target fails

### ISSUE THREAD

**Issue by ademus4** [spotify/luigi#2505]
I get errors about the quote marks being invalid JSON when trying to insert rows into a postgres database. The error is correct in the sense that the dictionary returned by the task is not valid JSON, however there is seemingly nothing I can do to correct this. Example code:

```
class TestJobToDB(postgres.CopyToTable):
    ...
    def rows(self):
        with self.input()['test_job'].open('r') as f:
            data = json.loads(f.read())

        for item in data:
            yield item['name'], item['data'], item['model_id']
```
The input data for this looks like the following:
```
[{"name": "Fish", "data": {"x": "45", "y": "55", "result": 100.0}, "model_id": 3}]
```
If I run that task, I get the following error:
```
psycopg2.DataError: invalid input syntax for type json
DETAIL:  Token "'" is invalid.
CONTEXT:  JSON data, line 1: {'...
COPY thing, line 1, column data: "{'x': '45', 'y': '55', 'result': 100.0}"
```
There is nothing I can control to beyond the part where I yield the dictionary, thus a problem with how the ORM is dealing with the data?

**Comment by dlstadther** [comment]
I have not utilized the JSON copying ability of Postgres nor Redshift so I have not directly encountered this issue before. However, I'd be happy to review a PR to resolve this issue :) Feel free to submit!

**Comment by ademus4** [comment]
Unfortunately I don't have much time for that right now, I may give it a go in the near future if no one else tries! Thanks for the response
