### ISSUE TITLE
temporary path context manager fails sometimes because folder is still locked

### ISSUE THREAD

**Issue by simonm3** [spotify/luigi#2513]
I have a pipeline with one stage where the output is a bcolz file which is actually a folder containing thousands of files. I have wrapped it in the temporary path context manager which  works as expected most of the time. However sometimes on windows when the context manager tries to rename the folder I get "permission denied" error and the job fails . If I manually rename and rerun the job it starts from where it left off and completes successfully. 

It appears that windows still has a lock on the folder. A workaround I am trying is to make multiple attempts to rename the folder. Then I have to rename it back and let the context manager do the real rename. However I think the context manager should be able to handle this or to use some other way to force the file to be released.

**Comment by Tarrasch** [comment]
What should luigi do if the folder is locked you think? Normally I imagine that if the folder is locked that indicates that whatever writes to it isn't finished, and then i probably want that luigi task to explode so I can debug that case. Let me know if you have an idea for a fix, otherwise this can be closed right?

**Comment by simonm3** [comment]
I am not sure why it happens but it is probably that the os is still
closing the file; or maybe something is accessing the file such as a virus
checker maybe? It is frustrating that it fails as this is a temporary file
created by this process so should be available.

I added the function below. However it still failed when luigi did its
rename. I think best solution is for luigi to do similar i.e. "sleep and
retry" a few times.

def release_lock(path):
    """ ensures path unlocked for temporary_path context manager

    Sometimes paths on windows are not ready immediately on creation
    """
    for x in range(10):
        try:
            os.rename(path, path+"_")
            break
        except:
            log.warning(f"{path} locked. retrying")
            sleep(1)
    for x in range(10):
        try:
            os.rename(path+"_", path)
            break
        except:
            log.warning(f"{path} locked renaming back. retrying")
            sleep(1)

**Comment by simonm3** [comment]
Another complexity is that it is a bcolz file, which is a folder made up of
many files; and is being written by pytorch predict which does use
multiprocessing (though luigi is set to single worker to avoid conflict).
On the other hand as the rename in my "release_lock" function works perhaps
it is not a file issue at all but some other resource issue or timeout. It
is hard to isolate as it happens so rarely but when running thousands of
jobs it shows up. Simplest fix would be when there is a failure to wait a
few seconds and retry.

**Comment by Tarrasch** [comment]
> I think best solution is for luigi to do similar i.e. "sleep and retry" a few times. 

Those kind of complicated solutions are maybe not of general interest. I mean many could benefit from it, but many more would loose on adding that complexity to luigi.

**Comment by simonm3** [comment]
I am still getting this error....only on one task in 100 but it is annoying. It means that the temporary_path context manager is not reliable. Does not have to be complicated. I am currently testing as below - though hard to test as it is a rare event.

If this were part of the context manager it would less lines. Also I have to repeat it for every task. Why would it inconvenience anyone? Would only execute if there is an error.

 ```
 try:
         with self.output().temporary_path() as f:
                job.prepare_data(f)
        except PermissionError:
            # Retries after unexplained windows permission error. happens on 1/100 jobs.
            for x in range(3):
                log.warning("permission error renaming temporary_path file. retrying.")
                sleep(5)
                try:
                    self.output().fs.rename_dont_move(f, self.output().path)
                    break
                except:
                    pass
```
