### ISSUE TITLE
Unable to connect to visualizer on remote host

### ISSUE THREAD

**Issue by nickymikail** [spotify/luigi#2520]
The issue arose suddenly this morning. Making requests to our EC2 hosted scheduler timeout. I SSH'd to the EC2 instance and tried `curl --trace-ascii dump.txt localhost:8082` and get the following output

```
== Info: Rebuilt URL to: localhost:8082/
== Info:   Trying 127.0.0.1...
== Info: Connected to localhost (127.0.0.1) port 8082 (#0)
=> Send header, 78 bytes (0x4e)
0000: GET / HTTP/1.1
0010: Host: localhost:8082
0026: User-Agent: curl/7.47.0
003f: Accept: */*
004c: 
== Info: Recv failure: Connection reset by peer
== Info: Closing connection 0
```
luigi (2.7.8)
tornado (4.5.3)

Not sure which other packages would be useful for diagnostic purposes.

**Comment by dlstadther** [comment]
@nickymikail Is this still an issue for you?

**Comment by nickymikail** [comment]
It is not. We killed the running luigi daemon process and restarted a new one, and it all works now. Thanks for checking back!
