### ISSUE TITLE
When upgrading beyond luigi 2.7.6 a part of the API breaks

### ISSUE THREAD

**Issue by jgb** [spotify/luigi#2522]
Hello,

we have a part of our code which does a call to http://127.0.0.1:xxx/api/task_list
This works fine on luigi <= v2.7.6 but it breaks with a HTTP/1.1 500 Internal Server Error when we upgrade to luigi v2.7.7 or v2.7.8

We're using:

tornado 4.5.3
python 2.7.12
ubuntu 16.04

Any ideas on what could be wrong?

Thanks!

**Comment by dlstadther** [comment]
[Here](https://github.com/spotify/luigi/compare/2.7.6...2.7.7) are all the commits between version 2.7.6 and 2.7.7. I don't have the time resource right now to investigate further. But please take a look here and check if a specific commit appears to impact `/api/task_list`.

Thanks for raising this issue!

**Comment by jgb** [comment]
I've just confirmed that the bug still exists in the newest version 2.7.9

**Comment by dlstadther** [comment]
Feel free to contribute back a fix! :)

**Comment by jgb** [comment]
I had a look at the commits, but unfortunately there's nothing which seems immediately suspicious to me, sorry :disappointed:

**Comment by dlstadther** [comment]
Hey @jgb , I have the following
* luigi (bleeding edge; > 2.7.9)
* tornado==4.5.3
* python 2.7.15
* Mac OSX 10.13

And am able to hit http://127.0.0.1:xxxx/api/task_list with the successful response `{"response": {}}`.

However, if i hit http://127.0.0.1:xxxx/tasklist , i get a 500 with the logged stack trace

```
2018-10-02 13:06:03,546 tornado.application[82384] ERROR: Uncaught exception GET /tasklist (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8082', method='GET', uri='/tasklist', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': '127.0.0.1:8082', 'Accept': '*/*', 'User-Agent': 'curl/7.54.0'})
Traceback (most recent call last):
  File "/Users/dstadther/venv/luigi/lib/python2.7/site-packages/tornado-4.5.3-py2.7-macosx-10.13-x86_64.egg/tornado/web.py", line 1510, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/dstadther/luigi/luigi/server.py", line 95, in get
    all_tasks = self._scheduler.task_history.find_all_runs()
AttributeError: 'NopHistory' object has no attribute 'find_all_runs'
```

Not sure where you have your logs pointing, but this one is called `luigi-server.log`.  If you're able to, could you look at it and paste a clean/safe version of the error stack trace here?

**Comment by jgb** [comment]
Well, to make a long story short, I deleted the luigi state pickle file, and that solved the issue for me!

**Comment by dlstadther** [comment]
Interesting... Well, i'll close this issue given the unknown source. But if you find this to reoccur in the future, please open a new issue with a stack trace :)
