### ISSUE TITLE
Documentation for using a config file within code

### ISSUE THREAD

**Issue by Alex-picwell** [spotify/luigi#2524]
There is an example that shows you being able to trigger pipelines from within code that is simple enough passing parameters in to some very basic tasks: https://luigi.readthedocs.io/en/stable/running_luigi.html#running-from-python-code

Now going a single step further is seemingly quite difficult to configure. I just want to run a Task, that depends on a single other Task. From all the digging I've been doing on the documentation and code I cannot pass that information through the one Task as params (without code modification to give the one task params it won't need to use, just pass on), and I'm really struggling to get the configuration file working this way as well. 

https://luigi.readthedocs.io/en/stable/configuration.html This section doesn't describe how to make the leap from having a config file, putting it into the `LUIGI_CONFIG_PATH` environment variable, and then somehow being able to use that dictionary from within code, as it doesn't appear to "just work".

Any help would be appreciated, and it seems like I'm not the only one as others I've talked to opted for using pdb to debug from the command line instead as a workaround. I want to use PyCharms nice debugger. Just expanding one of those two pages to be a bit more explicit on this functionality (which I assume is already written as its something that would obviously be wanted) would be enough.

```python

```

**Comment by Alex-picwell** [comment]
Hey thanks for that, I had found the way to do what I was aiming for, it was as simple as I had thought it must be:

```
config = luigi.configuration.get_config()
config.read('/path/to/the/config.cfg')
luigi.build([SomeTaskThatRequiresOtherTasks()], local_scheduler=True)
```

I'm not sure what made the environment variable not work, but this accomplished the same from within Python which I like better. Thanks!

**Comment by dlstadther** [comment]
Closing this since you appear to have acquired what you needed!

**Comment by tashrifbillah** [comment]
I am facing the same problem, although `LUIGI_CONFIG_PATH` is set up, the parameters are not loaded from that file. @Alex-picwell , did you continue experiencing this?

**Comment by tashrifbillah** [comment]
So, I realized something else that might be relevant to this issue.

Having a `[DEFAULT]` section in config file is not enough for tasks to acquire values defined there. The config file should also have sections for each task, even though they are empty.

```python
[DEFAULT]
a: hello

# although empty, this section is required
[TaskB]


[TaskC]
c: world

[TaskD]
d: cheers
e: happy
```

The above config file will not pass default parameters to `TaskB`, unless we keep an empty section for `TaskB` like above.

**Comment by mivade** [comment]
I found this while trying to figure out how to load a custom configuration file in unit tests. How the configuration gets loaded should probably be better documented since it's still not clear that there are magical incantations needed to load when not running a workflow from the command line.
