### ISSUE TITLE
502 Bad Gateway error tied to public_params

### ISSUE THREAD

**Issue by kockockockoc** [spotify/luigi#2535]
Update from luigi-2.7.5 to 2.7.8 and we do save state in a pickle file.

@Gr1f0n6x , does it look like https://github.com/spotify/luigi/issues/2507 ?

```

2018-09-26 14:43:21,542 tornado.access[40044] ERROR: 500 GET /api/task_list?data=...
    Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/web.py", line 1467, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/lib/python2.7/site-packages/luigi/server.py", line 77, in get
    result = getattr(self._scheduler, method)(**arguments)
  File "/usr/lib/python2.7/site-packages/luigi/scheduler.py", line 1430, in task_list
    serialized = self._serialize_task(task.id, include_deps=False)
  File "/usr/lib/python2.7/site-packages/luigi/scheduler.py", line 1284, in _serialize_task
    'display_name': task.pretty_id,
  File "/usr/lib/python2.7/site-packages/luigi/scheduler.py", line 351, in pretty_id
    param_str = ', '.join(u'{}={}'.format(key, value) for key, value in sorted(self.public_params.items()))
AttributeError: 'Task' object has no attribute 'public_params'
```

**Comment by Gr1f0n6x** [comment]
@kockockockoc Yes, it is exactly the same probem :(
At this moment you can fix it manually or make a git cherry-pick this commit: ` 2c98b5667c8d66c6975687f9f78b414a0709c275`
https://github.com/spotify/luigi/pull/2509/commits/2c98b5667c8d66c6975687f9f78b414a0709c275

**Comment by kockockockoc** [comment]
Hmm, this issue similar but not quite the same, IMHO: "param_visibilities" vs "public_params"

**Comment by Gr1f0n6x** [comment]
@kockockockoc yes, you're right. 
Probably, for backward compatibility we need to add something like that:
```
if hasattr(self, public_params):
    param_str = ', '.join(u'{}={}'.format(key, value) for key, value in sorted(self.public_params.items()))
else:
    param_str = ', '.join(u'{}={}'.format(key, value) for key, value in sorted(self.params.items()))
```

And also in this part: `'params': task.public_params,` for reliability.
Shame on me, but i didn't expect errors like that :(

I'll take a look in this issue more precisely tomorrow
