### ISSUE TITLE
Fix type warnings of parameters

### ISSUE THREAD

**Issue by pietermarsman** [spotify/luigi#2542]
I'm using PyCharm and it helps me by displaying warnings about all kinds of possible problems. One such a warning is if a variable with the wrong inferred type is passed to a function. This warning is triggered for all Luigi parameters, since PyCharm infers that these are of class `Parameter` and not, for example, of class `int`.

**Example**
```
class Square(luigi.Task):
    number = luigi.IntParameter()

    ...

    def run(self):
        square = math.square(self.number)
```

PyCharm knows that `math.square` is expecting a number, and that `luigi.IntParameter` is not a number, so it gives a warning that the wrong type is put into the `round` function.

**Solution**

I think this can be fixed without to much trouble. If `IntParameter` extends the `int` class besides extending the `Parameter` class the warnings go away. Similarly, `Parameter` could extend `str`, `DateParameter` could extend `datatime.datetime`, `DictParameter` could extend `dict`, etc. 

Besides fixing the warnings in PyCharm, this is also more explicit. Before luigi does the magic of filling in a parameter the variable behaves as a `Parameter`, but after that it behaves as a `str` (or alike). Explicitly saying this makes people more aware of this behaviour. 

**Fix it?**

What do you think of this? Do you see any unwanted side-effects? Are you willing to accept a pull request for this?

**Comment by pietermarsman** [comment]
> Are you willing to accept a pull request for this?

**Comment by dlstadther** [comment]
Sorry in my neglect to address this! Absolutely!

This has been a minor nit i've had so long as I've used Luigi. It would be great to remove these false warnings! Be sure to add tests :)

**Comment by pietermarsman** [comment]
I cannot get this to work. My original idea does not work. If I add `int` to the parent classes of `IntParameter` python raises errors about additional given parameters that are not used by `int`. For example, the `default` parameter (for __init__ of `IntParameter`) is not used in `int`. 

I also tried to use the new `typing` module, but that is not available in python <3.7. I also tried to add type hints in comments, but that does not work for classes. 

I did find a manual alternative:

```
class Square(luigi.Task):
    number = luigi.IntParameter()  # type: int

    ...

    def run(self):
        square = math.square(self.number)
```

I haven't got any other ideas. Does someone else have another ideas on how I should approach this? Otherwise this issue can be closed until further notice.

**Comment by kwilcox** [comment]
What about `# noqa` on the IntParameter line?

**Comment by DrPyser** [comment]
Yes, subclassing builtins like int(or tuple, str, ...) requires overriding `__new__`.

I'm not convinced this is the right way to go, though. The real problem is that the luigi parameters are defined as class attributes, while the actual parameter values are instance attributes. Without hinting the type of the instance attributes, type checkers assume their type is the same as the class attribute. 

If luigi parameters attributes were annotated with e.g. `ClassVar[LuigiParameter]`, I think typecheckers should at least understand that instance attributes won't have the type declared on the class attribute. But then I don't know of a way to also specify the instance attribute type.

**Comment by DrPyser** [comment]
Something to investigate is using the descriptor protocol: https://github.com/python/mypy/issues/4472. 
After experimenting with this, using `@overload` signatures doesn't seem to help pycharm. But you can get the attribute to typecheck as a `Union[IntParameter, int]` for example, which is a bit better I guess.

**Comment by alwaysmpe** [comment]
I found this issue because I had the exact same problem. To share my solution (using python3 type hints), DrPyser was nearly right:

    class Square(luigi.Task):
        number: int
        number: ClassVar[luigi.IntParameter] = luigi.IntParameter()

        def run(self):
            square = math.square(self.number)

The double declaration declares an instance member variable, then a class member variable. This fixes the errors that pylint was raising for me.

**Comment by adriangb** [comment]
Luigi only needs the metadata to know to "grab the value from env variables" and such. IMO the right thing to do here is to use PEP593:

```python
from typing import Annotated
import luigi

class MyTask(luigi.Task):
    number: Annotated[int, luigi.IntParameter()] = 1
```

That way we keep this metadata out of the type system and default values work.
You could even get a bit fancier and infer the type from the annotation (so no more `IntParameter`).
Maybe even use [PEP 681](https://peps.python.org/pep-0681/) to make type checkers understand how to construct `luigi.Task` subclasses.

**Comment by rodya-mirov** [comment]
It doesn't _feel_ right, but the following very compact code is satisfying mypy, at least for me, locally:

```
class MyTask(luigi.Task):
  my_param: str = luigi.Parameter()
  my_fparam: float = luigi.FloatParameter()
```

and so on. Obviously a parameter _isn't_ a string, so in some sense this shouldn't work, but it does, and the intention is clear, so I'm not gonna complain.

**Comment by adriangb** [comment]
That's definitely not going to work with mypy in strict mode or pyright

**Comment by tgy** [comment]
@adriangb I like your `Annotated` solution. Do you know if there's a way this could be done automatically each time an `IntParameter` is created? Because doing this every time we create a class is pretty verbose.

**Comment by StefanIgnjatovic12** [comment]
> Luigi only needs the metadata to know to "grab the value from env variables" and such. IMO the right thing to do here is to use PEP593:
> 
> ```python
> from typing import Annotated
> import luigi
> 
> class MyTask(luigi.Task):
>     number: Annotated[int, luigi.IntParameter()] = 1
> ```
> 
> That way we keep this metadata out of the type system and default values work. You could even get a bit fancier and infer the type from the annotation (so no more `IntParameter`). Maybe even use [PEP 681](https://peps.python.org/pep-0681/) to make type checkers understand how to construct `luigi.Task` subclasses.

This doesnt work for me. 


```python
class BaseScraperTask(Task):
    resources = {'scraper_slots': 1}
    marketplace: Annotated[str, Parameter()] = "test2"
    data_type: Annotated[str, Parameter()] = "sale"
    item_id: Annotated[int, IntParameter()] = 0
    fetch_first_page_only: Annotated[bool, BoolParameter()] = False

```

And when I try to create an instance of BaseScraperTask:
luigi.parameter.UnknownParameterException: BaseScraperTask[args=(), kwargs={'marketplace': 'test1', 'data_type': 'sale', 'item_id': 653407, 'fetch_first_page_only': True}]: unknown parameter marketplace      

Anyone know how to get around this? I can't come up with any solutions to satisfy pyright.
