### ISSUE TITLE
Per-task retry_count doesn't seem to work

### ISSUE THREAD

**Issue by deneb84** [spotify/luigi#2543]
I was trying to set a `retry_count` for a specific task, the idea is to wait for external dependencies but for a limited period of time.

I tried default luigi configuration with this sample code:

```
import luigi

from luigi import Parameter


class InputDataTask(luigi.ExternalTask):
    retry_count = 2

    target = Parameter()
    def output(self):
        return [luigi.LocalTarget(self.target)]

class CleanTask(luigi.Task):
    retry_count = 2

    def output(self):
        return luigi.LocalTarget("cleaned/cleaned")

    def requires(self):
        reqs = []
        reqs.append(InputDataTask(target = "input/file1"))
        reqs.append(InputDataTask(target = "input/file2"))
        reqs.append(InputDataTask(target = "input/file3"))
        return reqs

    def run(self):
        with self.output().open("w") as output_file:
            output_file.write("pipeline")

if __name__ == '__main__':
    luigi.run()
```
I run this script with the following command:
`python luigi-example-easy.py CleanTask --worker-retry-external-tasks --worker-keep-alive`

Anithing seem to work fine except the fact that the process never ends in case the external dependencies are not satisfied.

The same settings works if I modify luigi.cfg adding: 
```
[scheduler]
retry_count = 2
```
Furthermore, adding `--scheduler-retry-count 2` to the command line args returns:
`luigi-example-easy.py: error: unrecognized arguments: --scheduler-retry-count 5`
even though:
```
$ luigi --help-all | grep retry-count
             [--scheduler-retry-count SCHEDULER_RETRY_COUNT]
  --scheduler-retry-count SCHEDULER_RETRY_COUNT

```
calling the function using directly `luigi` seems to work again:
`luigi --module luigi-example-easy CleanTask --worker-retry-external-tasks --worker-keep-alive --scheduler-retry-count 2`

it works also without `--scheduler-retry-count 2` since the configuration is specified in the task

**Comment by Tarrasch** [comment]
Can you find and ping the author of this feature?

**Comment by deneb84** [comment]
sure, I think is @javrasya. I tried and it seems that all the parameters added  [here](https://github.com/spotify/luigi/pull/1791) are available only if the task is started using directly luigi.

```
"retry_count"
"disable_hard_timeout"
"disable_window"
```
