### ISSUE TITLE
Feature request: per-task event handlers

### ISSUE THREAD

**Issue by DrPyser** [spotify/luigi#2544]
Hi.

I'd like to be able to have some way of reacting to events of a single task instance, instead of every instance of a task class. I guess I could define event handlers on the task's class which check for the specific signature/id of the particular task instance I want, but then there's no way to unregister the handler, so this is not viable. 

The context is that I'm implementing a websocket api for triggering tasks(through `luigi.interface.build`), and I want to send a message once the task is done(or failed). I don't know of any way to track a task execution other than the class-based events.

I'm going to implement this myself on my base task class, but I guess this would be a valuable feature to have natively in Luigi?

**Comment by Tarrasch** [comment]
Thanks for sharing your plans. As for contributing, it's probably wise to start with something that works for you. Once it's been useful for you for a while one can think further.  What do you think?

**Comment by DrPyser** [comment]
Sure, that seems reasonable.

**Comment by kwilcox** [comment]
@DrPyser Unless I misunderstand your requirements you should be able to implement this using the existing event handlers. I tried to come up with a simple example based on what I'm already doing... I hope it is clear enough.

I have a mixin class that a Task can make use of:

```python
class NotifierMixin:
    @property
    def notifiers(self):
        return SimpleNamespace(
            success: [ KafkaNotifier() ]
        )
```

Or the task can define a custom notifier:

```python
class MyTask(luigi.Task):
    @property
    def notifiers(self):
        return SimpleNamespace(
            success: [ KafkaNotifier() ]
        )
```


And you can define any number of notifiers that have access to the task instance.

```python
class KafkaNotifier:
    def success(self, task):
        # sends success message to kafka
    def failure(self, task):
        # sends failure message to kafka
```

Now just listen for all events and call the notifier functions:

```python
@luigi.Task.event_handler(luigi.Event.SUCCESS)
def task_success(task):
    if hasattr(task, 'notifiers') and hasattr(task.notifiers, 'success'):
        for k in task.notifiers.success:
            try:
                k.success(task)
            except BaseException:
                L.exception("Notifier failed!")
```

**Comment by DrPyser** [comment]
Hmm, you're right, hadn't thought of doing it that way. I ended up overriding `Task.trigger_event`(in a base class) to first loop through `self._task_callbacks` before calling the `super()` implementation. That way the instance callbacks are all executed before the class callbacks. I guess both ways work. Yours has the advantage of relying only on the existing event system's "public" interface.

I guess this issue can be closed.
