### ISSUE TITLE
Warning message because task_process_context Parameter defaults to None

### ISSUE THREAD

**Issue by tomsing1** [spotify/luigi#2550]
When I start a luigi pipeline, I get the following warning:

```
/lib/python3.6/site-packages/luigi/parameter.py:261: UserWarning: Parameter "task_process_context" with value "None" is not of type string.
  warnings.warn('Parameter "{}" with value "{}" is not of type string.'.format(param_name, param_value))
```

I think this might be due to the `None` default argument to the `worker` class:
https://github.com/spotify/luigi/blob/de4629a4c7c562b53fee2045aabd84189f897593/luigi/worker.py#L449

Perhaps that should be `''` instead?

**Comment by tomsing1** [comment]
I am using luigi 2.7.9, installed via pip.

**Comment by dlstadther** [comment]
Ah, a [PR was opened but appears abandoned](https://github.com/spotify/luigi/pull/2468).

As mentioned in the PR, I believe i'd prefer to see that Parameter be moved to an OptionalParameter (rather than the solution which was proposed. 

Feel free to contribute. I'd be happy to review!
