### ISSUE TITLE
S3Client - unable to pass aws_session_token

### ISSUE THREAD

**Issue by citynorman** [spotify/luigi#2554]
There a way to pass in the session token? 

This causes an error:

	s3cnxn = luigi.contrib.s3.S3Client(usr_creds['Credentials']['AccessKeyId'], usr_creds['Credentials']['SecretAccessKey'], 
	aws_session_token=usr_creds['Credentials']['SessionToken'])
	s3cnxn.listdir('s3://mybucket')

It results in `AttributeError: 'TypeError' object has no attribute 'message'` which is ultimately because of `TypeError: resource() got multiple values for keyword argument 'aws_session_token'`

When I change s3.py line 153+ to the below, ie remove `aws_session_token` it works perfectly fine

            self._s3 = boto3.resource('s3',
                                      aws_access_key_id=aws_access_key_id,
                                      aws_secret_access_key=aws_secret_access_key,
                                      **options)

luigi-2.7.9

**Comment by citynorman** [comment]
Thanks! Unfortunately I'm having trouble getting the assume role to work. Instead I generated a session token for a federated user and wanted to pass that in.

**Comment by dlstadther** [comment]
Understood. I suppose there isn't any reason why we should prevent that behavior. It would be easy enough to insert the `aws_session_token` into kwargs when the role/session are included (to create the session_token). That way we would also avoid duplicate key names - like you've encountered.

**Comment by duckontheweb** [comment]
For what it's worth, I think that simply removing `aws_session_token` as an argument in [this line](https://github.com/spotify/luigi/blob/master/luigi/contrib/s3.py#L162) will break the case where `aws_role_arn` and `aws_role_session_name` are passed as arguments to `S3Client`. I took the addition step of changing [this line](https://github.com/spotify/luigi/blob/master/luigi/contrib/s3.py#L141) to:

```python
options['aws_session_token'] = assumed_role['Credentials'].get('SessionToken')
```
which seemed to keep things working. 

Hopefully that's helpful.
