### ISSUE TITLE
snakebite vs. cdh4 in luigi.hdfs.Target

### ISSUE THREAD

**Issue by JonNelson** [spotify/luigi#256]
When using cdh4, something like this works:

```
luigi.hdfs.HdfsTarget('hdfs:///some/path').exists()
```

When using snakebite, it doesn't.

Compare this to:

```
luigi.hdfs.HdfsTarget('/some/path').exists()
```

which works in both.

It seems that one or the other ought to be used, and it seems like the host (and port) should be parsed out of the URL (if it's present), like this:

```
luigi.hdfs.HdfsTarget('hdfs://host:port/path/filename').exists()
```

would (probably!) work as is when using cdh4.  When using snakebite, it'd be nifty to have it automatically pull the host and port out of the URL and use that.

**Comment by Tarrasch** [comment]
Luigi does not guarantee that the different clients will work exactly the same. Also this issue is old. :)
