### ISSUE TITLE
Timeout error message not showing the timeout seconds; says "None seconds"

### ISSUE THREAD

**Issue by evictor** [spotify/luigi#2560]
I have my timeout set to 60 seconds under `[worker]` in my config. When a task times out, I see this message: "Task {} timed out after None seconds and was terminated."

LMK if you need more info but pretty straightforward.

**Comment by dlstadther** [comment]
Looks like the [config_path for Worker's timeout](https://github.com/spotify/luigi/blob/master/luigi/worker.py#L429-L430) is
```ini
[core]
worker-timeout: 60
```

**Comment by evictor** [comment]
Shows timeout here: https://luigi.readthedocs.io/en/stable/configuration.html#worker

Also notably it actually _does_ pick up my timeout defined in `[worker]`.

**Comment by dlstadther** [comment]
Understood. Sorry, i pointed out the fallback path.

The error you're getting is:
https://github.com/spotify/luigi/blob/master/luigi/worker.py#L1025

Which ultimately calls the value provided here:
https://github.com/spotify/luigi/blob/master/luigi/worker.py#L1009

Which is the worker config `timeout` value.


Are you able to reproduce this error? Or was it a once and done error?

**Comment by evictor** [comment]
I went about trying to reproduce. This base case works (i.e. output is `INFO: Task TimeoutErrorTest__99914b932b timed out after 1 seconds and was terminated.`):

```
from time import sleep

import luigi


class TimeoutErrorTest(luigi.Task):
    worker_timeout = 1

    def complete(self):
        return False

    def run(self):
        sleep(5)


if __name__ == '__main__':
    luigi.build([TimeoutErrorTest()], local_scheduler=True)
```

I was able to repro the bug with the following CLI run style (same task class above):

```
PYTHONPATH=. luigi --module timeout_error_test TimeoutErrorTest --local-scheduler --worker-timeout 1
```

Output is:

```
INFO: Task TimeoutErrorTest__99914b932b timed out after None seconds and was terminated.
```
