### ISSUE TITLE
Problems with S3 get_as_string

### ISSUE THREAD

**Issue by adilkhash** [spotify/luigi#2568]
Hello,
I have upgraded Luigi to 2.7.8 and noticed that the behaviour of `get_as_string` method has changed. Now it returns Unicode instead of bytes as before (for Python2 strings are bytes). Moreover it decodes bytes using UTF-8 encoding and we have no control over it.

Take a look at how this method looked like in 2.7.5: https://github.com/spotify/luigi/blob/2.7.5/luigi/contrib/s3.py#L311

How it looks like now: https://github.com/spotify/luigi/blob/master/luigi/contrib/s3.py#L391

2.7.5 `get_as_string` relies on `S3.Key.get_contents_as_string` which returns bytes if no encoding is supplied. Also if I have files on S3 which are encoded by i.e. `latin-1`, I will not be able to decode them due to hardcoded utf-8.

I propose to create new method called `get_as_bytes` and modify `get_as_string` to introduce optional argument encoding with default value as `utf-8` in order to save backward compatibility.

What you think?

**Comment by dlstadther** [comment]
Hi @adilkhash  , There was a big S3 change between 2.7.5 and 2.7.8 (I don't recall the specific version where the change occurred) where we moved from Boto to Boto3. I'm sorry that the functionality of `get_as_string()` changed slightly. That was not our intent.

The stated goal of your request is reasonable and I will review your PR.

**Comment by adilkhash** [comment]
Issue has been resolved.
