### ISSUE TITLE
Feature suggestion: RegexParameter

### ISSUE THREAD

**Issue by nephtyws** [spotify/luigi#2597]
## Motivation

Recently I've got a job and I started to use this wonderful framework at my work. My first job is create a Luigi task to dump some SQL table into Hadoop environment for the data analyst.

Our analysts are using Jenkins to execute Luigi task with parameters they want, so I need to make sure that there was no problem. My idea is using regular expression to check the input parameters. But since there was no Luigi parameter that supported regex, I had to do like below **example**:
```python
class OneTimeDump(luigi.Task):
    output_db_table = luigi.Parameter()
    def __init__(self, *args, **kwargs):
        super(OneTimeDump, self).__init__(*args, **kwargs)
        match = re.match("^[a-zA-Z0-9_]+\.[a-zA-Z0-9_]+$", self.output_db_table)
        if match:
            # do something
        else:
            # NO!
```

and I certainly thought there would be a better solution... if Luigi supports `RegexParameter`!

## Solution
```python
class OneTimeDump(luigi.Task):
    output_db_table = luigi.RegexParameter("^[a-zA-Z0-9_]+\.[a-zA-Z0-9_]+$")
    # continue if legitimate input has been entered
    # otherwise raise Exception
```

### What do you think about that? 
If it seems right, I'm willing to make a pull request!

Thanks for reading!

**Comment by dlstadther** [comment]
Hey @nephtyws Thanks for this request!

I'm not sure i agree with the inclusion of a `RegexParameter`, but i do like the idea of adding some parameter validation_regex attribution or something similar.

I'll leave the conversation open for iteration, but i'm envisioning something like:
```python
output_db_table = luigi.Parameter(regex_validation="^[a-zA-Z0-9_]+\.[a-zA-Z0-9_]+$")
```
, add some number/types/etc of validation methods to Parameter (inherited by all other Parameters), then implement its usage in Task (similar to [warning on wrong parameter type](https://github.com/spotify/luigi/blob/cdd63df7173313107b57f824d8e77fa0b0be90ff/luigi/task.py#L463-L466)).

If we agree to add this change, it may make sense to add support for regex validation and possibly min/max validations (mostly for int/float/date)

---

All this said, when i've needed to perform parameter value validation, i've done like you and implement the checks in each applicable `__init__()`

---

Of course, any addition should not change default behavior and should include appropriates tests :)

**Comment by nephtyws** [comment]
@dlstadther Thanks for your kind feedback! I like your approach (and it looks better than mine :)) that adding some attribute for parameter validation instead of adding specific parameter.

Other ideas, like min/max validations also sounds great. I wish I got a chance to implement that feature after implementing the regex attribute...

So if you don't mind, I'd like to summary our conversation and wrap up with a pull request. What do you think?

**Comment by dlstadther** [comment]
Looking through `parameter.py`, looks like someone [added NumericalParameter a couple years](https://github.com/spotify/luigi/pull/1799) ago which already includes the min/max validation i mentioned.

I wish I had had the insight then that i do now to suggest this alternate validation methodology.

I'd be happy to review your submission!

**Comment by glazari** [comment]
In the spirit of this suggestion, it could be interesting to add a generic `validation` parameter

```python
output_db_table = luigi.Parameter(validation=lambda x: x > 0)
```

The `regex_validation` could still be included as a shorthand for

```python
output_db_table = luigi.Parameter(validation= lambda x: re.match("^[a-zA-Z0-9_]+\.[a-zA-Z0-9_]+$",  x))
```

This way any min, max or even more elaborate validations become trivial to include.

If this suggestion is of interest I could submit a pull request for it.

**Comment by dlstadther** [comment]
@glazari Thanks for adding that additional clarity of suggestion! I agree with your suggestion
