### ISSUE TITLE
cannot bind an existing table in a specific schema for sqla.CopyToTable when reflect is True

### ISSUE THREAD

**Issue by garaud** [spotify/luigi#2604]
Hi,

I would like to use `contrib.sqla.CopyToTable` for a table in a specific schema with the parameter `reflect=True`. SqlAlchemy can find by itself the column types and names since my table is already in my database. This table is not in the `public` schema. Thus, I use the class parameter `schema`.

Nevertheless, I got this traceback because `self.table_bound` is `None`. in other words, the reflection does not work.

```
Traceback (most recent call last):
  File "venv/lib/python3.6/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "venv/lib/python3.6/site-packages/luigi/worker.py", line 139, in _run_get_new_deps
    task_gen = self.task.run()
  File "venv/lib/python3.6/site-packages/luigi/contrib/sqla.py", line 391, in run
    for row in itertools.islice(rows, self.chunk_size)]
  File "venv/lib/python3.6/site-packages/luigi/contrib/sqla.py", line 391, in <listcomp>
    for row in itertools.islice(rows, self.chunk_size)]
AttributeError: 'MyTask' object has no attribute 'table_bound'
```

Here an example of my task:

```python

class MyTask(sqla.CopyToTable):
    schema = "jazz"
    table = "player"
    column_separator = ","
    connection_string = "postgresql:///jazzy"
    reflect = True

    def requires(self):
        return PlayerTaskFile()
```

I think I spot the problem.

* when the schema is not None, the `metadata` is built with the `schema` parameter https://github.com/spotify/luigi/blob/master/luigi/contrib/sqla.py#L343
* in this case, it's not necessary to specify the name of the schema at https://github.com/spotify/luigi/blob/master/luigi/contrib/sqla.py#L354

These lines work good for me:

```python
from sqlalchemy import create_engine, MetaData

eng = create_engine("postgresql:///jazzy")
meta = MetaData(schema="jazz")
meta.reflect(only=["player"], bind=eng)
# instead of meta.reflect(only=["jazz.player"], bind=eng)
meta.tables["jazz.player"]
```

Thanks
Damien G.

**Comment by dlstadther** [comment]
Is this #2605 ?

I'd like to be sure that the patch works for both reflect true and reflect false. I don't utilize this module, so i'm hoping you can grab someone who has contributed to this module for review. Otherwise, I'll investigate further and see what i can understand and contribute.

Thanks!

**Comment by garaud** [comment]
Yes, #2605 is the PR which fixes this issue.

> I'd like to be sure that the patch works for both reflect true and reflect false

I understand.

> i'm hoping you can grab someone who has contributed to this module for review.

I hope so :slightly_smiling_face:  I'll try to set up a tiny use case to check this patch.
