### ISSUE TITLE
failed saving scheduler state

### ISSUE THREAD

**Issue by simonm3** [spotify/luigi#2611]
Since upgrading (now on 2.8.2), I get this warning at the end of every pipeline:

WARNING:luigi.scheduler:Failed saving scheduler state
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/luigi/scheduler.py", line 458, in                                                                                                                                   dump
    with open(self._state_path, 'wb') as fobj:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/luigi-server/s                                                                                                                                  tate.pickle'
WARNING:luigi.scheduler:Failed saving scheduler state
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/luigi/scheduler.py", line 458, in                                                                                                                                   dump
    with open(self._state_path, 'wb') as fobj:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/luigi-server/s                                                                                                                                  tate.pickle'

**Comment by Tarrasch** [comment]
Do you have a space character in your path???

'/var/lib/luigi-server/s tate.pickle'

Generally though the state.pickle file can safely be nuked after luigi upgrades.

**Comment by simonm3** [comment]
I am not trying to save the file. It seems to be happening automatically.
However the folder does not exist. Obviously I can create the path manually
and all is fine. However luigi should do the makedir before it creates the
file.

**Comment by simonm3** [comment]
When you mentioned the space I thought maybe that was the issue so removed my "mkdirs". However the error is still there and there is no space in the actual error message - not sure where it came from!

So there should be line to create the folder if it does not exist.

**Comment by parlad** [comment]
I am having this issue. I am running Luigi 3.0.3 @simonm3 Did you managed to solve this issue? if yes how ?

**Comment by simonm3** [comment]
This is a different problem. Probably related to this:

https://github.com/tornadoweb/tornado/issues/2608
