### ISSUE TITLE
Task visualiser: time values of D3 graph edges don't make sense?

### ISSUE THREAD

**Issue by MichaelGrupp** [spotify/luigi#2620]
When using the D3 graph visualization, the time values at the edges don't seem to correspond to the actual duration of that task. The [code](https://github.com/spotify/luigi/blob/b2a5759108eabf657c1495dac32d48801fb64e3a/luigi/static/visualiser/js/visualiserApp.js#L721) indicates that it's a duration time.

Here's an example script. It runs a `TestTask` which wraps 4 `DummyTask`s that each create a temporary file and sleep for 1 second.

So, running the whole pipeline should take a bit more than 4 seconds in total.

```python
import time

import luigi


class DummyTask(luigi.Task):
    tmp_path = luigi.Parameter()

    def output(self):
        return luigi.LocalTarget(path=self.tmp_path, is_tmp=True)

    def run(self):
        open(self.tmp_path, 'w').write("")
        time.sleep(1)


class TestTask(luigi.WrapperTask):
    def requires(self):
        for path in ["/tmp/a", "/tmp/b", "/tmp/c", "/tmp/d"]:
            yield DummyTask(tmp_path=path)


if __name__ == "__main__":
    luigi.build([TestTask()])
```

When I run a `luigid` daemon and then start the script:
```
time python test.py
```
`time` reports a bit more than 4 seconds as expected.

However, the D3 graph in the web viewer shows this:
![screenshot from 2019-01-15 18-32-11](https://user-images.githubusercontent.com/8985495/51198224-f51dc800-18f3-11e9-9615-b62891452e92.png)

To add to the confusion, not even the `luigid` daemon was running as long as any of the shown times in this example.

Could this be a time conversion bug or am I understanding something wrong?

**Comment by MichaelGrupp** [comment]
I'm using luigi 2.8.2 from PYPI on Ubuntu 16.04

**Comment by dlstadther** [comment]
@MichaelGrupp  Could you @-blame the author of that section of code? I'm not familiar with the visualization integrations.

**Comment by MichaelGrupp** [comment]
@hadesbox can you help here?

The oldest occurence of this duration I could track down across file changes is here: https://github.com/spotify/luigi/commit/755064bddf756947f784c69b5b83faba89cdbea9#diff-c32982ed29d088f880fba9a28a99c1a7R294

**Comment by MichaelGrupp** [comment]
I think I fixed it. Will open a PR.

![screenshot from 2019-01-16 18-40-15](https://user-images.githubusercontent.com/8985495/51267528-40041200-19be-11e9-9e69-641233113477.png)

**Comment by Tarrasch** [comment]
Would be nice if the strings eventually get human formatted. But it's a good start to not have incorrect data. :)
