### ISSUE TITLE
Pid(s) set([10263]) already running

### ISSUE THREAD

**Issue by diegocorradini** [spotify/luigi#2637]
Hi all,

I am developing a webapp able to run a Luigi pipeline by triggering a button.
However, even if the workflow ends properly, when I run the pipeline again I get "Pid(s) set([xxx]) already running".

What am I doing wrong?
Plus, is there a way to stop the run once started?

Many thanks.

**Comment by veltzerdoron** [comment]
I'm getting this as well, calling luigi.run from code twice yields this, any solutions you come across?

**Comment by eloyfelix** [comment]
same issue here when running luigi tasks on diferent servers connected to a remote scheduler. I get this error from time to time.

**Comment by veltzerdoron** [comment]
Take a look at this
https://github.com/spotify/luigi/issues/2731

**Comment by eloyfelix** [comment]
many thanks, I'll take a look at it :)

**Comment by christopherpryer** [comment]
Is there any info on this? I get that it would typically be related to cronjob management, but it's throwing even when I'm a. not using cronjobs and b. not running multiple jobs. Has anyone had any success with luigi.lock workarounds? I'm running mine through the command line.
