### ISSUE TITLE
Inconsistent event handling

### ISSUE THREAD

**Issue by cosminlz** [spotify/luigi#2639]
Hi guys,

I encountered a strange behavior which seems to me inconsistent. Consider this simple code:
 ```
import luigi

class MyTask(luigi.Task):

    def run(self):
        print(1 / 0)

    def output(self):
        class Output():
            def exists(self):
                return False
        return Output()

errors = []

@luigi.Task.event_handler(luigi.Event.FAILURE)
def add_error(task, exception):
    errors.append(exception)

luigi.build([MyTask()], workers=2, log_level='WARNING')
print(errors)

errors.clear()

luigi.build([MyTask()], log_level='WARNING')
print(errors)
```
Specifying workers makes the error list empty, while running locally stores the exceptions in the list.
I understand that workers are ran in separate processes, but calling the handlers in the same worker processes seems inconsistent and I don't know if this is intended behavior or not. The documentation about event handing (https://luigi.readthedocs.io/en/stable/tasks.html#events) doesn't cover this case.

Is this inconsistency "by design", or is it a bug? 

Thanks!
Cosmin

[Edit]: If this helps, I'm using luigi 2.7.9, python 3.6.7, Ubuntu 16.04

**Comment by dgronskij** [comment]
This seems to be a multiprocessing issue -- when running one worker, by default `luigi` doesn't spawn separate process, so the global list is populated, and then the same list is printed. When number of workers is 2+, each worker runs its separate process (which does copies of everything when fork'ing)  process-wise list copies are populated, not the one you declared at first.

To verify this, I suggest you to print `errors` list in the handler (+ add random sleep to avoid breaking stdout) and/or set `luigi.worker.worker().force_multiprocessing = True` before spawning the tasks.

**Comment by cosminlz** [comment]
When printing `errors` in the handler, it does indeed contain the exception. I was expecting this because, like you said, the forking copies out all the context, so I am printing a copy of `errors`.
I was surprised to find this behavior because I was running a pipeline having this type of error handling mechanism for some time and, when scaling up the number of workers, it stopped working. 
Didn't look at the inner workings of `luigi` yet, but I expect to see some kind of wait/message loop for forking worker processes so that the call to `luigi.build()` finishes when it is supposed to. If this is the case, then I would also expect exceptions being sent to the 'main' process so that handlers can be called in the context where they were defined.
Looking at the unit test (https://github.com/spotify/luigi/blob/master/test/event_callbacks_test.py) I see that only 'single process' pipeline cases are covered.
So my question still: "is this behavior is 'by design' or intended?"

Thanks!

**Comment by Tarrasch** [comment]
Honestly I've never though about this, because I've never needed the event handlers. What you say makes sense to me. One could theoretically implement this interface:

```
class LuigiEventThread(enum)
  TASK_THREAD = 0
  PIPELINE_THREAD = 1

@luigi.Task.event_handler(luigi.Event.FAILURE, thread=LuigiEventThread.PIPELINE_THREAD)
def add_error(task, exception):
   errors.append(exception)

```

But it's at least a full week of work to get it working in all combinations and write good tests and all. It would also complicate the codebase further quite a lot.

Maybe it's instead more worthwhile (i) submit som doc update to luigi summarizing your finding in this issue and (ii) if possible, rewrite things on your side to use immutable data structures or whatever is necessary.

**Comment by cosminlz** [comment]
Hi @Tarrasch 
My use-case is this: I have a updates on data stored in sorted folders:
update1/
update2/
...
and cannot apply update2/ until update1/ is finished. I was relying on events because I needed to check if update1/ was correctly applied before doing update2/.

I could use a file to store/read task failures, but I was wondering if there is another way to check task statuses other than the event handling mechanism?
Meanwhile, I will create a pull request for the docs.

Thanks!
Cosmin

**Comment by dgronskij** [comment]
@cosminlz is it possible to delegate the scheduling and dependency resolution to `luigi` itself where it shines? I mean, creating a target (possibly with custom logic of `exists`, you name it) and making your update makertasks depending on them could probably help you avoid custom event handling machinery.
