### ISSUE TITLE
Phantom Tasks Running Interminably

### ISSUE THREAD

**Issue by nickymikail** [spotify/luigi#2640]
I have a task that has been in the "Running" state according to the task visualizer for 10 days (1). This task is not running. According to the API it is not assigned to any workers (3) and there are no history records for this task in our database (4). I've tried restarting the process that runs the central scheduler, and I've tried manually running the same task with identical parameter values (including `---start`) to mimic the task completing. I can't figure out how to get rid of this little spot, and I'm starting to feel like Macbeth.

(1)![screen shot 2019-01-31 at 9 19 49 am](https://user-images.githubusercontent.com/4106455/52072230-76529d00-2539-11e9-94f1-543b7b689720.png)
(2)![screen shot 2019-01-31 at 9 20 04 am](https://user-images.githubusercontent.com/4106455/52072231-76529d00-2539-11e9-93eb-8e65c89ba9e5.png)
(3)![screen shot 2019-01-31 at 9 22 55 am](https://user-images.githubusercontent.com/4106455/52072494-ee20c780-2539-11e9-9935-012a9fb60154.png)
(4)![screen shot 2019-01-31 at 9 23 24 am](https://user-images.githubusercontent.com/4106455/52072506-f4af3f00-2539-11e9-8b58-6f3559bfdd6c.png)

**Comment by Tarrasch** [comment]
Thanks for adding so much information to your bug report. Unfortunately I don't know why this is. If I recall correctly even RUNNING tasks should be pruned when there's been no ping for a while.

I would probably just quit luigid and remove the state file and just restart on a fresh state.

**Comment by nickymikail** [comment]
Making a new state file and killing luigid resolved the issue, thanks!
