### ISSUE TITLE
Jobs keep resetting for no clear reason

### ISSUE THREAD

**Issue by snenkov** [spotify/luigi#2641]
Hi,
I am using luigi to generate reports for various parameters once a day.
For some reason, luigi re-runs the failed reports multiple times.
I tried looking into the `worker` settings, but all I see is that I have the default settings running, hency my puzzlement. 

Here is example of my luigi code and config. I run the wrapper task, when executing luigi.

**Code**
```
class RunAllReports(luigi.WrapperTask):
    param_list= luigi.Parameter()

    def requires(self):
        for param in self.param_list:
            yield RunReport(param=param)

class RunReport(ExternalProgramTask):
    param= luigi.Parameter()

    def program_args(self):
        return f'report.py --param {self.param}'.split()

    def output(self):
        return luigi.LocalTarget('path/to/my/report/unique_name.txt')
```

**Config**
```
[core]
default-scheduler-host=server.name.com
default-scheduler-port=8082
parallel_scheduling=true
```

Not sure why I should expect suche behavior.
Logically, if a job fails, it should not change status.
If it's expecting a re-run, it makes intuitive sense to have another status, such as unsuccessful. Only after all reruns are exhausted, it should move to fail. At least that's intuitive to me.

**Comment by Tarrasch** [comment]
Well one basic idea in luigi is "If something fails, try again". I think many finds it useful but perhaps it's not the case in your domain.You should check out the "DISABLED" status which might be what you're looking for, and play around with task cool downs.

**Comment by snenkov** [comment]
Okay @Tarrasch, thanks for the advice.
So how can I do that? Can you give a reference points to start from (documentation link or otherwise)?

**Comment by Tarrasch** [comment]
Hi @snenkov, I would start [here](https://luigi.readthedocs.io/en/stable/configuration.html#scheduler), and read about the configuration options related to "disable" there.

It's not a feature we want enabled by default - for many of our lightweight users a single fail state is enough (I think).

**Comment by snenkov** [comment]
I read and what solved my issue is to set `retry_delay=86400` (or set it to some other large number). This way all failed jobs don't go to failed, but go to disabled.

But I found this with trial and error, because in the documentation it actually says that this config option specifies the "Number of seconds to wait after a task failure to mark it pending again. Defaults to 900 (15 minutes)." It does not say anywhere that these tasks are moved to disabled.

Also, when I tried other options in isolation, such as setting `disable-hard-timeout` to 60, even if a job ran at 14:40 and then again at 14:50, the job was not disabled.
Could you please elaborate why, because as per the documentation, it should have been disabled, correct? Or am I misunderstanding something?
