### ISSUE TITLE
running DockerTask

### ISSUE THREAD

**Issue by jyu-theartofml** [spotify/luigi#2648]
I have a general question about `luigi.contrib.docker_runner.DockerTask`, and I can't seem to find information anywhere else, so maybe someone can give some feedback here. If you have different Luigi tasks built in different environments and you want to 'glue' those tasks together under one system, can you use `DockerTask` to wrap each task and still be able to connect one DockerTask to another? For example, can you chain two different DockerTasks and pass the output from A -> B ?

**Comment by emptymalei** [comment]
I have exactly the same question.

**Comment by dlstadther** [comment]
@apierleoni contributed our Docker contrib library

**Comment by apierleoni** [comment]
not sure I got the question right, would be good to have a more detailed usecase.
Particularly not sure what `environment` means here.
Each DockerTask is independent from the other, so you should be able to pass the output for A to B if it is persisted somewhere in between.
