### ISSUE TITLE
A proper error should be written when the input param has underscore

### ISSUE THREAD

**Issue by salexln** [spotify/luigi#2653]
I used a parameter with underscore (target_db) for a Luigi task and got the following error:

> UnknownParameterException: MyTask[args=(), kwargs={..., 'target-db': 'db_name'...}]: unknown parameter target-db

I spent on this issue a couple of hours of debugging only to find out that the Luigi does not like underscore in it's input params.
Changing  the parameter from 

> target_db

 to 

> targetDB

 fixed the issue.

Please write a proper error for such cases.

This is the stacktrace:
```
 File ".../.virtualenvs/.../local/lib/python2.7/site-packages/luigi/worker.py", line 401, in check_complete
    is_complete = task.complete()
  File ".../.virtualenvs/.../local/lib/python2.7/site-packages/luigi/task.py", line 827, in complete
    return all(r.complete() for r in flatten(self.requires()))
  File ".../.virtualenvs/.../local/lib/python2.7/site-packages/luigi/task.py", line 888, in flatten
    for result in iterator:
...
UnknownParameterException: MyTask[args=(), kwargs={..., 'target-db': 'db_name'...}]: unknown parameter target-db

```

**Comment by dlstadther** [comment]
@salexln While i agree the error message is not as helpful as one would desire, please see the [Docs](https://luigi.readthedocs.io/en/latest/running_luigi.html_)

> Note that if a parameter name contains ‘_’, it should be replaced by ‘-‘. 
So parameter `target_db` would need to be referenced as `target-db` from CLI args.

**Comment by dlstadther** [comment]
Sorry; i just read your issue closer and see that my comment doesn't necessarily align with your report.

Are you getting this error from CLI args or elsewhere?

**Comment by salexln** [comment]
@dlstadther The link to the Docs you provided is broken :(

I'm getting the error using the CLI
My class looks like something this:

```
class MyTask(Task):
    target_db = TARGET_DB
    ....

    def requires(self):
        kwargs = {...,
                  'target_db': self.target_db
                  }
        yield PreviousTask(**kwargs)

```

This yield the error that I wrote earlier, and only after changing `target_db` to `targetDB` it started to run

**Comment by dlstadther** [comment]
Sorry about the link; looks like a hit a stray character at the end. I have fixed my referenced link.
