### ISSUE TITLE
SIGQUIT in luigid on Windows

### ISSUE THREAD

**Issue by chancyk** [spotify/luigi#267]
The luigid server fails to start on Windows due to the usage of signal.SIGQUIT which does not exist for Windows. The culprit line is:

https://github.com/spotify/luigi/blob/master/luigi/server.py#L160

I replaced the line with the following and it worked with my basic test, but I have no idea if that's the correct or advised way to handle the issue.

```python
if os.name == 'nt':
        signal.signal(signal.SIGBREAK, shutdown_handler)
else:
        signal.signal(signal.SIGQUIT, shutdown_handler)
```

**Comment by themalkolm** [comment]
This was fixed in fdae8baf4f768d4a15c1e04284ed41b284accd98
