### ISSUE TITLE
Luigi not working behind reversproxy with baseurl

### ISSUE THREAD

**Issue by zwotzie** [spotify/luigi#2670]
I would like to run Luigi behind haproxy with baseurl /luigi. 

client.cfg contains:
default-scheduler-url: http**s**://domain.tld/luigi

Normaly i would expect, that this would work, because this configuration is semantically a url not a hostname...

Luigi is running well until _urljoin(base, url) in rpc.py is called.

The "funny" thing is, that the parameter variable basecontains the right default-scheduler-url and the url contains at first time '/api/ping'. The result ends in the wrong url: https://domain.tld/api/ping but i would expect https://domain.tld/luigi/api/ping. The _urljoin function does not join the urls parts but rather replaces parts of it.

At least I do not know why the scheme is twice replaced back and forth in the same function.

**Comment by greysonevins** [comment]
@zwotzie did you find a solution to this one? I am not able to solve this one either. Want to host a scheduler on a sub directory of a url but no luck either.

**Comment by zwotzie** [comment]
yes i find a solution and build my own luigi.: https://github.com/zwotzie/luigi 
There are two differences between here and there. First i use snakebite-py3 and therefor i have to remove the code to stop and for the reverseproxy usage (haproxy) see the changes in  https://github.com/zwotzie/luigi/commit/e0175d682f47c19d55ffbdff11d36a0f2c49aaf3

Hope that helps

**Comment by tashrifbillah** [comment]
To add a bit more, I tried the following nginx.conf with default `luigi.cfg`:

```vim
server {
    location / {
        proxy_pass http://localhost:8082/static/visualiser/;
    }
}
```

Is that what @greysonevins failed to solve?

**Comment by zwotzie** [comment]
I had to explain the setup better, sorry for that.

The client.cfg from above is for the luigi workers and not for the scheduler.

In my case, the setup looks like:

`
haproxy (ssl offloading) -> nginx (revers proxy) -> luigi-central-scheduler
                                  -> nginx ...
`

The haproxy redirects everythin from /luigi to nginx. Nginx rewrites all urls so that luigi (with standard configuration) can understand it.

**Comment by tashrifbillah** [comment]
Thanks @zwotzie . This is how I solved this: issue https://github.com/spotify/luigi/issues/2972

**Comment by tashrifbillah** [comment]
Hello again @zwotzie , I was able to proxy the Luigi server against `https://yourdomain.xy/` using the following:
```vim
location / {
  proxy_pass http://localhost:8082;
}
```
as simple as that. Upon plugging in `https://yourdomain.xy/` on Mozilla, the URL got rewritten as `http://pnl_servers.dipr.partners.org/static/visualiser/index.html#`. Everything was fine.

---

However, now I found myself interested in the problem you might have solved already: proxy the server `https://yourdomain.xy/luigi/`. I used your snippet verbatim:
```vim
    port_in_redirect off;

    location /luigi/ {
        proxy_pass http://localhost:8082/;

        proxy_set_header Accept-Encoding "";

        sub_filter_types *;
        sub_filter 'src="/luigi/"' 'src="/luigi/static/visualiser';
        sub_filter 'href="/luigi/"' 'href="/luigi/static/visualiser';

        sub_filter 'href="static' 'href="/luigi/static/';
        sub_filter 'href="api'    'href="/luigi/api/';

        sub_filter_once on;

        expires -1;
    }
```

Now, upon plugging in `https://yourdomain.xy/luigi` on Mozilla, the URL got rewritten as `http://pnl_servers.dipr.partners.org/static/visualiser/index.html` (no trailing #) and I get error 404. Can you please advise?

**Comment by tashrifbillah** [comment]
By the way, should I need to build your Luigi for your solution to work?

**Comment by tashrifbillah** [comment]
Perhaps I should say this, I am getting an unstable behavior. Sometimes, it looks like this (no error404):


![image](https://user-images.githubusercontent.com/35086881/88683670-0e472d80-d0c2-11ea-9593-d5bf20f7d871.png)

**Comment by tashrifbillah** [comment]
Here is the associated error.log:

<Details>

```vim
2020/07/28 11:07:10 [debug] 108583#0: *515 free: 0000561A167B64E0
2020/07/28 11:07:10 [debug] 108583#0: *515 hc free: 0000000000000000
2020/07/28 11:07:10 [debug] 108583#0: *515 hc busy: 0000000000000000 0
2020/07/28 11:07:10 [debug] 108583#0: *515 reusable connection: 1
2020/07/28 11:07:10 [debug] 108583#0: *515 event timer add: 3: 65000:2683945147
2020/07/28 11:07:10 [debug] 108583#0: *515 http empty handler
2020/07/28 11:07:10 [debug] 108583#0: timer delta: 1
2020/07/28 11:07:10 [debug] 108583#0: worker cycle
2020/07/28 11:07:10 [debug] 108583#0: epoll timer: 64998
2020/07/28 11:07:10 [debug] 108583#0: epoll: fd:4 ev:0001 d:00007FD8C42BD2E1
2020/07/28 11:07:10 [debug] 108583#0: *517 http keepalive handler
2020/07/28 11:07:10 [debug] 108583#0: *517 malloc: 0000561A167B64E0:1024
2020/07/28 11:07:10 [debug] 108583#0: *517 recv: eof:0, avail:1
2020/07/28 11:07:10 [debug] 108583#0: *517 recv: fd:4 507 of 1024
2020/07/28 11:07:10 [debug] 108583#0: *517 reusable connection: 0
2020/07/28 11:07:10 [debug] 108583#0: *517 posix_memalign: 0000561A16859150:4096 @16
2020/07/28 11:07:10 [debug] 108583#0: *517 event timer del: 4: 2683945145
2020/07/28 11:07:10 [debug] 108583#0: *517 http process request line
2020/07/28 11:07:10 [debug] 108583#0: *517 http request line: "GET /api/task_list?data=%7B%22status%22%3A%22DONE%22%2C%22upstream_status%22%3A%22%22%2C%22search%22%3A%22%22%7D HTTP/1.1"
2020/07/28 11:07:10 [debug] 108583#0: *517 http uri: "/api/task_list"
2020/07/28 11:07:10 [debug] 108583#0: *517 http args: "data=%7B%22status%22%3A%22DONE%22%2C%22upstream_status%22%3A%22%22%2C%22search%22%3A%22%22%7D"
2020/07/28 11:07:10 [debug] 108583#0: *517 http exten: ""
2020/07/28 11:07:10 [debug] 108583#0: *517 posix_memalign: 0000561A1684A1F0:4096 @16
2020/07/28 11:07:10 [debug] 108583#0: *517 http process request header line
2020/07/28 11:07:10 [debug] 108583#0: *517 http header: "Host: pnl_servers.dipr.partners.org"
2020/07/28 11:07:10 [debug] 108583#0: *517 http header: "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
2020/07/28 11:07:10 [debug] 108583#0: *517 http header: "Accept: application/json, text/javascript, */*; q=0.01"
2020/07/28 11:07:10 [debug] 108583#0: *517 http header: "Accept-Language: en-US,en;q=0.5"
2020/07/28 11:07:10 [debug] 108583#0: *517 http header: "Accept-Encoding: gzip, deflate"
2020/07/28 11:07:10 [debug] 108583#0: *517 http header: "Referer: http://pnl_servers.dipr.partners.org/static/visualiser/index.html"
2020/07/28 11:07:10 [debug] 108583#0: *517 http header: "X-Requested-With: XMLHttpRequest"
2020/07/28 11:07:10 [debug] 108583#0: *517 http header: "DNT: 1"
2020/07/28 11:07:10 [debug] 108583#0: *517 http header: "Connection: keep-alive"
2020/07/28 11:07:10 [debug] 108583#0: *517 http header done
2020/07/28 11:07:10 [debug] 108583#0: *517 generic phase: 0
2020/07/28 11:07:10 [debug] 108583#0: *517 rewrite phase: 1
2020/07/28 11:07:10 [debug] 108583#0: *517 test location: "/luigi/"
2020/07/28 11:07:10 [debug] 108583#0: *517 using configuration ""
2020/07/28 11:07:10 [debug] 108583#0: *517 http cl:-1 max:1048576
2020/07/28 11:07:10 [debug] 108583#0: *517 rewrite phase: 3
2020/07/28 11:07:10 [debug] 108583#0: *517 post rewrite phase: 4
2020/07/28 11:07:10 [debug] 108583#0: *517 generic phase: 5
2020/07/28 11:07:10 [debug] 108583#0: *517 generic phase: 6
2020/07/28 11:07:10 [debug] 108583#0: *517 generic phase: 7
2020/07/28 11:07:10 [debug] 108583#0: *517 generic phase: 8
2020/07/28 11:07:10 [debug] 108583#0: *517 access phase: 9
2020/07/28 11:07:10 [debug] 108583#0: *517 access phase: 10
2020/07/28 11:07:10 [debug] 108583#0: *517 access phase: 11
2020/07/28 11:07:10 [debug] 108583#0: *517 post access phase: 12
2020/07/28 11:07:10 [debug] 108583#0: *517 generic phase: 13
2020/07/28 11:07:10 [debug] 108583#0: *517 generic phase: 14
2020/07/28 11:07:10 [debug] 108583#0: *517 content phase: 15
2020/07/28 11:07:10 [debug] 108583#0: *517 content phase: 16
2020/07/28 11:07:10 [debug] 108583#0: *517 content phase: 17
2020/07/28 11:07:10 [debug] 108583#0: *517 content phase: 18
2020/07/28 11:07:10 [debug] 108583#0: *517 content phase: 19
2020/07/28 11:07:10 [debug] 108583#0: *517 content phase: 20
2020/07/28 11:07:10 [debug] 108583#0: *517 http filename: "/usr/share/nginx/html/api/task_list"
2020/07/28 11:07:10 [debug] 108583#0: *517 add cleanup: 0000561A16859F48
2020/07/28 11:07:10 [error] 108583#0: *517 open() "/usr/share/nginx/html/api/task_list" failed (2: No such file or directory), client: 170.223.221.217, server: , request: "GET /api/task_list?data=%7B%22status%22%3A%22DONE%22%2C%22upstream_status%22%3A%22%22%2C%22search%22%3A%22%22%7D HTTP/1.1", host: "pnl_servers.dipr.partners.org", referrer: "http://pnl_servers.dipr.partners.org/static/visualiser/index.html"
2020/07/28 11:07:10 [debug] 108583#0: *517 http finalize request: 404, "/api/task_list?data=%7B%22status%22%3A%22DONE%22%2C%22upstream_status%22%3A%22%22%2C%22search%22%3A%22%22%7D" a:1, c:1
2020/07/28 11:07:10 [debug] 108583#0: *517 http special response: 404, "/api/task_list?data=%7B%22status%22%3A%22DONE%22%2C%22upstream_status%22%3A%22%22%2C%22search%22%3A%22%22%7D"
2020/07/28 11:07:10 [debug] 108583#0: *517 http set discard body
2020/07/28 11:07:10 [debug] 108583#0: *517 xslt filter header
2020/07/28 11:07:10 [debug] 108583#0: *517 HTTP/1.1 404 Not Found
Server: nginx/1.16.1
Date: Tue, 28 Jul 2020 15:07:10 GMT
Content-Type: text/html
Content-Length: 153
Connection: keep-alive

2020/07/28 11:07:10 [debug] 108583#0: *517 write new buf t:1 f:0 0000561A16859FC8, pos 0000561A16859FC8, size: 155 file: 0, size: 0
2020/07/28 11:07:10 [debug] 108583#0: *517 http write filter: l:0 f:0 s:155
2020/07/28 11:07:10 [debug] 108583#0: *517 http output filter "/api/task_list?data=%7B%22status%22%3A%22DONE%22%2C%22upstream_status%22%3A%22%22%2C%22search%22%3A%22%22%7D"
2020/07/28 11:07:10 [debug] 108583#0: *517 http copy filter: "/api/task_list?data=%7B%22status%22%3A%22DONE%22%2C%22upstream_status%22%3A%22%22%2C%22search%22%3A%22%22%7D"
2020/07/28 11:07:10 [debug] 108583#0: *517 image filter
2020/07/28 11:07:10 [debug] 108583#0: *517 xslt filter body
2020/07/28 11:07:10 [debug] 108583#0: *517 http postpone filter "/api/task_list?data=%7B%22status%22%3A%22DONE%22%2C%22upstream_status%22%3A%22%22%2C%22search%22%3A%22%22%7D" 0000561A1685A128
2020/07/28 11:07:10 [debug] 108583#0: *517 write old buf t:1 f:0 0000561A16859FC8, pos 0000561A16859FC8, size: 155 file: 0, size: 0
2020/07/28 11:07:10 [debug] 108583#0: *517 write new buf t:0 f:0 0000000000000000, pos 0000561A14F964E0, size: 100 file: 0, size: 0
2020/07/28 11:07:10 [debug] 108583#0: *517 write new buf t:0 f:0 0000000000000000, pos 0000561A14F96C40, size: 53 file: 0, size: 0
2020/07/28 11:07:10 [debug] 108583#0: *517 http write filter: l:1 f:0 s:308
2020/07/28 11:07:10 [debug] 108583#0: *517 http write filter limit 0
2020/07/28 11:07:10 [debug] 108583#0: *517 writev: 308 of 308
2020/07/28 11:07:10 [debug] 108583#0: *517 http write filter 0000000000000000
2020/07/28 11:07:10 [debug] 108583#0: *517 http copy filter: 0 "/api/task_list?data=%7B%22status%22%3A%22DONE%22%2C%22upstream_status%22%3A%22%22%2C%22search%22%3A%22%22%7D"
2020/07/28 11:07:10 [debug] 108583#0: *517 http finalize request: 0, "/api/task_list?data=%7B%22status%22%3A%22DONE%22%2C%22upstream_status%22%3A%22%22%2C%22search%22%3A%22%22%7D" a:1, c:1
2020/07/28 11:07:10 [debug] 108583#0: *517 set http keepalive handler
2020/07/28 11:07:10 [debug] 108583#0: *517 http close request
2020/07/28 11:07:10 [debug] 108583#0: *517 http log handler
2020/07/28 11:07:10 [debug] 108583#0: *517 free: 0000561A16859150, unused: 8
2020/07/28 11:07:10 [debug] 108583#0: *517 free: 0000561A1684A1F0, unused: 2602
2020/07/28 11:07:10 [debug] 108583#0: *517 free: 0000561A167B64E0
2020/07/28 11:07:10 [debug] 108583#0: *517 hc free: 0000000000000000
2020/07/28 11:07:10 [debug] 108583#0: *517 hc busy: 0000000000000000 0
2020/07/28 11:07:10 [debug] 108583#0: *517 reusable connection: 1
2020/07/28 11:07:10 [debug] 108583#0: *517 event timer add: 4: 65000:2683945148
2020/07/28 11:07:10 [debug] 108583#0: timer delta: 1
2020/07/28 11:07:10 [debug] 108583#0: worker cycle
2020/07/28 11:07:10 [debug] 108583#0: epoll timer: 64998

```

</Details>

**Comment by zwotzie** [comment]
> Perhaps I should say this, I am getting an unstable behavior. Sometimes, it looks like this (no error404):

this sounds strange. normaly the behavior shoud be deterministic.

> 
> ![image](https://user-images.githubusercontent.com/35086881/88683670-0e472d80-d0c2-11ea-9593-d5bf20f7d871.png)

This looks like, if the api is not responding or is not been able to called.

**Comment by zwotzie** [comment]
> By the way, should I need to build your Luigi for your solution to work?

My luigi you only need if you want to use luigi-worker with base_url .../luigi/. Because the "/luigi"-part was lost in rpc.py.

The scheduler I used was a normal actual build.

**Comment by tashrifbillah** [comment]
Hi @zwotzie , sorry I keep coming back to you, and thanks a lot for answering my questions so far. First of all, you are right, I haven't gotten to the worker `rpc.py` yet, I am still trying to figure the `server.py` part. So I came up with a better description of the problem-- 

For the root URL Nginx configuration, which works as expected--
```vim
location / {

            proxy_pass http://127.0.0.1:8082;

} 
```
The following is the log of Tornado server launched by Luigi:
```bash
> curl -L http://`hostname`/
2020-08-11 INFO: 302 GET / (127.0.0.1) 0.47ms
2020-08-11 INFO: 200 GET /static/visualiser/index.html (127.0.0.1) 0.77ms
```
---
On the other hand, for the **non-root** URL Nginx configuration, which results in error 404--
```vim
location /luigi/ {

            proxy_pass http://127.0.0.1:8082/$1;

} 
```
The following is the log of Tornado server launched by Luigi:
```bash
> curl -L http://`hostname`/luigi
2020-08-11 INFO: 302 GET / (127.0.0.1) 0.47ms
(2nd line is missing)
```

Do that give us a better idea about where the error is coming from? I am pretty convinced that it is a Tornado issue and not an Nginx issue. If you have time, the above blocks should be enough to reproduce this at your end.

Thank you.

**Comment by zwotzie** [comment]
This is what is running in my container:

`bash-4.4# python --version
Python 2.7.15

bash-4.4# pip freeze
cachetools==3.1.0
certifi==2018.11.29
chardet==3.0.4
Click==7.0
dnspython==1.16.0
docker==3.7.0
docker-pycreds==0.4.0
docutils==0.14
Flask==1.0.2
Flask-HTTPAuth==3.2.4
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10
kazoo==2.6.1
lockfile==0.12.2
luigi==2.8.3
MarkupSafe==1.1.0
MicroFlack-Common==0.6
psycopg2==2.7.5
PyJWT==1.7.1
python-daemon==2.1.2
python-dateutil==2.7.5
python-etcd==0.4.5
requests==2.21.0
six==1.12.0
SQLAlchemy==1.3.0
tornado==4.5.3
urllib3==1.24.1
websocket-client==0.54.0
Werkzeug==0.14.1
`

I didn't updated it since a couple of month (I'm no longer working on it). Maybe there is something going wrong with your newer packages.

**Comment by zwotzie** [comment]
Your setup seems to work (screenshot) except api-calls. I quess you need the additional sub_filters as mentioned above. I did place them there, because the api did'nt work.

You can also use the dev-tools in your browser to see which calls are working and which are not. So you can fix one after another.
