### ISSUE TITLE
Unable to schedule dynamically created task

### ISSUE THREAD

**Issue by charlesoblack** [spotify/luigi#2671]
I have several postgres tables to write to and don't want to constantly adapt cookie-cutter code by creating several different task types that are all very similar but write to different tables. For this, I wanted to dynamically create a luigi Task:

```@requires(requirement1,requirement2)
class PostGreSQLTaskWrapper(Task):

	ps_password = Parameter(visibility=ParameterVisibility.PRIVATE)
	tables = ['test_table2','test_table2']
	tasks = []

	def output(self):
		for task in self.tasks:
			yield task.output()

	def run(self):
		from luigi import build
		from luigi.contrib import postgres
		from luigi.task_register import load_task

		for index,item in zip(range(len(self.input())),self.input()):
			self.tasks.append(type('PostGreSQLTask_'+item.path,
				(postgres.CopyToTable,),
				dict(
				    password = self.ps_password,
				    host = our_host,
				    database = our_db,
				    user = my_user,
				    table = self.tables[index],
				    column_separator = ',')))

		for task in self.tasks:
			load_task(None,task,self.get_params())
```

However, `load_task()` fails with a `TaskClassNotFoundException`. I assume this is because i've created the task class dynamically with `type()`, and the scheduler/register does not know of the existence of this task (i.e. it's not in the `reg` list inside the scheduler/register).

How can I go about scheduling these dynamically created tasks so that this "wrapper" task can create `postgres.CopyToTable`-based Tasks dynamically and run them?

**Comment by dlstadther** [comment]
try

```python
def run(self):
    tasks = []
    for index, item in zip(....):
        tasks.append(postgres.CopyToTable(**dict_params))
    yield tasks

    # write some sort of output
```

When i use dynamic dependencies, i use the `yield` methodology i've tried to denote above.

**Comment by charlesoblack** [comment]
I'm not sure I understand how to pass in the class-level variables. With this:
```python
for index,item in zip(range(len(self.input())),self.input()):
	self.tasks.append(postgres.CopyToTable(**dict(
		#columns = [],
		password = self.ps_password,
		host = our_host,
		database = our_db,
		user = my_user,
		table = self.tables[index],
		column_separator = ',')))
yield self.tasks
```
I get the concept of not instantiating something based off of CopyToTable but CopyToTable directly, but passing in `**dict()` fails because luigi doesn't know what to do with the `dict` given:

```luigi.parameter.UnknownParameterException: CopyToTable[args=(), kwargs={'password':'asdf123',...}]: unknown parameter password```

**Comment by dlstadther** [comment]
Oh, i see. I've not run into this before bc when i call for a CopyToTable, i'm calling a custom class where i've already provided those abstractproperty attributes

I don't show a dynamic dependency [here](https://gist.github.com/dlstadther/eec24fe797d7c86ec1a19389a0ce9d7c), but I do show how i instantiate a Redshift S3CopyToTable class. The configuration of the db args are pre-set and I only have to supply that which changes (table, etc).

**Comment by charlesoblack** [comment]
That looks perfect, actually. I'll try implementing this in my project and if all goes well close the issue. Thanks @dlstadther !

**Comment by charlesoblack** [comment]
It took a little bit to get the params working properly but the dynamic task creation works now. Thanks again dlstadther.

For anyone who comes across this issue later: this is the code I am using now:

```python
@inherits(Task1,Task2)
class PostGreSQLTask(postgres.CopyToTable):

	columns = Parameter()
	password = Parameter(visibility=ParameterVisibility.PRIVATE)
	table = Parameter()
	fn = Parameter()

	host='our_host'
	database='our_db'
	user='my_user'
	column_separator = ','

	def requires(self):
		return self.clone(self.fn)

@inherits(Task1,Task2)
class PostGreSQLTaskWrapper(WrapperTask):

	password = Parameter(visibility=ParameterVisibility.PRIVATE)

	jobs = [{'fn':Task1,'table':'table_1','columns':[('col1','type1'),('col2','type2'),('col3','type3')]},
		{'fn':Task2,'table':'table_2','columns':[('col4','type4'),('col5','type5'),('col6','type6')]}]

	def requires(self):
		for job in self.jobs:
			self.table = job['table']
			self.fn = job['fn']
			self.columns = job['columns']
			yield self.clone(PostGreSQLTask)
```

Conceptually, the way it works is: `Task1` and `Task2` are both "normal" Luigi `Task`s that you set up manually. The `PostGreSQLTask` is a subclass of `postgre.CopyToTable`, except with some of our parameters hardcoded in (column separator, host, database, user). It inherits the tasks that might be required (this is for the `Parameter`s that may be needed).

The `PostGreSQLTaskWrapper` is a wrapper task that dynamically changes the `table`/`columns` attributes according to the `jobs` dictionary, then calls `clone(PostGreSQLTask)`. `clone(fn_arg)` calls the argument `fn_arg` with only the common parameters between the calling task and the called task. This way only the relevant parameters are passed to `PostGreSQLTask`.

Inside `PostGreSQLTask`, it also dynamically requires a function; this is also called with `clone()` so that only the relevant parameters are passed down the line.

For adding a new job, you'd have to include it in both the `inherits` decorators, as well as a larger description (i.e. which table/columns to write to) in the `jobs` dictionary. I'm not really sure how to make it any better than this - ideally you'd only add the required job to the `jobs` dict but then the params might be missing. If anyone can figure out a better way, I'd love to hear about it.
