### ISSUE TITLE
Feature request: Detailed example of ECSTask usage

### ISSUE THREAD

**Issue by allyunion** [spotify/luigi#2677]
It would be nice to have a detailed example of ECSTask as well as supporting documentation and AWS account setup

**Comment by dlstadther** [comment]
I'll tag the contrib/ecs.py contributors here to see if anyone can help you out:
@vanhove  @daveFNbuck  @dfeldstarsky

**Comment by dfeldstarsky** [comment]
Hmm not a bad idea - unfortunately we're working off a fork of ECS task at my company that we're getting up to snuff to get back into luigi atm. We'll make a note to get better ECS task usage examples in if we can as well. We ran into difficulties very early on with getting ECS permissions all set up, but it was ECS problems, not luigi issues.

**Comment by allyunion** [comment]
Still an issue.

**Comment by alxjsn** [comment]
@dfeldstarsky any chance you could share the fork you have?
