### ISSUE TITLE
2.7 to 2.8 upgrade path?

### ISSUE THREAD

**Issue by rayrrr** [spotify/luigi#2684]
Revisiting familiar territory here. We are using luigi 2.7.6 and tried unsuccessfully some time ago to upgrade to 2.8.x, as reflected in #2507. Now we tried again, and are seeing the same exact error as described in #2535.

Here is the behavior I'm now seeing with 2.8.3:

- The UI "Done Tasks" tile shows a spinning loading icon, that's it. Examining the JavaScript console reveals a 500 error associated with the `task_list` endpoint.

- Our actual DAG is running fine. The bug is limited to the Luigi UI.

- We do use a `state.pickle` file but even after deleting it after upgrading and rebooting the cloud "server," the bug persists.

Given the PR to "resolve the upgrade issue" (https://github.com/spotify/luigi/pull/2537) was closed without being merged is there a working upgrade path for existing users to 2.8 at this time? Or should we just stay on 2.7.6 for now?

**Comment by rayrrr** [comment]
Not sure what "thumbs up" means in this context, @Tarrasch , but thanks. If I don't hear anything from the team by EOW we'll just roll back to Luigi version 2.7.6 which we know has a working UI in our use case.

**Comment by Tarrasch** [comment]
Thumbs up == Thanks for well written issue.

Unfortunately I don't know any answers to this issue. Good luck to your team!

**Comment by rayrrr** [comment]
Rolling back to 2.7.6. Thanks for the clarity.

**Comment by rayrrr** [comment]
Reopening this issue because of new information. Tried some other versions and confirmed that 2.7.7 is when the UI breaks. Seems like the issue has something to do with the parameter visibility features added in PR #2278.

The traceback of the exception is as follows (using v2.7.9 on this test):

```
File "/usr/local/lib/python3.6/site-packages/luigi/scheduler.py", line 1430, in task_list
    'display_name': task.pretty_id,
File "/usr/local/lib/python3.6/site-packages/luigi/scheduler.py", line 351, in pretty_id
    AttributeError: 'Task' object has no attribute 'public_params'
```

Will investigate further as time permits.
