### ISSUE TITLE
Global parameters when workers != 1 not being passed to workers

### ISSUE THREAD

**Issue by veltzerdoron** [spotify/luigi#2693]
I'm not sure what the status of global parameters (apart from being in the documentation), I tried to use them but since I plan on using palatalization I can't since whenever I use run with workers != 1 the global parameter values don't seem to propagate correctly to the workers (I get the default value for the parameter), I say it doesn't propagate to the workers because if I break the run before the workers are assigned the tasks the values seem to be as passed in the command line.

**Comment by veltzerdoron** [comment]
I am looking for the standard way to share common task parameters, if Global config can't be relied on I could give all tasks of type A a parameter to set is as global but thing is that if I build a hierarchy of task classes, inheriting classes won't get the common parent's parameter since luigi only propagates the parameters to the actual parent Task and not children of that Task.

**Comment by Tarrasch** [comment]
Reproducible test case would help here.

**Comment by hirolau** [comment]
I have had problems with logging that I think are related. See issue:

 https://github.com/spotify/luigi/issues/2247

The problem is that variables cannot be shared when forking in Windows, simply due to the model or spawning processes in the OS. Window  does not allow subprocess read-only access to objects in the parent process's space, Linux do.

Can you confirm that you are using Windows? If so I do not think there is a good solution, other than creating a permanent file or other temporary storage and have each sub-process re-read them.

In our logging setup on Windows, I have each worker re-read the logging config at startup.

**Comment by veltzerdoron** [comment]
Yep, I'm developing using windows and deploying on redhat, I had to drop the global config way to out of other reasons so this is not an issue anymore for me, but thanks for the tip, its good to know that issues are handled.

Also, FYI, the solution you propose doesn't use luigi parameters which means that there is no single task per set of parameters which is bad for caching, recalculation, stuff like that...

**Comment by veltzerdoron** [comment]
Come to think of it you guys might be interested in the other reason I decided not to use global parameters from a design concern...

I needed to be able to run the inards of the task outside of the luigi framework in order to speed up prediction of my ML models, so, I have run which among other things has an inner process(message) method that processes a single message and my pipeline designers must adhere that piping large amounts of messages through the pipeline tasks will lead to training but then that in order to process a single message I just need to build the dependency DAG and pump that message in order along that DAG (the process(message) method works by taking out some features from the message and putting back some other features so that this is totally general for all types of ML pipelines and assures that the production will not be slowed down by using luigi and file Target overheads to pass a single message for prediction while in production)

In order to do this I had to have the parameters during luigi.run equal to the ones that are passed in the task instantiations, Task parameters are ok in this sense, but try as I might I couldn't get global parameters to give me the same parameters when run outside and inside of luigi.run so as I said I stopped using a global config class and instead wrote a method that wraps task instantiation and passed all pipeline (my wrapper class for wrapperTask) parameters to all tasks instantiated in the pipeline.

If you came to this line, thanks for reading this, hope you found it useful.

**Comment by stolpovsky** [comment]
Seeing the same problem: global parameters are not passed to workers on Windows.

**Comment by eewallace** [comment]
Here's a simple script to illustrate the issue. It's just a single task that prints the value of the config parameter and then exits. 
```
import luigi

class test_config(luigi.Config):
    param = luigi.BoolParameter()

class NotDone(luigi.Target):
    def exists(self):
        return False

class A(luigi.Task):
    def requires(self):
        return []

    def run(self):
        print(f"===== test_config.param={test_config().param} =====")

    def output(self):
        return NotDone()

```
Running with 1 worker, I see the expected result:
```
$ python -m luigi A --module luigi_config_test --local-scheduler --test-config-param --log-level WARNING
===== test_config.param=True =====
```
With 2 workers, the config parameter does not get passed to the workers.
```
$ python -m luigi A --module luigi_config_test --local-scheduler --test-config-param --log-level WARNING --workers 2
===== test_config.param=False =====
```

**Comment by DmytroLapshyn** [comment]
Unfortunately multiple workers are not supported on Windows, as stated here: https://luigi.readthedocs.io/en/stable/running_luigi.html?highlight=windows#luigi-on-windows 😞
