### ISSUE TITLE
Luigi Tasks not failing on custom condition

### ISSUE THREAD

**Issue by amirkhn33** [spotify/luigi#2694]
I am trying to load data from text files to PostgreSQL. Code for doing so is written in R and I'm running it from RScript command using subprocess. I've overridden `complete(self)` method to provide a custom condition for Task completion which checks whether or not a new table is created, with a predefined name.

The issue I'm facing is that even though `subprocess.call([command, path2script])` fails, Task is getting completed. Also, those tables are not written in the DB, which means Task should fail as the custom condition evaluates to `False`.
```
import luigi
import subprocess
from sqlalchemy import create_engine

class LoadingFiles(luigi.Task):

    def output(self):
        files_required = [
            luigi.LocalTarget('foo.txt'),
            luigi.LocalTarget('foo2.txt'),
]
        return files_required


class DataLoading(luigi.Task):

    def __init__(self):
        super(DataLoading, self).__init__()
        self.engine = create_engine('postgresql://user:pwd@127.0.0.0/pg_db')
        self.task_complete = False

    def complete(self):
        status = self.engine.dialect.has_table(self.engine, 'data_1', schema='automation') and \
                 self.engine.dialect.has_table(self.engine, 'data_2', schema='automation')
        self.task_complete = status
        return self.task_complete

    def requires(self):
        LoadingFiles()

    def run(self):
        command = '/usr/bin/Rscript'
        path2script = '../RScripts/data_loading.R'
        subprocess.call([command, path2script])

if __name__ == '__main__':
    luigi.run()
```

I've also tried an alternate way but still result is the same.
```
import luigi
import subprocess
from sqlalchemy import create_engine

class LoadingFiles(luigi.Task):

    def output(self):
        files_required = [
            luigi.LocalTarget('foo.txt'),
            luigi.LocalTarget('foo2.txt'),
]
        return files_required


class DataLoading(luigi.Task):

    def __init__(self):
        super(DataLoading, self).__init__()
        self.engine = create_engine('postgresql://user:pwd@127.0.0.0/pg_db')
        self.task_complete = False

    def output(self):
        return luigi.LocalTarget('Script_01_status.txt')

    def requires(self):
        LoadingFiles()

    def run(self):
        command = '/usr/bin/Rscript'
        path2script = '../RScripts/data_loading.R'
        subprocess.call([command, path2script])

        status = self.engine.dialect.has_table(self.engine, 'data_1', schema='automation') and \
                 self.engine.dialect.has_table(self.engine, 'data_2', schema='automation')

        if status:
            with open('Script_01_status.txt', 'w') as wf:
                wf.write("Status : Complete")

if __name__ == '__main__':
    luigi.run()
```

**Comment by rayrrr** [comment]
A workaround here would be to just write a flat file after the table has been created and use that as your output target instead, and skip using a custom complete() condition altogether.

**Comment by amirkhn33** [comment]
That is what I've tried to do in my alternate approach, but that didn't help either.

**Comment by Sahilshetye** [comment]
If I am not wrong. subprocess.call() does not throw error  if the call  fails.Check [this](https://docs.python.org/2/library/subprocess.html#using-the-subprocess-module)

You should use subprocess.check_call() to throw the error.

**Comment by amirkhn33** [comment]
As a hack, I'm throwing an error if my custom condition is not met (i.e., status is False in alternate approach) which will force the task to fail. I could not find a more elegant way to ensure the failure of tasks.
