### ISSUE TITLE
S3 Client doesn't work with TOML configuration

### ISSUE THREAD

**Issue by liamlundy** [spotify/luigi#2698]
When using the TOML configuration, the s3 client breaks.

To reproduce, create luigi.toml configuration file and set the `LUIGI_CONFIG_PARSER` environment variables to `toml` and running the following code:

```
from luigi.contrib.s3 import S3Target
S3Target('test_path')
```

Error:
```
ae_luigi_worker/tasks/pipeline_mta_model_task.py:43: in output
    return self.upload_task.output()
ae_luigi_worker/tasks/pipeline_mta_model_task.py:160: in output
    for output_file in self.run_model_task.output_files]
ae_luigi_worker/tasks/pipeline_mta_model_task.py:160: in <listcomp>
    for output_file in self.run_model_task.output_files]
../../../.local/share/virtualenvs/ae/lib/python3.7/site-packages/luigi/contrib/s3.py:673: in __init__
    self.fs = client or S3Client()
../../../.local/share/virtualenvs/ae/lib/python3.7/site-packages/luigi/contrib/s3.py:106: in __init__
    options = self._get_s3_config()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
key = None

    @staticmethod
    def _get_s3_config(key=None):
>       defaults = dict(configuration.get_config().defaults())
E       AttributeError: 'LuigiTomlParser' object has no attribute 'defaults'
```

This error is occurring at: https://github.com/spotify/luigi/blob/c5eca1c3c3ee2a7eb612486192a0da146710a1e9/luigi/contrib/s3.py#L507 and appears to be due to the fact that the `LuigiTomlParser` doesn't have a defaults method like the standard configuration object. This could be fixed in the s3 client code, but it seems like the interface of the two configuration objects should be standard.

**Comment by tfiers** [comment]
PR for a very similar issue: #2702
