### ISSUE TITLE
2.8.4 is broken for the TOML configuration

### ISSUE THREAD

**Issue by dycw** [spotify/luigi#2703]
[Release 2.8.4](https://github.com/spotify/luigi/releases/tag/2.8.4) included [this change set](https://github.com/spotify/luigi/commit/9afc222c5f3497a512ccf6a76cf03b492ded54ec) (which was used to address [#2656](https://github.com/spotify/luigi/pull/2656)). The unfortunate side-effect is that the TOML configuration is now broken:

`AttributeError: 'LuigiTomlParser' object has no attribute 'has_option'`

This arises because unlike the default `LuigiCfgParser`, the former does not inherit from `configparser.ConfigParser`.

**Comment by dlstadther** [comment]
addressed by #2702 which did not make it into 2.8.4

**Comment by dycw** [comment]
Hi, sorry I missed this (and [#2698](https://github.com/spotify/luigi/issues/2698)) too. I'll close this issue then.
