### ISSUE TITLE
ReadTheDocs: Not Building

### ISSUE THREAD

**Issue by dlstadther** [spotify/luigi#2706]
[Luigi hasn't had a success ReadTheDocs build since late December 2018](https://readthedocs.org/projects/luigi/builds/). The last build failed and no builds have attempted since 2018-12-20.

@Tarrasch @honnix Do either of you have access to that RTD project to investigate further? Or force a new build?

**Comment by honnix** [comment]
I don't think I have access to that. Why would it stop? 🤔

**Comment by dlstadther** [comment]
It looks like @econchick , @erikbern  , and @Tarrasch  are the listed project owners on RTD

**Comment by econchick** [comment]
I manually triggered a rebuild, and it looks like it passed. It was an nondescript error that failed the build, so not sure what was going on. However, it looked like the github incoming webhook integration got dropped, so I re-added that.

Who else can I add as admins of the RTDs site? Let me know your RTD's username. cc @spotify/dataex @spotify/luigi-dev @spotify/datainfra

**Comment by dlstadther** [comment]
Thanks so much @econchick !

**Comment by honnix** [comment]
@econchick Please add me as admin of the site. Thanks.
