### ISSUE TITLE
"sqlalchemy" requirement not in setup.py

### ISSUE THREAD

**Issue by tfiers** [spotify/luigi#2712]
This package is used when task history is enabled for the central scheduler.

**Comment by tfiers** [comment]
I wonder if there was a reason. If not, I'll add it in a PR

**Comment by tashrifbillah** [comment]
Hi @tfiers , did you do it because I don't see it [here](https://github.com/spotify/luigi/blob/master/setup.py#L50).

**Comment by tfiers** [comment]
Nope, feel free to make a PR
