### ISSUE TITLE
SendGrid integration is deprecated

### ISSUE THREAD

**Issue by charlesoblack** [spotify/luigi#2714]
Just like #1956 . Somehow I can't reopen the old issue.

I can work on fixing this, but would appreciate some pointers as to how the config files work exactly.

**Comment by dlstadther** [comment]
The contribution/bugfix is appreciated

What is/are your question(s) about config files?

**Comment by charlesoblack** [comment]
I was under the impression the config worked in a far more complicated manner. Please see PR #2715 . Let me know if any changes need to be done :)
