### ISSUE TITLE
PidLockAlreadyTakenExit

### ISSUE THREAD

**Issue by veltzerdoron** [spotify/luigi#2731]
This lock means that luigi.run() can't be invoked more than once per process, can you please explain why this is so? why not clean the lock once the run is complete? I'm kind of forced to run the method with --no-lock as suggested [here](https://groups.google.com/forum/#!topic/luigi-user/7ZCY18l5uJM), they also suggested opening a luigi issue for this which I'm doing right now, please ask for further details if necessary.

**Comment by kwilcox** [comment]
Is there a reason you are using .run and not .build?  https://luigi.readthedocs.io/en/stable/running_luigi.html#running-from-python-code

**Comment by veltzerdoron** [comment]
I checked luigi build before this and it seems to me that the major difference is that it turns on the no-lock parameter (I mentioned I already stumbled across) by default.

I'm not sure this is a safe way to go?
Will it support multi processing?
Are there any other related issued I should consider?

**Comment by Tarrasch** [comment]
> why not clean the lock once the run is complete?

is it not??

Oh well, I think people rarely call luigi.run() - I still recommend to use the command line to invoke it but I understand that many prefer not to, any reason you don't you `luigi.build()`. If you take a quick look at the implementation you'll see that you it's very similar to `run()`. You won't have any of the issues you mentioned.

**Comment by veltzerdoron** [comment]
Thanks, Tarrasch, for the response, did you take a look at the link I linked to in the first comment?
Its linked to some issue to solve this which never got done to the best of my knowledge.
I came across this issue when I tried to iterate train and test runs on pipelines and found out I can't run two pipelines under the same process even if the pipelines share no tasks. Its also an issue running unit tests as well as some other use cases.

It seems like running without the lock seems to solve but my thought was that if there is a lock it must be used for some reason, can I read more about its purpose or function somewhere? I mean, I'm guessing it wouldn't be there if it doesn't protect some critical section or other.

**Comment by Tarrasch** [comment]
I don't have time to deep dive into this. But the tl;dr; of the lock is that it's super useful when you "overcron" a job. It ensures you don't have the same "cronline" running twice.

**Comment by veltzerdoron** [comment]
No need to deep dive, I appreciate your responses very much.

I see, and the lock is shared across processes, I guess I need to do some tests with running the learning very often. Why then does build not need to lock it?

**Comment by DrPyser** [comment]
I'm getting this in my logs. I'm running luigi as cronjobs. Does this mean the task is being launched while it is already running?
