### ISSUE TITLE
enum34 dependency breaks install using poetry on python 3.7.3

### ISSUE THREAD

**Issue by Timost** [spotify/luigi#2734]
Hi,
I've several projects that depend on luigi, I use poetry to manage their dependencies and when trying to build them on python `3.7.3` the install fails because of `enum34`.
The issue with `enum34` has impacted many well known projects (see https://github.com/sdispater/poetry/issues/1122 for more details):
- https://github.com/sdispater/poetry/issues/881
- https://github.com/sdispater/poetry/issues/844
- https://github.com/tensorflow/tensorflow/issues/15136

It seems these projects had to modify their `setup.py` to properly use environment markers as specified in https://www.python.org/dev/peps/pep-0508/#environment-markers.

I've taken a quick look at the `setup.py` of luigi and there is a comment dating back from 2016 guarding against the use of those environment markers for `enum34`. I was wondering if this was still needed and if not if it could be be modified to conform to PEP508.

**Comment by Tarrasch** [comment]
Hi @Timost, feel free to do a PR making us conform to PEP508 - most maintainers here (including me) are not really packaging gurus. Help to make us conform to the standards would be much appreciated.

**Comment by Timost** [comment]
Hi @Tarrasch, Thank you for your answer.

I'm not a packaging guru either. I've dug into the issue a bit more and it seems that this issue is only present when using poetry with python 3.7.3. Using pip or pipenv, the install works with python 3.7.3.
There are actually two severity degrees to this issue. When installing luigi using poetry on python 3.7.3 the `enum34` package gets installed (although it shouldn't) but the installation succeeds. When using poetry's path dependencies together with poetry and python 3.7.3 the install actually crashes (see https://github.com/sdispater/poetry/issues/1122#issuecomment-500124981)

From what I gather from https://github.com/grpc/grpc/issues/18013#issuecomment-476763524 and https://github.com/sdispater/poetry/issues/328#issuecomment-407472719 poetry does not parse the setup.py file so cannot take into account the `> python 3.4` guard that is implemented in python. Poetry  only parses the data coming from the built package provided by pipy (probably `luigi-2.8.7/luigi.egg-info/requires.txt`), In which `enum34` is listed with no `<python3.4` environment marker.

I've taken a look at https://github.com/spotify/luigi/pull/2623 which actually reverts the changes that are needed for the install to work when using poetry. Since this is a pretty recent PR and the issue seems present only when using poetry, python 3.7.3. I'm not sure what the best decision is.
Either stop supporting very old versions of setuptools and lose support on some plateforms (Google AI/ML from https://github.com/spotify/luigi/pull/2623#issuecomment-459005333, maybe the situation has changed for @brianmartin ) but be compliant with PEP508, or keep supporting old versions of setuptools but luigi cannot be installed with poetry on python 3.7.3 and path dependencies.

Pip runs the setup.py on install so it takes the `<python3.4` guard into account and I don't know what pipenv does but it seems that it does not install the `enum34` package.

**Comment by Tarrasch** [comment]
I think following a PEP standard outweighs demands to support old versions. Is it anyway possible for you to create a PR where you both fix the issue *and* add a automated check (run by Travis) that makes sure we always conform to the standard? That way anyone can later come and "fix" things but they won't be able to unbreak the "follows PEP invariant".

That said, there being an automatic way to check for PEP508 compliance is just wishful thinking from me. :)

**Comment by Timost** [comment]
I'm not sure how automatic PEP508 compliance checks would work. If this was one of my project I would probably add a linting step where I parse the `setup.py` searching for things that look like `if sys.version_info `. I'm not sure if that would make any sense in the context of luigi though. What do you think ?

**Comment by Timost** [comment]
Hi @brianmartin. I just wanted to let you know this is still an issue not only form enum34 but for all the conditional dependencies defined in the setup.py using python logic instead of the new syntax.
I just stumbled on it today (python 3.6.12, luigi 3.0.1) for the tornado dependency.

I can understand if you can't move to the new syntax due to GCP/cloud requirements.
It's quite sad to be stuck to a 4 years old version of setuptools though.
