### ISSUE TITLE
Kubernetes spark operator support

### ISSUE THREAD

**Issue by ekhaydarov** [spotify/luigi#2736]
Currently, when using `from luigi.contrib.kubernetes import KubernetesJobTask` it is only possible to create a Job resource in kubernetes. I am trying to implement a [spark operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator) which is a different kubernetes resource

I was wondering if it would be under luigis scope to implement a more dynamic `KubernetesJobTask`. So far I have tried to just override the run method of the class but the internal methods that check on the job, starting with `self.__track_job()` dont get inherited properly as well as their scope of tracking the `Job` resource only.

My question is, with more and more operators coming into the kubernetes ecosystem it seems some kind of support for that would be good in luigi? 

Thanks

**Comment by dlstadther** [comment]
I'm not aware of the details here around using different operators in Kubernetes (specifically how the contrib.kubernetes module is setup), but I'd support a generalized structure which maintains the current behavior by default.

I'll tag the original author here in hopes they can provide more specific insight.

@mcapuccini

**Comment by mcapuccini** [comment]
Hi! Good point. When we fist implemented this, operators didn't exist yet. I don't have time to work to this right now, but essentially the [job_json](https://github.com/spotify/luigi/blob/master/luigi/contrib/kubernetes.py#L340) definition is what should be adapted to enable operators. It may be good to just enable any kind of k8s json definition?

If your goal is to send a Spark job, my suggestion is to try to use the native k8s support in Spark and use to the Spark job support in Luigi. You should be able to just specify the k8s master as Spark master.

I hope this helps, and good luck!
