### ISSUE TITLE
History page is unavailable from the central visualizer page

### ISSUE THREAD

**Issue by charlesoblack** [spotify/luigi#2743]
I can't seem to find a link to the task history from the central visualizer page. Am I missing a link somewhere?

**Comment by shan224** [comment]
You have to visit the /history url directly. 

> This information is exposed via the Central Scheduler at /history.

https://luigi.readthedocs.io/en/stable/central_scheduler.html#enabling-task-history

**Comment by charlesoblack** [comment]
Yes, I've been accessing it like that. But maybe there should be a hyperlink on the central visualizer page that points us to the /history url?

**Comment by shan224** [comment]
I would like to see that feature as well. Not sure what the maintainers think

**Comment by dlstadther** [comment]
Is #2759 what you're asking for?

**Comment by charlesoblack** [comment]
Yep! That looks like exactly what I wanted, at least. Thanks @riga !
