### ISSUE TITLE
No best practice for noop?

### ISSUE THREAD

**Issue by charlesoblack** [spotify/luigi#2744]
Some pipelines don't have any new data to push through and thus end up in "noop" state. However, there don't seem to be good noop handling practices; the only solution I've found is to add a "if there is no data" check wrapping the entire run function. Should this be the way to go? Or maybe there's a different way of doing things that I'm not aware of?

**Comment by Tarrasch** [comment]
I often create the `output()` folder and write a dummy (empty) file like `SUCCEDED` in the folder. But yes I'm not really sure what to do for the cases where your `output()` isn't for a file system.

**Comment by charlesoblack** [comment]
Yeah, here's the solution I came up with:

    self.output().makedirs()

    with self.input().open('r') as f:
        df = read_pickle(f, compression=None)

    if df.empty:

        def complete(self):
            return True

        with self.output().temporary_path() as temp_output_path:
            df.to_pickle(temp_output_path, compression=None)

        return

for pandas DataFrames. Obviously this is not very elegant but it works for now...
