### ISSUE TITLE
Luigi atomic write fails with pandas.DataFrame.to_pickle() in pandas 0.25.0

### ISSUE THREAD

**Issue by charlesoblack** [spotify/luigi#2750]
It seems in pandas 0.25.0 that when `to_pickle()` is called, it closes the file before Luigi does. This throws the following error:

    Traceback (most recent call last):
      File "c:\python37\lib\site-packages\luigi\worker.py", line 199, in run
        new_deps = self._run_get_new_deps()
      File "c:\python37\lib\site-packages\luigi\worker.py", line 141, in _run_get_new_deps
        task_gen = self.task.run()
      File "C:\git\chess-pipeline\chess_pipeline.py", line 81, in run
        df.to_pickle(f, compression=None)
      File "c:\python37\lib\site-packages\luigi\target.py", line 349, in __exit__
        return super(AtomicLocalFile, self).__exit__(exc_type, exc, traceback)
      File "c:\python37\lib\site-packages\luigi\target.py", line 329, in close
        self.move_to_final_destination()
      File "c:\python37\lib\site-packages\luigi\local_target.py", line 40, in move_to_final_destination
        os.rename(self.tmp_path, self.path)
    FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\abcd/Temp/luigi/raw-games.pckl-luigi-tmp-910384860' -> 'C:\\Users\\abcd/Temp/luigi/raw-games.pckl'

Sample Tasks:

    class SampleTask(Task):
    
        def output(self):
            return LocalTarget('testfile.pckl', format=Nop)
    
        def run(self):
            from pandas import DataFrame
    
            self.output().makedirs()
    
            df = DataFrame()
    
            with self.output().open('w') as db:
                df.to_pickle(db, compression=None)
    
    
    @requires(SampleTask)
    class SampleTask2(Task):
    
        def run(self):
            from pandas import read_pickle
    
            with self.input().open('r') as f:
                df = read_pickle(f, compression=None)

The above works in pandas 0.24.2 but not 0.25.0, all other dependencies being equal. I suspect the line that affects it is [this one](https://github.com/pandas-dev/pandas/blob/3b96ada3a17f5fcc8c32a238457075ec4dd8433a/pandas/io/pickle.py#L78). Any ideas on how to fix this?

**Comment by kwilcox** [comment]
`to_pickle` takes a filepath, not an open file handle: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_pickle.html. The fact that this worked in 0.24.2 is probably no fault of luigi.

try:

```
df.to_pickle(self.output().path, compression=None)
```

**Comment by charlesoblack** [comment]
Oh, I see. It's a little inconsistent behavior on pandas' side, since other `to_...` functions accept file buffers too. I'll take a look into `temporary_path()` and close once I have it, thank you!

**Comment by charlesoblack** [comment]
Yep, looks like this works:

    class SampleTask(Task):

        def output(self):
            return LocalTarget('testfile.pckl', format=Nop)

        def run(self):
            from pandas import DataFrame

            self.output().makedirs()

            df = DataFrame()

            with self.output().temporary_path() as temp_output_path:
                print(temp_output_path)
                df.to_pickle(temp_output_path, compression=None)


    @requires(SampleTask)
    class SampleTask2(Task):

        def run(self):
            from pandas import read_pickle

            with self.input().open('r') as f:
                df = read_pickle(f, compression=None)

Thanks for your help!
