### ISSUE TITLE
current working directory not in sys.path causing "module not found" errors

### ISSUE THREAD

**Issue by jocassid** [spotify/luigi#2752]
I just found out about luigi this afternoon and started teaching myself how to use it.  

I set up an environment in `/home/john/Practice/luigi/`.  I created a hello_luigi.py based on an example in the documentation in `/home/john/Practice/luigi` While in `/home/john/Practice/luigi` I ran the command `luigi --local-scheduler --module hello_luigi MyTask --x 1 --y 2` and got a "hello_luigi" module not found error.  I modified  `/home/john/Practice/luigi/bin/luigi` to print the contents of `sys.path` and found out that whereas the `bin` directory was on the path it's parent (and my current working directory) `/home/john/Practice/luigi` was not.  By adding a symbolic in bin using the command `ln -s ../hello_luigi.py hello_luigi.py` I could get it to run.  This experiment with the symbolic link led the way to my workaround which is to add the following lines to  `/home/john/Practice/luigi/bin/luigi` just under `if __name__ == '__main__`

```
    cwd = getcwd()
    if cwd not in sys.path:
        sys.path.insert(0, cwd)
```
I see a `bin/luigi` file in the source code, but it differs from what I'm seeing.  I'm guessing this file is altered by the setup process.  The need for this hack was unexpected.  Skimming through the documentation I didn't see anything as to how a luigi project directory should be set up (i.e. where do the modules with my tasks go?).  Is there some `luigi.cfg` option that fixes this problem?

**Comment by dgronskij** [comment]
This has nothing to do with `luigi` itself: when it sees '--module hello_luigi' it (roughly saying) tries to import it by means of standard python import system. It's just as if you wrote `from hello_luigi import MyTask` in your arbitrary script , so the `hello_luigi` module must be visible to Python interpreter. The list of locations where Python looks for packages is governed by `sys.path` list which can be configured via `PYTHONPATH` environment variable. Thus, doing

`export PYTHONPATH="$PYTHONPATH:<directory where hello_luigi.py resides>"` before runng scripts must help.

**Comment by jocassid** [comment]
I think we need to include instructions about modifying `PYTHONPATH` right after the `pip install` command.  

[Some musings on technological work-arounds]
I've written Python programs for years and I don't think I've modified `PYTHONPATH` more than once or twice, so this caught me surprise.  I'm comparing this to some other packages that I've used (pytest, Django, Jupyter, pyflakes).  Django is probably the best parallel in that you have a main script that comes with the package which runs your code.  It side-steps the `PYTHONPATH` issue by dropping a script (`manage.py`) in your code directory when you run it's `django-admin` script to start the project.  Perhaps a more descriptive "You need to add your directory full of tasks to the `PYTHONPATH`" error message.

I'm aware of the practice of separating out my source code from the virtualenv.  To just crack open a package and try some "hello world" examples I usually don't bother to create the 2 separate directories.

**Comment by shouldsee** [comment]
Modifying PYTHONPATH seems a bad idea to introduce python2/3 incompatibility. If you check 
`python3 -c "import sys;print(sys.path)"` you would see an empty string included `[''",... ]`. Setting `luigi` to behave differently from `python3 -c` would violate the minimal surprise principle
```
###['', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '/home/shouldsee/.local/lib/python3.5/site-packages', '/home/shouldsee/.local/lib/python3.5/site-packages/smop-0.32_7_gcce8558-py3.5.egg', '/home/shouldsee/.local/lib/python3.5/site-packages/simplesbml-1.1-py3.5.egg', '/home/shouldsee/.local/lib/python3.5/site-packages/pip-20.1-py3.5.egg', '/usr/local/lib/python3.5/dist-packages', '/usr/lib/python3/dist-packages']
```

I am making a monkepatch that could be tested.
