### ISSUE TITLE
Unfulfilled External Tasks do not trigger error emails

### ISSUE THREAD

**Issue by dlstadther** [spotify/luigi#2766]
Incomplete External Tasks do not cause error emails due to their lack of completeness being defined as a WARNING.

https://github.com/spotify/luigi/blob/e2228418eec60b68ca09a30c878ab26413846847/luigi/worker.py#L830-L837

I would propose that this should be updated to an Error.

For automated pipelines where you expect to have received an external dependency and it doesn't exist, that's an error.

As a warning, when this event occurs it acts as a silent error. The pipeline will "fail" due to inability to schedule upstream tasks, but no error emails are sent. Requires digging through logs to find this warning for missing dependency.

I've been unable to find any discussion about the motivation for leaving it as a warning. This line's origin dates back to [early 2012](https://github.com/spotify/luigi/commit/cac259af401a2db13c7d4c5bf9ba14fa5de0963c) with only languages changes over time.

Thought?

I'm happy to submit that PR

**Comment by dlstadther** [comment]
FYI: @honnix @Tarrasch

**Comment by Tarrasch** [comment]
From how I've seen ExternalTask being used, it doesn't make sense for an email to be sent. Usually you keep re-scheduling the workflow which have an ExternalTask, long before you expect your data dependency to actually exist, eventually the data will be there and it's so cheap to try.

In a more sophisticated workflow tool one should be able to say that a data dependency should have a SLA (service level agreement, like "6am UTC every day"). If this kind of functionality makes it into luigi I think it makes more sense for this to be stored, checked, surfaced and potentially email (or alarm somehow) from the _scheduler_. You could have a tab for "delayed dependencies" etc. Does that make sense?

**Comment by dlstadther** [comment]
In my cases, i use external tasks to denote requirement of files which fall under the responsibility of another team or another org. In the event those files do not exist when they should, my tasks fail - but they do so silently. My custom alerting tells me my tasks never completed, but i have to search logs to find why. 

Perhaps i don't use external tasks as they were originally designed such that the silent failure and retry makes sense.

**Comment by hirolau** [comment]
Now I am no expert with all use-cases and how people are running pipelines. But if you just trigger jobs and do not keep workers alive would not this work? Just add a failing run methods after the SLA has passed...
```Python

class SLAMissException(Exception):
    pass

class ExternalFileWithSLA(luigi.ExternalTask):

    sla = luigi.DateMinuteParameter()

    def __init__(self, *args, **kwargs):

        if kwargs["sla"] > datetime.datetime.now():
            self.run = self.sla_miss
        else:
            self.run = None

        super().__init__(*args, **kwargs)

    def sla_miss(self):
        raise SLAMissException(f'Expected to be completed by {self.sla}')

    def output(self):
        path_given_sla = self.sla.strftime("//path/to/my/external/file_%y%m%d.csv")
        return luigi.LocalTarget(path_given_sla)

```

Another solution is to have a condition in the requires method to only add the external dependencies before the SLA has been hit, after that you remove them, and the task itself will fail when running.

```Python
class MyTask(luigi.Task):
    
    ...

    def requires(self):
        ...

        for task in requirements:
            if task.sla_not_hit:
                yield task(parameter=parameter)
```
