### ISSUE TITLE
SQLServer incompatibility with task history: Operand type clash: datetime2 is incompatible with timestamp

### ISSUE THREAD

**Issue by shan224** [spotify/luigi#2769]
Error occurs when accessing the /history endpoint and when using pyodbc+mssql. 

Root cause: 
The TaskEvent class creates a column of type [TimeStamp.](https://github.com/spotify/luigi/blob/0f31f07ecc58acda864e14ae563484865ff3128a/luigi/db_task_history.py#L213) Which is incorrect for mssql because the [mssql implementation of TimeStamp](https://github.com/zzzeek/sqlalchemy/blob/7e0dfd2ad4141289a992adc65d2a6641f46dc82d/lib/sqlalchemy/dialects/mssql/base.py#L1039) is different from the SQL standard 🙄 .

Solution: 
This column needs to be defined as of type DateTime2 if connecting to mssql

**Comment by shan224** [comment]
Update: 

I have tested that the column type is DATETIME2. 
However, I get another error when accessing the /history endpoint 

```
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Column 'tasks.task_id' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause. (8120) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")
[SQL: SELECT tasks.id AS tasks_id, tasks.task_id AS tasks_task_id, tasks.name AS tasks_name, tasks.host AS tasks_host
FROM tasks JOIN task_events ON tasks.id = task_events.task_id
WHERE task_events.ts >= ? GROUP BY tasks.id, task_events.event_name, task_events.ts ORDER BY task_events.ts DESC]
[parameters: (datetime.datetime(2019, 8, 19, 10, 53, 33, 459352),)]

```

I tried using an explicit select ([previous line](https://github.com/spotify/luigi/blob/0f31f07ecc58acda864e14ae563484865ff3128a/luigi/db_task_history.py#L163))  which cleared a few errors.

 ``` 
return session.query(TaskRecord.id, TaskRecord.name, TaskRecord.host, TaskEvent.event_name,TaskEvent.ts).\
                join(TaskEvent).\
                filter(TaskEvent.ts >= yesterday).\
                group_by(TaskRecord.id, TaskRecord.name, TaskRecord.host, TaskEvent.event_name, TaskEvent.ts).\
                order_by(TaskEvent.ts.desc()).\
                all()
```

 But it seems like the attributes form the tasks object being render in server.py and recent.html dont match up with the query. 

I'm unfamiliar with tornado and don't have much time to keep going down this path unfortunately.

**Comment by albuquerquejp** [comment]
Is there any update on this error?
