### ISSUE TITLE
Task died unexpectedly with exit code -11

### ISSUE THREAD

**Issue by deatinor** [spotify/luigi#2774]
Hello, my Luigi pipeline failed with this error.

Do you have an idea what does it mean? I didn't find any documentation regarding this.
I have no clue about what could have caused this error.

Thank you!

**Comment by lallea** [comment]
IIRC, it means that one of your tasks launched a program, which ran into a segmentation fault (signal 11).

**Comment by Bonsanto** [comment]
@lallea Something similar happened to me. I have a Task that trains a machine learning model using sklearn's GridSearchCV and it runs perfectly when I use luigi 2.7.5 but when I use luigi 2.8.9. Perhaps I am wrong but if it had to do with a segmentation fault, shouldn't it happen with both versions. Am I missing something?  Thanks!

**Comment by lallea** [comment]
Luigi cannot cause a segmentation fault inside a spawned process. Butterfly effects can, however. If your program has wild pointers, a slight change in the environment, or in timing, can trigger a segmentation fault.

**Comment by Bonsanto** [comment]
I see, nevertheless I can replicate this problem just by changing Luigi's library version. This is why I thought it was related to Luigi.

**Comment by luizender** [comment]
The same issue for me running with luigi 2.8.11. But I did not test in luigi 2.7.5 to see if its work without any problem.

**Comment by lallea** [comment]
This is almost certainly a symptom of a problem with a program that is started from Luigi, and not with Luigi itself. I suggest closing this issue.

If you want to debug the issue, searching the web for "segmentation fault" yields some starting points, linked below. Segmentation faults happen primarily in C/C++ programs, but can also occur in other languages that link in C libraries. 

https://en.wikipedia.org/wiki/Segmentation_fault
https://stackoverflow.com/questions/2346806/what-is-a-segmentation-fault
https://www.cprogramming.com/debugging/segfaults.html
https://kb.iu.edu/d/aqsj

**Comment by Tarrasch** [comment]
Closing for the reasons provided by @lallea.
