### ISSUE TITLE
Feature request: Progress reporting during requires()

### ISSUE THREAD

**Issue by evictor** [spotify/luigi#2776]
It would be nice to be able to use `set_progress_percentage` during `requires()` for tasks that take a while to calculate and yield dependencies (e.g. migration-type wrapper tasks). LMK if you need an example of why I would want to do this if it is not obvious and I will write something up.

**Comment by Tarrasch** [comment]
Calling `requires()` should have no side effects in general (so is almost fast). So not sure if we want to increase functionality of luigi to support this (I mean it's maybe not worth the added maintenance burden).

**Comment by evictor** [comment]
Roger... Perhaps the alternative implementation strategy should be to use dynamic dependencies then in `run()`?
