### ISSUE TITLE
Parallel scheduling hangs with no output

### ISSUE THREAD

**Issue by evictor** [spotify/luigi#2777]
Luigi verison 2.8.7

I'm attempting to use parallel scheduling for a migration task that needs to schedule several thousand dependencies. Normally (without parallel scheduling), I see this kind of output once scheduling begins:

```
16:24:10 INFO:luigi-interface:Informed scheduler that task   RepredictWithDemogFallback_0_047b165dd5   has status   PENDING
```

However when using parallel scheduling, this console output from Luigi never appears, and in the Luigi Web GUI nothing appears to be scheduled; instead the runner just hangs and nothing ever happens.

Please LMK what debug logs I can provide.

**Comment by ryantam626** [comment]
Hello, just randomly browsing issues and found this.

Try making sure your tasks can be pickled, a test that ensures your tasks can suvive pickle roundtrip would be nice. (i.e. something like `assert pickle.loads(pickle.dumps(task_instance)) == task_instance`) At least that was what was causing issue for me.

The code where luigi does parallel scheulding fails sliently when tasks are not pickle-able, it's entirely possible that there are other issues, I would recommend placing `pdb.set_trace()` in the relevant places and see what's going on if my suggestion didn't fix your issues.

**Comment by evictor** [comment]
Thx for the notes. Is it possible to implement something that logs errors when tasks are not pickleable? I can, of course, write tests on my end, too, but I imagine the error logging would be trivial to implement...

**Comment by ryantam626** [comment]
I don't maintain project this btw. I was just stating what my issue was and how you can go about fixing it.

Also, it seems there are some logging and error handling already, but somehow the exception is not bubbling up correctly :thinking: 
https://github.com/spotify/luigi/blob/b9a1bbd1d7cf0b583c06b6142585b90aeeff373c/luigi/worker.py#L771
