### ISSUE TITLE
System Requirements?

### ISSUE THREAD

**Issue by cowlinator** [spotify/luigi#2784]
The documentation lacks sufficient information about the things Luigi depends on (a.k.a. System Requirements, a.k.a. Prerequisites).

For example, the Central Scheduler requires a Unix-based OS.

**Comment by charlesoblack** [comment]
I run a central scheduler on Windows 10 just fine.

**Comment by cowlinator** [comment]
I swear I had a good reason for believing that the central scheduler requires linux.  But I can't remember it now so I suppose it doesn't matter.

**Comment by pybokeh** [comment]
Hi @charlesoblack I'm on Windows 10.  I can run luigid command without the --background flag and I can access http://localhost:8082/static/visualiser/index.html  But my Luigi tasks are not able to connect to the central scheduler.  I get the following errors:

```
WARNING: Failed connecting to remote scheduler 'http://localhost:8082'
```
and also:
```
requests.exceptions.HTTPError: 500 Server Error: INKApi Error for url: http://localhost:8082/api/ping
```

**Comment by cowlinator** [comment]
@pybokeh , maybe you should open a new issue

**Comment by pybokeh** [comment]
@cowlinator I will as soon as I explicitly set host and port and see if I still have the same problem.

**Comment by pybokeh** [comment]
@cowlinator @charlesoblack I forgot to include the --scheduler-host flag and just pass the host ip after that flag.  For example: 

```python my_script.py --scheduler-host localhost TaskName```

So all is good.  User error on my part!
