### ISSUE TITLE
Feature Request: free resource at tasks' run time

### ISSUE THREAD

**Issue by FxIII** [spotify/luigi#2787]
### Rationale
The resource declaration mechanism allows the scheduler to delay the execution of tasks when there are not enough resources available for them.

Currently the resource allocation is bound to the task lifetime i.e. resource are allocated by the scheduler before the task execution and freed upon task completition/exit.

While the resource allocation needs to be done upfront by the scheduler, the tasks should be allowed to notify the scheduler if they released some of the declared resources _**before**_ the tasks completition/exit.

This should prevent long running tasks to stop other tasks if the firsts use the resources for a fraction of their time.

### Feature Request
A task method that notifies the scheduler that a subset of the allocated resources can be deallocated. Something like
```python
self.free_resources(stone=1, wood=2)
```
which frees one stone and two woods; obviously exceeding values should be clamped to actually allocated resources.
optionally
```python
self.free_resources()
```
should free all the allocated resources as if the task was completed/terminated.

**Comment by lallea** [comment]
One could handle such scenarios by splitting the task into multiple tasks, and have the part of the computation that requires a resource in a dedicated task. Splitting tasks covers the use cases that I can think of. Do you have an example of where the manual resource handling you suggest would be necessary?

**Comment by FxIII** [comment]
I have some tasks with a huge disk read hit at the beginning, then some cpu intensive workload and a write of a small synthetic data. I would like to mitigate the disk load by stagger them acquiring some disk resource and release as long as the read is done.
In this setting the task splitting is not a viable solution and I can guess that some other use cases like this can benefit on a in-process resource release.

**Comment by lallea** [comment]
I see. Since the protected resource is disk bandwidth, I assume that the tasks compete for on a single machine, or at least have a shared file system. Could you reserve the resource with a lock file instead? I guess that your use case is rare, and that the added scheduler complexity is not justified, and/or the problem can usually be addressed by other means.

**Comment by FxIII** [comment]
I can use some external lock mechanism, of course, yet I think that this responsibility lies with the scheduler. 
IMHO one should not be forced to tailor the tasks granularity just to overcome the scheduler assumptions about the resource usage.
By the way, I can see your point: I went through the code and this change is not perfectly straightforward. 
May I try to make a lightweight implementation or do you think it wont be accepted anyhow?

**Comment by ThePletch** [comment]
https://luigi.readthedocs.io/en/stable/luigi_patterns.html#decreasing-resources-of-running-tasks Does this existing feature not cover your use case?

**Comment by FxIII** [comment]
yes @ThePletch, it does absolutely! I completely miss that (even when I tracked scheduler.py for task.resources_running).
