### ISSUE TITLE
Need documentation on "assistant" feature

### ISSUE THREAD

**Issue by ttpro1995** [spotify/luigi#2790]
I would like to read documentation on "assistant", which is mention on #1217 . 

I can't find any detail about assistant on current stable build [documentation ](https://luigi.readthedocs.io/en/stable/index.html).

Something like How to use, Systax, Example will be helpful.

**Comment by Tarrasch** [comment]
I wish I had written the documentation while I still had everything in my head :(.

The "not terrible" new is though that I'm sure you can find some of my old posts in the luigi users email. I challenge you to learn the usage and then create the docs. :)

**Comment by ttpro1995** [comment]
I think this is the luigi users email @Tarrasch  mention 
https://groups.google.com/g/luigi-user/c/ytSSbOhAFaM?pli=1
