### ISSUE TITLE
"ValueError: Unknown format code 'd' for object of type 'str'"

### ISSUE THREAD

**Issue by sarwatfatimam** [spotify/luigi#2792]
I am trying to override the scheduler_host in luigi.build in order to connect to luigid in docker.  However, it gives a format error as follows. 

```
luigi.build([MyTask()], scheduler_host="0.0.0.0", scheduler_port="8082")

```

I believe the issue in the function **_schedule_and_run** in the following code. I don't think so the URL port should have "d" after ':' has {port:d}

``` 
if env_params.local_scheduler:
        sch = worker_scheduler_factory.create_local_scheduler()
    else:
        if env_params.scheduler_url != '':
            url = env_params.scheduler_url
        else:
            url = 'http://{host}:{port:d}/'.format(
                host=env_params.scheduler_host,
                port=env_params.scheduler_port,
            )
```

**Comment by victoriaalee** [comment]
`:d` specifies type conversion of `port` from integer to str. You should pass `scheduler_port` as an integer.

```python
luigi.build([MyTask()], scheduler_host="0.0.0.0", scheduler_port=8082)
```

**Comment by ihowell** [comment]
@sarwatfatimam , did @victoriaalee fix your problem? Can this issue be closed?
