### ISSUE TITLE
Luigi Tasks get stuck in 'RUNNING' state when emails are not properly setup

### ISSUE THREAD

**Issue by junisaji** [spotify/luigi#2793]
We have been seeing tasks get stuck in a 'RUNNING' state, where the task is not actually progressing and which causes errors trying to schedule similar tasks. We were also seeing a ton of log lines with the following stack trace:

```
      File "/opt/virtualenv/luigi2/local/lib/python2.7/site-packages/luigi/scheduler.py", line 1202, in get_work
        reply = self.count_pending(worker_id)
      File "/opt/virtualenv/luigi2/local/lib/python2.7/site-packages/luigi/scheduler.py", line 1069, in count_pending
        more_info = {'task_id': task.id, 'worker': str(other_worker)}
    TypeError: __str__ returned non-string (type NoneType)
```

This issue seems to have been reported here: https://github.com/spotify/luigi/issues/2200 though was closed after some time.

After a few days of debugging, we've determined that the root cause was that our email configuration was set up incorrectly. Our full root cause analysis from the post mortem is below:

**Why were users unable to run certain tasks?**
When a task is kicked off, the Luigi worker checks to make sure that a task with the same id (essentially task family and parameters) is not running. It does this by calling the /get_work api on the scheduler. Unfortunately, the scheduler was throwing 500s for these tasks, causing the worker to abort.

**Why was the Luigi scheduler throwing 500s on /get_work?**
The /get_work api does a number of things in the process of deciding which piece of work to assign to a worker. One of these things is to catalog the number of pending tasks, running tasks, and the worker state. This piece of code attempts to do so:

```
for task in worker.get_tasks(self._state, RUNNING):
    if self._upstream_status(task.id, upstream_status_table) == UPSTREAM_DISABLED:
        continue
    # Return a list of currently running tasks to the client,
    # makes it easier to troubleshoot
    other_worker = self._state.get_worker(task.worker_running)
    if other_worker is not None:
        more_info = {'task_id': task.id, 'worker': str(other_worker)}
        more_info.update(other_worker.info)
        running_tasks.append(more_info)
```

The following stack trace illustrates the bug, that other_worker is unfortunately returning None from its __str__ method:
```
      File "/opt/virtualenv/luigi2/local/lib/python2.7/site-packages/luigi/scheduler.py", line 1202, in get_work
        reply = self.count_pending(worker_id)
      File "/opt/virtualenv/luigi2/local/lib/python2.7/site-packages/luigi/scheduler.py", line 1069, in count_pending
        more_info = {'task_id': task.id, 'worker': str(other_worker)}
    TypeError: __str__ returned non-string (type NoneType)
```

**Why was other_worker returning None from __str__?**
Tracing back up through the code, the Worker class implements __str__ by returning self.id, which is normally a string, but in this case was None. Tracing further, this happens because the task in the above code is both RUNNING, and worker_running is None. This is a corrupted task, as a task that is running should always have a worker that is running it.

**Why were these tasks corrupted?**
These tasks became corrupted when they failed on the workers. When a task fails, the worker makes an api call to /add_task, which informs the scheduler that the task has failed. The worker will retry, but eventually, a task will fail so many times that the scheduler decides the task should be disabled. Within /add_task, the code calls a function to update the state of the task, which, simplified, does the following:

Housekeeping, like adding a failure log to the task, setting scheduler_disable_time, and setting worker_running to None.
Send an email to warn that the scheduler is disabling a task
Actually change the state of the task

Unfortunately, because there was an exception sending the email, the task never gets to correctly set the state of the task to disabled, and the task is left in RUNNING but with a worker_running of None.

**Why was an exception thrown while trying to send an email?**
Diving a bit deeper into the logs, the key exception was found:

File "/opt/virtualenv/luigi2/local/lib/python2.7/site-packages/luigi/notifications.py", line 220, in send_email_ses from boto3 import client as boto3_client ImportError: No module named boto3

We're opening this ticket in hopes that this issue can be fixed. It seems like the structure of the code on master https://github.com/spotify/luigi/blob/master/luigi/scheduler.py#L584 still has a similar problem.

**Comment by sebdiem** [comment]
> We have been seeing tasks get stuck in a 'RUNNING' state, where the task is not actually progressing and which causes errors trying to schedule similar tasks. We were also seeing a ton of log lines with the following stack trace:
> 
> ```
>       File "/opt/virtualenv/luigi2/local/lib/python2.7/site-packages/luigi/scheduler.py", line 1202, in get_work
>         reply = self.count_pending(worker_id)
>       File "/opt/virtualenv/luigi2/local/lib/python2.7/site-packages/luigi/scheduler.py", line 1069, in count_pending
>         more_info = {'task_id': task.id, 'worker': str(other_worker)}
>     TypeError: __str__ returned non-string (type NoneType)
> ```
> 
> This issue seems to have been reported here: #2200 though was closed after some time.
> 
> After a few days of debugging, we've determined that the root cause was that our email configuration was set up incorrectly. Our full root cause analysis from the post mortem is below:
> 
> **Why were users unable to run certain tasks?**
> When a task is kicked off, the Luigi worker checks to make sure that a task with the same id (essentially task family and parameters) is not running. It does this by calling the /get_work api on the scheduler. Unfortunately, the scheduler was throwing 500s for these tasks, causing the worker to abort.
> 
> **Why was the Luigi scheduler throwing 500s on /get_work?**
> The /get_work api does a number of things in the process of deciding which piece of work to assign to a worker. One of these things is to catalog the number of pending tasks, running tasks, and the worker state. This piece of code attempts to do so:
> 
> ```
> for task in worker.get_tasks(self._state, RUNNING):
>     if self._upstream_status(task.id, upstream_status_table) == UPSTREAM_DISABLED:
>         continue
>     # Return a list of currently running tasks to the client,
>     # makes it easier to troubleshoot
>     other_worker = self._state.get_worker(task.worker_running)
>     if other_worker is not None:
>         more_info = {'task_id': task.id, 'worker': str(other_worker)}
>         more_info.update(other_worker.info)
>         running_tasks.append(more_info)
> ```
> 
> The following stack trace illustrates the bug, that other_worker is unfortunately returning None from its **str** method:
> 
> ```
>       File "/opt/virtualenv/luigi2/local/lib/python2.7/site-packages/luigi/scheduler.py", line 1202, in get_work
>         reply = self.count_pending(worker_id)
>       File "/opt/virtualenv/luigi2/local/lib/python2.7/site-packages/luigi/scheduler.py", line 1069, in count_pending
>         more_info = {'task_id': task.id, 'worker': str(other_worker)}
>     TypeError: __str__ returned non-string (type NoneType)
> ```
> 
> **Why was other_worker returning None from **str**?**
> Tracing back up through the code, the Worker class implements **str** by returning self.id, which is normally a string, but in this case was None. Tracing further, this happens because the task in the above code is both RUNNING, and worker_running is None. This is a corrupted task, as a task that is running should always have a worker that is running it.
> 
> **Why were these tasks corrupted?**
> These tasks became corrupted when they failed on the workers. When a task fails, the worker makes an api call to /add_task, which informs the scheduler that the task has failed. The worker will retry, but eventually, a task will fail so many times that the scheduler decides the task should be disabled. Within /add_task, the code calls a function to update the state of the task, which, simplified, does the following:
> 
> Housekeeping, like adding a failure log to the task, setting scheduler_disable_time, and setting worker_running to None.
> Send an email to warn that the scheduler is disabling a task
> Actually change the state of the task
> 
> Unfortunately, because there was an exception sending the email, the task never gets to correctly set the state of the task to disabled, and the task is left in RUNNING but with a worker_running of None.
> 
> **Why was an exception thrown while trying to send an email?**
> Diving a bit deeper into the logs, the key exception was found:
> 
> File "/opt/virtualenv/luigi2/local/lib/python2.7/site-packages/luigi/notifications.py", line 220, in send_email_ses from boto3 import client as boto3_client ImportError: No module named boto3
> 
> We're opening this ticket in hopes that this issue can be fixed. It seems like the structure of the code on master https://github.com/spotify/luigi/blob/master/luigi/scheduler.py#L584 still has a similar problem.

Thank you very much ! It helped we had the same problem and had no idea why the scheduler would become nuts.
