### ISSUE TITLE
Adding subclass of RangeBase

### ISSUE THREAD

**Issue by tayal007** [spotify/luigi#2800]
I want to schedule my tasks weekly and so I made my own RangeWeeklyBase class which derives RangeBase.
My question is how do I use to to run luigi through cmd?

**Comment by tayal007** [comment]
One of the solution which I found is to paste this class directly in luigi module of python. But I want to keep this file inside my project which is some directory. Can anyone help regarding this?

**Comment by Tarrasch** [comment]
Hi @tayal007, look for `--module` in the docs online.

**Comment by tayal007** [comment]
Hi Tarrasch, thanks for replying but I'm not able to figure out what you are trying to imply. Can you tell me using an example?

we use RangeDailyBase like this:
luigi --module all_reports RangeDailyBase --of AllReports --start 2015-01-01

now I what something like this:
luigi --module all_reports RangeWeeklyBase --of AllReports --start 2015-01-01
RangeWeeklyBase is a module in the same directory as all_reports

**Comment by tayal007** [comment]
@Tarrasch, well thanks for your help I was able to figure it out myself
