### ISSUE TITLE
How to send custom notification on failed task ? 

### ISSUE THREAD

**Issue by ttpro1995** [spotify/luigi#2811]
I would like to send notification by calling my custom api. As far as I can see on documentation, (https://luigi.readthedocs.io/en/stable/api/luigi.notifications.html) luigi support notification by email. 

However, I want to write custom notification function (call my api with a message) that will be invoke when there is failed task. 

How can I write my own notification function, how to make my notification function be call when a task failed ?

**Comment by kwilcox** [comment]
Two parts of the documentation you should read over and choose from:

* The [`on_failure`](https://luigi.readthedocs.io/en/stable/api/luigi.html#luigi.Task.on_failure) method on Task
* [Events/callbacks](https://luigi.readthedocs.io/en/stable/tasks.html#events) - You may want to handle more than `FAILURE`, see a list of events [here](https://luigi.readthedocs.io/en/stable/api/luigi.event.html). Generally I add event handlers for `FAILURE`, `PROCESS_FAILURE`, `TIMEOUT` and `BROKEN_TASK` to report a problem but YMMV.

**Comment by ttpro1995** [comment]
what is the different between FAILURE, PROCESS_FAILURE, BROKEN_TASK  ?

**Comment by kwilcox** [comment]
The documentation on the event types needs some work.. PRs accepted! You can take a look at 
https://github.com/spotify/luigi/blob/e2228418eec60b68ca09a30c878ab26413846847/luigi/worker.py and search for `Event.` in the code to see where each is triggered.
