### ISSUE TITLE
Luigi Passes List to json.loads When Using TOML Config and ListParameter

### ISSUE THREAD

**Issue by adonig** [spotify/luigi#2812]
I'm using luigi 2.8.9 with toml 0.10.0 as extra. My luigi.toml contains a list. Accessing its value with a luigi.ListParameter causes the following error:

>   File "/Users/asd/Projects/smtc/pipeline/.venv/lib/python3.7/site-packages/luigi/parameter.py", line 1054, in parse
>     return list(json.loads(x, object_pairs_hook=_FrozenOrderedDict))
>   File "/Users/asd/.pyenv/versions/3.7.4/lib/python3.7/json/__init__.py", line 341, in loads
>     raise TypeError(f'the JSON object must be str, bytes or bytearray, '

The problem is that `x` already has type `<class 'list'>` while it should be a `str` instead.

**Comment by adonig** [comment]
NOTE: A workaround is just using a luigi.Parameter instead.

**Comment by ihowell** [comment]
Would you mind posting your `.toml` file and associated config? This is an interesting case.
