### ISSUE TITLE
Scheduler ignores task failure when getting Unfulfilled dependency at run time

### ISSUE THREAD

**Issue by Joao-M-Almeida** [spotify/luigi#2824]
This is probably a very special case, but it was very hard to debug and I believe some improvement is needed.

### Description
When a Task A runs sucessfully, but doesn't fulfil the conditions of the complete method, then task B which depends on A will fail with `RuntimeError: Unfulfilled dependency at run time: JobA_...`. After this Task A and B should be marked as PENDING and Task A should be run again, however due to the change in #2645 this is not the case anymore. Now, because task A receives a PENDING status very soon after it got the DONE status the scheduler ignores the status change.

### Cause:
#2645 

### Minimal example:

```python
import luigi

class JobA(luigi.Task):
    is_first_run = True
    def run(self):
        if self.is_first_run:
            print("First run!")
            self.is_first_run = False
            return True
        print("\n\nCreating TMP file \n\n")
        f = open("./outfileA.tmp", "w")
        f.write("file")
        f.close()
        return True

    def output(self):
        return luigi.LocalTarget('./outfileA.tmp')


class JobB(luigi.Task):

    def requires(self):
        return [JobA()]

    def run(self):
        f = open("./outfileB.tmp", "a")
        f.write("file")
        f.close()
        return True

    def output(self):
        return luigi.LocalTarget('./outfileB.tmp')
```

This example run with `luigi --module tmpLuigi JobB --local-scheduler` fails with the follwing output:
```
DEBUG: Checking if JobB() is complete
DEBUG: Checking if JobA() is complete
INFO: Informed scheduler that task   JobB__99914b932b   has status   PENDING
INFO: Informed scheduler that task   JobA__99914b932b   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 2
INFO: [pid 64429] Worker Worker(salt=609258805, workers=1, host=Joaos-MacBook-Pro, username=joaoalmeida, pid=64429) running   JobA()
First run!
INFO: [pid 64429] Worker Worker(salt=609258805, workers=1, host=Joaos-MacBook-Pro, username=joaoalmeida, pid=64429) done      JobA()
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   JobA__99914b932b   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 64429] Worker Worker(salt=609258805, workers=1, host=Joaos-MacBook-Pro, username=joaoalmeida, pid=64429) running   JobB()
ERROR: [pid 64429] Worker Worker(salt=609258805, workers=1, host=Joaos-MacBook-Pro, username=joaoalmeida, pid=64429) failed    JobB()
Traceback (most recent call last):
  File "/Users/joaoalmeida/venvs/prod3-venv/lib/python3.7/site-packages/luigi/worker.py", line 184, in run
    raise RuntimeError('Unfulfilled %s at run time: %s' % (deps, ', '.join(missing)))
RuntimeError: Unfulfilled dependency at run time: JobA__99914b932b
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   JobB__99914b932b   has status   FAILED
DEBUG: Checking if JobB() is complete
DEBUG: Checking if JobA() is complete
INFO: Informed scheduler that task   JobB__99914b932b   has status   PENDING
INFO: Informed scheduler that task   JobA__99914b932b   has status   PENDING
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 64429] Worker Worker(salt=609258805, workers=1, host=Joaos-MacBook-Pro, username=joaoalmeida, pid=64429) running   JobB()
ERROR: [pid 64429] Worker Worker(salt=609258805, workers=1, host=Joaos-MacBook-Pro, username=joaoalmeida, pid=64429) failed    JobB()
Traceback (most recent call last):
  File "/Users/joaoalmeida/venvs/prod3-venv/lib/python3.7/site-packages/luigi/worker.py", line 184, in run
    raise RuntimeError('Unfulfilled %s at run time: %s' % (deps, ', '.join(missing)))
RuntimeError: Unfulfilled dependency at run time: JobA__99914b932b
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   JobB__99914b932b   has status   FAILED
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: There are 1 pending tasks possibly being run by other workers
DEBUG: There are 1 pending tasks unique to this worker
DEBUG: There are 1 pending tasks last scheduled by this worker
INFO: Worker Worker(salt=609258805, workers=1, host=Joaos-MacBook-Pro, username=joaoalmeida, pid=64429) was stopped. Shutting down Keep-Alive thread
INFO:
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 ran successfully:
    - 1 JobA()
* 1 failed:
    - 1 JobB()
```

And succeeds with `luigi --module tmpLuigi JobB --local-scheduler --scheduler-stable-done-cooldown-secs 0`

### Proposal
Either set the default value of `stable_done_cooldown_secs` to 0 or add more logging to inform the user that the scheduler is ignoring the status change

**Comment by Joao-M-Almeida** [comment]
Just wanted to ping this issue again, it's a quite significant bug in my opinion and has already happened a few times on my company's production system. 

If a maintainer agrees I can go ahead and create a PR to change the default value of `stable_done_cooldown_secs` to 0.

**Comment by Tarrasch** [comment]
So in the issue that you linked to, #2645, there's quite some discussion and thinking that went into the new behaviour. I understand however that the change we created also creates problem elsewhere, when luigi is used in different environments, maybe even a different industry or based on a completely different storage backing the `complete()` methods.

--------

That said. the world views on "correct luigi usage" seems to differ at this sentence:

> When a Task A runs sucessfully, **but doesn't fulfil the conditions of the complete method**,

Luigi is built so that:

 * It normally expects `complete()` to be true after successful runs.
 * Even when it isn't, or needs a re-run, things should "just work out" as long as you've cron-ed luigi to rerun and try to make up missing data (incomplete tasks).

It seems like in your case it's hard to fulfil the first and you don't necessarily want to rely on the second point of reruns.

I can say that I don't think we should "take a step back" and set `stable_done_cooldown_secs` to `0`. But I'm happy to have a debug-level logging being added whenever the scheduler ignores a Pending status being given by a worker as of recently DONE task is in cooldown. I'm  happy to accept such a PR that adds debug logging.
