### ISSUE TITLE
Feature request: Load logging config using JSON or YAML.

### ISSUE THREAD

**Issue by hirolau** [spotify/luigi#2853]
The current way to load logging using a file only support the basic logging file format.

This format is somewhat limited in that one cannot add custom filters.

I am planning on changing the setup logging code to look at the extension, and if it matches yaml or json, try to load it by parsing the file, and then using the the logging dict config option.

Does this sounds reasonable? I will not do this unless I get positive feedback on this issue.

**Comment by adonig** [comment]
I've created [a pull request for a JSON config parser](https://github.com/spotify/luigi/pull/2849). You can install luigi from [my luigi fork](https://github.com/adonig/luigi) if you want to try it out. You have to set LUIGI_CONFIG_PARSER=json and create a luigi.json

```
{
    ...
    "logging": {
        "version": 1,
        "disable_existing_loggers": false,

        "formatters": {
            "simple": {
                "format": "{levelname:8} {asctime} {module}:{lineno} {message}",
                "style": "{",
                "datefmt": "%Y-%m-%d %H:%M:%S",

        ...
    }
}
```

Note you have to escape backslashes in JSON using a second backslash (like `\\`).

Let me know if everything works for you. I hope it gets merged soon :-)

**Comment by hirolau** [comment]
Ohh, I missed one could already configure using dict-config in the regular config-file. Then I could actually try to solve my problem using the TOML parser. Anyway, nice work!

**Comment by lascott** [comment]
Looking to do this as well. yaml is easy to share and very readable.
