### ISSUE TITLE
Exception on macOS thrown by MockTarget() with 2 or more workers

### ISSUE THREAD

**Issue by indexless** [spotify/luigi#2858]
Tried to run this couple of chained tasks writing to MockTarget's:

```
from luigi import Task
from luigi.mock import MockTarget

class A(Task):
    def run(self):
        with self.output().open('w') as f:
           f.write('done')

    def output(self):
        return MockTarget('A')


class B(Task):
    def requires(self):
        return [A()]

    def run(self):
        with self.output().open('w') as f:
           f.write('done')

    def output(self):
        return MockTarget('B')


if __name__ == '__main__':
    luigi.run()
```

With a single worker works perfectly on both Linux Mint 19 and macOS 10.13..6 (High Sierra).

With --workers=2 or more still works on Linux Mint, but raises an exception on macOS.

The full command line is:

```
PYTHONPATH='.' luigi --module test-mock-target --local-scheduler --workers=2 B
```

The test script (with .py renamed to .txt) with both macOS and Linux logs is attached.

----
The versions used on macOS:

Python 3.8.0 (default, Nov 18 2019, 19:10:44) 
[Clang 10.0.0 (clang-1000.10.44.4)] on darwin

luigi 2.8.10
----

[test-mock-target.txt](https://github.com/spotify/luigi/files/3922384/test-mock-target.txt)
[linux-mint.log](https://github.com/spotify/luigi/files/3922362/linux-mint.log)
[macos-high-sierra.log](https://github.com/spotify/luigi/files/3922363/macos-high-sierra.log)

**Comment by H4dr1en** [comment]
This is interesting.

Can you try with the following script (adapted from yours):

```
import luigi
from luigi.mock import MockTarget


class A(luigi.Task):
    i = luigi.IntParameter()

    def run(self):
        with self.output().open('w') as f:
            f.write('done')

    def output(self):
        return MockTarget(str(self.i))


class B(luigi.Task):
    def requires(self):
        return [A(i) for i in range(500)]

    def run(self):
        with self.output().open('w') as f:
            f.write('done')

    def output(self):
        return MockTarget('B')


if __name__ == '__main__':
    luigi.build([B()], workers=2)
```

Start it using:

```
python name_of_the_script.py
```

This works on macOS 10.14

**Comment by indexless** [comment]
Unfortunately, it doesn't on 10.13 again. Here are logs from running linux and macOS.

Apart from failure, it took quite a bit more time to proceed (almost 3 min 56 sec vs ~2 seconds on linux). The macOS hardware doesn't seem to be so weak though (screenshot is attached).

[macos-high-sierra-2.log](https://github.com/spotify/luigi/files/3933735/macos-high-sierra-2.log)
[linux-mint-2.log](https://github.com/spotify/luigi/files/3933734/linux-mint-2.log)

![Screen Shot 2019-12-06 at 22 25 57](https://user-images.githubusercontent.com/1623159/70350955-e11ae600-1878-11ea-81d6-6f16be57ae4b.png)

**Comment by H4dr1en** [comment]
OK,
What is the version of python used in Linux? Also 3.8?
Can you try using python 3.6 on macOS? This is the one I have.

**Comment by indexless** [comment]
> What is the version of python used in Linux? Also 3.8?

Right, I tested with 3.8.0 everywhere.

> Can you try using python 3.6 on macOS? This is the one I have.

Done (with **3.6.9** version), and now they (both your and my code snippets) work! Also, processing your script took ~5 sec, which looks much more reasonable.

Here is the log produced by 3.6.9 after running your example:

[macos-high-sierra-3.log](https://github.com/spotify/luigi/files/3933937/macos-high-sierra-3.log)

**Comment by H4dr1en** [comment]
Alright, 
I also tested with python 3.8 and I have exactly the same problem that you described.
We can safely assume incompatibility of luigi in macOS with python 3.8 that should be investigated.

**Comment by hirolau** [comment]
See this tweet, some multiprocessing implementations changed in 3.8. I do not have a mac, but does it work if you move the main logic to a separate script (not main) then import it and run the task?

https://twitter.com/raymondh/status/1180209729609420800

**Comment by H4dr1en** [comment]
> See this tweet, some multiprocessing implementations changed in 3.8. I do not have a mac, but does it work if you move the tasks to a separate script (not main) then import it and run the it?

Good stuff!

Unfortunately on my mac it doesn't work :(
