### ISSUE TITLE
Trouble running tutorial on "@inheritance"

### ISSUE THREAD

**Issue by tashrifbillah** [spotify/luigi#2867]
I can't run any of the approaches given [here](https://luigi.readthedocs.io/en/stable/api/luigi.util.html#using-inherits-and-requires-to-ease-parameter-pain):

# Approach 1:
> luigi --module my_tasks TaskC --param-c foo --TaskB-param-b bar --TaskA-param-a baz --local-scheduler

```
===== Luigi Execution Summary =====

Scheduled 3 tasks of which:
* 3 were left pending, among these:
    * 1 were missing external dependencies:
        - 1 TaskA(param_a=baz)
    * 2 had missing dependencies:
        - 1 TaskB(param_b=bar)
        - 1 TaskC(param_c=foo)

Did not run any tasks
This progress looks :| because there were missing external dependencies

===== Luigi Execution Summary =====
```

# Approach 3:
> luigi --module my_tasks TaskC --param-c foo --param-b bar --param-a baz --local-scheduler

```
===== Luigi Execution Summary =====

Scheduled 3 tasks of which:
* 3 were left pending, among these:
    * 1 were missing external dependencies:
        - 1 TaskA(param_a=baz)
    * 2 had missing dependencies:
        - 1 TaskB(param_a=baz, param_b=bar)
        - 1 TaskC(param_a=baz, param_b=bar, param_c=foo)

Did not run any tasks
This progress looks :| because there were missing external dependencies

===== Luigi Execution Summary =====

```

I appreciate any advice you may have.

**Comment by tashrifbillah** [comment]
@reckbo

**Comment by Tarrasch** [comment]
Well I mean you _can_ run them (you did). That page is not demonstrating "luigi examples that produce output" or "luigi examples that don't fail to run a pipeline", rather it just shows how `inherits` and `requires` work.

**Comment by tashrifbillah** [comment]
Many of you new to Luigi, might be wondering why this example is not running. It is mentioned in the [tutorial](https://luigi.readthedocs.io/en/stable/tasks.html) that each task should have three methods: 
`requires()`, `run()`, and `output()`. 

But, what I didn't find clear is each `output()` method should refer to a local target i.e. a file in your local directory. When a luigi `Task` runs, it checks whether the output in `output()` exists. If not, then it goes to `requires()-->run()` methods.

Since there weren't any targets for `TaskB()` and `TaskC()` in the examples, they failed on runtime. See my modification below that defines a local target for each of the tasks:

```python
import luigi
from luigi.util import inherits

class TaskA(luigi.ExternalTask):
    param_a = luigi.Parameter()
    
    def run(self):
        with open(f'/tmp/log-{self.param_a}','w') as f:
            pass

    def output(self):
        return luigi.LocalTarget('/tmp/log-{t.param_a}'.format(t=self))

@inherits(TaskA)
class TaskB(luigi.Task):
    param_b = luigi.Parameter()

    def requires(self):
        return self.clone(TaskA)
    
    def run(self):
        with open(f'/tmp/log-{self.param_b}','w') as f:
            pass

    def output(self):
        return luigi.LocalTarget('/tmp/log-{t.param_b}'.format(t=self))

@inherits(TaskB)
class TaskC(luigi.Task):
    param_c = luigi.Parameter()

    def requires(self):
        return self.clone(TaskB)
    
    def run(self):
        with open(f'/tmp/log-{self.param_c}','w') as f:
            pass
        
    def output(self):
        return luigi.LocalTarget('/tmp/log-{t.param_c}'.format(t=self))

if __name__=='__main__':
    luigi.build([TaskC(param_a='foo',param_b='bar',param_c='baz')], local_scheduler=True)

```

You should be able to run it successfully in either of the following ways:
> python my_task.py

or

> luigi --module my_tasks TaskC --param-c foo --param-b bar --param-a baz --local-scheduler

I'll let our "chief maintainer of Luigi" close this issue unless he thinks slight modification of the tutorial is necessary or I can be of any help.

**Comment by nesat** [comment]
@tashrifbillah I think **ExternalTask** should not have a run implementation: https://luigi.readthedocs.io/en/stable/api/luigi.task.html#luigi.task.ExternalTask

More about **ExternalTask**: http://luigi.readthedocs.org/en/latest/tasks.html?highlight=externaltask#requiring-another-task

> If you have a simple Target object that is created externally you can wrap it in a Task class like this:
> 
> ```
> class LogFiles(luigi.ExternalTask):
>     def output(self):
>         return luigi.contrib.hdfs.HdfsTarget('/log')
> ```

**Comment by tashrifbillah** [comment]
@nesat , thanks I figured that out on my own.
