### ISSUE TITLE
"there were tasks that were not granted run permission by the scheduler"

### ISSUE THREAD

**Issue by ocschwar** [spotify/luigi#2882]
I have a task that runs and babysits an R script, which is consistently being refused permission to run, with nothng in the job log or the Luigi server lot to indicate the reason. 

Here is a mock task that is a stripped down version, which fails semiconsistently right now: 

```
class MockTask(luigi.Task):
    r_path = luigi.Parameter(default='../..')
    source_path = luigi.Parameter()
    r_params = luigi.DictParameter(default = {})
    def output(self):
        sha = hashlib.sha256()
        sha.update(self.source_path.encode())
        sha.update(self.r_path.encode())
        sha.update(open(self.source_path).read().encode())
        sha.update(datetime.datetime.now().isoformat().encode())
        return luigi.LocalTarget('/var/tmp/mock.tgt.{}'.format(sha.hexdigest()))
    def run(self):
	f = open(self.output().path,'w')
        f.close()
```

Here's the output I get: 

```oschwarz@ip-10-0-0-206:~/r_oschwarz/REhedge$ /usr/bin/env R_DEFAULT_SERIALIZE_VERSION=2 R_DEFAULT_SAVE_VERSION=2 LD_LIBRARY_PATH=/usr/lib/jvm/java-11-openjdk-amd64/lib/server XGBOOST_NTHREAD=2 PYTHONPATH=`pwd`/inst/python TOML=TRUE luigi --module luigitask --workers 3 MockTask --source-path inst/Pipelines/closed/pipeline_BearkatII.R
R[write to console]: Loading required package: stats

R[write to console]: Loading required package: utils

DEBUG: Checking if MockTask(r_path=../.., source_path=inst/Pipelines/closed/pipeline_BearcatII.R, r_params={}) is complete
INFO: Informed scheduler that task   MockTask__________inst_Pipelines_c_8e0260877f   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 3 processes
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO: Worker Worker(salt=521944519, workers=3, host=ip-10-0-0-206, username=oschwarz, pid=3712) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 were left pending, among these:
    * 1 was not granted run permission by the scheduler:
        - 1 MockTask(r_path=../.., source_path=inst/Pipelines/closed/pipeline_BearcatII.R, r_params={})

Did not run any tasks
This progress looks :| because there were tasks that were not granted run permission by the scheduler

===== Luigi Execution Summary =====
```

I cannot understand why, but when I "ask the scheduler for work" it balks, and then the job halts.

**Comment by ocschwar** [comment]
I notice also that when I do this, the job gets listed as "pending" on the web interface.

**Comment by tashrifbillah** [comment]
Go to the Web Visualizer, mark any pending jobs as "Done". I trust you to know what icon to click on.
Then, your re-attempt should be successful.

If that still doesn't work, `killall -9 luigid` and restart. 

Hope this helps.
