### ISSUE TITLE
Why not become a Apache or LF or CNCF project?

### ISSUE THREAD

**Issue by ChethanUK** [spotify/luigi#2887]
So many projects have massive after becoming Apache or LF or CNCF project, just was wondering why Luigi still not one..

**Comment by ihowell** [comment]
What would the advantages be to becoming a larger project? The fewer dependencies, the better, because it allows the developers using Luigi to make their own choices. If you want to do this for your own project, you can, but that won't (probably shouldn't) impact how other people use this work.

**Comment by Tarrasch** [comment]
What @ihowell said. At some point we discussed it. No-one wanted to put the time for it, but more importantly, I felt "being Apache" had many more disadvantages over advantages. For example at some point one couldn't submit a PR fixing a typo, without creating a JIRA ticket for it.
