### ISSUE TITLE
Tasks don't fail although LocalTarget is not created

### ISSUE THREAD

**Issue by tashrifbillah** [spotify/luigi#2888]
Hi all,

It appears that Luigi doesn't check if the `LocalTarget` is created after execution of `run` method. Is it really the case? In other words, is there a way to check if `LocalTarget` is created after execution of `run` method?

# Expected behavior

Let's see the following simple task, that completes even though I don't create `/tmp/test.txt`. On the contrary, I expected the task to fail.

# Way to reproduce

Save the following as `task1.py `and then `python task1.py`

<details><summary>task1.py</summary>
<p>

```python
from luigi import Task, build, LocalTarget

class TaskA(Task):

    def run(self):
        print('\n*\nDo not create /tmp/test.txt\n*\n')

    def output(self):
        return LocalTarget('/tmp/test.txt')

if __name__=='__main__':
    build([TaskA()])
```
</p>
</details>

**Comment by ihowell** [comment]
I hope that's not your formatting, because that would directly lead to the issue. Other than that, Luigi does check after run is completed, because that's how it knows whether the task succeeded or failed (output exists). Can you show how you are running and give the output of running luigi with that task?

**Comment by tashrifbillah** [comment]
> I hope that's not your formatting

You are right, there must have been a GitHub web artifact. I edited my post, please see `task1.py` again.

> Can you show how you are running and give the output of running luigi with that task?

Please see below:

```bash
luigid --background --logdir /tmp/luigi.log
python task1.py
```


```bash
DEBUG: Checking if TaskA() is complete
INFO: Informed scheduler that task   TaskA__99914b932b   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 160057] Worker Worker(salt=175033521, workers=1, host=pnl-z840-2, username=tb571, pid=160057) running   TaskA()

*
Do not create /tmp/test.txt
*

INFO: [pid 160057] Worker Worker(salt=175033521, workers=1, host=pnl-z840-2, username=tb571, pid=160057) done      TaskA()
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   TaskA__99914b932b   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO: Worker Worker(salt=175033521, workers=1, host=pnl-z840-2, username=tb571, pid=160057) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 ran successfully:
    - 1 TaskA()

This progress looks :) because there were no failed tasks or missing dependencies

===== Luigi Execution Summary =====

```

As you see, there is no checking after run is completed.

**Comment by tashrifbillah** [comment]
Hi @ihowell , what do you think?

**Comment by ihowell** [comment]
Alright. There is actually a configuration setting that is defaulted to `False` for checking if a task is complete after running the task. This is in fact intended behavior. Take a look at https://github.com/spotify/luigi/blob/2d5fbc844cbb13dcae36291a95dc1db649fc8b9a/luigi/worker.py#L458

So, all you need to do is set `check_complete_on_run` in your worker config section to fix the issue.

**Comment by ihowell** [comment]
You can also find this in https://luigi.readthedocs.io/en/stable/api/luigi.worker.html#luigi.worker.worker.check_complete_on_run though, maybe there should be a pullrequest updating the documentation on the https://luigi.readthedocs.io/en/stable/configuration.html#worker page.

**Comment by tashrifbillah** [comment]
Thanks @ihowell , I put the following in `luigi.cfg`:

```
[worker]
check_complete_on_run=True
```

and it worked.

However, is there a way for directly passing `check_complete_on_run=True` to `luigi.build([TaskA()])` that I have in the `main()` function?

**Comment by ihowell** [comment]
It does not look like it. `luigi.build` only accepts a few env params and that is not one of them.

**Comment by tashrifbillah** [comment]
Hi @Tarrasch , 

> Alright. There is actually a configuration setting that is defaulted to False for checking if a task is complete after running the task. This is in fact intended behavior. 

Can the intended behavior be mentioned somewhere in the documentation? One possible place is this section:
https://luigi.readthedocs.io/en/stable/tasks.html#task-run
