### ISSUE TITLE
SVG does not capture dependency correctly, but D3 does

### ISSUE THREAD

**Issue by tashrifbillah** [spotify/luigi#2889]
# Description

SVG graph (incorrect): missing link between TaskB and D

![image](https://user-images.githubusercontent.com/35086881/73485287-d2c8e200-4370-11ea-93a1-5b08c013af66.png)

D3 graph (correct): see the link between TaskB and D
![image](https://user-images.githubusercontent.com/35086881/73485336-ea07cf80-4370-11ea-8039-e9e56fdff1bf.png)

# Way to reproduce

> python svgVsd3_issue.py

<details><summary>svgVsd3_issue.py</summary>
<p>

```python
from luigi import build, Task, LocalTarget
from luigi.util import requires

class TaskA(Task):

    def run(self):
        with open('/tmp/a.txt','w') as f:
            f.write('a')


    def output(self):
        return LocalTarget('/tmp/a.txt')

@requires(TaskA)
class TaskB(Task):

    def run(self):
        with open('/tmp/b.txt', 'w') as f:
            f.write('b')

    def output(self):
        return LocalTarget('/tmp/b.txt')


@requires(TaskB)
class TaskC(Task):

    def run(self):
        with open('/tmp/c.txt', 'w') as f:
            f.write('c')

    def output(self):
        return LocalTarget('/tmp/c.txt')


@requires(TaskC,TaskB)
class TaskD(Task):

    def run(self):
        with open('/tmp/d.txt', 'w') as f:
            f.write('d')

    def output(self):
        return LocalTarget('/tmp/d.txt')


if __name__=='__main__':
    build([TaskD()])
    
```
</p>
</details>

Is there suggestion about fixing it or is it a bug?

**Comment by tashrifbillah** [comment]
Hi @ihowell, did you experience this before?

**Comment by ihowell** [comment]
I haven't worked with the web view before, but from what you're showing, it looks like those graphs are intended for two different things.

The second graph (that you labeled correct) is for directly showing and exploring the dependency graph.

The first image looks like it is purely for showing what order the tasks will be run in with topological ordering.

Suppose you also had a task E that was required by C and task E requires task A. The second graph would show the dependency graph with B and E on the same level, with both being required by C and requiring A. However, the order in which they execute doesn't matter, so Luigi needs to pick an ordering and that order would show up in the first graph.

**Comment by Tarrasch** [comment]
To me it looks like a bug, but not so important one really in this case as that dependency doesn't since you depend on something implicitly forcing that dependency order anyway.

I feel it's clear the issue is that since it's a straight line you just can't see the dependency edge. :)
