### ISSUE TITLE
Docker support 

### ISSUE THREAD

**Issue by ahmedspiir** [spotify/luigi#2899]
I found this image on docker hub for luigi https://hub.docker.com/r/spotify/luigi/tags
The version over there is 2.7.2 and the latest version of this repo is 2.8.11 .
So do you have any plans for supporting the image or is it already dead?

**Comment by tobiasfielitz** [comment]
It would also be nice to see the Dockerfile.

**Comment by guidopetri** [comment]
For anyone else who comes across this hunting for a Dockerfile: it looks like it's just based off of the `python` image on Alpine. Something like this:

```Dockerfile
FROM python:alpine
RUN /bin/sh -c pip install luigi
EXPOSE 8082
ENTRYPOINT ["luigid"]
```

Of course, you'll have to make sure that the Python tag you're using is one supported by Luigi, so probably `python:3.9-alpine` right now.
