### ISSUE TITLE
Workers stopping early

### ISSUE THREAD

**Issue by hh2110** [spotify/luigi#2928]
Hi all,

I am running a pipeline over 51 samples. I have set n_workers=51 too. The whole pipeline can take up to three weeks to finish.

I have set the log_level=DEBUG, so I can see all 51 workers and the task each one is doing periodically in the following format:

```
DEBUG:Asking scheduler for work...
DEBUG:Done
DEBUG:There are no more tasks to run at this time
DEBUG:T1a_qTSAF_screen___golotr_______batch_name_____DS05225_370d145121 is currently run by worker Worker(salt=585687098, workers=51, host=hpcpetgp, username=hasanhik, pid=127735)
DEBUG:T1a_qTSAF_screen___golotr_______batch_name_____DS05669_88bf6f74ac is currently run by worker Worker(salt=585687098, workers=51, host=hpcpetgp, username=hasanhik, pid=127735)
...
DEBUG:Asking scheduler for work...
DEBUG:Done
....
```

Everything is usually running perfectly fine and I can see the tasks that are done/pending in the luigi central scheduler visualiser too. However at some later point in the log file, rather than `DEBUG:Asking scheduler for work...` - 1000s of null characters (`^@`) are returned and then the worker-task lines disappear and the pending tasks from the central scheduler disappear too. Eventually luigi thinks the job is finished because the worker has been stopped:

```
INFO:Worker Worker(salt=585687098, workers=51, host=hpcpetgp, username=hasanhik, pid=127735) was stopped. Shutting down Keep-Alive thread
```

I know that if I restart the pipeline, luigi will continue from where it has stopped. However, I want to know why the worker stopped in the first place and why 1000s of null characters were printed to the logfile. The pipeline is run on a hpc cluster where I have to submit jobs in queues and so continually restarting the pipeline is not ideal. Thanks!

**Comment by charlesoblack** [comment]
Is this maybe related to worker configs? I'm not sure how long a worker is allowed to stay alive. Do you have a custom config file?

Also, could you maybe post a part of the log (edited for a single worker) that shows what happens, exactly?

**Comment by hh2110** [comment]
HI @charlesoblack  - thank you for your comment and apologies for this late reply. 

I do have a custom log file which has been further customized after 3 unsuccessful attempts at running the pipeline: 

```
[core]
log_level = DEBUG
rpc-connect-timeout = 300
rpc-retry-attempts = 6
rpc-retry-wait = 300

[worker]
max_reschedules = 0
keep_alive = true
count_uniques = true
ping_interval = 10
wait_interval = 10

[resources]
genomicsDBImport = 1

[configParams]
path_to_source_code = /home/hasanhik/current-ppl/
outfile_dir = /home/hasanhik/1-allcats/output_files/
search_dir = /home/hasanhik/1-allcats/config_files/
```

I have not seen any null characters in my log file again but in one of my attempts, I did see `WARNING:Failed connecting to remote scheduler 'http://localhost:8082'` and hence I added in the `[core]` config parameters related to `rpc`. The `[worker]` config parameters were added in because of the following.

I have set my `log_level` to `DEBUG`, so every 10s (`ping_interval`), the log file shows what each worker is doing. I have 53 workers but as you said, here is a edited version of the log file for 2 workers: 

```
DEBUG:21/04/2020 07:01:53 Asking scheduler for work...
DEBUG:21/04/2020 07:01:53 Done
DEBUG:21/04/2020 07:01:53 There are no more tasks to run at this time
DEBUG:21/04/2020 07:01:53 T1a_Fastq_screen___trimgalore_______batch_name_____DS05256_17c17f8bd5 is currently run by worker Worker(salt=314854159, workers=53, host=hpcpetgp, username=hasanhik, pid=85377)
DEBUG:21/04/2020 07:01:53 T1a_Fastq_screen___trimgalore_______batch_name_____DS06155_96e64a8600 is currently run by worker Worker(salt=314854159, workers=53, host=hpcpetgp, username=hasanhik, pid=85377)
DEBUG:21/04/2020 07:02:03 Asking scheduler for work...
DEBUG:21/04/2020 07:02:03 Done
DEBUG:21/04/2020 07:02:03 There are no more tasks to run at this time
DEBUG:21/04/2020 07:02:03 T1a_Fastq_screen___trimgalore_______batch_name_____DS05256_17c17f8bd5 is currently run by worker Worker(salt=314854159, workers=53, host=hpcpetgp, username=hasanhik, pid=85377)
DEBUG:21/04/2020 07:02:03 T1a_Fastq_screen___trimgalore_______batch_name_____DS06155_96e64a8600 is currently run by worker Worker(salt=314854159, workers=53, host=hpcpetgp, username=hasanhik, pid=85377)
DEBUG:21/04/2020 07:02:13 Asking scheduler for work...
DEBUG:21/04/2020 07:02:13 Done
DEBUG:21/04/2020 07:02:13 There are no more tasks to run at this time
DEBUG:21/04/2020 07:02:13 T1a_Fastq_screen___trimgalore_______batch_name_____DS05256_17c17f8bd5 is currently run by worker Worker(salt=314854159, workers=53, host=hpcpetgp, username=hasanhik, pid=85377)
DEBUG:21/04/2020 07:02:13 T1a_Fastq_screen___trimgalore_______batch_name_____DS06155_96e64a8600 is currently run by worker Worker(salt=314854159, workers=53, host=hpcpetgp, username=hasanhik, pid=85377)
DEBUG:21/04/2020 07:02:23 Asking scheduler for work...
DEBUG:21/04/2020 07:03:25 Done
DEBUG:21/04/2020 07:03:25 There are no more tasks to run at this time
DEBUG:21/04/2020 07:03:35 Asking scheduler for work...
DEBUG:21/04/2020 07:03:35 Done
DEBUG:21/04/2020 07:03:35 There are no more tasks to run at this time
DEBUG:21/04/2020 07:03:45 Asking scheduler for work...
DEBUG:21/04/2020 07:03:45 Done
DEBUG:21/04/2020 07:03:45 There are no more tasks to run at this time
DEBUG:21/04/2020 07:03:55 Asking scheduler for work...
DEBUG:21/04/2020 07:03:55 Done
DEBUG:21/04/2020 07:03:55 There are no more tasks to run at this time
DEBUG:21/04/2020 07:04:05 Asking scheduler for work...
DEBUG:21/04/2020 07:04:05 Done
```

You can see that after 21/04/2020 07:02:23, there is no information on what the workers are doing and this continues indefinitely until the current tasks finish after which Luigi thinks everything is finished and stops the job. When I open my central scheduler, the workers have disappeared from the 'Worker' tab too at this time of 07:02. This has happened three times in a row, all at various times with slight modifications to the config file. I have checked the log file for other warnings and/or errors but to no avail so I'm quite stuck at the moment.

**Comment by charlesoblack** [comment]
@hh2110 what happened? did you solve your issue?

**Comment by hh2110** [comment]
@charlesoblack - no I found that the null characters were related to the hard disk filling up. However the workers still disappear but I am able to produce this problem in a much more consistent way. I am running a pipeline over 4 samples and minutes into the simulation I get this error

**Comment by hh2110** [comment]
@charlesoblack  - no I didn't. I had a look at my central scheduler log and found the following log messages: 

`2020-04-28 06:09:17,396 luigi.scheduler[96607] INFO: Task 'T1_TrimGalore___trimgalore_______batch_name_____B16_5048_d926984fac' is marked as running by disconnected worker 'Worker(salt=536726733, workers=4, host=hpcpetgp, username=blademat, pid=105662)' -> marking as FAILED with retry delay of 900.0s`

for each of my workers. After some searching I have tried to implement this [solution ](https://github.com/spotify/luigi/issues/2200#issuecomment-418404742). So far, after 2 days of running, I have not encountered a problem yet. However, my colleague, who is following the same steps as me keeps having the above 'disconnected worker issue'.
