### ISSUE TITLE
Integrate with event-driven architecture

### ISSUE THREAD

**Issue by jhagege** [spotify/luigi#2937]
Hi, is there any possibility to integrate a luigi pipeline with an event-driven architecture.
I'd like to have steps trigger external jobs on different infra and block until those jobs communicate their response through existing pubsub infrastructure.
On successful receival of message, I'd like to unblock the step and pass him the result from the pubsub message.
Can you think of any possibility to handle it ?
Thanks.

**Comment by PeteW** [comment]
In my experience I've written tasks which have custom targets which check for the presence of flags that signify execution is requested. Then on a high-frequency (5-15 minutes?) basis, cron invokes this luigi workflow/task knowing it will effectively poll for the presence of the flag, only execute when no other task of a similar type is already running and execution is requested.
