### ISSUE TITLE
ExternalProgramTask -- disabling capture_output

### ISSUE THREAD

**Issue by indexless** [spotify/luigi#2938]
I'm wondering how could I disable the ExternalProgramTask's capture_output property when it's already turned on by default?

>     By default, the output (stdout and stderr) of the run external program
>     is being captured and displayed after the execution has ended. This
>     behaviour can be overridden by passing "--capture-output False"
> 

     `capture_output = luigi.BoolParameter(default=True, significant=False, positional=False)`

"--capture-output False" doesn't work since it's as a boolean parameter doesn't accept an argument, so I don't see how to switch it off from the command line. May be it would be better to replace it with something like --disable-capture-output or --no-capture-output to be able to control this behavior?

Thanks!

**Comment by Tarrasch** [comment]
@indexless yes, this was clearly a design miss from us. I think `--disable-capture-output` would make much more sense. How long has the behavior been around? Perhaps we could change it as long as there's some reasonable check of the variable for backward compatibility for a short while?
