### ISSUE TITLE
MRJob adaptation

### ISSUE THREAD

**Issue by rudaoshi** [spotify/luigi#294]
MRJob is a good tool to write simple multi-step hadoop jobs. I'd like luigi use MRJob to write a single node in the workflow.

**Comment by Jyrsa** [comment]
Are there many people who would like to use this feature? I'm currently working on triggering S3->S3 mrjob EMR tasks using luigi for the simplicity it would offer to data flow management.

@danielhfrank wrote [Waluigi](https://github.com/danielhfrank/waluigi) a while ago and I believe by adding a few more batteries I could make it work at least for simple use cases in the abovementioned context. I can't make any guarantees about having the time to clean it up to publish, though.

@Tarrasch are there any objections on principle to having a contrib.mrjob.MRJobTask?

**Comment by Tarrasch** [comment]
Nope, no objections. Though some form of tests are expected. Also, don't hesitate to reuse/refactor/generalize other modules relating to map reduce if it makes sense.

**Comment by Jyrsa** [comment]
I wouldn't trust the quality of my own code without at least some tests.

The general idea is to assume that the user knows what they're doing with MRJob and just provide a simple wrapper that instantiates the object with user given parameters and and lets MRJob handle the rest. It comes with plenty of batteries already so I don't expect the bridge to be too complex or smart.

**Comment by Tarrasch** [comment]
Jyrsa. It's sane too assume the user knows what they are doing. But don't forget to add documentation as pydocs, at least describing how to inherit your base task. Looking forward to your PR :)

**Comment by Jyrsa** [comment]
Sorry about the delay. It was surprisingly difficult to find the person at my employer to OK my open sourcing this.

**Comment by Tarrasch** [comment]
Added by @Jyrsa in #1731. Thanks again!

**Comment by rudaoshi** [comment]
I wrote a extension package for luigi to support mrjob protocol and default parameters. 

https://github.com/rudaoshi/super_luigi

**Comment by bnewbold** [comment]
PR #1731 never got merged; i'm not sure why this issue was closed before that happens.
