### ISSUE TITLE
luigi leaves some zombie processes

### ISSUE THREAD

**Issue by indexless** [spotify/luigi#2941]
Hi, I've found that sometimes luigi leaves zombies. Here is a simple code where the issue can be reproduced. This is a trivial task called 'Slowpoke' which does nothing but sleeps, accepting sleep time as a parameter. The 'Result' task creates three slowpokes which sleep 3, 6, and 9 seconds, and waits for them:

```
#!/usr/bin/env python

from time import sleep
from luigi import Task, IntParameter, run
from luigi.mock import MockTarget

class Slowpoke(Task):
    seconds = IntParameter()

    def run(self):
        sleep(self.seconds)
        with self.output().open('w'):
            pass

    def output(self):
        return MockTarget('Slowpoke')

class Result(Task):
    def requires(self):
        return [Slowpoke(seconds) for seconds in [3, 6, 9]]

    def run(self):
        with self.output().open('w'):
            pass

    def output(self):
        return MockTarget('Result')

if __name__ == '__main__':
    run()
```
([download](https://github.com/spotify/luigi/files/4570154/slowpokes.py.txt))

Run this code with workers >= 3, and you'll find that after the first task has finished (3 sec), the appropriate worker turns to a zombie; and after 6 second, the same for the next worker:
```
$ ps x | awk '$3~/Z/'
 8776 pts/0    Z+     0:00 [python] <defunct>
 8778 pts/0    Z+     0:00 [python] <defunct>
```
In this toy example, the dead workers don't affect result since they can not be reused here anymore, but the real graph I'm targeting at is much more complex, and I see zombies there too. And in that case I'm not sure so much the dead workers could not be reused again.

So the existence of zombies seems to be an issue, but I'm not sure yet whether can it break an execution graph somehow.

- luigi version: 2.8.13
- python versions: 3.6.10, 3.7.7, 3.8.2
- OS: Linux Mint 19.3

Thank you!

Cheers,
Timur

**Comment by alexanderhupfer** [comment]
I'm having the same issue on luigi 3.4.0
