### ISSUE TITLE
`config_path` should default to `{TaskName:parameterName}` in the case of inherit or shouldn't be deprecated

### ISSUE THREAD

**Issue by hnykda** [spotify/luigi#2946]
I propose that when an `@inherit(TaskA)` is used to decorate `TaskB`, the default argument for `TaskA` should be used so `TaskB` doesn't have to respecify it. Basically, I would recommend to have:
```
class TaskA(luigi.Task):
  parname = luigi.Parameter(config_path=dict(section="TaskA", name="parname"))
```
as a default. As mentioned, it's especially useful in scenarios with `@inherit` or `@requires` to avoid repeating arguments on CLI or in Config for the downstream tasks.

## Reproducible example
`pkg/tasks.py`
```
import luigi
from luigi.util import requires

class A(luigi.Task):
    pars = luigi.Parameter()
    par_w_config_default = luigi.Parameter(config_path={"section":"A", "name": "par_w_config_default"})

    def output(self):
        return luigi.LocalTarget("a.txt")

@requires(A)
class B(luigi.Task):
    def run(self):
        with open("b.txt", "w") as ofile:
            ofile.write("bla")

    def output(self):
        return luigi.LocalTarget("b.txt")
```

and `luigi.cfg`:
```
[A]
pars = somedefaultg
par_w_config_default = somedefaultg
```

and run it with:
```
env PYTHONPATH=. luigi --local-scheduler --module pkg.tasks B
```

in this case, the execution will fail because `--pars` cannot take the default from the config section which I would expect it to do so. This can be mitigated by `config_path`, but it means more boilerplate. 

Additionally, `config_path` is marked as `DEPRECATED` in the code and docs. Without this, it will be impossible to have defaults specified via config for `@requires` tasks. Is that really necessary? What's the reasoning behind that?

**Comment by tashrifbillah** [comment]
@hnykda , I agree with you. See my [comment](https://github.com/spotify/luigi/issues/2864#issuecomment-632927416) in the other [issue](https://github.com/spotify/luigi/issues/2864) where I provided a way around. I think Luigi developers don't get time to fix issues nowadays.

**Comment by tashrifbillah** [comment]
Hi @Tarrasch , I think this is a better description of the issue we are facing.

**Comment by rosscleung** [comment]
bumping. This issue still exists.

If we want to use @inherits along with config files, all the parameters will need to be at the most "bottom" task and flow everything upwards.
