### ISSUE TITLE
[Question] How to store history indefinitely?

### ISSUE THREAD

**Issue by tashrifbillah** [spotify/luigi#2947]
According to `Section 8.6.2 Enabling Task History` in the [doc](https://readthedocs.org/projects/luigi/downloads/pdf/latest/), task history is stored for last 24 hours only. Is there a way to override that to make it indefinite?

There is one parameter in Section `8.9.4 [cors]`:
`max_age Content of Access-Control-Max-Age. Defaults to 86400 (24 hours)`
that seems relevant to the duration. Would changing that help?

**Comment by tashrifbillah** [comment]
Hi @Tarrasch , can you give me a direction?

**Comment by Tarrasch** [comment]
Are you talking about the "Task DB" feature? I've never used that actually.

**Comment by tashrifbillah** [comment]
I am talking about 

```cfg
[task_history]
db_connection = sqlite:////usr/local/var/luigi-task-hist.db
```

not sure if you call that "Task DB".

Can we ping someone who might know?

**Comment by drowoseque** [comment]
@tashrifbillah 
Actually the history db stores data infinitely
24 hours relates to the history displaying.

**Comment by tashrifbillah** [comment]
Hi @drowoseque , in that case, do you know how to display history beyond 24 hours?

**Comment by drowoseque** [comment]
unfortunately there is no way to do it right now as limitation of 24 hours is hardcoded
![image](https://user-images.githubusercontent.com/3604364/85408349-12d17100-b56d-11ea-8c83-1b6ea7127ce9.png)

**Comment by tashrifbillah** [comment]
So I should be able to link `days=1` to a new configuration parameter and submit a PR :)

**Comment by drowoseque** [comment]
@tashrifbillah btw if you're interested in some particular task you can use /history/by_name/ endpoint which doesn't have any restrictions on dates

**Comment by tashrifbillah** [comment]
Hi @drowoseque , can you help a bit about `/history/by_name/` ? [This](https://gist.github.com/tashrifbillah/2bca276c7a6e2d5c85e9206d6522b37e) is my simple job, upon execution of which--

`/history` shows fine:

![image](https://user-images.githubusercontent.com/35086881/85422248-63cc6f80-b543-11ea-825d-e21caaf7cb20.png)

But `/history/by_name/:TaskB` does not:

![image](https://user-images.githubusercontent.com/35086881/85422351-83639800-b543-11ea-87c2-edaa662f7ddf.png)


Here is my `luigi.cfg`:
```vim
[scheduler]
record_task_history = True
state_path = ${HOME}/luigi-state.pickle

[task_history]
db_connection = sqlite:///${HOME}/luigi-task-hist.db
```

**Comment by drowoseque** [comment]
@tashrifbillah 
I'm not sure, but maybe that's because of a typo in the url
it looks like it should be **localhost:8082/history/by_name/TaskB** instead of  **localhost:8082/history/by_name/:TaskB**
you have an odd colon

**Comment by tashrifbillah** [comment]
That's awesome, thanks for your help. We need to correct the URL on page 39 of the [pdf documentation](https://readthedocs.org/projects/luigi/downloads/pdf/latest/) which I followed:

![image](https://user-images.githubusercontent.com/35086881/85425906-caec2300-b547-11ea-9d73-ee26133c6812.png)


I am happy to submit a PR. @Tarrasch , can you please direct me to which md/rst I should correct?

**Comment by drowoseque** [comment]
No worries, you're more than welcome :)
I think it's this file https://github.com/spotify/luigi/blob/master/doc/central_scheduler.rst

**Comment by tashrifbillah** [comment]
Hi @drowoseque , I have another question for you--

The link you attached says:

> /history/by_params/:name?data=params a listing of all runs of a given task restricted to runs with param values matching the given data. The data is a json blob describing the parameters, e.g. {"foo": "bar"} looks for a task with foo=bar.

We figured the extra colon part before but now I am trying to understand what should be `name`, `data` and `params` if the `/history/by_params/name?data=params` is at all correct. I believe `name` is the task name though.

To be more specific, I want to filter all `PnlEddyUkf` tasks with `id=01`:

![image](https://user-images.githubusercontent.com/35086881/89567162-3421b000-d7ef-11ea-895f-7b887cc95822.png)

Thanks for your time.

**Comment by drowoseque** [comment]
Hi @tashrifbillah 
it looks like the get request should be smth like `/history/by_params/PnlEddyUkf?data={"id": "01"}`
according to https://github.com/spotify/luigi/blob/master/luigi/server.py#L266

**Comment by tashrifbillah** [comment]
Worked perfectly. Thank you very much @drowoseque , it seems like you are very knowledgeable about the code base.

**Comment by tashrifbillah** [comment]
Hi @drowoseque , according to your suggestion and my testing, I edited the doc. I think it would help if you please review it.

**Comment by tashrifbillah** [comment]
Hi @drowoseque , what is a task ID in the following table?

![image](https://user-images.githubusercontent.com/35086881/98605412-5ece4980-22b3-11eb-9ac2-e9e0552cf939.png)

**Comment by tashrifbillah** [comment]
Hi, I figured a way by querying the SQL database file. [Here](https://gist.github.com/tashrifbillah/5f2d28ca17f1099aef08d81727d74942) is my gist. Thanks.

**Comment by MrityunjoyS** [comment]
Great way to get history features. 
But, @drowoseque did you find the way how to view the workflow indefinitely in UI. It would be great help if you can give me some directions
