### ISSUE TITLE
Support Tornado>=6

### ISSUE THREAD

**Issue by maresb** [spotify/luigi#2949]
Sorry to duplicate #2805, but I'm forced to uninstall Luigi from my JupyterLab environment since Tornado < 6 is breaking my extensions. Would you reconsider supporting Tornado 6? Thanks!

**Comment by honnix** [comment]
According to Tornado release notes: `Python 2.7 and 3.4 are no longer supported; the minimum supported Python version is 3.5.2.`

However Luigi still claims to support Python 3.3 and 3.4. So there are two options: 1) Luigi drops 3.3. and 3.4; 2) have more branches in [setup.py](https://github.com/spotify/luigi/blob/master/setup.py#L51). Wdyt @Tarrasch @dlstadther ? Both 3.3. and 3.4 have reached end of life, so it seems fair to drop them (we are not testing either of those anyway in CI).

**Comment by dlstadther** [comment]
I'm cool to drop mentioned support of 3.3 and 3.4

**Comment by honnix** [comment]
Cool. I will work on some PRs to follow this up.

**Comment by stonebig** [comment]
hum, still no hope for tornado>=6 support ? waiting for https://github.com/tornadoweb/tornado/pull/2815 ?

**Comment by honnix** [comment]
@stonebig Sorry, blame me on this. I will make a few PRs to move this forward.
