### ISSUE TITLE
Travis CI is missing a few collections of test cases

### ISSUE THREAD

**Issue by honnix** [spotify/luigi#2959]
As an effort improving CI response time, in #2541 we introduced `core` environment and deprecated `nonhdfs`, and one of the results of this change, collections of test case such as `gcloud` and `contrib` were disabled.

To continuously improve quality of contrib code and give contributors higher confidence of their changes, we should get back those while still have a reasonable CI response time.

**Comment by lallea** [comment]
This seems important, so I am commenting here in order to prevent the issue from going stale. :-)
