### ISSUE TITLE
local_target.py - os.rename change to os.replace ?

### ISSUE THREAD

**Issue by Hjorthmedh** [spotify/luigi#2975]
https://github.com/spotify/luigi/blob/master/luigi/local_target.py#L40

When trying to rename to an existing file it fails. Better to use os.replace instead?

**Comment by yuta100101** [comment]
I think it is better to use `os.replace` or `shutil.move` because `os.rename` to an existing file causes error in Windows.
Is there any reason not to fix?

**Comment by lallea** [comment]
AFAIK, no. It's probably just that no one has written the PR yet. Yield to
temptation and submit a patch. :-)


Lars Albertsson
Data engineering entrepreneur
www.scling.com
+46 70 7687109
https://twitter.com/lalleal, https://www.linkedin.com/in/larsalbertsson/
