### ISSUE TITLE
Multiple worker pods with a central scheduler in a Kubernetes setting

### ISSUE THREAD

**Issue by kipstakkr** [spotify/luigi#2987]
Hi team,

Is there a way to deploy luigi on Kubernetes with a central scheduler pod and multiple worker pods, which would run the jobs based on a REST API?

The closest solution (I can think of) for this use case from the luigi documentation is `luigi.rpd.RemoteScheduler`, which has a url config, but still don't know how to configure it with multiple workers apart from the central scheduler pod. Any leads would be much appreciated.

**Comment by zanthorn** [comment]
You can use [KubernetesJobTask](https://luigi.readthedocs.io/en/stable/api/luigi.contrib.kubernetes.html) and the central scheduler will create a [job](https://kubernetes.io/docs/concepts/workloads/controllers/job/) in your cluster.
