### ISSUE TITLE
Feature Request: Catch exceptions from dynamic dependencies

### ISSUE THREAD

**Issue by LinqLover** [spotify/luigi#3012]
In our pipeline, we make a lot of use of dynamic dependencies, for instance, to download HTML files whose URLs are only known at runtime. However, we now would like to continue our pipeline even if the download of a few HTML files failed, i.e. the relevant dynamically depended tasks failed. At the moment, the depending task (`BaseTask`) fails irrecoverably once any dynamic dependency fails. It would be great if it was given the chance to catch exceptions raised by the dependent tasks in order to react to them, e.g. by ignoring or retrying the task:

```python3
"""Pseudo code"""
import requests

import luigi


class BaseTask(luigi.Task):

    def run(self):
        for key in my_dynamic_list:
            try:
                output = yield FetchTask(f'example.com/?q={key}')
            except requests.HTTPError:
                continue  # robust mode
            # process output ...


class FetchTask(luigi.Task):

    url = luigi.Parameter()

    def run(self):
        response = requests.get(url)
        with self.output().open('w') as f:
            f.write(response.content)
```

I did not find any existing solution to this problem. Did I miss something? If not, how would you think about adding support for this? :-)

**Comment by lallea** [comment]
You don't need support in Luigi to solve this. IIUC, you want to continue
with downstream tasks in spite of some dependency tasks failing. From a
dependency perspective, a task is not failing if you want downstream to
continue anyway - it merely did not perform any processing and did not
produce any data to the output dataset.

Just catch the exception in FetchTask and write an empty result. Or retry
if you wish.

Note that your tasks are data collection tasks and not computation tasks.
Luigi is primarily focused on the latter. It can perform data collection
tasks, but not all data collection patterns have a natural Luigi
representation.

Regards,

Lars Albertsson
Data engineering entrepreneur
www.scling.com, www.mapflat.com
https://twitter.com/lalleal
+46 70 7687109

**Comment by LinqLover** [comment]
Hi @lallea,

> IIUC, you want to continue with downstream tasks in spite of some dependency tasks failing.

That's correct.

> Just catch the exception in FetchTask and write an empty result. Or retry if you wish.

Hm, this is a workaround in my eyes. In a real-world example, `FetchTask` is depended by many other tasks, too, that expect it to create a valid output unless it failed explicitly. Of course, I could add a parameter `ignore_error` to the fetch task, but from a design perspective, this is suboptimal since it increases the coupling between the tasks. A `try ... except` solution would be much more cleaner IMHO.

> Note that your tasks are data collection tasks and not computation tasks. Luigi is primarily focused on the latter. It can perform data collection tasks, but not all data collection patterns have a natural Luigi representation

This is an interesting statement, given the fact that we implemented a data mining project with more than 150 task classes using luigi. :-) However, tbh I do not think that the present pattern is specific to data collection/mining. Just rename `FetchTask` into `LinearRegressionTask` and it will fail if the specified data is too sparse for regressing. (Yes, you could check this before yielding the task, but this would violate the EAFP principle of Python.)

**Comment by lallea** [comment]
On Thu, Oct 29, 2020 at 12:18 AM Christoph Thiede
<notifications@github.com> wrote:
>
> Hi @lallea,
>
> IIUC, you want to continue with downstream tasks in spite of some dependency tasks failing.
>
> That's correct.
>
> Just catch the exception in FetchTask and write an empty result. Or retry if you wish.
>
> Hm, this is a workaround in my eyes. In a real-world example, FetchTask is depended by many other tasks, too, that expect it to create a valid output unless it failed explicitly. Of course, I could add a parameter ignore_error to the fetch task, but from a design perspective, this is suboptimal since it increases the coupling between the tasks. A try ... except solution would be much more cleaner IMHO.

That's how you signal to Luigi whether you want downstream to proceed
or not. From a workflow perspective, there is no point in
distinguishing between "FetchTask collected some data" and "FetchTask
failed to collect data, but we want downstream to continue anyway". If
you want to distinguish in downstream tasks, find a way to represent
the difference in your data.

> Note that your tasks are data collection tasks and not computation tasks. Luigi is primarily focused on the latter. It can perform data collection tasks, but not all data collection patterns have a natural Luigi representation
>
> This is an interesting statement, given the fact that we implemented a data mining project with more than 150 task classes using luigi. :-) However, tbh I do not think that the present pattern is specific to data collection/mining. Just rename FetchTask into LinearRegressionTask and it will fail if the specified data is too sparse for regressing. (Yes, you could check this before yielding the task, but this would violate the EAFP principle of Python.)

We also collect data with Luigi, but we don't use it for all forms of
data collection, since not all collection patterns fit Luigi.

Regarding LinearRegressionTask, you are right. It is a useful pattern
to use Luigi task failure to signal that a data quality check failed,
and that you want downstream not to proceed, e.g. not put a model into
production.

**Comment by LinqLover** [comment]
Thanks for your explanations.

My current solution is an extra `ignored_status_codes` ListParameter added to the `FetchTask` plus a `FailableTarget` wrapper around the output target of the task. If the download fails with a status code that is in the ignore list, the output path is appended with the suffix `.error`, and the `FailableTarget` detects that the task is complete but has an error.

If someone is interested in the implementation, I can share it.

I do not consider this a perfect implementation, but it works, so if you think this is a "wont-fix" issue, please feel free to close it.

**Comment by LinqLover** [comment]
> From a workflow perspective, there is no point in distinguishing between "FetchTask collected some data" and "FetchTask failed to collect data, but we want downstream to continue anyway".

And that's exactly the problem in my eyes. :-) luigi is a great framework for orchestrating pipeline tasks, but the creators of almost every major high-level programming language did not design an exception system for fun but because it provides an additional way to react to exceptional events, eliminating the need to transport and check status codes for every operation that will pass in 99.9% of all invocations. I think ubiquitous zero and nonzero return codes in low-level C/C++ frameworks are the best example for the added value of such an exception system.

In the example I have given, the lack of an exception mechanism means:

> If you want to distinguish in downstream tasks, find a way to represent the difference in your data.

However, there are nearly a dozen other tasks that depend on a `FetchTask` instance as well, and if I represented every HTTP error in the output file, each of these tasks had to check for the error manually, whereas an exception handler is available anywhere without additional efforts. Also, encoding the error within the output data would be a strong sign of primitive obsession IMO.

Asked differently: What would be the problem with forwarding exceptions between tasks? Is it the cost of sharing the exception object between several worker processes, or do you simply have any objections against this design change?

**Comment by lallea** [comment]
Luigi's main strengths are IMHO simplicity, narrow scope, and pure Python. It only handles the control plane, which keeps the scope narrow and simplifies the implementation. You are suggesting adding data flow to Luigi itself: the reason that your collection task fetched zero records is not part of the control flow, it is data. It would not affect workflow or control logic - it would only be data passed between your tasks. 

If you feel that it is important for you to have data flowing through the workflow orchestrator, you could try Airflow. IIUC, the xcom feature is a channel for passing data between tasks. IIRC, the person that implemented xcom later regretted doing so due to the added complexity... :-/
