### ISSUE TITLE
stderr not printed from failing spark jobs 

### ISSUE THREAD

**Issue by lallea** [spotify/luigi#3018]
If a SparkSubmitTask fails, stderr from the Spark job is not printed by Luigi. It is a regression introduced in 2.8.4, probably by https://github.com/spotify/luigi/commit/62fbaf20775b69995cacb3e266a8b50a6959fd92

Reproduce by creating a derived instance of SparkSubmitTask, with `entry_class` overridden with a non-existing class. (Not tried.)

Reverting to Luigi 2.8.3 fixes the problem. One can also work around the problem by disabling the URL tracking; set `stream_for_searching_tracking_url = 'none'` in the child class of SparkSubmitTask.

As a side note, it was surprising to find a regression in a patch version. If we want to follow semantic versioning, 2.8.4 should have been named 2.9.0, since it introduced new functionality.

**Comment by harpaj** [comment]
Note that #3000 is a PR to fix this and #2999 describes the same problem.

**Comment by lallea** [comment]
Closing this one as a duplicate.
