### ISSUE TITLE
How to wrap luigi task

### ISSUE THREAD

**Issue by Inuita** [spotify/luigi#302]
Hi!
I have one task class, let's say: class Task1(luigi.Task)
I need a possibility to wrap the task inside some wrapper that changes the behavior of the task (for example performs different actions in run method) but the task is still visible to luigi as Task1 with given parameters:
task1 = Task1(param1=value1) 
task2 = TaskWrapper(Task1(param1=value1))
In the example above I need that task1 is (for luigi) the same as task2

What is the best (suggested) way to achieve that?

**Comment by Tarrasch** [comment]
This is an (old) user question. Closing.
