### ISSUE TITLE
Tasks Stuck Running

### ISSUE THREAD

**Issue by stnguyen90** [spotify/luigi#3053]
Sorry I'm unable to provide code samples right now. I'll try to add some snippets when I can.

I'm running into a problem in which tasks get stuck with status `RUNNING`. My tasks are quite small and shouldn't be run for longer than a couple minutes. When looking at the visualizer, the task shows running but it's missing it's dynamic dependency (via `yield`). The logs just say the task is being run by some worker process, but I see no longs from any worker process processing the task.

Some additional context:

* I'm running tasks via `luigi.build` from a `pika` consumer
* The tasks don't always get stuck
* I'm using 30 worker processes
* The entire pipeline ranges from 500 - 3000 tasks

**Comment by vbarbaresi** [comment]
This could be related to https://github.com/spotify/luigi/issues/814

**Comment by stnguyen90** [comment]
I didn't find a solution but I'll close this since there's not much to be done.
