### ISSUE TITLE
an optional argument to disable the web GUI

### ISSUE THREAD

**Issue by anilbey** [spotify/luigi#3092]
Hi,

It would be really useful to have an option to disable the web gui.

On remote clusters the webui is sometimes causing connection issues such as this one: https://stackoverflow.com/questions/68468722/luigi-disable-web-gui

When the http connection is refused, I still want to use the workflow management system.

Also from the design point of view, the user interface should be decoupled from the workflow management system.

I look forward to your response, let me know what you think.

**Comment by lallea** [comment]
I don't think the reported problem is caused by the GUI. What did you run
and what did you expect to happen?

**Comment by anilbey** [comment]
The problem is due to my server configuration, but as a user I really would like to be able to use luigi with my favourite scheduler from the command line (as I run snakemake or GNU make) without having to deal with the visualiser or the http requests. 

A flag to disable the web visualiser would be great.
E.g. 

`luigi --module top_artists AggregateArtists --date-interval 2012-06 --no-visualizer`

I almost never use the web visualiser. I call the `luigi-deps-tree` command and pass it to `graphviz` to get a static visualisation of the workflow and I rely on my logs to track the progress.

**Comment by lallea** [comment]
I don't think the web UI is the problem. I never use it as well.

The error message stems from the worker attempting to contact the central scheduler for synchronisation. Is your intention to run without central scheduler? In that case, use `--local-scheduler`. See https://luigi.readthedocs.io/en/stable/central_scheduler.html . Make sure you are aware of the limitations running without luigid.

If that's not what you intended, please explain what command you run and what you aim to achieve.

**Comment by anilbey** [comment]
I'm unable to reproduce the problem. Ok let's close the ticket since the issue's not UI related. If the error occurs again I'll try to identify what may be going wrong with the scheduler usage. Thanks for the help!
