### ISSUE TITLE
Document DB Task History

### ISSUE THREAD

**Issue by jcrobak** [spotify/luigi#311]
There's a good start from a thread on the list:

>Unfortunately we haven't written any docs on it, yet. You can get an idea of what problem it's trying to solve at: https://github.com/spotify/luigi/issues/51 and there are some screen shots in the original pull request: https://github.com/spotify/luigi/pull/72
>
>The system uses SQLAlchemy, which you can use to auto-generate the tables or to give you the relevant CREATE TABLE statements to run.

We'll have to put together some instructions, too, about how to actually use the sqlalchemy features for generating tables.

**Comment by Tarrasch** [comment]
Fixed in #589
