### ISSUE TITLE
Tasks look the same for scheduler but they have different output.

### ISSUE THREAD

**Issue by viyx** [spotify/luigi#3118]
```python
import luigi
from luigi.parameter import DictParameter


class PreviousTask(luigi.Task):
    previous_params: DictParameter()

    def output():
         return luigi.LocalTarget(str_from_params(self.previous_params))

    def run(self):
        result = do_a_lot_work()
        json.dump(result, str_from_params(self.previous_params))


class A(luigi.Task):
    current_params: DictParameter(default={'n': 123 })

    def requires(self):
        return PreviousTask()

    def run(self):
       result = do_a_lot_lot_work()
       filename = str_from_params(self.requires().previous_params) + str_from_params(self.current_params)
       json.dump(result, filename)

   def output(self):
        filename = str_from_params(self.requires().previous_params) + str_from_params(self.current_params)
        return luigi.LocalTarget(filename)
```

I use central scheduler.

First I run:
```bash
luigi --module my_tasks A --PreviousTask_previous_params '{"param1": "value1"}'
```

Second I run:
```bash
luigi --module my_tasks A --PreviousTask_previous_params '{"param1": "value2"}'
```

But after second run I get in summary message

```
* 1 were left pending, among these:
    * 1 were being run by another worker:
        - 1 A(n=123)
    The other workers were:
    - Worker(salt=762024377, ...) ran 1 tasks

   Did not run any tasks
   This progress looks :) because there were no failed tasks or missing dependencies

    ===== Luigi Execution Summary =====
```

Tasks will have different output but central scheduler doesn't consider it and exit. What's the proper to run these tasks at the same time?

**Comment by lallea** [comment]
The scheduler considers the two A tasks the same, since the have the same params. You need to add previous_params also to A and propagate it to the upstream task:

`
class A(luigi.Task):
    current_params = DictParameter(default={'n': 123 })
    previous_params = DictParameter()

    def requires(self):
        return PreviousTask(self.previous_params)
`

In case there are lots of params that get duplicated in your code, there are convenience decorators to remove the duplication, but I generally find it more clear to be explicit.

BTW, in order to debug similar issues, you can print the `task_id` field of a task. The scheduler will consider tasks with the same `task_id` to be the same.

**Comment by lallea** [comment]
Luigi works as intended, so I suggest closing. Perhaps improved documentation would be useful.

**Comment by viyx** [comment]
As I understand a proper way to distinguish these tasks is to propagate and instanciate all significant parameters to upstream tasks like that:
```
Task1(**kwargs1) -> Task2(**{**kwargs2, **kwargs1}) -> ... -> TaskN(**{**kwargs2, **kwargs1, ... , **kwargsN})
Task1(**kwargs1) -> Task2(**{**new_kwargs2, **kwargs1})-> ... -> TaskN(**{**new_kwargs2, ... ,**kwargs1, **kwargsN})
```
So I specify my quiestion. How can I pull all downstream significant parameters to unambiguously identify TaskN?

**Comment by lallea** [comment]
You explicitly enumerate all relevant parameters in TaskN, as with `previous_params` above.

I don't think of it as pulling down. Downstream tasks should explicitly contain all parameters that define their uniqueness. They explicitly propagate parameters that are necessary to uniquely identify upstream tasks. 

For example, if you are in the restaurant business and gather sales reports and prefer to have them separated by type of restaurant, you code might look like:

```
class CleanedSales(Task):
  restaurant_type = Parameter()
  date = DateParameter()

  def run(self):
    # Transform raw input by dropping invalid records, and filtering by restaurant_type

class AggregatedSales(Task):
  restaurant_type = Parameter()  # "restaurant", "pub", "cafe", ...
  date = DateParameter()

  def requires(self):
    return CleanedSales(restaurant_type=self.restaurant_type, date=self.date)
```

The type and date are part of the definition of AggregatedSales, so they are present there and passed upstream.

Perhaps it would be easier for us to suggest how to build the DAG if you provide a more concrete example?

**Comment by viyx** [comment]
```python
class PullData(Task):
    date: DateParameter()

    def run(self):
        # pull data and save with date in name

    def output(self):
        return LocalTarget(params_to_str(self))


class BuildMatrix(Task):
     matrix_type = Parameter()

    def requires(self):
        return PullData()

    def run(self):
        data = self.requires()
        # build matrix and save with  matrix_type in name

    def output(self):
        return params_to_str(self, self.requires())


class TrainModel(luigi.Task):
    n_epochs: IntParameter()

    def requires(self):
        return BuildMatrix()

    def run(self):
       matrix = self.requires()
       result = train_model(matrix)
      #  train a model and save with  n_epochs in name

    def output(self):
        return params_to_str(self, self.requires())
```

My graph is straightforward but it is quite deep. Actually as run many `TrainModel` tasks with different downstream tasks' parameters like that

`luigi --module my_tasks TrainModel n-epochs 1 --BuildMatrix-matrix-type "csr"`
`luigi --module my_tasks TrainModel n-epochs 1 --BuildMatrix-matrix-type "coo"`
`luigi --module my_tasks TrainModel n-epochs 1 --BuildMatrix-matrix-type "csr" --PullData-date "2021-09-09"`

for each task the DAG is builded and new output files are generated if needed but central scheduler
doesn't distinguish `TrainModel` tasks and keep only one TrainModel(n_epochs=1) task on execution.

folder structucture is like that:

> data_2021_09_09/csr/model_1_epochs.json
> data_2021_09_09/coo/model_1_epochs.json
> data_2021_09_10/csr/model_1_epochs.json

Actually I am asking to provide some function that indicate for central scheduler these tasks are different
`luigi --module my_tasks TrainModel n-epochs 1 --BuildMatrix-matrix-type "csr"`
`luigi --module my_tasks TrainModel n-epochs 1 --BuildMatrix-matrix-type "coo"`
`luigi --module my_tasks TrainModel n-epochs 1 --BuildMatrix-matrix-type "csr" --PullData-date "2021-09-09"`

**Comment by lallea** [comment]
Ah, I see. I think that I understand the confusion. I suggest that you constrain yourself not to use command line parameters that refer to upstream tasks, e.g. `--Pulldata-date`. Those should rarely be used, and typically only for non-significant parameters, e.g. number of threads for a computation.

Add `matrix_type` and `date` parameters to `TrainModel`. They are significant for the uniqueness of your model dataset, and need to explicitly be present. They should also be present in the path of whatever files that you define in `output()`. Pass the parameters upstream in `requires()` in the way that I wrote in my previous post.

This involves some copying and boilerplate, but parameters become explicit and easy to understand and debug. If you find yourself with too much duplication, you can look at `luigi.util.inherits` and `luigi.util.requires`. I would suggest that you start explicit until you feel comfortable with the model and with debugging problems, however.

**Comment by viyx** [comment]
Thanks a lot for your clarification. I understand that task should have all parameters it depends on. It is clear and proper way to identify task or output file.
