### ISSUE TITLE
Types of parameters

### ISSUE THREAD

**Issue by borgr** [spotify/luigi#3132]
A small thing, but when we use parameters in the class (e.g. def class a: var=luigi.Parameter()), the result in self is not type consistent. While it works alright, it is not an str, a Mapping when dict etc. So a good IDE warns that this is not type safe.

I am a new user so I might be wrong though...

**Comment by lallea** [comment]
The last piece of Luigi magic. When Luigi instantiates objects of Task, it populates the object properties with parameter values of the basic type that corresponds to the parameter type. So, for your `var` parameter, while the class property is of type `Parameter`, the object property will be populated with a `str`. For a `DateParameter`, it will be populated with a `datetime.date`, etc.

It would be great to remove this magic with something more ordinary that IDEs understand, but it would be backwards incompatible.

In the meanwhile, you can trick the IDE by using type hints to tell it that your parameter has the corresponding basic type. E.g. ```
class A(Task):
  var: str = luigi.Parameter()
```

The IDE (at least IntelliJ) will trust you and treat `var` as a string.
