### ISSUE TITLE
Changing parameter based file format API to Inheritance based API

### ISSUE THREAD

**Issue by lukauskas** [spotify/luigi#315]
Hi,

I am looking into the `luigi.File` object, particularly the `format` parameter, and to me it looks like the current API could be simplified.

The current formatting behaviour, introduced by ccf61987be48c231dc269536fe5af3654e4288ba, seems to work in a following fashion (let's use Gzip format for example):

First, `File` with `format=luigi.format.Gzip` is created.
Then, when this file is opened as writable, the code snippet that replaces the file object returned without a format, with the `pipe_writer` specified by the format:

```
if self.format:
    return self.format.pipe_writer(atomic_file(self.path))
else:
    return atomic_file(self.path)
```

This `pipe_writer` pretends to have the same interface as a writable file, and implements a `write` method. Instead of writing to file, this write method writes to a new process that feeds the data in `write` to the stdin of i.e. `gzip` shell command and redirects it's output to the file in question.

Now I see two places how this could be simplified:

First, I am not really sure why this elaborate piping behaviour that spawns a subprocess to do gzipping is necessary, python has `gzip` module to handle this kind of behaviour directly.

What is more surprising, this behaviour is used as ground truth in the the unit tests:

```
# Using gzip module as validation
f = gzip.open(self.path, 'rb')
self.assertTrue(test_data == f.read())
f.close()
```

I cannot access the link to spotify's internal bug tracker this commit is associated with (https://gerrit.spotify.net/gerrit/16975), therefore I am not sure if the explanation for this particular choice of implementation is there, but I would be glad if somebody with access to it could shed some light on this.

Secondly, I propose to get rid of the `format=` parameter and replace the behaviour with inheritance based approach.

That is, instead of using `file.File(format=<gzip>)`, I propose using `file.GzipFile()` that would override the open() and write() methods to return the wrappers directly, rather than having the if statement described above, i.e. something among the lines:

```
class GzipFile(File):

     def open(self, mode='r'):
           file_handle = super(GZipFile, self).open(mode=mode)
           if mode == 'w':
               return self.pipe_writer(file_handle)
           else:
               return self.pipe_reader(file_handle)
```

to keep the existing behaviour.

This has the advantages of mimicking the pythonic behaviour for these file types (i.e. is exactly the same interface `gzip` implements). Similarly, we could then add inheritance for these new filetypes, for instance `Gzip` and `Bzip2` could both be `CompressedFile`  or something. 

This hierarchical nesting would allow to add additional methods, to these file types. 
For instance, consider the use case where you have a task to download a particular dataset in GZip format from a public repository. In this scenario, I would probably use `requests` library to open a buffer with `stream=True` and keep dumping the contents from that buffer to a file, until the file is downloaded. 
However, if I desire to keep the compression of the file transparent, with the current implementation I would need to download the full dataset into memory, uncompress it, and feed it in to a gzip formatted file (which would do the compression again). 
This is not the most efficient way of doing things. Obviously, I could download everything into yet another temporary file, and then rename it to match the correct filename, but this is quite hacky, in my point of view.
If we provided a common interface for compressed files, we could add a method to feed in the binary data directly. For instance, implementing something among the lines `open(self, raw='False')`  would allow to just feed the downloaded dataset from online repository as file contents  directly.

The problem with these proposed changes is, of course, backwards compatibility. 
We might be able to do this and keep the `format=` API while everybody updates, but nevertheless it is significant change of the design. I would like to hear what do `luigi` developers think before proceeding with it.

So let me know your thoughts on this.

Regards,
Saulius

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)

**Comment by Tarrasch** [comment]
Honestly I hate the "format' code that exists in the luigi code base I still don't understand it. A re-haul would be appreciated.
