### ISSUE TITLE
Upgrade prometheus_client

### ISSUE THREAD

**Issue by nstinus** [spotify/luigi#3161]
Currently, yoshi pins the prometheus_client dependency to 0.5.0 which is more than 3yo. Latest is 0.14.
Having such an old version prevents the installation of other libs next to luigi in a conda env.

**Comment by lallea** [comment]
Yoshi? I suppose you mean luigi.

I have learnt the hard way that for python, it is preferable to specify ranges of dependency versions. I guess a newer version would also pass the test suite. May I suggest that you send a pull request with a range specification and a newer version in tox.ini? I guess that should be sufficient.

**Comment by dlstadther** [comment]
Closed by https://github.com/spotify/luigi/pull/3163
