### ISSUE TITLE
Documentation on readthedocs.io needs to be updated

### ISSUE THREAD

**Issue by pgrunewald** [spotify/luigi#3223]
The README.rst claims that the docs for the latest stable release are available at https://luigi.readthedocs.io/en/stable/
This however cannot be true, since we have already version 3.2.0 released on pypi, whereas the docs say the latest one is 2.8.13 (released April 2020).

Apart from potential API breaks during that time in the documentation, there are very apparent misinformation like in the first paragraph saying that the current luigi version does support Python 2.7.

I therefor propose to update public available documentation.

**Comment by FaridFArab** [comment]
I think it is OK now @pgrunewald, could you check it again ?

**Comment by pgrunewald** [comment]
Thanks for the hint. It now looks indeed better.

Closing the issue now.
