### ISSUE TITLE
specify resources in luigi.build

### ISSUE THREAD

**Issue by aykhuss** [spotify/luigi#3240]
The way I use luigi is within a script that I want to distribute but where I do not wish to expose the user to all possible luigi settings. Instead, I call `luigi.build` in my script and all necessary settings are done on my end (very specialised workflow that does not need many of the features available in luigi). In particular, I do not have a `luigi.cfg` and don't wish to require such a file. 

In order to better manage the tasks, I now want to use the `resources` feature of luigi. The concrete use-case for me is to manage cpu resources, where different tasks have very different CPU loads:
``` python
class LocalNormalJob(luigi.Task):
  """ normal calculation """
  resources = {"cpu": 1}
  pass

class LocalExpensiveJob(luigi.Task):
  """ expensive local calculation on many cores """
  resources = {"cpu": 8}
  pass

class RemoteJob(luigi.Task):
  """ job submitted to the cluster -> just polling queue every few minutes (virtually zero cost) """
  resources = {"cpu": 0}
  pass

if __name__ == '__main__':
  luigi.build([...],
              workers=X,  # big enough for the concrete workflow (determined @ runtime)
              resources={"cpu":32},  # <- THIS DOES NOT WORK
              local_scheduler=True)
```
The above call to `luigi.build` was what I naively hoped could do, however, it fails as `resources` is not a Parameter in the `core` settings. The constructor for `scheduler.Scheduler` has a `resources` argument, but it's build from a factory class where I don't see how I can inject an appropriate argument easily. The other place I could inject resources would be the configuration and adding a luigi.cfg with 
```
[resources]
cpu = 32
```
does work, but I very much prefer not having to create a file just to pass a single setting... 

Is there any other way to accomplish what I want? I have the feeling that this could be very useful beyond my specific use-case I described above.

**Comment by lallea** [comment]
If resources were implemented as floats that default to 1.0, rather than ints, we would not need to first tell the server how many resources we have of a particular type. You could then state that `LocalNormalJob` requires 0.125 and `LocalExpensiveJob` 1.0. It would also work in cases without `--local-scheduler`.

 I think that such a patch would be simple, so feel free to create one. Beware of float comparisons. :-)

**Comment by krabo0om** [comment]
More of a workaround/hack than a fix: Before you call `build`, create a [temporary file](https://docs.python.org/3/library/tempfile.html), write your config into that file, and set the environment variable `LUIGI_CONFIG_PATH` to that temporary file.

**Comment by junhl** [comment]
[This](https://github.com/spotify/luigi/blob/master/luigi/scheduler.py#L691) seems to be the place where the value gets picked up, that also have TODO comment about making it available as parameter. Also, it shows that it's forcing INT values.

While little off the topic, I don't think `"cpu": 8` actually makes the task to use 8 cores.

**Comment by aykhuss** [comment]
thanks, that comment is also something I spotted. I hoped that this means that someone is interested in promoting it to a genuine parameter but maybe it's not one of the priorities atm.

Yes, just setting `"cpu": 8` will of course not make the task run on 8 cores out of the box. That logic would be something I then need to implement in the execution of the task. I only wanted to use my stripped-down use case to illustrate the problem I'm facing.

**Comment by tgy** [comment]
How can this be done with a central scheduler? Say I have a central scheduler that receives tasks, and I have some luigi workers all connected to this central scheduler. Some of these workers have some specific types of resources. How can I start my luigi workers in a way that I can specify the type of resources that this worker will have?

**Comment by krabo0om** [comment]
Worker-specific resources is a very common question and, as far as I understood it, a "won't fix" because of the increased complexity in the scheduler. There are some derived projects from luigi that you can check out.
