### ISSUE TITLE
Bug-Report: Tenacity 8.4.0

### ISSUE THREAD

**Issue by AlexanderHeidelbach** [spotify/luigi#3292]
Dear Devs,

The `tenacity` package just [released](https://pypi.org/project/tenacity/#history) the version 8.4.0. Unfortunately, this update brakes the `luigi` import most likely due to an API change of `tenacity`. More specifically, the error occurs when importing the `rpc` module. Please find below the traceback. Judging by the description this only happens for `python>3.8`. `python==3.6` still installs `tenacity==8.2.2`

```
>>> import luigi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<path_python>/lib64/python3.9/site-packages/luigi/__init__.py", line 34, in <module>
    from luigi import rpc
  File "<path_python>/lib64/python3.9/site-packages/luigi/rpc.py", line 33, in <module>
    from tenacity import Retrying, wait_fixed, stop_after_attempt
  File "<path_python>/lib64/python3.9/site-packages/tenacity/__init__.py", line 653, in <module>
    from tenacity.asyncio import AsyncRetrying  # noqa:E402,I100
ModuleNotFoundError: No module named 'tenacity.asyncio'
```

**Comment by JosephP91** [comment]
Same error here

**Comment by ztime** [comment]
Same error, setting `tenacity<8.4.0` was a temporary solve

**Comment by AlexanderHeidelbach** [comment]
The issue is also now reported in `tenacity` itself. https://github.com/jd/tenacity/issues/471

**Comment by AlexanderHeidelbach** [comment]
Fixed by https://github.com/jd/tenacity/releases/tag/8.4.1
