### ISSUE TITLE
In 3.5.2, code using luigi fails mypy type checks

### ISSUE THREAD

**Issue by ccmaymay** [spotify/luigi#3312]
The mypy type checker accepted the following code before 3.5.2:

```python
import luigi  # type: ignore


def process_string(s: str) -> str:
    return s


class Streams(luigi.Task):
    param = luigi.Parameter()

    def run(self) -> None:
        with self.output().open('w') as output:
            output.write(process_string(self.param))

    def output(self) -> luigi.LocalTarget:
        return luigi.LocalTarget('data.txt')
```

But with the addition of `py.typed` in 3.5.2, mypy complains:

```
mwe.py:13: error: Argument 1 to "process_string" has incompatible type "Parameter"; expected "str"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

At runtime in the user code, the `param` member isn't an instance of `Parameter`; rather, it has been overwritten [here](https://github.com/spotify/luigi/blob/v3.5.2/luigi/task.py#L469) with the parsed, normalized parameter value, which has the expected type.

Is there any guidance on writing type-checked code in 3.5.2?  Or will type compliance be added later?  Otherwise, could the addition of `py.typed` be reverted?

Thank you!

**Comment by dlstadther** [comment]
@hiro-o918 , given that you added all the mypy support in luigi, could you take a look at this?

**Comment by hiro-o918** [comment]
@dlstadther Thank you for your mentioning.

@ccmaymay 
Can you activate mypy plugin in your project based on the following document.
It should be solve this issue.
https://github.com/spotify/luigi/blob/master/doc/mypy.rst

In addition, I recommend add a type annotation for the param like this.
```python
 param: str= luigi.Parameter()
```

**Comment by ccmaymay** [comment]
It looks like that will work when the `luigi.mypy` module is released.

However, I'm having trouble annotating a task that generates dynamic dependencies and yields both a task and (later) a list of tasks (and needs to use the outputs).  Illustrative example:

```python
def run(self) -> Generator[Union[luigi.Task, list[luigi.Task]], list[luigi.LocalTarget], None]:
    output_a = yield TaskA()
    ...
    output_b_list = yield [TaskB(i) for i in range(3)]
```

Basically, the generator send type depends on the yield type.  Please let me know if there's a known solution for this, beyond putting type guards on the sent values (LHS of the yield expressions).

**Comment by dlstadther** [comment]
I hope that Luigi 3.6.0 will be released soon.
https://github.com/spotify/luigi/pull/3328

**Comment by dlstadther** [comment]
@ccmaymay , luigi 3.6.0 has been released.
* https://pypi.org/project/luigi/3.6.0/
* https://github.com/spotify/luigi/releases/tag/v3.6.0

**Comment by ccmaymay** [comment]
Fantastic, thank you!
