### ISSUE TITLE
Add "execution time" info to Done tasks in the Web UI

### ISSUE THREAD

**Issue by samuell** [spotify/luigi#345]
Currently the Web UI shows the time when tasks are submitted like so:

![selection_405](https://cloud.githubusercontent.com/assets/125003/3187597/929c09ac-ecb2-11e3-8d94-f5df81a62d49.png)

...but it would be very useful to also be able to see how long it took to execute a task, from when it starts executing the run() method, until it finishes

We find that we need this info in order for figuring out good max execution times to set when running things via our resource manager (SLURM).

**Comment by mapeveri** [comment]
Hi, i will like take this issue. I want know if this new label, will add in this screen in the grid:

![image](https://user-images.githubusercontent.com/6276555/35101346-fd08d6dc-fc3d-11e7-9542-f303364ba995.png)

Thanks!
