### ISSUE TITLE
Allow to capture luigi-interface logger without it spawning a stream handler

### ISSUE THREAD

**Issue by aldanor** [spotify/luigi#372]
In `luigi.interface`, we have:

``` python
def setup_interface_logging(conf_file=None):
    # use a variable in the function object to determine if it has run before
    if getattr(setup_interface_logging, "has_run", False):
        return

    if conf_file is None:
        logger = logging.getLogger('luigi-interface')
        logger.setLevel(logging.DEBUG)

        streamHandler = logging.StreamHandler()
        streamHandler.setLevel(logging.DEBUG)

        formatter = logging.Formatter('%(levelname)s: %(message)s')
        streamHandler.setFormatter(formatter)

        logger.addHandler(streamHandler)
    else:
        logging.config.fileConfig(conf_file, disable_existing_loggers=False)

    setup_interface_logging.has_run = True
```

If I want to capture/redirect luigi's loggers, I'd expect this to work (can use the standard `logging` handlers as well, it doesn't really matter):

``` python
import logbook.compat
logbook.compat.redirect_logging()
```

However, `setup_interface_logging` will still eventually create a `StreamHandler` when `luigi.run` is called and it will dump everything to console, so instead of capturing the log you will end up with duplicate streams. The only way to avoid this currently is to do something like

``` python
from luigi.interface import setup_interface_logging
setup_interface_logging.has_run = True
logbook.compat.redirect_logging()
```

... which is quite bad since it uses internal implementation details.

I wonder if this could be improved to allow log stream capturing in a cleaner fashion? Maybe just move stream handler instantiation somewhere else or allow to hook into this function.

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months.
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this issue is about.
- [ ] There exists a reasonable workaround for this.
- [ ] We need to check if this hasn't been fixed by now (for old issues).
- [ ] This is kind of by design and not a bug.
- [ ] Resolving this would probably add a lot of complexity.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)

**Comment by Tarrasch** [comment]
We really need somebody who knows Python logging to jump in and help us. Though I suspect there are more recent discussions on this.

**Comment by alanjds** [comment]
We are being bitten by problems with logs too. Is there some real-time chat you prefer to talk?

**Comment by sklarsa** [comment]
Has anyone found a workaround for this?

**Comment by walkingpendulum** [comment]
@aldanor @alanjds @Tarrasch @sklarsa have you tried to insert 
```python
if __name__ == '__main__':
  import luigi
  from luigi.interface import setup_interface_logging

  # set it up as you want it to be setted up
  setup_interface_logging(...)
  
  luigi.run()
```
at the end of your `main.py` and call it `python main.py Main <parameters>`?

**Comment by alanjds** [comment]
cc: @psugimoto

**Comment by aldanor** [comment]
@walkingpendulum That was the whole point of this issue - `setup_interface_logging()` creates stream handlers where it generally shouldn't.

**Comment by walkingpendulum** [comment]
@aldanor now I get it. I end up with setup as follows
```
$ cat luigi.cfg 
[core]
logging_conf_file=luigi_logging.cfg

$ cat luigi_logging.cfg 
[loggers]
keys=my-logger,root

[logger_my-logger]
handlers=custom
qualname=my-logger
level=INFO
propagate=0

[logger_root]
handlers=output

[formatters]
keys=simple

[formatter_simple]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s

[handlers]
keys=output,custom

[handler_output]
class=StreamHandler
formatter=simple
args=(sys.stdout,)

[handler_custom]
class=StreamHandler
formatter=simple
args=(sys.stdout,)

$ cat script.py 
import luigi


class MyTask(luigi.Task):
    def run(self):
        self.called_once = True
        
        import logging
        logging.getLogger('my-logger').info('Here we are')

    def complete(self):
        return hasattr(self, 'called_once')

if __name__ == '__main__':
    luigi.run()

$ python script.py MyTask --local-scheduler
2017-11-14 10:15:24,942 - my-logger - INFO - Here we are
```

**Comment by psugimoto** [comment]
What I'm doing is to reconfigure logging after I the luigi import in my script file, basically:

```
LOGGING =  some_logging_dict_config
logging.config.dictConfig(LOGGING)
```

**Comment by walkingpendulum** [comment]
@psugimoto eventually (someone correct me if I'm wrong) luigi doesn't have pythonic api (with python dictionary) for logging configuration. either you setup logging with *.cfg file or you monkeypatch luigi's `setup_interface_logging`

**Comment by psugimoto** [comment]
In my case what I want are the logs from the tasks luigi runs, which have their own loggers. It works for me. If you want logs from luigi itself you are probably right and this does not help
