### ISSUE TITLE
Adding Python 3 support

### ISSUE THREAD

**Issue by konklone** [spotify/luigi#382]
I've moved all of my Python work over to Python 3 over the last 6 months, and am not eager to look back. This topic also [came up on the list](https://groups.google.com/forum/#!topic/luigi-user/nhZfyjSjKaA) back in April.

Transitioning to Python 3 has been easy so far for me, but I don't have any experience at managing a project that supports both Python 2 *and* 3. Does anyone here?

**Comment by gpoulin** [comment]
I started some work in PR #745. It's still not working but the Top10Artist with a local scheduler is now working.

**Comment by gpoulin** [comment]
@erikbern You can close this one too.
