### ISSUE TITLE
Pig support

### ISSUE THREAD

**Issue by DandyDev** [spotify/luigi#436]
I was looking at Luigi to run some dependent Pig jobs on a CDH5 cluster, but I couldn't figure out if Luigi supports Pig jobs, and if so, how to go about it. The Readme [mentions Pig support](https://github.com/spotify/luigi/blob/master/README.rst#L34), but on the other hand the Contributing guide [mentions Pig support as a todo](https://github.com/spotify/luigi/blob/master/doc/contributing.rst#L24).

Also, I couldn't find anything in the documentation or the code. Am I missing something here?

**Comment by dajobe** [comment]
There's a pig task here from mortardata's fork: https://github.com/mortardata/luigi/commit/8362e9b32128b6f0bfd7e15d3ecfb6406ff88962

I haven't tried it

**Comment by toidi** [comment]
You can write pig job tasks in luigi workflow using  [`luigi.contrib.pig.PigJobTask`](http://luigi.readthedocs.org/en/stable/api/luigi.contrib.pig.html) class.

**Comment by Tarrasch** [comment]
Exists by now.
