### ISSUE TITLE
Code organization

### ISSUE THREAD

**Issue by erikbern** [spotify/luigi#451]
I think we need to start cleaning up `luigi.*`. What do you think about something like

`luigi.tasks` – contains all built-in tasks, like the hadoop mapreduce, scalding, hive, etc
`luigi.targets` – all filfesystem stuff
`luigi.task_history` – foursquare's and mortardata's task history implementations
`luigi.task_storage` – future implementation of different storage engines for the scheduler

 etc

**Comment by gouthambs** [comment]
I like the batteries included approach as well. Sub-modules based on functionality could help organize better. But I have also run into libraries where there were many sub-modules and it wasn't obvious where a particular class belonged. 

I would suggest that if we create sub-modules, we limit it to just a few such that the destinations of a class is rather obvious.

**Comment by erikbern** [comment]
I like the batteries included approach. Let's keep adding well-tested stuff to `luigi.contrib`. If we ever hit say 40-50 submodules then we can move it to other repos

**Comment by Tarrasch** [comment]
Sounds good plan to me as well. Can this be closed?

**Comment by erikbern** [comment]
ok just like 1999 more issues to close now :)
