### ISSUE TITLE
RFC: Luigi Task History

### ISSUE THREAD

**Issue by jcrobak** [spotify/luigi#51]
# Problem

The luigi _scheduler_'s main purpose is to act as a locking service for running jobs. Its secondary function is to provide a web-interface to view the dependency luigi dependency graph. There are a few pieces of important information that it doesn't provide, such as:
1. A historic list of runs. In fact, the scheduler aggressive prunes finished tasks in order to keep the dependency graph reasonable.
2. Per-task run times, or per-task run histories (time, status, which host it ran on, etc).
3. A link from a running task to the JobTracker details page for that task.
4. A mechanism to investigate the worker logs for a task.
# Data Recording

There are a few potential mechanisms to get at this data:
## Job History

The Hadoop JobTracker History has much of this data. Luigi sets mapred.job.name (unless the sub-task overrides) to the same name as the job itself. The job names could be indexed, which would give us a mechanism to investigate 1, 2, and 3. This solution doesn't work if the user overrides mapred.job.name or in the case of a job that spawns multiple mapreduce jobs (i.e. hive or pig).
## Scheduler recording

The scheduler could record much of this data, to a local database or file. Unfortunately, the scheduler doesn't currently have access to information like which mapreduce jobs were generated or the task output. This data could potentially be uploaded from the workers to the scheduler on completion or failure.
## Worker recording

The workers have all the information about a run. In addition, the workers already sort of have an event system -- at least we have on_complete() and on_failure(). So we could plug some (or all) of this logic into those methods, although it might also be nice to have updates while Tasks are running (particularly to get links to the jobs that they're running and current job logs).
# Data Storage

This data would fit well in either a relational database or a column-family database like hbase or cassandra. 
## Relational

This is a strawman proposal of a relational database schema
Task(
  name String,
  id int auto increment primary key,
  host String,
)

TaskParameters(
  taskId foreign key Task.id,
  name string,
  value string)

TaskEvents(
  taskId foreign key Task.id,
  eventName String, -- READY, START, END, FAIL
  ts Timestamp
  )

TaskHadoopJobs(
  taskId foreign key Task.id,
  id String,
  url String,
  startTime ts,
  endTime ts,
  status String)

TaskLogs(
  taskId foreign key Task.id,
  logType String, // stderr, sdout
  uri String // uri in HDFS or somewhere else.
)
## Column-family

Task table with 'details' (Task), 'parameters' (TaskParameters), 'events' (TaskEvents),  'hadoopJobs' (TaskHadoopJobs) and logs (TaskLogs), 
# UI

I'm envisioning a table-based UI that ignores the dependency graph and only shows the status per task. For example, we have something similar for workflows in oozie: http://cl.ly/image/343k3h2y2u0L (the table would look slightly different due to the differences between oozie and luigi).

This could live separately from the luigi scheduler or be deployed alongside it a la the api server.
# Possible extensions

1) A "predicted" or "estimated" time based upon historical data.
2) ...

**Comment by ataki** [comment]
Hey guys, first, thanks for open sourcing this awesome project on behalf of our data team :)
For our use case, it would be great if there were a simple interface to view the recorded history of tasks (with possible web hooks to rerun)

Are there any plans to / open PR's that implement the Oozie-like web interface? If not, would you be open to pull requests?

**Comment by Tarrasch** [comment]
But task history have been merged a long time ago. See [this](http://luigi.readthedocs.org/en/latest/central_scheduler.html#enabling-task-history). However, if there's anything missing the task history server, we're of course happy to see you contribute. :)

**Comment by ataki** [comment]
@Tarrasch ah, that's awesome! Rushed through that part of the documentation.

**Comment by steveb-cirina** [comment]
Is there a way to see a dependency graph based on the history ?  If not, is there a way to preserve the graph for a longer period of time (e.g. a week) ?

Thanks!

**Comment by steveb-cirina** [comment]
Another question, is there a way to turn off trimming completely in the config file ?  I haven't seen anything on this but I might have missed something.
