### ISSUE TITLE
Spark job written in Python support

### ISSUE THREAD

**Issue by ziky90** [spotify/luigi#511]
I can see that luigi supports Spark when the Spark job is implemented in anything that can be wrapped to .jar file. But Spark also enables to write code directly in Python and submit it. So I would like to ask if it is currently somehow possible to run a job written in Python from luigi?

When I'm trying to run this kind of job from luigi the problem for me seems to be 'def job_class' which would raise NotImplementedError. But there is nothing like job_class in Spark job written in Python, so I would like to have a possibility to not set it. I also can't see any possibility of how to set --py-files option in spark.py file. So my questions are: Is Spark job written in Python currently supported in luigi? If so, then how can I run it without having NotImplementedError and with possibility to set --py-files? 

If Spark jobs written in Python are not supported, then do you think that simply slight modification of Spark1xJob (removing job_class and adding --py-files option) would be enough? It seems to me like not a very difficult contribution, but I'm quiet new to luigi so I think that I might not see everything that is behind running the job.

**Comment by erikbern** [comment]
Was this solved by #837 or #812?

**Comment by ziky90** [comment]
Yes it was originally solved by #512 (I have just forgotten to close this issue), but #812  and #837 seems to solve this more in general and not only for Spark on YARN.
