### ISSUE TITLE
Luigi command line runner not displaying paramaters

### ISSUE THREAD

**Issue by helger** [spotify/luigi#521]
If I want to run Luigi command line runner as per 

http://luigi.readthedocs.org/en/latest/command_line.html

for example

```luigi --module my_module MyTask --x 123 --y 456```

and I want to get help for this workflow

```luigi --module my_module MyTask --help```

then I'm not seeing the MyTask parameters in the help text.

**Comment by erikbern** [comment]
Solved in #855

**Comment by erikbern** [comment]
now with unit tests :)
