### ISSUE TITLE
Support for basic_authentification for ElasticSearch CopyToIndex task

### ISSUE THREAD

**Issue by dvxam** [spotify/luigi#531]
HTTP basic-authentification is not currently supported for the CopyToIndex task under contrib.esindex.

Will soon attach a PR using [Urllib3HttpConnection](http://elasticsearch-py.readthedocs.org/en/latest/transports.html#urllib3httpconnection) instead of default connection class.

**Comment by miku** [comment]
@Tarrasch, this issue can be closed on the next occasion, since it has been resolved in #532.

**Comment by Tarrasch** [comment]
Thanks for reminding me @miku! :)
