### ISSUE TITLE
Extend deps.py to find all upstream dependency

### ISSUE THREAD

**Issue by zenlucent** [spotify/luigi#542]
@rantav made a very good script, deps.py, to find upstream dependency of a given tasks

I could see this script to be more generic and do the followings:
* Update the mistaken example in the code. The current code actually runs as below

`sink` is the downstream task
`task` is an upstream task.
```
python task_deps.py \
    --module my.tasks  MyDownstreamTask
    --downstream_task_param1 123456
    --sink MyUpstreamTask
```
* I suggest renaming the param `--sink` to `--source` 
* list all upstream dependencies if no specific upstream task are given.
* display output file of each task for easy debug and re-run. sample output as below:
```
   TASK: DBTask1(date=2014-11-19)
                       : [DB] db_name:table_name
   TASK: RemoteTask2(date=2014-11-19)
                       : [SSH] host_name: file_name
   TASK: S3Task3(date=2014-11-19)
                       : [S3] s3://path/to/output/file
```

I already had some code for my own project, and I will be happy to make a pull request.

**Comment by d6tdev** [comment]
[d6tflow](https://github.com/d6t/d6tflow) implements that, `d6tflow.taskflow_downstream(task, task_downstream)` and `d6tflow.taskflow_upstream(task)` see https://d6tflow.readthedocs.io/en/latest/d6tflow.html#d6tflow.taskflow_downstream
