### ISSUE TITLE
test_dynamic_dependencies is flaky on Travis CI

### ISSUE THREAD

**Issue by daveFNbuck** [spotify/luigi#571]
I've had a few builds recently fail on Travis on test_dynamic_dependencies. I cannot replicate them locally and I they're not consistent about which version of python/TOX_ENV fails, nor do they consistently fail when rebuilt. Example: https://travis-ci.org/spotify/luigi/builds/43781202 we see it fails for 2.7/cdh and 2.6/hdp but passes for 2.7/hdp and 2.6/cdh.

**Comment by berkerpeksag** [comment]
#576 has been merged. Can this be closed now?
