### ISSUE TITLE
Provide RDBMS target using SQLAlchemy 

### ISSUE THREAD

**Issue by gouthambs** [spotify/luigi#592]
@rantav @erikbern I have an implementation of a SQLAlchemy target. I created this feature in luigi to be able to test by writing to SQLite.  Using SQLAlchemy will open up other db targets such as Oracle or SQL Server that don't currently exist in luigi.

I am wondering if there is an interest in taking this feature if I provide a pull request.

**Comment by gouthambs** [comment]
My implementation (so far) only requires sqlalchemy, which is already something that luigi requires. Additional dependencies will be left to the user based on what dbapi they chose to use.

**Comment by erikbern** [comment]
I think it sounds great. You can put it in luigi.contrib. Regarding imports I think it's fine to depend on anything as long as it's separate from the core luigi codebase.
