### ISSUE TITLE
HiveQueryTask doesn't use output/isn't atomic

### ISSUE THREAD

**Issue by freider** [spotify/luigi#60]
`HiveQueryTask` assumes that the user will enter an output path/partition/table directly in the query. If you specify an `output()` anyways (which you still want to, to help the scheduler), and then reference the same output in the hive query the run operation will not be atomic since Hive will directly write to that directory. Since we want to try to keep as much atomic things as possible I think the HiveQueryTask should by default add a temporary output path to the query and then move that result into a final destination once the run has completed successfully.
That way we can get much cleaner queries as well, especially if we do output-type aware insertions, i.e. doing INSERT OVERWRITE DIRECTORY if output is an `HdfsTarget`, doing LOCAL DIRECTORY if it's a `LocalTarget` and doing table/partition creation if output is a `HiveTableTarget` or `HivePartitionTarget`. I think that would create a much smoother workflow for working with scheduled Hive queries.

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this is issue is about.

Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
