### ISSUE TITLE
luigi should allow for a user level config, not just a root path and system level

### ISSUE THREAD

**Issue by jcoveney** [spotify/luigi#63]
from interface.py, you can set a client configuration here:
_config_paths = ['/etc/luigi/client.cfg', 'client.cfg']

We should also support a ~/.luigi/client.cfg type situation

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this is issue is about.
- [ ] There exists a reasonable workaround for this.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
