### ISSUE TITLE
Per-task max-reschedules

### ISSUE THREAD

**Issue by boosh** [spotify/luigi#635]
Hi,

It'd be useful if different tasks could be configured with different values of `max-reschedules`. For example I need to poll an FTP server and run an EMR job once files have been delivered. So I want the FTP task to run continually for 8 hours (but with a sleep time of 5 minutes between tries), whereas the EMR task should only retry once or twice before indicating failure.

**Comment by Tarrasch** [comment]
Per task configuration exists since [2.3.0](https://github.com/spotify/luigi/releases/tag/2.3.0)
