### ISSUE TITLE
HiveQueryTask doesn't create parent dirs

### ISSUE THREAD

**Issue by freider** [spotify/luigi#66]
Getting the "Failed with exception Unable to rename:" if the parent directory of the output catalog doesn't exist when running Hive queries through HiveQueryTask. Should probably create the dir before running the query if it doesn't exist.

**Comment by Tarrasch** [comment]
I'm closing this issue. 

- [x] It has been inactive for +4 months
- [ ] It's not about luigi core, so not as many users are affected about this.
- [ ] The change seems quite big, it's unlikely to be sporadically picked up.
- [ ] The owner haven't responded or disappeared.
- [ ] I don't understand what this is issue is about.
- [ ] There exists a reasonable workaround for this.


Every open issue adds some clutter, and we try to make the issues fewer and make it easier for new collaborators to find. Currently we try to close any issue that meets the first checkbox + one other.

Feel free to reopen this issue at any point if you have the intent to continue to work this. :)
