### ISSUE TITLE
It is possible for Travis to *comment* as well build status?

### ISSUE THREAD

**Issue by themalkolm** [spotify/luigi#662]
https://github.com/spotify/luigi/pull/661

Like there I saw build failures from travis and decided to back off and close the pull request. But after closing pull request we no longer see a link to travis build status so other contributors left puzzled why I did so.

This could be easily fixed if travis comments its build status as well.

**Comment by Tarrasch** [comment]
Ah, I don't know if you can enable comments from Travis. It's not necessary, in the #661 case I was just stupid. Look here:

![selection_027](https://cloud.githubusercontent.com/assets/294349/5897916/0fb4b682-a54a-11e4-8d17-f305c96db4d7.png)

**Comment by themalkolm** [comment]
Hm, OK.
