### ISSUE TITLE
Proposal for re-evaluating completion of ExternalTasks

### ISSUE THREAD

**Issue by boosh** [spotify/luigi#683]
Currently because ExternalTasks don't implement `run()`, they are marked as not runnable when the task is added. That means that they aren't assigned to a worker if they haven't completed. As a result, the scheduler will never return a PENDING ExternalTask to a worker in `get_work`. So if an ExternalTask completes while luigi is running, it will never be detected and so dependent Tasks will not run on that invocation. I want to change that.

I suggest implementing logic to retry ExternalTasks as follows:

1. Set `runnable=True` for tasks that don't implement `run()`.
2. Create a new multiprocessing.Process subclass that calls `task.complete()` if `run()` is not implemented.

What are your thoughts? I don't want to do this work if it won't be merged in since we don't want to maintain our own fork.

**Comment by boosh** [comment]
Actually I've created something that seems to work on initial testing. I'll do more testing and submit a PR if it is OK.

**Comment by erikbern** [comment]
Ok, sounds interesting. I think the easiest thing is to just re-schedule the graph after it finishes (meaning re-evaluate all external tasks)

**Comment by boosh** [comment]
See PR #684

**Comment by boosh** [comment]
Resolved in #684.
