### ISSUE TITLE
Task scripts should return non-zero if any tasks were DISABLED or FAILED

### ISSUE THREAD

**Issue by boosh** [spotify/luigi#687]
This would make error handling much simpler because the return code of a workflow would indicate whether it completed successfully. Workflows could then be run in a shell script which could check the return code and take appropriate action if anything failed (e.g. try again, trigger alerts, etc.).

**Comment by Tarrasch** [comment]
Hmm, maybe that should be configurable from a command line flag to the `luigi` command. But I don't think we dare change the current behavior.

**Comment by erikbern** [comment]
I actually agree with this,  think it would make more sense. What's the current behavior?

**Comment by Tarrasch** [comment]
The current behavior is that we return 0, because the scheduler didn't crash.

**Comment by Tarrasch** [comment]
I've changed my mind on this. I'm all for this being implemented. :)

**Comment by themalkolm** [comment]
I would say it should be optional. There is a difference between luigi & tasks failing.

Maybe some option like in salt i.e. --retcode-passthrough to pass return code from task to the runner.

**Comment by erikbern** [comment]
I doubt we're going to break anything if we just exit 1. Should we try?

**Comment by Tarrasch** [comment]
Follow progress in #1264
