### ISSUE TITLE
hadoop --config cannot be set in client.cfg

### ISSUE THREAD

**Issue by kalaidin** [spotify/luigi#713]
We use a config option for hadoop command, so I put the following line to client.cfg:
command: /usr/bin/hadoop --config /etc/rutarget
This results in a "no such file" error raised by Popen.

Here is a simple [fix](https://github.com/kalaidin/luigi/commit/f9db4c189e5171812f959a19d516ca51850bc5fa) I can provide, not sure if this is a right way to go.

**Comment by erikbern** [comment]
looks good to me, send it as a PR?

**Comment by kalaidin** [comment]
Yep, added #716.
