### ISSUE TITLE
Support for notifications through Amazon SNS

### ISSUE THREAD

**Issue by apetresc** [spotify/luigi#717]
I've noticed that you guys support notifications through Amazon SES, raw SMTP, and Sendgrid. Would you also be open to a patch that added support for Amazon SNS?

It's the AWS-recommended way to send these types of automated notifications (SES is meant to be used more for marketing blasts). There's several benefits, including:
  * One-to-many subscriptions
  * Receiving SMS in addition to e-mail (with no extra work on the client)
  * Simpler setup (no need to mess with verifying your e-mail domain, etc)
  * Lower chance of getting caught in spam filters (since the e-mail comes from the trusted AWS domain rather than whatever random domain the user may have configured)

It shouldn't be hard to add, we're willing to send in a PR, I just want to make sure the team isn't philosophically opposed to it for some reason.

**Comment by erikbern** [comment]
Yeah, sounds great!

The notifications module is a bit messy, so I don't mind if you want to restructure it in any way

**Comment by cpapazian** [comment]
https://github.com/spotify/luigi/pull/1048

**Comment by jslovan** [comment]
Hi, #1048 was closed for inactivity.  I have tried to resolve it in #1391 .

**Comment by apetresc** [comment]
Yes, #1391 seems to address the issue perfectly. Thanks, @jslovan!
