### ISSUE TITLE
README not in readthedocs

### ISSUE THREAD

**Issue by steenzout** [spotify/luigi#719]
somehow in my local machine I get the README piece to get included in the HTML docs.
now the current version @ readthedocs that piece is missing.
I also noticed some of the colors are different so I wonder if the sphinx-rtd-theme is also different.

on my local env
```
$ source .tox/docs/bin/activate
$ pip list
argparse (1.3.0)
Babel (1.3)
backports.ssl-match-hostname (3.4.0.2)
certifi (14.05.14)
docutils (0.12)
Jinja2 (2.7.3)
luigi (1.0.19)
MarkupSafe (0.23)
pip (1.5.6)
protobuf (3.0.0-alpha-1)
Pygments (2.0.2)
pyparsing (2.0.3)
pytz (2014.10)
setuptools (3.6)
six (1.9.0)
snakebite (2.5.1)
snowballstemmer (1.2.0)
Sphinx (1.3b2)
sphinx-rtd-theme (0.1.6)
SQLAlchemy (0.9.8)
tornado (4.1b2)
wsgiref (0.1.2)
```

can someone check what's the env on the machine and updated the docs?

**Comment by steenzout** [comment]
another guess is the way the HTML docs is being generated before uploading them to rtd is not using `tox -e docs`.

**Comment by erikbern** [comment]
solved right?

**Comment by steenzout** [comment]
yes.
