### ISSUE TITLE
Override _requires leads to infinite recursion.

### ISSUE THREAD

**Issue by macks22** [spotify/luigi#734]
Without realizing that the `Task` class already has a `_requires` method, I went ahead and made my own which served as a helper method to the `requires` function. Unfortunately, this led to an infinite recursion which raised a `RuntimeError`. After spending several hours with this, I was browsing the `Task` source code and noticed the offending method. It would be helpful if the documentation somewhere warned against this. Or perhaps exception handling could be made to catch this sort of thing and give a helpful hint.

**Comment by erikbern** [comment]
Unfortunately there's no way to state that a method is final in Python.

I think it would be good to have some checks but I'm not sure how to do it easily. You would have to check for any method on a base class. I guess we should try to be more strict using double underscores for naming though

**Comment by macks22** [comment]
I was not thinking of stating a method as final; more like a try/except with a case for maximum recursion depth exceeded. However, switching to double underscore naming conventions would avoid the issue and seems a more reasonable resolution.

**Comment by erikbern** [comment]
Going to close this for now. Maybe we should have a bigger overhaul of method names at some point and avoid the single underscore ones. That's a separate task. I doubt many people will run into this specific bug.
