### ISSUE TITLE
Allow specification of input() and output() filenames.

### ISSUE THREAD

**Issue by macks22** [spotify/luigi#740]
I have found several cases where I need to write a task that takes multiple inputs and outputs, like so:

    class GraphBuildingTask(luigi.Task):
        def requires(self):
            return BuildNodeList(), BuildEdgeList()

        def output(self):
            return 'graph.pickle.gz', 'graph.graphml.gz'

Now when referencing these files in the `run` method, it seems fragile to use the offsets of the `input()` and `output()` lists in multiple places (perhaps for multiple sweeps over the same file), so I usually do something like this:

        @property
        def nodes_file(self):
            return self.input()[0]

        @property
        def edges_file(self):
            return self.input()[1]

And often I do the same for the outputs.

It would be handy if I could instead specify the filenames using a dict, like so:

    class GraphBuildingTask(luigi.Task):
        def requires(self):
            return {
                'nodes_file': BuildNodeList(),
                'edges_file': BuildEdgelist()
            }

and then have these filenames be added as properties, as above.

**Comment by Tarrasch** [comment]
I'm pretty sure you can already. Have you tried?

**Comment by erikbern** [comment]
Yeah, this should be doable. Not sure how well documented this is (and we should probably add a unit test for it)

**Comment by erikbern** [comment]
If you return a dict in `requires`, you will get a dict back in `input`, with the Task objects replaced by Target objects

**Comment by macks22** [comment]
It does appear to work as you say. While this isn't what I was thinking of, it's certainly better than using indices. I didn't see this documented anywhere.

**Comment by erikbern** [comment]
Added it to the documentation: http://luigi.readthedocs.org/en/latest/api_overview.html#task-input-getting-dependencies
