### ISSUE TITLE
BoolParameters without config_path set to default value by set_global_parameters

### ISSUE THREAD

**Issue by daveFNbuck** [spotify/luigi#743]
Since my latest upgrade, my snakebite has stopped working. Looking into it, I see that before set_global_parameters is called, snakebite_autoconfig is True and after set_global_parameters is called, snakebite_autoconfig becomes False, overriding the value from client.cfg and causing the wrong snakebite client to be used.

The problem seems to be that the command-line argument is overriding the value from client.cfg, but for boolean flags the command-line argument is present and False when not specified. This bug affects any BoolParameter that doesn't specify a config_path, as Parameter.value is called to find the default value and this doesn't pass a task_name or param_name to _get_value, causing it to ignore client.cfg.

It looks like snakebite_autoconfig, use_snakebite, and record_task_history are the only current parameters vulnerable to this bug. parallel_scheduling is ok because it has config_path set.

**Comment by erikbern** [comment]
That's annoying. Let me add a test tonight and fix it

**Comment by erikbern** [comment]
I haven't been able to reproduce this. My code:

```python
class SnakebiteConfigTest(unittest.TestCase):
    @with_config({"hdfs": {"snakebite_autoconfig": "true"}})
    def testBoolOverride(self):
        # See #743
        self.assertEqual(hdfs().snakebite_autoconfig, True)

        class MYTask(luigi.Task):
            pass

        luigi.run(['--local-scheduler', '--no-lock', 'MyTask'])
        self.assertEqual(hdfs().snakebite_autoconfig, True)
```

**Comment by erikbern** [comment]
I haven't been able to repro. My code:

```python
class SnakebiteConfigTest(unittest.TestCase):
    @helpers.with_config({"hdfs": {"snakebite_autoconfig": "true"}})
    def testBoolOverride(self):
        # See #743
        self.assertEqual(hdfs.hdfs().snakebite_autoconfig, True)

        class MyTask(luigi.Task):
            pass

        luigi.run(['--local-scheduler', '--no-lock', 'MyTask'])
        self.assertEqual(hdfs.hdfs().snakebite_autoconfig, True)
```

**Comment by erikbern** [comment]
Nvm realized I had already fixed the issue when I ran the test :)

**Comment by Tarrasch** [comment]
Did you check that the test failed without https://github.com/spotify/luigi/commit/f6cb70fce4a6cbd64d26cc355a248c1791188d7c?

**Comment by erikbern** [comment]
It did in Travis, but not on my machine. Really weird.
