### ISSUE TITLE
running test/runtests.py create side effect on unit test

### ISSUE THREAD

**Issue by gpoulin** [spotify/luigi#761]
Running the uni test with `test/runtest.py` doesn't run the independently. Mock that doesn't clean themselves correctly after a test may cause other totally unrelated test to fail (c4905da). Running the test with nosetests doesn't create those side effect.

Currently `test/worker_test.py:MultipleWorkersTest.test_multiple_workers` fails under python3 because of those side effect. Renaming `worker_test.py` to `a_worker_test.py` magically "solves" the issue since `test_multiple_workers` is run before the culprit test.

**Comment by berkerpeksag** [comment]
test/runtests.py is just a wrapper around nose.main(). I don't understand how it creates a side effect.

**Comment by gpoulin** [comment]
It seems to be due to a difference between system python environment and the tox environment.
