### ISSUE TITLE
Cannot run more than 2 workers at the same time

### ISSUE THREAD

**Issue by david-cliqz** [spotify/luigi#815]
I started a task, which has 30 prerequisites, each of which, in turn, have 1. All the tasks (except the "umbrella" task, which is empty) involve running [mrjob](https://github.com/Yelp/mrjob)s. I explicitly set the number of workers to 6 (`--workers 6`). However, luigi only seems to run two tasks parallelly.

This is not the first time I experience this issue. Do I do something wrong? Is there a way to debug what is happening?

Luigi version 1.0.19.

**Comment by erikbern** [comment]
It's impossible to know what you are doing without seeing the code

**Comment by david-cliqz** [comment]
@erikbern I will try to upload a MWE. However, even like that, it would be nice to know how I could debug this myself aside from tracing everything.

**Comment by erikbern** [comment]
Does it say something like "worker xyz is running task xyz"? The scheduler should return some information back to the worker explaining why it can't pull more work

**Comment by erikbern** [comment]
Does it say something like "worker xyz is running task xyz"? The scheduler should return some information back to the worker explaining why it can't pull more work

**Comment by david-cliqz** [comment]
No. In the server log, all I get is Starting pruning of task graph / Done pruning task graph, and stuff about removing tasks. Nothing about adding or running them (aside from stuff like _/api/get_work_ from tornado which reveal nothing).

There are a few worker timeouts, but due to the issues above, I have no idea at what point these happened. Also, they are spread a bit farther apart than I expected (since 6 - 2 = 4 should have timed out at the same time, at the beginning).

**Comment by david-cliqz** [comment]
@erikbern I could not reproduce this issue with a minimal working example. So I'll close this issue for now, and start playing with `worker-disconnect-delay`. Will re-open if I discover something.

**Comment by erikbern** [comment]
ok thanks lmk!
