### ISSUE TITLE
What is the point of target_table in sqla.SQLAlchemyTarget?

### ISSUE THREAD

**Issue by soxofaan** [spotify/luigi#821]
Hi,

I was exploring contrib.sqla for using `SQLAlchemyTarget` without `CopyToTable`. 
(Not sure how recommended this is, but that is not the point here)

I was wondering about the point of the `target_table` constructor argument and instance property.
It is used in `touch()` for insert/update in the marker table
but is not read/checked somewhere (e.g. it could be added as where clause in `exists()`)

For my use case, the target_table is not interesting (I use "dummy"), so I'd like to have it dropped,
but I guess for users of `CopyToTable` covering multiple target tables, this might be a source of bugs (wrong results from `exists()`).

**Comment by Tarrasch** [comment]
Ping @gouthambs

**Comment by gpoulin** [comment]
My current impression is that sqla module is the "poor children" of Luigi. RDBMS ( and NOSQL) are a little overlooked and see just as an end result. It's possible to create pretty complex data workflow/analysis with relatively a lot of data without needed using those (it's sure that when you are Spotify and you are looking at many millions of lines of logs a day, postgres becomes fast overwhelm).

There is place to a lot of improvement there and if there is functionality that are missing you could open a PR. The guys at Spotify are pretty open to outside to outside contribution (pretty far from Oracle).

I have a many functionality base on sqla in my little "homemade" data workflow framework that I hope to find time to port over to Luigi (atomic table, backup table, rollback, "custom" structure copy, "custom" data copy, data integrity check, ...)

**Comment by gouthambs** [comment]
The ``sqla`` ``target_table`` is the name of the table where the data needs to be copied. As @gpoulin points out, the ``sqla`` works best with single table as an end result.

Can you override the ``copy`` method in ``CopyToTable`` to implement your actual copy operation? Potentially we can make the ``CopyToTable`` generic enough to work with multiple tables as target.

**Comment by soxofaan** [comment]
ok, never mind, 
my concern is already covered by 19f3937bb66921c8af8f1b22e

I was looking at version 1.0.24, which did not handle target_table properly in `SQLAlchemyTarget.exists`
