### ISSUE TITLE
Luigi and Cassandra

### ISSUE THREAD

**Issue by dmlayton** [spotify/luigi#848]
I am looking to use Luigi to ingress to Cassandra. In the docs, the example mentions loading data into Cassandra, but there is no Cassandra or CFS specific code. Do you just use the HDFS module? Do you use cassandraTable in PySpark? Any advise would be appreciated.

**Comment by erikbern** [comment]
In Spotify's case we used github.com/spotify/hdfs2cass i.e. scheduled a
hadoop job that inserted the data. For small datasets we used pycassa iirc

2015-03-13 7:24 GMT-04:00 dmlayton <notifications@github.com>:

**Comment by dmlayton** [comment]
Thank you for the quick reply. How then does luigi know that a job has previously completed successfully? My understanding is that luigi checks that the output exists?

**Comment by erikbern** [comment]
The easiest thing is to write a dummy file once the ingestion is complete.
Slightly more advanced is you can implement a Target subclass that checks
whether data exists in Cassandra

2015-03-13 8:11 GMT-04:00 dmlayton <notifications@github.com>:

**Comment by dmlayton** [comment]
Ah, the flag technique used in the s3 module and presumably elsewhere. Thank you so much.
