### ISSUE TITLE
PyPI released version 1.1.1 breaks because `logger` is not defined in task_register.py

### ISSUE THREAD

**Issue by laserson** [spotify/luigi#857]
See:

https://github.com/spotify/luigi/blob/be728d82ff90f879fef703e13b6b9192de0d8b27/luigi/task_register.py#L91

**Comment by erikbern** [comment]
thanks, will fix. sorry about it

**Comment by laserson** [comment]
Would it be possible to quickly put out a bug fix release?

**Comment by erikbern** [comment]
See #858

I'll merge and bump version to 1.1.2.

Good catch. We need to get coverage up for the core parts of Luigi. This was actually fairly obvious from the coveralls report:

![image](https://cloud.githubusercontent.com/assets/1027979/6699911/01f95d76-ccdd-11e4-936c-04bae896ec29.png)

**Comment by erikbern** [comment]
Yes I will release 1.1.2 shortly

**Comment by erikbern** [comment]
Fixed

**Comment by laserson** [comment]
awesome, thanks @erikbern!
