### ISSUE TITLE
List pass to Luigi as parameter become tuple type.

### ISSUE THREAD

**Issue by MathiasDesch** [spotify/luigi#859]
I am using Luigi to process a list as batch entry. However when I test the type of the parameter passed, It does return a tuple.
That's not a big issue, since it does not change behaviour of my code. But I report the issue in order to be sure that luigi don't stay with unpredicted behaviour.

Here an exemple of the issue :

    class MyTask(luigi.Task):
        list = getParameter()

        def run():
              print type(list)

    __main__:
        print MyTask(list=[1,2,3,4,5,6])

Which return "tuple"

**Comment by erikbern** [comment]
I think tuples makes more sense than lists because they are immutable. But
it's a bit confusing and the documentation should point this out.

https://github.com/spotify/luigi/blob/master/luigi/parameter.py#L295

2015-03-18 6:39 GMT-04:00 MathiasDesch <notifications@github.com>:

**Comment by MathiasDesch** [comment]
Indeed, it makes sense. Thanks for your answer.

**Comment by jeremyjjbrown** [comment]
This is unexpected behavior as your docs say:

Python is not a strongly typed language and you don’t have to specify the types of any of your parameters. You can simply use the base class Parameter if you don’t care.

Should you at least log the conversion at the INFO level.

**Comment by Tarrasch** [comment]
> "Explicit is better than implicit"

Yes. That's why I really don't like the name `Parameter`. It should be called `StringAndOnlyStringParameter`, or well, maybe just `StringParameter`.

In summary: you are *not* allowed to put a non-string type into a `Parameter`

**Comment by erikbern** [comment]
tarrasch what do you mean? you can use other types for a Parameter if you want to. I'm not saying it's good, but you can :)

**Comment by Tarrasch** [comment]
You can often get away with it. But one shouldn't assume luigi to work if `serialize<--->parse` isn't complementing each other. For example serialize needs to be injective. If I'm not mistaken, the luigi server will think of `MyTask(a=[5])` as the same task as `MyTask(a='[5]')`.

I would like to introduce runtime checks that verifies parameters are valid when you instantiate tasks. But so many tests would break and there could potentially be production code that breaks plus so many tests would need rewriting perhaps.

**Comment by citynorman** [comment]
Sorry for possibly being off topic but this is the closest to answering a question I had: is there are way to run luigi tasks without the command line args? I'm calling luigi from inside python code and have a list object I would like to pass in. Seems I can do something like `MyTask([1,2]).run()` but not sure if that's best. For one thing that method is not producing any log output.

**Comment by citynorman** [comment]
Nvm answered my own questions. In case someone comes across it's `luigi.build([MyTask([1,2])], local_scheduler=True)`
