### ISSUE TITLE
Luigi Compatibility issue with Spark 1.3?

### ISSUE THREAD

**Issue by cqnguyen** [spotify/luigi#866]
Was able to run luigi task with pyspark (Spark version 1.2.1) but when upgraded to Spark version 1.3 - luigi failed to run even the workcount_pyspark example successfully.

This is the error that is returned:
INFO: Running: ['spark-submit', '--deploy-mode', 'client', '--name', 'PySpark Word Count', '--driver-memory', '2g', '--executor-memory', '3g', '--total-executor-cores', '100', 'wordcount_spark.py', 's3n://inputfilelocation/file', 's3n://outputfilelocation/file'] 
ERROR: [pid 27675] Worker Worker(salt=585058106, workers=1, host=ip-10-20-66-24.us-west-1.compute.internal, username=hadoop, pid=27675) failed    PySparkWordCount(total_executor_cores=100) 
Traceback (most recent call last): 
  File "/usr/lib/python2.6/site-packages/luigi-1.1.3-py2.6.egg/luigi/worker.py", line 166, in run 
    task_gen = self.task.run() 
  File "/usr/lib/python2.6/site-packages/luigi-1.1.3-py2.6.egg/luigi/contrib/spark.py", line 235, in run 
    universal_newlines=True) 
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__ 
    errread, errwrite) 
  File "/usr/lib64/python2.6/subprocess.py", line 1234, in _execute_child 
    raise child_exception 
OSError: [Errno 2] No such file or directory

**Comment by jthi3rry** [comment]
Can you try changing the name property to remove spaces? That might be the problem as the command that's executed would contain the same spaces without wrapping the string in quotes or escaping spaces. If it works that should be an easy fix. It shouldn't work on spark 1.2.1 either though.

Let me know and I'll look into it further.
