### ISSUE TITLE
Boolean CLI arguments should be parsed as such

### ISSUE THREAD

**Issue by boosh** [spotify/luigi#869]
I expected 'true'/'false' (regardless of case) to be parsed as booleans by the arg parser, instead of strings. I think it'd make more sense if that were the case.

**Comment by erikbern** [comment]
If you use `BoolParameter` you get that ability – otherwise I think it would be inconsistent. It's like how `bool('False') == True` which is confusing the first time you see it but actually makes sense if you think about it

**Comment by boosh** [comment]
My bad, sorry. BoolParameter sounds like what I was looking for then.

**Comment by boosh** [comment]
@erikbern I've changed a parameter to a BoolParameter, but now I don't appear to be able to pass a value to it on the command line to set it to false. On the command line it's now just a flag. 

Is there any way I can pass 'false' to a bool parameter on the command line?

**Comment by Tarrasch** [comment]
@boosh You should be passing `False`, but are you saying that it ignores that and sets to True? Hmm, I recall hearing of this bug before. Can you create a failing test case and put it in a PR? Potentially with a fix?

**Comment by erikbern** [comment]
+1 sounds broken

**Comment by boosh** [comment]
I mean that I'm declaring it as:
```
    wait = luigi.BoolParameter(default=True,
                               description="Whether to block until the step has "
                                           "completed, or return immediately after "
                                           "adding it to the cluster.")
```
But when I run it on the command line with `-h`, it only offers me `--wait`. If I try to pass a parameter (e.g. `--wait false`), it complains that it doesn't know what to do with the `false` parameter.

**Comment by erikbern** [comment]
yes they are exposed as `store_true` meaning presence = true, not presence = false

default should be false for all boolean parameters by design. maybe the design is bad though.

i remember a long time ago we discussed if for those variables we should expose eg `--no-wait` instead

**Comment by boosh** [comment]
Ah OK. Well `--no-wait` would be handy for my usecase. Want me to open a ticket?

**Comment by evictor** [comment]
+1 I would like this. Automatic "--no-*" prefix recognized to negate a bool param.

**Comment by tiamot** [comment]
+1 I would like this. Automatic "--no-*" prefix recognized to negate a bool param.
