### ISSUE TITLE
Submit Hadoop job with luigi as the current user and not as YARN

### ISSUE THREAD

**Issue by junchenfeng** [spotify/luigi#884]
I am running a hadoop job within the framework of luigi under the HADOOP_USER_NAME of hadoop (let's say).

However, luigi launches the task under the user name of YARN, which does not have write privilege on certain folders.

Currently I change the owner of the folder to YARN, but that is certainly not Kosher.

Any idea how I can regulate the user name on luigi?

**Comment by erikbern** [comment]
I'm not exactly sure how this work, but it shouldn't be very hard to fix it. If you figure out how to do it, and send a pull request, I'm happy to merge it!
