### ISSUE TITLE
python setup.py install leads to exception

### ISSUE THREAD

**Issue by StefanPapp** [spotify/luigi#887]
Running the python setup for luigi runs into the following error.

  File "/tmp/easy_install-Afyf58/python-daemon-2.0.5/version.py", line 438
    for item in versions}

source platform is the HDP 2.1 Sandbox from hortonworks

**Comment by gpoulin** [comment]
The issue seems to be with the installation python-daemon. Can you give the complete output of

```bash
pip install python-daemon
```

**Comment by erikbern** [comment]
i wonder if we can/should run setup.py as a part of the tests

**Comment by gpoulin** [comment]
@erikbern Isn't it run automatically by tox?

**Comment by erikbern** [comment]
i think that's true

**Comment by StefanPapp** [comment]
Yes, it is Python-daemon. Version 2.0.5 is not compatible with Python 2.6 any more

**Comment by erikbern** [comment]
weird we don't see an issue with our travis builds then

**Comment by Tarrasch** [comment]
Still an issue @StefanPapp ?

**Comment by stroykova** [comment]
version from master
python2.6 setup.py install
leads to
File "/tmp/easy_install-iFDv97/python-daemon-2.0.5/version.py", line 438
    for item in versions}
      ^
SyntaxError: invalid syntax

**Comment by gpoulin** [comment]
@stroykova the support for python2.6 was drop in recent version.

**Comment by stroykova** [comment]
@gpoulin thank you, got it. Main page has list of supported versions, maybe it is time to close an issue?
