### ISSUE TITLE
hive table_exists should be case insensitive?

### ISSUE THREAD

**Issue by nzlinus** [spotify/luigi#896]
Any thoughts on this one?

In https://github.com/spotify/luigi/blob/master/luigi/contrib/hive.py#L141
(possibly here too, but we're not on CDH: https://github.com/spotify/luigi/blob/master/luigi/contrib/hive.py#L192)

Sometimes we have tables that are defined as capitalized, rather than lower case underscored names.  These are easier to read in code if left capitalized, though hive is case insensitive, and will return them as lower case.

E.g. when checking for an existing table `table = 'FooBar'`, stdout will return with `foobar` and the test will fail

This wasn't an issue in older versions, which just checked for string "does not exist" or "Table not found" in stdout.

Would be easy to fix using `return stdout and table.lower() in stdout` or `return stdout and table.lower() in stdout.lower()`

Let me know your thoughts on this.  I can supply a pull request if necessary.

Thanks,
Lin.

**Comment by Tarrasch** [comment]
Please do give a pull request, with an accompanying test if possible :)
