### ISSUE TITLE
Exception when a command-line parametter contains a non-ascii character

### ISSUE THREAD

**Issue by jonasbru** [spotify/luigi#901]
Hey,

We've just upgraded to Luigi 1.1.2, and now we get an error when launching Tasks that have utf-8 characters on the parameters.  (using python 2.7.3)

Here's the stacktrace we get : 
```
Traceback (most recent call last):
  File "examples/top_artists.py", line 283, in <module>
    luigi.run()
  File "/home/jonas/.virtualenvs/website/local/lib/python2.7/site-packages/luigi/interface.py", line 434, in run
    return interface.run(tasks, worker_scheduler_factory, override_defaults=override_defaults)
  File "/home/jonas/.virtualenvs/website/local/lib/python2.7/site-packages/luigi/interface.py", line 165, in run
    not(lock.acquire_for(env_params.lock_pid_dir, env_params.lock_size))):
  File "/home/jonas/.virtualenvs/website/local/lib/python2.7/site-packages/luigi/lock.py", line 59, in acquire_for
    my_pid, my_cmd, pid_file = get_info(pid_dir)
  File "/home/jonas/.virtualenvs/website/local/lib/python2.7/site-packages/luigi/lock.py", line 44, in get_info
    pid_file = os.path.join(pid_dir, hashlib.md5(my_cmd.encode('utf8')).hexdigest()) + '.pid'
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 97: ordinal not in range(128)
```

Here I've just added a `plop = luigi.Parameter()` to `AggregateArtists`, and called it with 
`python examples/top_artists.py AggregateArtists --local-scheduler --date-interval 2012-06 --plop à`

The error seems to come from the [Python3 refactoring](https://github.com/spotify/luigi/pull/745). Removing `.encode('utf8')` on [this line](https://github.com/spotify/luigi/blob/master/luigi/lock.py#L44) seems to solve the problem, but I guess it was added for a reason ^^.

Any ideas of how we could solve this on our side, other than removing the encode?  (I'll try to add a test for it later)

**Comment by Tarrasch** [comment]
@gpoulin, do you know the why of this? :)

**Comment by erikbern** [comment]
i would argue utf-8 support on the command line is one of those things we can live without. i don't see why it's needed

but it's probably an easy fix.

**Comment by gpoulin** [comment]
@Tarrasch On python3, `hashlib.md5` need `bytes` and not `str` (which make sense). I'll fix that.
