### ISSUE TITLE
Tasks that complete in <1s may display as RUNNING or PENDING in task history

### ISSUE THREAD

**Issue by stephenpascoe** [spotify/luigi#905]
Using MySQL backend, I am seeing tasks that have completed in either "RUNNING" or "PENDING" state in the task_history webpage.  Looking at the db there is a row marking these tasks as "DONE" but their timestamps clash with the displayed event.  Clearly the timestamps aren't sub-second precision.

E.g.

    mysql> select id, event_name, ts from task_events where task_id=61;
    +-----+------------+---------------------+
    | id  | event_name | ts                  |
    +-----+------------+---------------------+
    | 181 | PENDING    | 2015-04-22 15:10:02 |
    | 230 | RUNNING    | 2015-04-22 15:12:38 |
    | 231 | DONE       | 2015-04-22 15:12:38 |
    +-----+------------+---------------------+
    3 rows in set (0.00 sec)

Modern MySQL should support this.  I have found this stackoverflow question suggesting the issue is with SQLAlchemy: http://stackoverflow.com/questions/29711102/sqlalchemy-mysql-millisecond-or-microsecond-precision

Other than fixing this in SQLAlchemy it might work to simply sort task_event rows by timestamp *and* primary key, assuming the events are inserted in true order.

**Comment by stephenpascoe** [comment]
As per the SO post.  You need to use the `sqlalchemy.dialects.mysql.TIMESTAMP` column as `TIMESTAMP(fsp=6)` to get sub-second precision.

I suggest db_taskhistory.py could use this when using mysql.

**Comment by Tarrasch** [comment]
Why don't you send a PR @stephenpascoe ? :)

**Comment by stephenpascoe** [comment]
Sure, PR should follow soon.
