### ISSUE TITLE
Deprecate global parameters?

### ISSUE THREAD

**Issue by erikbern** [spotify/luigi#94]
Is anyone using them? I'm not sure if it was a good design decision to have them and they have led to a lot of headache for me at least. Is it OK if we deprecate them with the goal of removing them down the road? Wanted to hear what you think

**Comment by toidi** [comment]
Can anyone remind me how create global parameter using `client.cfg`?

**Comment by Tarrasch** [comment]
Parameter system is completely rewritten and there are no globals anymore. Closing this.  See docs for usage of the new system.
