### ISSUE TITLE
S3FlagTarget doesn't pass client to super constructor

### ISSUE THREAD

**Issue by IgorBerman** [spotify/luigi#946]
If I use manually configured S3Client and create S3FlagTarget with this client I get 
NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials

This happens because in S3FlagTarget c'tor the call to super c'tor is not passing aforementioned client
super(S3FlagTarget, self).**init**(path)
and thus self.fs = client or S3Client() in S3Target c'tor tries to create S3Client from global configuration

**Comment by Tarrasch** [comment]
Nice find! Please create a pull request. :)

**Comment by rapen** [comment]
what are prerequisites to run tests? I found how to run them, but probably due to missing packages I have many of those "error". Is there any such list?(I haven't changed anything yet...just tried to create "baseline")

**Comment by Tarrasch** [comment]
Ah, you run `tox -e pep8` and `tox -e py27-nonhdfs` basically

**Comment by dlstadther** [comment]
Closing b/c appears to be fixed
