### ISSUE TITLE
Central scheduler crashes on startup if state file broken

### ISSUE THREAD

**Issue by freider** [spotify/luigi#96]
If the state (pickle) file somehow gets broken (process gets killed while writing it?) the scheduler will crash on the next startup while trying to read it. We should catch such errors and remove the broken state to allow process managing of the scheduler to auto-restart it in those cases.
This has only ever happened once to me, so it doesn't seem to be a common error.

**Comment by Tarrasch** [comment]
Fixed, see https://github.com/spotify/luigi/blob/1c48aac5b2109deb7fdf706b176deb19762bdd31/luigi/scheduler.py#L460
