### ISSUE TITLE
Can I setup luigi offline?

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#985]
When I run setup.py, I got the err message:
Download error on https://pypi.python.org/simple/python-daemon/: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed -- Some packages may not be found!
Download error on https://pypi.python.org/simple/: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed -- Some packages may not be found!

So, setup.py will download modules online, Can I setup it offline?

Or how can I solve the errors above?

**Comment by demoray** [comment]
setup.py pulls down the prerequisite packages if they are not already installed.  Check install_requires within setup.py for a list of the prerequisite packages.  Other libraries may be needed depending on the 'luigi.contrib modules used, but those are not install prerequisites.

**Comment by Tarrasch** [comment]
I don't  get this issue. Closing.
