### ISSUE TITLE
luigi with python2.7 problem: 

### ISSUE THREAD

**Issue by leafjungle** [spotify/luigi#987]
after setup, I run: python wordcount.py --date 2012-W03

I encount the problem:

 File "/home/users/lijun26/.jumbo/lib/python2.7/multiprocessing/synchronize.py", line 59, in <module>
    " function, see issue 3770.")
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

It seems that luigi is not compatible with python2.7?

**Comment by Tarrasch** [comment]
Isn't it a problem with your platform (operating system?)? Have you googled the error messge?

**Comment by erikbern** [comment]
Are you on windows? Pretty sure multiprocessing isn't fully supported on
win

**Comment by MrChrisJohnson** [comment]
Looks like multiprocessing support is broken in Ubuntu for python 2.7 https://bugs.launchpad.net/ubuntu/+source/python2.7/+bug/683027

The same bug was reported and fixed with python 3.1 but doesn't seem like they've fixed it for 2.7
https://bugs.launchpad.net/ubuntu/lucid/+source/python3.1/+bug/630511

**Comment by Tarrasch** [comment]
That sounds crazy. Also the ticket is ancient it seems.

**Comment by leafjungle** [comment]
"Isn't it a problem with your platform (operating system?)? Have you googled the error messge?"

My operating system is centos.

After google, I found  issue 3770 is quite famous on python 2.7.

**Comment by leafjungle** [comment]
"Looks like multiprocessing support is broken in Ubuntu for python 2.7 https://bugs.launchpad.net/ubuntu/+source/python2.7/+bug/683027

The same bug was reported and fixed with python 3.1 but doesn't seem like they've fixed it for 2.7
https://bugs.launchpad.net/ubuntu/lucid/+source/python3.1/+bug/630511"


I can not change the python from 2.7 to other versions because all the other python programs of our company are based on this version.

**Comment by leafjungle** [comment]
https://pypi.python.org/pypi/luigi

this website says that luigi is compatible with python 2.6 / 2.7 / 3.3 / 3.4.

So I am so puzzled.

**Comment by Tarrasch** [comment]
Ah, the 2.6 support was dropped but not 2.7.

@leafjungle, as I pointed out, those threads you link to are **5 years old**. The problem is something else for sure, there's no way the most used linux distribution have an unfixed bug there for one of the most used programming languages for half a  decade.

**Comment by erikbern** [comment]
Yes Luigi works with Python 2.7. There must be something else with your
environment causing the issues

**Comment by leafjungle** [comment]
"Ah, the 2.6 support was dropped but not 2.7.

@leafjungle, as I pointed out, those threads you link to are 5 years old. The problem is something else for sure, there's no way the most used linux distribution have an unfixed bug for one of the most used programming languages for half a decade."

@Tarrasch @erikbern ,
Thanks very much, I change the permission of /etc/shm to 777, and the problem solved.

**Comment by Tarrasch** [comment]
Thanks for contributing back with your solution. :)
