### ISSUE TITLE
Task is not test as complete once scheduled

### ISSUE THREAD

**Issue by MathiasDesch** [spotify/luigi#994]
A task which is scheduled is not test as `complete()` anymore before its run. However, should it not be ? 

I have the case that the output target of a task (so the complete test) is fulfilled by a required task because of some retrievement in my database. Therefore I would like my primary task not to execute if the required task as found things and fulfilled the output target of my primary task.
Should it be an improvement or is there a reason for this implementation ?

**Comment by Tarrasch** [comment]
You mean some external process fulfilled the dependency while your workflow was running?

**Comment by MathiasDesch** [comment]
It can be also this way yes. The main idea is that I want to run a Task C, which depend on Task A and B. During the running of A and B, some process will fulfilled the dependancy of C (like creating a file, an entry in database). Then if C could check complete method it return True. But C will still be executed since it has been scheduled previously.

**Comment by Tarrasch** [comment]
Hmm, but I'm not sure what makes sense to do, seems like most people have not stumbled on this issue since you wouldn't use luigi to complete C if you already have another external process making C complete without luigi.

**Comment by MathiasDesch** [comment]
That might come from design mistake. I'll investigate.
